### ISSUE TITLE
Display Machine Group name

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/munkireport-php#1008]
It would be useful to see the computer group name wherever a computer is listed - including the computer details page. Currently the group is only displayed there, but as a numerical id, which is less helpful.

**Comment by bochoven** [comment]
Should not be too hard to implement

**Comment by ofirgalcon** [comment]
Would be nice to have it shown in lists as well.

**Comment by MichalMMac** [comment]
It would be great to be able to see machine group in computer summary.
