### ISSUE TITLE
Bug - custom.js is intermittently available

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/munkireport-php#1011]
As far as I can tell this is what is occurring.

I'm still getting strange behaviour with custom.js - sometimes I see it, most times I don't.

**Comment by bochoven** [comment]
`custom.js` is just a static file served by your webserver. Could you elaborate on the issue?

**Comment by ofirgalcon** [comment]
I just used the sample custom.js - sometimes when I log in I can see the extra buttons it creates and sometimes not. It’s pretty random.


Ofir
Gal consultancy Ltd
www.galweb.com <http://www.galweb.com/>
Twitter <http://twitter.com/galconsultancy#>Skype <skype:galofir1>
iChat/AIM <aim:goim?screenname=galofir1>
LinkedIn <http://www.linkedin.com/in/ofirgal>

**Comment by ofirgalcon** [comment]
I still can't get custom.js to work, I put a copy of it in every possible location and still no joy. I am hosting this as an addon cpanel domain. 

When I look at the source code in my browser I don't see a custom.js file. No error is displayed in the safari console.

**Comment by bochoven** [comment]
Try putting the full url in the config:
```
$conf['custom_js'] = 'https://fqdn/path/to/custom.js';
```

**Comment by ofirgalcon** [comment]
I tried that - when I do I see a custom.js is the browser source but it's not my custom.js, it appears to be the default one - from what I can tell it's the code for the default page (it has the favicons definitions at the top). My custom.js is not showing.

**Comment by ofirgalcon** [comment]
So strange, sometimes  see a custom.js in the browser, sometimes I don't, but it's never the one I want.

**Comment by ofirgalcon** [comment]
OK so I served the file from a different domain on same server that doesn't have the htaccess redirect and web.config, just a plain clean domain and now it works. It seems to me something about the way MR redirects things confuses my web server.
