### ISSUE TITLE
Location fails intermittently but quite often

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/munkireport-php#1015]
I'm finding that on many of my clients pinpoint/location fails with an error, even on first run. But many times it runs once successfully and reports a stale location thereafter. 

`Error obtaining a location. LS was unresponsive or a lookup timeout occurred.`

I ran pinpoint -f on a few clients, it found a new location and that appeared in MR after I ran managedsoftwareupdate

**Comment by bochoven** [comment]
Please file an issue in https://github.com/clburlison/pinpoint
