### ISSUE TITLE
Feature request: add TeamViewer to Remote Control menu

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/munkireport-php#1025]
Now that tuxudo wrote the very useful TeamViewer module, it would be nice to add TeamViewer to the remote options.

**Comment by bochoven** [comment]
I agree.

**Comment by mosen** [comment]
The following URI schemes are registered by the TeamViewer app, a sample of the launch services database is below
`
schemesList:   tvvpn1, tvfiletransfer1, teamviewer8, tvsendfile1, tvchat1, tvpresent1, teamviewer10, tvcontrol1, tvjoinv8, tvvideocall1
		bindings:      .tvs
		icon:          Contents/Resources/tvdownload.icns
		bindings:      .tvdownload
		bindings:      tvjoinv8:
		name:          com.teamviewer.tvchat1
		bindings:      tvchat1:
		name:          com.teamviewer.tvcontrol1
		bindings:      tvcontrol1:
		name:          com.teamviewer.tvfiletransfer1
		bindings:      tvfiletransfer1:
		name:          com.teamviewer.tvpresent1
		bindings:      tvpresent1:
		name:          com.teamviewer.tvsendfile1
		bindings:      tvsendfile1:
		name:          com.teamviewer.tvvideocall1
		bindings:      tvvideocall1:
		name:          com.teamviewer.tvvpn1
		bindings:      tvvpn1:
                wtv
		bindings:      .wtv`

This was generated using `/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -dump |grep tv`, you can also consult the `Info.plist` from the bundle.

**Comment by ofirgalcon** [comment]
Just a note - Tuxudo's module already has this button, I just thought it would be nice to place it in the Remote menu too.

**Comment by tuxudo** [comment]
Added to the drop down menu. Only shows if module is enabled and there is a client ID on record for the client. Shows all client IDs for the client and labels them with the different ID.

**Comment by ofirgalcon** [comment]
Hi 

This menu displays ssh and vnc only.

**Comment by Bluscream** [comment]
So you say only ssh and vnc is considered "remote control"? :man_facepalming:
