### ISSUE TITLE
installhistory module does not show under "Listings"

### ISSUE THREAD

**Issue by wadewei01** [munkireport/munkireport-php#1027]
I tried munkireport 3.0.2, and found installhistory module does not show under "Listings" menu even it is enabled at config.php file, tried 3.0.0, got the same problem, not tried 3.0.1 yet.

Anyone else has the same problem? Or somewhere I configured wrong?

**Comment by poundbangbash** [comment]
The installhistory module doesn't have a listing view.
The module provides information in the client details as "Apple Software" and "Third Party Software"

-Eric
