### ISSUE TITLE
filevault_2_status_check.sh on systems with multiple disks/partitions

### ISSUE THREAD

**Issue by thehilll** [munkireport/munkireport-php#103]
On a host that has multiple disks/partitions where each is encrypted with FileVault, I believe that filevault_2_status_check.sh will incorrectly return an empty string for fv_status.

The issue appears to be on line 42:

     ENCRYPTIONEXTENTS=`grep -E "$EGREP_STRING\Has Encrypted Extents" $CORESTORAGESTATUS | sed -e's/\|//' | awk '{print $4}'`

On my system this gives a column of the word Yes:

```
grep -E "^\| *\Has Encrypted Extents" /private/tmp/corestorage.txt | sed -e's/\|//' | awk '{print $4}'
Yes
Yes
Yes
Yes
Yes
```
which then fails to match on line 122

    if [ "$ENCRYPTIONEXTENTS" = "Yes" ]; then

leaving the output of the script empty.  In my case changing line 42 to be:

    ENCRYPTIONEXTENTS=`grep -E "$EGREP_STRING\Has Encrypted Extents" $CORESTORAGESTATUS | sed -e's/\|//' | awk '{print $4}' | uniq`

generates a single Yes for output and causes the match to succeed on line 122.  I think this means that a single encrypted partition among many will generate this output.

**Comment by bochoven** [comment]
Latest release has support for FV on multiple disks
