### ISSUE TITLE
Feature request: help button with customisable URL

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/munkireport-php#1033]
Would be nice to have a button top right for Help - this should open a URL that could be defined in config

**Comment by ofirgalcon** [comment]
Yes, exactly. What you suggest sounds perfect.

**Comment by ofirgalcon** [comment]
Make it open in a separate window/tab.

**Comment by danner26** [comment]
Check PR #1041

**Comment by ofirgalcon** [comment]
Doesn't work for me in v4
