### ISSUE TITLE
[WIP] No Encryption Key Found in Config while escrow disabled

### ISSUE THREAD

**Issue by danner26** [munkireport/munkireport-php#1035]
Latest WIP version:

I do not have filevault_escrow config enabled so there is no encryption key in my config, as well as there is no filevault_escrow table in my database, but when I run the migration it errors out with:

```
No encryption key found in config
--
started update: Fri Mar 23 2018 11:17:13 GMT-0400 (Eastern Daylight Time)
No encryption key found in config
stack trace follows:
in /secure/DEV/vendor/illuminate/database/Migrations/Migrator.php:417 FilevaultEscrowEncryptPlaintextKeys->__construct.
in /secure/DEV/vendor/illuminate/database/Migrations/Migrator.php:168 Illuminate\Database\Migrations\Migrator->resolve.
in /secure/DEV/vendor/illuminate/database/Migrations/Migrator.php:146 Illuminate\Database\Migrations\Migrator->runUp.
in /secure/DEV/vendor/illuminate/database/Migrations/Migrator.php:95 Illuminate\Database\Migrations\Migrator->runPending.
in /secure/DEV/app/controllers/database.php:79 Illuminate\Database\Migrations\Migrator->run.
in /secure/DEV/system/kissmvc_core.php:88 munkireport\controller\Database->migrate.
in /secure/DEV/system/kissmvc.php:17 KISS_Engine->__construct.
in /secure/DEV/public/index.php:147 Engine->__construct.
```

Instead of ignoring the migration step it errors out and stops there.

**Comment by danner26** [comment]
Looks like the latest release fixed that, but now I am getting the "base table or view not found"

Maybe add a clause if the table does not exist, create it?

**Comment by bochoven** [comment]
Did you modify the db manually?

**Comment by danner26** [comment]
I did not but it is possible another tech did by accident. If that is the case, how can we create it manually so it will migrate in the future?

**Comment by bochoven** [comment]
remove 2017_12_19_193803_filevault_escrow from the migration table, run migration again

**Comment by bochoven** [comment]
migrations stack on top of each other, so the first one creates the table, the second one makes adjustments (in this case I did not realise that there were people storing plaintext keys already)

**Comment by danner26** [comment]
Looks like that fixed it, thanks.
