### ISSUE TITLE
Feature request - Geekbench stats

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/munkireport-php#1044]
Display computer Geekbench stats (like MacTracker). Useful when searching for the fastest spare laptop available.

**Comment by WardsParadox** [comment]
Aren't the Geekbench stats generated from the machine?

**Comment by ofirgalcon** [comment]
There's a database of Mac results. MacTracker uses these. http://browser.geekbench.com/mac-benchmarks

**Comment by WardsParadox** [comment]
Just found that, and you can get the mac-benchmarks as a json file by appending a `.json` to the url.
https://browser.geekbench.com/mac-benchmarks.json

So the biggest thing would be to find a matching correlation. Looks like processor might be a good one. Might have some ideas here.

**Comment by WardsParadox** [comment]
take cpu.cpu data, split it and get the family-model number of processor like `i5-4258U` and find the corresponding stats. Wonder if I can filter the json more first.

**Comment by WardsParadox** [comment]
@ofirgalcon Not really, time got swamped with a bunch of things, both personal and professional. I see you have a module plugin for this going?

**Comment by ofirgalcon** [comment]
Well check this - https://github.com/ofirgalcon/geekbench (most of the hard work by tuxudo

**Comment by ofirgalcon** [comment]
Module available at https://github.com/ofirgalcon/geekbench
