### ISSUE TITLE
FR: Report the UID of Users

### ISSUE THREAD

**Issue by gmarnin** [munkireport/munkireport-php#1057]
It would be helpful if MR would show the UID along with the user name for the current user and for local administrators. At a minimum the UID should be displayed on the Mac summary page under the Users section and in the local admin report and listings.

**Comment by poundbangbash** [comment]
@gmarnin See if https://github.com/munkireport/munkireport-php/pull/1059 addresses your requests.

To test it out:
```
git remote add eholtam https://github.com/poundbangbash/munkireport-php
git fetch eholtam
git checkout add-user-uid
```

There are two database migrations that will need to be run and then a new client install will need to happen to get the uids sent to MR. 

-Eric

**Comment by gmarnin** [comment]
Tested on a local test environment. Looks good, nice addition. Thank you.

**Comment by mosen** [comment]
Got merged into wip so will be available at next release. Cheers gmarnin
