### ISSUE TITLE
Retire AuthLDAP in favour of ADLDAP2

### ISSUE THREAD

**Issue by bochoven** [munkireport/munkireport-php#1061]
ADLDAP2 has support for FreeIPA and OpenLDAP through schemas. ADLDAP2 is an actively developed library.

Changing would be simple: copy Auth_AD.php top Auth_LDAP and add the proper schema. Same could be done for FreeIPA.

**Comment by jelockwood** [comment]
The switch to ADLAP2 was part of the v3 upgrade and after a few initial teething problems with using schema entries now works. Presumably this ticket should now be closed?

**Comment by bochoven** [comment]
Do you have a working config for OpenLDAP @jelockwood ? I am not able to test at the moment.

**Comment by jelockwood** [comment]
Sorry no. At my current place of employment we only use FreeIPA so that is the only one I could test against.

**Comment by bochoven** [comment]
Could you share your (sanitised) FreeIPA config?

**Comment by jelockwood** [comment]
@bochoven 
Sure here are my FreeIPA entries from my config.php

```
$conf['auth']['auth_AD']['schema'] = 'FreeIPA';
$conf['auth']['auth_AD']['base_dn'] = 'cn=accounts,dc=internal,dc=domain,dc=com';
$conf['auth']['auth_AD']['account_prefix'] = 'uid=';
$conf['auth']['auth_AD']['account_suffix'] = ',cn=users,cn=accounts,dc=internal,dc=domain,dc=com';
$conf['auth']['auth_AD']['domain_controllers'] = array('freeipa.internal.domain.com'); //can be an array of servers
$conf['auth']['auth_AD']['mr_allowed_groups'] = array('mygroup'); //case sensitive
$conf['auth']['auth_AD']['use_tls'] = true;
```
It is possible - indeed likely that other variables are also possible, I believe some of the following might work but I did not need them. These would therefore need further testing as the value formats may not be correct.

```
$conf['auth']['auth_AD']['mr_allowed_users'] = array('myname');
$conf['auth']['auth_AD']['ad_port'] = 636;
$conf['auth']['auth_AD']['admin_username'] = 'uid=myname,cn=users,cn=accounts,dc=internal,dc=domain,dc=com'; //if needed to perform the search
$conf['auth']['auth_AD']['admin_password'] = 'mypassword'; //if needed to perform the search
```

Note: I believe it is more common with LDAP servers for the account_suffix to be like cn=users,dc=internal,dc=domain,dc=com but FreeIPA uses an extra level in its hierarchy i.e. the cn=accounts level.
