### ISSUE TITLE
FindMyMac status

### ISSUE THREAD

**Issue by robriley78** [munkireport/munkireport-php#1066]
Hi,

We have our computers grouped and clients can log in to see just their machines. However under security report Find My Mac shows figures for all of the machines on our system - not just the client's own. Clicking through only reveals only the client's own machines so it's just the overall figure that's wrong.

Thanks,

**Comment by tuxudo** [comment]
Thank you for this bug report. It should be fixed with PR #1067. You can test it out by editing the one file to match the file that has the changes.

**Comment by robriley78** [comment]
Amazing. Thanks.
