### ISSUE TITLE
Upgraded to MunkiReport 3.2.0.3397 and now get errors from a couple of Listings choices

### ISSUE THREAD

**Issue by jelockwood** [munkireport/munkireport-php#1078]
I have now managed to upgrade from MunkiReports 2.15.2 to 3.2.0.3397. This included modfying my config.php to stop using the PDO approach and to use the Eloquent/Laravel approach. I have managed to get LDAP authentication working and the MySQL config is now connecting successfully to my MariaDB (acting as a MySQL server) with SSL.

I then followed the instructions to Migrate the database i.e. upgrade it via the Web interface of Admin->Database. This ran and claimed to have completed successfully. The initial complaint about a FileVault escrow table was also fixed.

Unfortunately I am now getting some new errors, I got this when I tried accessing Listings->Security (the most important list for me)

`DataTables warning: table id=DataTables_Table_0 - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'security.ssh_groups' in 'field list'`

I got the following error from Listings->Extensions

`DataTables warning: table id=DataTables_Table_0 - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'extensions.developer' in 'field list'`

The Reports all seem to work without error, so it is just those two Listings.

**Comment by jelockwood** [comment]
Having upgraded to MunkiReports 3.x I then reviewed the list of enabled and available modules. When I activated the Listing->Applications module it also generated an error -

DataTables warning: table id=DataTables_Table_0 - SQLSTATE[42S02]: Base table or view not found: `1146 Table 'munkireport.applications' doesn't exist`

I thought I would try doing another database update/migrate. This time it is showing errors.

From the command line I get -

`ERROR: previous failed migration exists`

From the web gui I get -

```
started update: Mon May 14 2018 14:31:47 GMT+0100 (BST)
--
previous failed migration exists
stack trace follows:
in /usr/local/munkireport-php/vendor/illuminate/database/Migrations/Migrator.php:359 Homebrew->up.
in /usr/local/munkireport-php/vendor/illuminate/database/Migrations/Migrator.php:365 Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}.
in /usr/local/munkireport-php/vendor/illuminate/database/Migrations/Migrator.php:177 Illuminate\Database\Migrations\Migrator->runMigration.
in /usr/local/munkireport-php/vendor/illuminate/database/Migrations/Migrator.php:146 Illuminate\Database\Migrations\Migrator->runUp.
in /usr/local/munkireport-php/vendor/illuminate/database/Migrations/Migrator.php:95 Illuminate\Database\Migrations\Migrator->runPending.
in /usr/local/munkireport-php/app/controllers/database.php:79 Illuminate\Database\Migrations\Migrator->run.
in /usr/local/munkireport-php/system/kissmvc_core.php:88 munkireport\controller\Database->migrate.
in /usr/local/munkireport-php/system/kissmvc.php:17 KISS_Engine->__construct.
in /usr/local/munkireport-php/public/index.php:148 Engine->__construct.


```

**Comment by bochoven** [comment]
If you don't need the data, I would advise to remove the Homebrew table and the Homebrew migration.

**Comment by jelockwood** [comment]
There are three homebrew tables - 

homebrew
homebrew_info
homebrew_orig

and two records in the Migration table - 

homebrew
homebrew_info

Are you suggesting I simply delete all those?

I am not concerned with the current homebrew data in MunkiReports, presumably after deleting the above I can try another migrate and it would create new empty ones and these would then be repopulated by the MunkiReport clients when they check in.

**Comment by bochoven** [comment]
Delete all three if you don't care about the contents

**Comment by jelockwood** [comment]
Ok that has helped, Listings->Security now works, Listings->Extensions now works, Listings->Applications also works. Also Listings->HomeBrew works.

However Listings->HomeBrew_Info does not it gives the following.

`DataTables warning: table id=DataTables_Table_0 - SQLSTATE[42S02]: Base table or view not found: 1146 Table 'munkireport.homebrew_info' doesn't exist`

My Sequel Pro tool confirms the homebrew_info table does not exist.

Note: I deleted all three tables, and then did a Migration run again.

**Comment by bochoven** [comment]
Did you do a command line migration?

**Comment by bochoven** [comment]
If you remove the `homebrew_info` migration from the `migrations` table then you can run the migration command line again. It will recreate the table.

**Comment by bochoven** [comment]
```sql
DELETE FROM migrations WHERE migration = '2017_12_19_193901_homebrew_info';
```

**Comment by jelockwood** [comment]
Yep, that got it, looks like they are all working now.

Thanks, you can close this issue.
