### ISSUE TITLE
MariaDB 10.1  Index column size too large

### ISSUE THREAD

**Issue by MichalMMac** [munkireport/munkireport-php#1088]
I am trying to upgrade Munkirepot 2.15.2 to the latest 3.1.1.
I've run once again into issue with MariaDB 10.1 (My vesrion 10.1.26-MariaDB-0+deb9u1)

When I try to run `database/migrate.php` either on the database used by 2.15.2 or on the new empty database I get:

```
ERROR: SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes. (SQL: alter table `bluetooth` add index `bluetooth_serial_number_index`(`serial_number`))
```

This is know [issue](https://laravel-news.com/laravel-5-4-key-too-long-error ) with MariaDB. I followed advice in migration [guide](https://laravel.com/docs/master/migrations#creating-indexes) and tried to enable `innodb_large_prefix` (For this to work I set MariaDB to use BARRACUDA InnoDB file format and created all MunkiReport tables with `ROW_FORMAT=DYNAMIC`). However even with  `innodb_large_prefix` and its prerequisites enables I was unable to get around error above. I'll try this again in my dev environment more thoroughly.

My db config:
```
	$conf['connection'] = [
        'driver'    => 'mysql',
        'host'      => '127.0.0.1',
       'port'      => 3306,
       'database'  => '*database*',
      'username'  => '*username*',
      'password'  => '*password*',
      'charset'   => 'utf8mb4',
      'collation' => 'utf8mb4_unicode_ci',
      'strict'    => true,
      'engine'    => 'InnoDB',
      'options'   => [PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8mb4'],
	];
```

**Comment by MichalMMac** [comment]
I missed one thing. My colleague @VojtechMyslivec found a tip for laravel configuration. You have to set `ROW_FORMAT` in `engine` configurartion like this:

```
 'engine'    => 'InnoDB ROW_FORMAT=DYNAMIC',
```

Previously I tried to use `mysql_create_tbl_opts` variable which does not seem to be relevant used in v3.X at all.

**Comment by mosen** [comment]
I didn't replicate this issue on my MariaDB 10.3.7 installation, but I will attempt to change the default ROW_FORMAT as suggested.

**Comment by VojtechMyslivec** [comment]
The `ROW_FORMAT=DYNAMIC` is needed in MariaDB `< 10.1.32`. in `>= 10.1.32`, [innodb_default_row_format](https://mariadb.com/kb/en/library/xtradbinnodb-server-system-variables/#innodb_default_row_format) is introduced and set to `DYNAMIC` by default (as needed in munkireport).

Forcing `ROW_FORMAT=DYNAMIC` should not do any harm in any MariaDB version IMO.

**Comment by MichalMMac** [comment]
PR #1101 seems to deal with this.
