### ISSUE TITLE
Client Summary display does not populate with data

### ISSUE THREAD

**Issue by cdhw2018** [munkireport/munkireport-php#1090]
I've had Munkireport setup for a few days. It's going well so far, except:

The Client Summary display 

	https://myserver.xx.yy.zz/munkireports/index.php?/clients/detail/SERIAL_NUMBER

populates only:

	Est. Manufacture Date
	
	ARD / text1

with all other data fields empty.

The other, more-specific, displays selected with the Show menu on the same page all seem to populate correctly.

I have the Munkireport installation on MacOS Server (php v7.1) here:

	/Users/Shared/munki/munkireport-3
	
with a symbolic link from the web-server root to

	/Users/Shared/munki/munkireport-3/public

Setting 'debug' mode did not reveal any error messages.

Any ideas for how I can fix this would be welcome.

TIA

C.

**Comment by tuxudo** [comment]
Verify that your web server is using PHP 7, it may be installed, but it could be using PHP 5. You can check which version it is using by looking in the Show System Status page under the Admin tab.

**Comment by cdhw2018** [comment]
Thanks for replying. According to that page I have:

	PHP Version 7.1.13
	...
	Driver sqlite

I originally set up the system when the server (Sierra 10.12.6) had php5 installed, but I upgraded it per the instructions here:

https://github.com/munkireport/munkireport-php/wiki/Upgrading-PHP-for-Server.app

The only noticeable effect of the upgrade was that a placeholder (the Apple logo) in the top left of the report started being replaced with a photo of an iMac.

C.

**Comment by cdhw2018** [comment]
Success! I've just noticed that there were database updates pending under the

Admin > Database

menu. I clicked to install these and now the client details reports are populating nicely so I assume that's what was needed.

Thanks all

C.
