### ISSUE TITLE
Listings in Munkireport 3.1.1 error

### ISSUE THREAD

**Issue by macgurus** [munkireport/munkireport-php#1091]
Ever since I upgraded to Munkireport 3.1.1 all the listing options throw this error

DataTables warning: table id=DataTables_Table_0 - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

not sure why but all reports work. Listings do not. Any help is appreciated.

**Comment by bochoven** [comment]
Github issues are for bugs, for support please go to the Munkireport mailinglist or head over to the #munkireport channel on the macadmins slack
