### ISSUE TITLE
Business Listings - Loading data from server

### ISSUE THREAD

**Issue by macgurus** [munkireport/munkireport-php#1092]
I upgraded to Munkireport 3.1.1. Prior to that I was using LDAP and after I migrated I could not get LDAP to work even after following all the advice listed here

https://github.com/munkireport/munkireport-php/issues/1075
https://github.com/munkireport/munkireport-php/issues/993

I had to move back to local authentication, and after doing so my business listings do not load or show up and only say "Loading data from server"

I have made sure to use the same username as I had before with LDAP and added it to the admin role in the config.php. Machines report in and I can see them but I cant see my business listings. Any help is appreciated.

**Comment by bochoven** [comment]
Github issues are for bugs, for support please go to the Munkireport mailinglist or head over to the #munkireport channel on the macadmins slack
