### ISSUE TITLE
Fatal error  Connection failed: SQLSTATE[HY000] [2002] Connection refused

### ISSUE THREAD

**Issue by notverypc** [munkireport/munkireport-php#1095]
I'm configuring MR3 with a mysql database. 
When I test the connection to the database from the command line I can connect. 
When I did a `php database/migrate.php` the database was migrated without errors.
Now when I login to MR3 I get the following error `php database/migrate.php` 

My mysql config looks like this:
```$conf['connection'] = [
  'driver'    => 'mysql',
  'host'      => 'mysql-server',
  'port'      => 4583,
  'database'  => 'MunkiReport',
  'username'  => 'username',
  'password'  => 'password',
  'charset' => 'utf8',
  'collation' => 'utf8_general_ci',
  'strict' => true,
  'engine' => 'InnoDB ROW_FORMAT=DYNAMIC',
  ];```

**Comment by bochoven** [comment]
Please use Slack or the munkireport mailinglist for support
