### ISSUE TITLE
[q] Inventory

### ISSUE THREAD

**Issue by dnsBlah** [munkireport/munkireport-php#1111]
Hi all,

Is there anyone who uses munkireport for a complete inventory system as well?

I'd like to bury old inventory databases instead of having multiples..

Is there any way I can manually add 'other' devices in the munkireport as well? i.e. printers, windows workstations, network components (switches, routers etc)

I really love this tool, but the above would be a cherry on the cake :)

**Comment by bochoven** [comment]
There are no plans to add this, sorry
