### ISSUE TITLE
tuxudo memory module bug

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/munkireport-php#1145]
The module works great but the display on the client page is corrupted showing: "key 'translation:memory (en)' returned an object instead of string." instead of the label RAM

![image](https://user-images.githubusercontent.com/16665880/45261647-7eca0000-b3ff-11e8-838f-96ec5f838411.png)

**Comment by ofirgalcon** [comment]
Any reason why dns-column, icloud, ios devices, launch daemons, memory and teamviewer modules are not in main release? Most seem to work just fine.

**Comment by tuxudo** [comment]
This should be resolved with the Feb 25 commit to the memory module branch. A login/out and/or clearing of the cache may be needed for it to be fixed.

The iCloud module needs updating to properly work with 10.14 and Launch Daemons needs to be reworked in how it stores data. Currently working on other projects, but will resolve those issues when I have some free time.

**Comment by ofirgalcon** [comment]
I've had the memory module installed since April and logged in and out many times, used on multiple devices, always the same thing. This is the Feb 25 version. I only downloaded the module folder from the git branch, could this be the reason?  Am I missing other files?

**Comment by ofirgalcon** [comment]
It was my fault, I didn't download all the files.
