### ISSUE TITLE
Feature request - Filters key shortcut

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/munkireport-php#1147]
I like using D and C shortcuts. How about F for the Machine Group Filter?

**Comment by tuxudo** [comment]
Give PR 1150 a test, f to show the filter popup and shift-f to hide it again

**Comment by ofirgalcon** [comment]
I still have no clue about git and how to merge code from various pathces, test modules.

**Comment by ofirgalcon** [comment]
Has this feature been merged into v4? It doesn't seem to work.

**Comment by bochoven** [comment]
It's merged now. Available in wip
