### ISSUE TITLE
Bug - Caching Report graph ignores machine groups filters

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/munkireport-php#1154]
I think the same applies to a couple more modules but I need to check.

**Comment by ofirgalcon** [comment]
Other **reports** with same issue:

Certificates by Name
Munki Facts
Profiles

**Comment by ofirgalcon** [comment]
And the same is true for users that are supposed to only see a subset of computers - those 4 reports show them all computers.

**Comment by tuxudo** [comment]
Caching graph fixed with PR #1143

**Comment by tuxudo** [comment]
Profiles listing should be resolved with PR #1144
