### ISSUE TITLE
Bug - Filters don't work with Network Locations, Network VLANs, Client Registration widgets

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/munkireport-php#1161]
Selecting filters has no effect on these widgets

**Comment by bochoven** [comment]
The filters *do* work, just not live.

**Comment by ofirgalcon** [comment]
You're right, but the Network VLANs still show all the networks, even ones that are filtered and have 0 clients. Maybe the solution would be to not display VLANs with 0 clients.

**Comment by ofirgalcon** [comment]
This problem still exists in v4 with the Network Report - it shows all VLANs - even ones that are filtered out.

**Comment by bochoven** [comment]
Please refresh my memory. Not sure what exactly is the problem.

**Comment by ofirgalcon** [comment]
To reproduce go to filters and choose a group. Now go to Network Report - you can see all VLANS listed. I think same happens if you login as a user - you still see VLANs listed that you shouldn't.

**Comment by bochoven** [comment]
VLANS are not connected to machinegroups, so you would see all configured VLANS. This works as designed. Munkireport has no machine group based settings.

**Comment by ofirgalcon** [comment]
This is a potential security issue as it reveals info about network configs to people that shouldn't see them. Maybe it would make sense to hide VLANs that have 0 devices?

**Comment by ofirgalcon** [comment]
This would also be consistent with how WAN networks are handled - or am I missing something?

**Comment by bochoven** [comment]
Please file a Feature Request in the Network module
