### ISSUE TITLE
Highest Supported OS doesn't show 10.14

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/munkireport-php#1163]
EVen on computers that are already running 10.14 - highest supported OS is still 10.13.6. Even more strange is that it shows 10.13.5 as the highest possible - when the computer already has 10.13.6 installed.

![image](https://user-images.githubusercontent.com/16665880/46320105-b37f4080-c5d4-11e8-9726-745def4f369c.png)

**Comment by kevinmcox** [comment]
@ofirgalcon See the note here: https://github.com/munkireport/munkireport-php/tree/master/app/modules/supported_os

> Highest supported OS is manually updated by updating MunkiReport, may not always reflect maximum supported OS version

This is something that'll need to be updated in the next release of MR.
