### ISSUE TITLE
Port value in $conf['connection'] is not applied for mysql

### ISSUE THREAD

**Issue by sctthffnr** [munkireport/munkireport-php#1168]
The $conf associative array in config_default.php shows a 'port' key as an option, but that value is not applied when the mysql dsn is created. There is a function, getdbh() in app/helpers/site_helper.php, that creates the dsn, on line 83, which currently reads:

`$dsn = "mysql:host={$conn['host']};dbname={$conn['database']}";`

It should be:

`$dsn = "mysql:host={$conn['host']};port={$conn['port']};dbname={$conn['database']}";`

**Comment by bochoven** [comment]
tx for reporting
