### ISSUE TITLE
Make summary tab hide disabled modules

### ISSUE THREAD

**Issue by MagerValp** [munkireport/munkireport-php#1171]
It would be nice if `/app/views/client/summary_tab.php` respected `$conf['modules']`.

**Comment by gmarnin** [comment]
As of https://github.com/munkireport/munkireport-php/releases/tag/v5.1.0 you can customize the Client Summary Tab. See the Wiki: https://github.com/munkireport/munkireport-php/wiki/Client-Summary-Tab
