### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by digitalhealer** [munkireport/munkireport-php#1200]
I updated to the lastest docker build and I noticed the lastest dockerfile now includes 'ENV AUTH_METHODS NOAUTH' and it no longer prompts you to login when I go to my site

What would I set this to if I wanted munkireport to use the local accounts in the config.php?

**Comment by bochoven** [comment]
Don't use the wip container, auth is a bit broken at the moment if you use local accounts

**Comment by bochoven** [comment]
You can override AUTH_METHODS with an empty string

**Comment by digitalhealer** [comment]
That worked

Thanks for your help!!
