### ISSUE TITLE
AD Auth fail - fall at first hurdle

### ISSUE THREAD

**Issue by itsmartin-BOUFF** [munkireport/munkireport-php#1213]
I have been tasked with creating a Munki Server on Linux.
I have read the install instructions.
I am trying to get logins to the web front end to work with AD.
I cannot get it to work at all.
I tried local auth - that works fine, but they want AD with group permissions.
Any help would be gratefully accepted

Bouff

**Comment by itsmartin-BOUFF** [comment]
There is an older version already in use here, but need to migrate to Linux.
Also, the old one used config.php, and I am trying to translate the entries to the new .env format.

**Comment by bochoven** [comment]
Github issues are meant for bug reporting and feature requests. Please use the mailinglist or the #munkireport slack channel for general support questions
