### ISSUE TITLE
TOO MANY REDIRECTS

### ISSUE THREAD

**Issue by HaniAlshikh** [munkireport/munkireport-php#1219]
Hi, 

I'm trying to setup Munkireport-PHP on a mac mini running High Sierra using nginx 1.15.8 and i keep geeting "ERR_TOO_MANY_REDIRECTS". Can anyone please help?

I tried with apache and got the same error.
but using php -s localhost:8888 --docroot public works!!

![screenshot 2019-01-25 at 11 09 04](https://user-images.githubusercontent.com/39484930/51739614-33ed1400-2092-11e9-9157-56998da083a4.png)
[nginx.conf.txt](https://github.com/munkireport/munkireport-php/files/2795621/nginx.conf.txt)

**Comment by bochoven** [comment]
I’m not well versed in NGINX config, but you can run 

curl -v https://munki.xxx/index.php?/auth/login <https://munki.xxx/index.php?/auth/login>

To see where you get redirected to, which may help troubleshoot your issue.

-Arjen

**Comment by HaniAlshikh** [comment]
@bochoven Thanks for helping.
the redirection happens form https://munki.***/index.php? to https://munki.***/index.php?/auth/login and vice versa. So if i don't have authentication setup it will keep looping between this two URLs.
 
![screenshot 2019-01-25 at 12 56 47](https://user-images.githubusercontent.com/39484930/51744770-1bd0c100-20a1-11e9-83c0-42a5dbefdca5.png)

But if i have, it will redirect me to /auth/login and succeed but it won't be able to redirect from this page, even if i entered the right username and password.
![screenshot 2019-01-25 at 12 47 05](https://user-images.githubusercontent.com/39484930/51744805-3d31ad00-20a1-11e9-9852-7983f274f1f6.png)

[curl_output.txt](https://github.com/munkireport/munkireport-php/files/2795985/curl_output.txt)

**Comment by HaniAlshikh** [comment]
I don't know what was the problem exactly, but i think it was some sort of conflict between Apache and Nginx ( i used to run MR-PHP with apache before switching to Nginx). Anyway, i had to reconfigure my server from the scratch to fix this problem.

**Comment by jby** [comment]
@HaniAlshikh what reconfiguration did you end up doing?
I'm having the exakt same problem, and I'm at a loss as what to do...

**Comment by HaniAlshikh** [comment]
@jby it's been a long time since I did this and I don't really remember, however, what I remember is running profile manager, which runs a PHP server on its on and I was using brew to setup another PHP server which I think caused the redirects. So make sure there is only one instance of PHP running on your server and take a look at the attached Nginx configuration (change username to an admin user). hope it helps.
[ngx.txt](https://github.com/munkireport/munkireport-php/files/6190662/ngx.txt)

**Comment by jby** [comment]
I found it, with some assistance from @bochoven: https://stackoverflow.com/questions/9203320/php-fpm-and-nginx-session-problems
`chown -R nginx:nginx /var/lib/php/session/` solved it
