### ISSUE TITLE
Cannot Find config.php in Docker Image

### ISSUE THREAD

**Issue by NickFuscoMeriden** [munkireport/munkireport-php#1224]
Hello,
I recently installed munkireport via the docker image.
I do not see the config.php file in /var/munkireport/ 

```
root@munkireport:/var/munkireport# ls 
CHANGELOG.md  _config.yml  composer.json  docs	       storage
Dockerfile    app	   composer.lock  index.html   system
LICENSE.md    bootstrap    database	  phpunit.xml  tests
README.md     build	   docker	  public       vendor
```

or in its sub folders. 
I looked in app and in app i looked in config but it wasn't there.
```
root@munkireport:/var/munkireport/app# ls
config	controllers  db  helpers  lib  models  views
```
```
root@munkireport:/var/munkireport/app/config# ls
app.php  auth  auth.php  dashboard.php	db.php	widget.php

```
Any direction would be helpful. Just want to get in so i can make an actual username with a password.

Thanks
Nick

**Comment by bochoven** [comment]
MunkiReport now uses environment variables for configuration. See the wiki: https://github.com/munkireport/munkireport-php/wiki/Server-Configuration
