### ISSUE TITLE
Bug: Excel export not available for admins

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/munkireport-php#1229]
normal user

![image](https://user-images.githubusercontent.com/16665880/53294130-436a9480-37d9-11e9-98a3-74e557d921dc.png)

admin

![image](https://user-images.githubusercontent.com/16665880/53294132-c3442f00-37d8-11e9-81de-25c2f87c6d57.png)

**Comment by flammable** [comment]
Seems to be an issue with Safari.

**Comment by bochoven** [comment]
be87e9057c22b252aaa4d879579d1685fce231ec
