### ISSUE TITLE
External Displays widget not working v4

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/munkireport-php#1230]
show/report/machine/hardware

v4
![image](https://user-images.githubusercontent.com/16665880/53295398-6eadad80-37f2-11e9-9ced-6ed3636721aa.png)

v3
![image](https://user-images.githubusercontent.com/16665880/53295401-7bca9c80-37f2-11e9-91f5-1d51ca97e9e5.png)

**Comment by tuxudo** [comment]
This has been resolved in the module repo.
