### ISSUE TITLE
VLANs not displaying correctly in Network Report

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/munkireport-php#1231]
Was working in v3, but in v4 my settings are ignored. The ip4routers.yml file was created with the upgrade script.

It looks something like this:

```
148:
    - 10.148.41.%
38:
    - 10.38.147.%
40:
    - 10.40.103.%
45:
    - 10.45.103.%
137:
    - 192.168.137.%
```

The result:

![image](https://user-images.githubusercontent.com/16665880/53328676-6a60bd80-38e2-11e9-963c-457732fd48a6.png)

**Comment by bochoven** [comment]
I can't replicate your issue. Is the`ip4routers.yml` located at `local/module_configs` ?

**Comment by ofirgalcon** [comment]
Yes it is. I have some entries in it that look like this

'SW Kip 20':
     10.12.5.%

**Comment by bochoven** [comment]
Please validate your `.yml` file. You can use something like: https://www.json2yaml.com and see if the structure comes out ok.

**Comment by ofirgalcon** [comment]
It seems to OK. Maybe I will rebuild it and see what happens.
