### ISSUE TITLE
 pending_apple and pending_munki "This widget cannot be found"

### ISSUE THREAD

**Issue by crsleeth** [munkireport/munkireport-php#1236]
Using MunkiReport 4.0.2.3701, PHP 7.2.15-0ubuntu0.18.04.1, and MariaDB 10.3.13 the site is fully working except on the default dashboard I'm getting two errors of "Unknown widget" and "This widget cannot be found" for the widgets pending_apple and pending_munki. I've verified pending_apple_widget.php and pending_munki_widget.php exist in /var/munkireport/vendor/munkireport/managedinstalls/views. I don't think its a permissions issue because no other modules are having issues--permissions for all modules is at 664 and ownership is www-data:www-data.

**Comment by bochoven** [comment]
You need te enable the 'managedinstalls' module in your configuration for the widgets to load.
