### ISSUE TITLE
Default timeout too short

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/munkireport-php#1237]
I find some modules like applications and fonts can take up to 90 seconds on some systems. I have an idle macmini server with SSD yet applications takes 80 secs.

**Comment by rickheil** [comment]
My $0.02 as the author of a module (Sophos) that requires configuring a longer timeout: I think the default one is appropriate to prevent munki runs from getting unnecessarily long. Admins who need more time can easily add it with a config profile. Perhaps the solution is more in optimization of code and in documenting the ability to increase the timeout.

**Comment by bochoven** [comment]
I’m with Rick on this issue
