### ISSUE TITLE
network module - bond interface not displayed

### ISSUE THREAD

**Issue by psaintemarie** [munkireport/munkireport-php#1241]
I have a MacPro5,1 with munkireport 4.0.2.3701 running and on the network listing module, it doesn't show the bond interface for en0 + en1.

```➜ ifconfig bond0
bond0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=b<RXCSUM,TXCSUM,VLAN_HWTAGGING>
	ether e8:06:88:ce:07:5f
	inet6 fe80::871:e8f0:abba:b986%bond0 prefixlen 64 secured scopeid 0x12
	inet 10.18.42.41 netmask 0xffffff00 broadcast 10.18.42.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (1000baseT <full-duplex>)
	status: active
	bond interfaces: en0 en1```

**Comment by tuxudo** [comment]
This has been fixed in the dns branch of the network module rewrite: https://github.com/tuxudo/network/tree/dns Make sure to run the database migrations and rebuild the client package
