### ISSUE TITLE
Doesn't successfully install via munki, only by hand

### ISSUE THREAD

**Issue by sau70networkadmin** [munkireport/munkireport-php#1246]
Summary: I have munkireport set as a managedinstall for my clients. They see that they need it, and they see it and download it successfully, and it appears to install happily, but then they start all over again on the next munki check, and I never actually get the client to appear in the munkireport console unless I install the munkireport pkg by hand. 

Details:

Output from a managedsoftwareupdate -v run on a High Sierra client:

----------------
  * Processing manifest item munkireport for install
    Looking for detail for: munkireport, version latest...
    Considering 2 items with name munkireport from catalog main
    Considering item munkireport, version 2.15.3 with minimum os version required 10.5.0
    Our OS version is 10.12.6
    Found munkireport, version 2.15.3 in catalog main
    Looking for package com.github.munkireport, version 2.15.3
    Need to install munkireport
    Downloading munkireport-2.15.2.pkg from utilities/munkireport-2.15.2.pkg
    Looking for updates for: munkireport
    Looking for updates for: munkireport-2.15.3
    Looking for updates for: munkireport--2.15.3
...
    The following items will be installed or upgraded:
        + munkireport-2.15.3
            Adds reporting capability to Managed Software Center.

Run managedsoftwareupdate --installonly to install the downloaded updates.
----------------

This is the output in /var/log/install.log after I run managedsoftwareupdate --installonly:

----------------
Apr  3 12:05:39 complit09 installer[27995]: Referenced component packages (1) trustLevel=100
Apr  3 12:05:39 complit09 installer[27995]: -[IFPKGDerivedDocument sortedPackageLocations]: result = (
            "file://localhost"
        )
Apr  3 12:05:39 complit09 installer[27995]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: location = file://localhost
Apr  3 12:05:39 complit09 installer[27995]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Library/Managed%20Installs/Cache/munkireport-2.15.2.pkg
Apr  3 12:05:39 complit09 installer[27995]: Set authorization level to root for session
Apr  3 12:05:39 complit09 installer[27995]: Administrator authorization granted.
Apr  3 12:05:39 complit09 installer[27995]: Will use PK session
Apr  3 12:05:39 complit09 installer[27995]: Using authorization level of root for IFPKInstallElement
Apr  3 12:05:39 complit09 installer[27995]: Starting installation:
Apr  3 12:05:39 complit09 installer[27995]: Configuring volume "Macintosh HD"
Apr  3 12:05:39 complit09 installer[27995]: Preparing disk for local booted install.
Apr  3 12:05:39 complit09 installer[27995]: Free space on "Macintosh HD": 890.25 GB (890252058624 bytes).
Apr  3 12:05:39 complit09 installer[27995]: Create temporary directory "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T//Install.27995CCEvHZ"
Apr  3 12:05:39 complit09 installer[27995]: IFPKInstallElement (1 packages)
Apr  3 12:05:39 complit09 installd[498]: PackageKit: Adding client PKInstallDaemonClient pid=27995, uid=0 (/usr/sbin/installer)
Apr  3 12:05:40 complit09 installer[27995]: PackageKit: Enqueuing install with framework-specified quality of service (utility)
Apr  3 12:05:40 complit09 installd[498]: PackageKit: ----- Begin install -----
Apr  3 12:05:40 complit09 installd[498]: PackageKit: request=PKInstallRequest <1 packages, destination=/>
Apr  3 12:05:40 complit09 installd[498]: PackageKit: packages=(
            "PKLeopardPackage <file://localhost/Library/Managed%20Installs/Cache/munkireport-2.15.2.pkg>"
        )
Apr  3 12:05:40 complit09 installd[498]: PackageKit: Session UUID file exists - will not overwrite /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/3BC84EEF-9A43-4D8C-9AC0-CCBF674409DB.activeSandbox
Apr  3 12:05:40 complit09 installd[498]: PackageKit: Will do receipt-based obsoleting for package identifier com.github.munkireport (prefix path=/)
Apr  3 12:05:40 complit09 installd[498]: PackageKit: Extracting file://localhost/Library/Managed%20Installs/Cache/munkireport-2.15.2.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/3BC84EEF-9A43-4D8C-9AC0-CCBF674409DB.activeSandbox/Root, uid=0)
Apr  3 12:05:40 complit09 installd[498]: PackageKit: prevent user idle system sleep
Apr  3 12:05:40 complit09 installd[498]: PackageKit: suspending backupd
Apr  3 12:05:40 complit09 installd[498]: PackageKit: Executing script "./preinstall" in /private/tmp/PKInstallSandbox.N5qhlJ/Scripts/com.github.munkireport.8xejYN
Apr  3 12:05:40 complit09 install_monitor[28000]: Temporarily excluding: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Apr  3 12:05:40 complit09 installd[498]: ./preinstall: - Uninstalling appusage
Apr  3 12:05:40 complit09 installd[498]: ./preinstall: - Uninstalling backup2go
Apr  3 12:05:40 complit09 installd[498]: ./preinstall: - Uninstalling caching
Apr  3 12:05:40 complit09 installd[498]: ./preinstall: - Uninstalling certificate
Apr  3 12:05:40 complit09 installd[498]: ./preinstall: - Uninstalling crashplan
Apr  3 12:05:40 complit09 installd[498]: ./preinstall: - Uninstalling deploystudio
Apr  3 12:05:40 complit09 installd[498]: ./preinstall: - Uninstalling displays_info
Apr  3 12:05:40 complit09 installd[498]: ./preinstall: - Uninstalling fonts
Apr  3 12:05:40 complit09 installd[498]: ./preinstall: - Uninstalling gpu
Apr  3 12:05:40 complit09 installd[498]: ./preinstall: - Uninstalling gsx
Apr  3 12:05:40 complit09 installd[498]: ./preinstall: - Uninstalling homebrew
Apr  3 12:05:40 complit09 installd[498]: ./preinstall: - Uninstalling homebrew_info
Apr  3 12:05:40 complit09 installd[498]: ./preinstall: - Uninstalling location
Apr  3 12:05:40 complit09 installd[498]: ./preinstall: - Uninstalling mbbr_status
Apr  3 12:05:40 complit09 installd[498]: ./preinstall: - Uninstalling sccm_status
Apr  3 12:05:40 complit09 installd[498]: ./preinstall: - Uninstalling servermetrics
Apr  3 12:05:40 complit09 installd[498]: ./preinstall: - Uninstalling service
Apr  3 12:05:40 complit09 installd[498]: ./preinstall: - Uninstalling smart_stats
Apr  3 12:05:40 complit09 installd[498]: PackageKit: Using trashcan path /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/PKInstallSandboxTrash/3BC84EEF-9A43-4D8C-9AC0-CCBF674409DB.sandboxTrash for sandbox /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/3BC84EEF-9A43-4D8C-9AC0-CCBF674409DB.activeSandbox
Apr  3 12:05:40 complit09 installd[498]: PackageKit: Shoving /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/3BC84EEF-9A43-4D8C-9AC0-CCBF674409DB.activeSandbox/Root (1 items) to /
Apr  3 12:05:40 complit09 installd[498]: PackageKit: Executing script "./postinstall" in /private/tmp/PKInstallSandbox.N5qhlJ/Scripts/com.github.munkireport.8xejYN
Apr  3 12:05:40 complit09 installd[498]: PackageKit: Writing receipt for com.github.munkireport to /
Apr  3 12:05:40 complit09 installd[498]: Installed "munkireport-2.15.2" ()
Apr  3 12:05:40 complit09 install_monitor[28000]: Re-included: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Apr  3 12:05:41 complit09 installd[498]: PackageKit: releasing backupd
Apr  3 12:05:41 complit09 installd[498]: PackageKit: allow user idle system sleep
Apr  3 12:05:41 complit09 installd[498]: PackageKit: ----- End install -----
Apr  3 12:05:41 complit09 installd[498]: PackageKit: 1.4s elapsed install time
Apr  3 12:05:41 complit09 installd[498]: PackageKit: Running idle tasks
Apr  3 12:05:41 complit09 installd[498]: PackageKit: Removing client PKInstallDaemonClient pid=27995, uid=0 (/usr/sbin/installer)
Apr  3 12:05:41 complit09 installd[498]: PackageKit: Done with sandbox removals
Apr  3 12:05:42 complit09 installer[27995]: Removing temporary directory "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T//Install.27995CCEvHZ"
Apr  3 12:05:42 complit09 installer[27995]: Finalize disk "Macintosh HD"
Apr  3 12:05:42 complit09 installer[27995]: Notifying system of updated components
Apr  3 12:05:42 complit09 installer[27995]: **** Summary Information ****
Apr  3 12:05:42 complit09 installer[27995]:   Operation      Elapsed time
Apr  3 12:05:42 complit09 installer[27995]: -----------------------------
Apr  3 12:05:42 complit09 installer[27995]:        zero      0.00 seconds
Apr  3 12:05:42 complit09 installer[27995]:        disk      0.02 seconds
Apr  3 12:05:42 complit09 installer[27995]:     install      2.07 seconds
Apr  3 12:05:42 complit09 installer[27995]:     -total-      2.09 seconds
----------------

Then, if I run managedsoftwareupdate again, it thinks it needs it again, downloads it again, etc. Notably, it also appears to trigger the various munkireport processes, suggesting that munkireport DID install successfully on the prior run:

`
...
Finishing...
    Getting info on currently installed applications...
    Performing postflight tasks...
    postflight stdout:     Munkireport: # Executing scripts in postflight.d
    Munkireport: Running inventory_add_plugins.py
    Munkireport: Adding 10 plugins
    Munkireport: Running managedinstalls.py
    Munkireport: Running munki_facts.py
    Munkireport: Running munkireport.py
    Munkireport: Requesting applications
    Munkireport: Requesting profile
    Munkireport: Requesting inventory
    Munkireport: Requesting printer
    Munkireport: Requesting munkireportinfo
    Munkireport: Requesting timemachine
    Munkireport: Requesting usage_stats
    Munkireport: Requesting localadmin
    Munkireport: Requesting directory_service
    Munkireport: Requesting munkireport
    Munkireport: Requesting warranty
    Munkireport: Requesting disk_report
    Munkireport: Requesting user_sessions
    Munkireport: Requesting managedinstalls
    Munkireport: Requesting munki_facts
    Munkireport: Requesting installhistory
    Munkireport: Requesting softwareupdate
    Munkireport: Requesting network
    Munkireport: Requesting munkiinfo
    Munkireport: Requesting crashplan
    Munkireport: Need to update warranty (29B)
    Munkireport: Need to update installhistory (121KB)
    Munkireport: Need to update reportdata (372B)
    Munkireport: Need to update localadmin (12B)
    Munkireport: Need to update crashplan (61B)
    Munkireport: Need to update network (473B)
    Munkireport: Need to update disk_report (768B)
    Munkireport: Need to update timemachine (542B)
    Munkireport: Need to update managedinstalls (17KB)
    Munkireport: Need to update inventory (254KB)
    Munkireport: Need to update directory_service (876B)
    Munkireport: Need to update munkireport (3KB)
    Munkireport: Need to update profile (13KB)
    Munkireport: Need to update printer (1KB)
    Munkireport: Need to update munkireportinfo (2KB)
    Munkireport: Need to update munkiinfo (3KB)
    Munkireport: Need to update user_sessions (154KB)
    Munkireport: Need to update applications (210KB)
    Munkireport: Need to update softwareupdate (678B)
    Munkireport: Need to update usage_stats (2KB)
    Munkireport: Need to update munki_facts (947B)
    Munkireport: Sending items (783KB)
    Munkireport: Server info: starting: warranty
Server info: warranty: current status: Can't lookup warranty
Server info: starting: installhistory
Server info: starting: reportdata
Server info: starting: localadmin
Server info: starting: crashplan
Server info: starting: network
Server info: starting: disk_report
Server info: starting: timemachine
Server info: starting: managedinstalls
Server info: starting: inventory
Server info: starting: directory_service
Server info: starting: munkireport
Server info: starting: profile
Server info: starting: printer
Server info: starting: munkireportinfo
Server info: starting: munkiinfo
Server info: starting: user_sessions
Server info: starting: applications
Server info: starting: softwareupdate
Server info: starting: usage_stats
Server info: starting: munki_facts
Done.
`
But, nothing for this client ever appears in my munkireport console.

If I *manually* install the .pkg (by downloading it from my munki repo and installing via the gui), then the client DOES start actually reporting in. 

The client munki version is 3.6.0.3721. Here's my munkireport pkginfo in case that helps (derived from autopkg recipe):

`
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>_metadata</key>
	<dict>
		<key>created_by</key>
		<string>admin</string>
		<key>creation_date</key>
		<date>2019-03-29T18:59:29Z</date>
		<key>munki_version</key>
		<string>3.5.1.3622</string>
		<key>os_version</key>
		<string>10.14.4</string>
	</dict>
	<key>autoremove</key>
	<false/>
	<key>allow_untrusted</key>
	<true/>
	<key>catalogs</key>
	<array>
		<string>main</string>
	</array>
	<key>description</key>
	<string>Munkireport is a reporting tool.</string>
	<key>display_name</key>
	<string>Munkireport</string>
	<key>installed_size</key>
	<integer>117</integer>
	<key>installer_item_hash</key>
	<string>9f991885773e937df8f07ccfa2c58b662d728023e7c332bc01c54fe569c7a405</string>
	<key>installer_item_location</key>
	<string>apps/munkireport-4.0.2.pkg</string>
	<key>installer_item_size</key>
	<integer>32</integer>
	<key>minimum_os_version</key>
	<string>10.5.0</string>
	<key>name</key>
	<string>Munkireport</string>
	<key>receipts</key>
	<array>
		<dict>
			<key>installed_size</key>
			<integer>117</integer>
			<key>packageid</key>
			<string>com.github.munkireport</string>
			<key>version</key>
			<string>4.0.2</string>
		</dict>
	</array>
	<key>unattended_install</key>
	<true/>
	<key>uninstall_method</key>
	<string>removepackages</string>
	<key>uninstallable</key>
	<true/>
	<key>version</key>
	<string>4.0.2</string>
</dict>
</plist>
`

Thank you for any light you can shed.

**Comment by sau70networkadmin** [comment]
I failed to mention, once I've installed it by hand, managedsoftwarecenter stops trying to reinstall it.

**Comment by bochoven** [comment]
Github issues are for bug reporting and feature requests. If you want help setting up MunkiReport, please visit the #munkireport channel on https://macadmins.slack.com or ask on the MunkiReport mailinglist: https://github.com/munkireport/munkireport-php#mailinglists
