### ISSUE TITLE
Can't write to SQLite db w/ 4.1.2; and NGINX documentation is confusing if not outright incorrect

### ISSUE THREAD

**Issue by fseesink** [munkireport/munkireport-php#1248]
I've been using munkireport for years, and recently changed jobs.  I've been trying to spin up a new instance of munkireport using the latest (4.1.2) tar.gz file, a very simple setup using Ubuntu 18.04 LTS with NGINX, PHP7.2, and using the SQLite database.  And I have been having one heckuva time doing so.  No matter what I do, I can't get past the fact it appears unable to write to the database.  To say it's been frustrating would be an understatement.

Now I'm well aware of dealing with file permissions, and I've made sure that www-data owns all the necessary directories and can write to the directory ./app/db/.  In fact, when I ran the database migration step to initialize the SQLite database, I did so using

`sudo -u www-data php database/migrate.php`

from the main munkireport-php directory, and sure enough, it generated the appropriate db.sqlite file where expected.  However, when I visit the site, every time I get a 

> Fatal error
> Connection failed: SQLSTATE[HY000] [14] unable to open database file
> 
> Try again

message.

Now I have no trouble setting up NGINX.  I used Apache for eons, and a few years back I got into using NGINX instead for performance reasons.  And frankly, it's a lot easier to configure.  And I noticed that in v4, the setup involves setting the document root to the munkireport/public directory, thereby keeping the rest of the app, notably munkireport/app/db/ etc. out of the webroot.

However, I suspect this may well be the reason the app is unable to write to the SQLite database.  The migration step is done from the CLI, so no worries there as the code was running as user www-data.  And in older versions of munkireport-php, the SQLite database lived inside the document root, just protected using things like .htaccess files.

But now that SQLite file lives outside the webroot, and most webservers do not allow PHP code to access such files.  Or am I missing something?  (This, by the way, won't manifest itself with MySQL, as you typically connect to it using either IP:port or a socket, but in either case, it's not a file system/directory boundary issue.  But MySQL is overkill for the setup I'm doing, and at least until now, I've always found SQLite performed just fine for my use case.)

Now in the process of all this, I also found the instructions regarding configuring NGINX here to be extremely confusing:

https://github.com/munkireport/munkireport-php/wiki/NGINX

First of all, that symbolic link statement makes no sense.  Where it says

> Assuming you have setup the proper symbolic link in the webroot:
> 
> ln -s /path/to/web/root/report /path/to/munkireport/public

that's _backwards_.  That command will create a symbolic link FROM /path/to/web/root/report which will be located inside /path/to/munkireport/public.  That is, if you type

`cd /path/to/munkireport/public`
`ls -al`

you will see what appears to be a directory named `report` which links to the location /path/to/web/root/report, assuming there even IS such a directory.  I doubt this is what was intended, as it makes no sense.

Next, the configuration snippet provided is also a bit confusing:
____
The following location block should work to serve MunkiReport out of the /report subdirectory:

```
root     /path/to/web/root;

location /report {
    autoindex on;
    location ~* \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
        fastcgi_param SCRIPT_FILENAME  /media/Data/$fastcgi_script_name;
    }
}
```
____

What exactly is the purpose of the `fastcgi_param` line?  And where exactly is this `/media/Data/` directory referenced?  And do we really want to have autoindex enabled here?

**Comment by fseesink** [comment]
Not sure if this is tied together or not, or if it will help or hurt track down the issue, but even though I get those failure messages, when I reload the page or click the 'Try again' link, the main dashboard does load, but I do then see under 'Events'

> Request Failed: parsererror, SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

And going to 'Listings | Clients' shows

> DataTables warning: table id=DataTables_Table_0 - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

**Comment by fseesink** [comment]
Ok, I'm a a loss.  I can't figure out what's causing this.  I've now gone back and removed the `./app/db/db.sqlite` file and done some testing.  Unless said otherwise, I'm sitting at the root of the application directory.  If I change the `.env` config file so that it reads

`CONNECTION_DATABASE="db/db.sqlite"`

as indicated on this wiki page:  https://github.com/munkireport/munkireport-php/wiki/Server-Configuration

and then try to run

`sudo -u www-data php database/migrate.php`

it fails.  If I set it back to

`CONNECTION_DATABASE="app/db/db.sqlite"`

and run it, I get the following:

> $ sudo -u www-data php database/migrate.php
Migrating: 0100_00_00_000001_timemachine_schema_v1
Migrated:  0100_00_00_000001_timemachine_schema_v1
Migrating: 0213_00_00_000001_add_columns_for_pmset_data
Migrated:  0213_00_00_000001_add_columns_for_pmset_data
Migrating: 0213_00_00_000001_add_dsconfigad_data
Migrated:  0213_00_00_000001_add_dsconfigad_data
Migrating: 0213_00_00_000001_add_filevault_users
Migrated:  0213_00_00_000001_add_filevault_users
Migrating: 0213_00_00_000001_bluetooth_model_columns_to_integers
Migrated:  0213_00_00_000001_bluetooth_model_columns_to_integers
Migrating: 0213_00_00_000001_cleanup_hash_table
Migrated:  0213_00_00_000001_cleanup_hash_table
Migrating: 0213_00_00_000001_convert_physical_memory
Migrated:  0213_00_00_000001_convert_physical_memory
Migrating: 0213_00_00_000001_installhistory_fix_indexes
Migrated:  0213_00_00_000001_installhistory_fix_indexes
Migrating: 0213_00_00_000001_inventoryitem_fix_indexes
Migrated:  0213_00_00_000001_inventoryitem_fix_indexes
Migrating: 0213_00_00_000001_location_stale_location_columns
Migrated:  0213_00_00_000001_location_stale_location_columns
Migrating: 0213_00_00_000001_multiple_disks_addition
Migrated:  0213_00_00_000001_multiple_disks_addition
Migrating: 0213_00_00_000001_munkireport_add_unique_index
Migrated:  0213_00_00_000001_munkireport_add_unique_index
Migrating: 0213_00_00_000001_network_model_fix_ipv4router
Migrated:  0213_00_00_000001_network_model_fix_ipv4router
Migrating: 0213_00_00_000001_printer_fix_indexes
Migrated:  0213_00_00_000001_printer_fix_indexes
Migrating: 0213_00_00_000001_reportdata_fix_indexes
Migrated:  0213_00_00_000001_reportdata_fix_indexes
Migrating: 0213_00_00_000001_security_add_ssh
Migrated:  0213_00_00_000001_security_add_ssh
Migrating: 0213_00_00_000002_bluetooth_all_devices_in_separate_db_row
Migrated:  0213_00_00_000002_bluetooth_all_devices_in_separate_db_row
Migrating: 0213_00_00_000002_directory_service_fix_indexes
Migrated:  0213_00_00_000002_directory_service_fix_indexes
Migrating: 0213_00_00_000002_disk_report_fix_indexes
Migrated:  0213_00_00_000002_disk_report_fix_indexes
Migrating: 0213_00_00_000002_filevault_status_fix_indexes
Migrated:  0213_00_00_000002_filevault_status_fix_indexes
Migrating: 0213_00_00_000002_inventoryitem_rename_serialcolumn
Migrated:  0213_00_00_000002_inventoryitem_rename_serialcolumn
Migrating: 0213_00_00_000002_machine_add_indexes
Migrated:  0213_00_00_000002_machine_add_indexes
Migrating: 0213_00_00_000002_munkireport_fix_indexes
Migrated:  0213_00_00_000002_munkireport_fix_indexes
Migrating: 0213_00_00_000002_network_fix_indexes
Migrated:  0213_00_00_000002_network_fix_indexes
Migrating: 0213_00_00_000002_reportdata_add_uptime
Migrated:  0213_00_00_000002_reportdata_add_uptime
Migrating: 0213_00_00_000002_security_add_ard
Migrated:  0213_00_00_000002_security_add_ard
Migrating: 0213_00_00_000003_inventoryitem_max_pathlength
Migrated:  0213_00_00_000003_inventoryitem_max_pathlength
Migrating: 0213_00_00_000003_machine_add_cpu
Migrated:  0213_00_00_000003_machine_add_cpu
Migrating: 0213_00_00_000003_munkireport_bigger_blob
Migrated:  0213_00_00_000003_munkireport_bigger_blob
Migrating: 0213_00_00_000003_reportdata_add_group
Migrated:  0213_00_00_000003_reportdata_add_group
Migrating: 0213_00_00_000003_security_add_firmwarepw
Migrated:  0213_00_00_000003_security_add_firmwarepw
Migrating: 0213_00_00_000004_machine_osversion_integer
Migrated:  0213_00_00_000004_machine_osversion_integer
Migrating: 0213_00_00_000004_munkireport_new
Migrated:  0213_00_00_000004_munkireport_new
Migrating: 0213_00_00_000004_security_add_indexes
Migrated:  0213_00_00_000004_security_add_indexes
Migrating: 0213_00_00_000005_machine_add_buildversion
Migrated:  0213_00_00_000005_machine_add_buildversion
Migrating: 0215_00_00_000001_certificate_add_columns
Migrated:  0215_00_00_000001_certificate_add_columns
Migrating: 0215_00_00_000002_certificate_bigint_cert_exp_time
Migrated:  0215_00_00_000002_certificate_bigint_cert_exp_time
Migrating: 0215_00_00_000002_power_fix_indexes
Migrated:  0215_00_00_000002_power_fix_indexes
Migrating: 0215_00_00_000002_timemachine_remove_fake_null
Migrated:  0215_00_00_000002_timemachine_remove_fake_null
Migrating: 0215_00_00_000003_disk_report_add_media_type
Migrated:  0215_00_00_000003_disk_report_add_media_type
Migrating: 0215_00_00_000003_power_remove_fake_null
Migrated:  0215_00_00_000003_power_remove_fake_null
Migrating: 0215_00_00_000004_power_schedule_text
Migrated:  0215_00_00_000004_power_schedule_text
Migrating: 0215_00_00_000005_security_add_firewall_state
Migrated:  0215_00_00_000005_security_add_firewall_state
Migrating: 1000_00_00_000001_extensions_php_migrations
Migrated:  1000_00_00_000001_extensions_php_migrations
Migrating: 2017_02_09_231419_bluetooth
Migrated:  2017_02_09_231419_bluetooth
Migrating: 2017_02_09_234100_ard
Migrated:  2017_02_09_234100_ard
Migrating: 2017_02_09_234110_backup2go
Migrated:  2017_02_09_234110_backup2go
Migrating: 2017_02_09_234136_certificate
Migrated:  2017_02_09_234136_certificate
Migrating: 2017_02_09_234207_crashplan
Migrated:  2017_02_09_234207_crashplan
Migrating: 2017_02_09_234219_deploystudio
Migrated:  2017_02_09_234219_deploystudio
Migrating: 2017_02_09_234232_directoryservice
Migrated:  2017_02_09_234232_directoryservice
Migrating: 2017_02_09_234243_diskreport
Migrated:  2017_02_09_234243_diskreport
Migrating: 2017_02_09_234251_displays
Migrated:  2017_02_09_234251_displays
Migrating: 2017_02_09_234311_filevault_status
Migrated:  2017_02_09_234311_filevault_status
Migrating: 2017_02_09_234321_findmymac
Migrated:  2017_02_09_234321_findmymac
Migrating: 2017_02_09_234329_gsx
Migrated:  2017_02_09_234329_gsx
Migrating: 2017_02_09_234335_inventoryitem
Migrated:  2017_02_09_234335_inventoryitem
Migrating: 2017_02_09_234346_localadmin
Migrated:  2017_02_09_234346_localadmin
Migrating: 2017_02_09_234352_location
Migrated:  2017_02_09_234352_location
Migrating: 2017_02_09_234358_machine
Migrated:  2017_02_09_234358_machine
Migrating: 2017_02_09_234433_managedinstalls
Migrated:  2017_02_09_234433_managedinstalls
Migrating: 2017_02_09_234611_munkiinfo
Migrated:  2017_02_09_234611_munkiinfo
Migrating: 2017_02_09_234619_munkireport
Migrated:  2017_02_09_234619_munkireport
Migrating: 2017_02_09_234656_network
Migrated:  2017_02_09_234656_network
Migrating: 2017_02_09_234916_profile
Migrated:  2017_02_09_234916_profile
Migrating: 2017_02_09_234923_reportdata
Migrated:  2017_02_09_234923_reportdata
Migrating: 2017_02_09_234931_sccm_status
Migrated:  2017_02_09_234931_sccm_status
Migrating: 2017_02_09_234938_security
Migrated:  2017_02_09_234938_security
Migrating: 2017_02_09_234959_warranty
Migrated:  2017_02_09_234959_warranty
Migrating: 2017_02_09_235003_wifi
Migrated:  2017_02_09_235003_wifi
Migrating: 2017_02_11_074454_event
Migrated:  2017_02_11_074454_event
Migrating: 2017_02_12_012330_comment
Migrated:  2017_02_12_012330_comment
Migrating: 2017_02_12_235252_hash
Migrated:  2017_02_12_235252_hash
Migrating: 2017_02_14_091413_installhistory
Migrated:  2017_02_14_091413_installhistory
Migrating: 2017_02_20_085316_machine_group
Migrated:  2017_02_20_085316_machine_group
Migrating: 2017_11_29_000001_extensions
Migrated:  2017_11_29_000001_extensions
Migrating: 2017_12_17_0000001_devtools
Migrated:  2017_12_17_0000001_devtools
Migrating: 2017_12_17_0000001_supported_os
Migrated:  2017_12_17_0000001_supported_os
Migrating: 2017_12_18_132621_user_sessions
Migrated:  2017_12_18_132621_user_sessions
Migrating: 2017_12_18_173230_business_unit
Migrated:  2017_12_18_173230_business_unit
Migrating: 2017_12_18_211801_appusage
Migrated:  2017_12_18_211801_appusage
Migrating: 2017_12_18_211802_caching
Migrated:  2017_12_18_211802_caching
Migrating: 2017_12_18_211803_fan_temps
Migrated:  2017_12_18_211803_fan_temps
Migrating: 2017_12_18_220830_tag
Migrated:  2017_12_18_220830_tag
Migrating: 2017_12_19_172407_munki_facts
Migrated:  2017_12_19_172407_munki_facts
Migrating: 2017_12_19_193501_usb
Migrated:  2017_12_19_193501_usb
Migrating: 2017_12_19_193803_filevault_escrow
Migrated:  2017_12_19_193803_filevault_escrow
Migrating: 2017_12_19_193901_homebrew_info
Migrated:  2017_12_19_193901_homebrew_info
Migrating: 2017_12_19_194601_firmware_escrow
Migrated:  2017_12_19_194601_firmware_escrow
Migrating: 2017_12_19_195001_fonts
Migrated:  2017_12_19_195001_fonts
Migrating: 2017_12_19_195401_network_shares
Migrated:  2017_12_19_195401_network_shares
Migrating: 2017_12_19_195601_service
Migrated:  2017_12_19_195601_service
Migrating: 2017_12_19_195801_smart_stats
Migrated:  2017_12_19_195801_smart_stats
Migrating: 2017_12_19_200401_softwareupdate
Migrated:  2017_12_19_200401_softwareupdate
Migrating: 2017_12_19_201201_gpu
Migrated:  2017_12_19_201201_gpu
Migrating: 2017_12_19_201501_mbbr_status
Migrated:  2017_12_19_201501_mbbr_status
Migrating: 2017_12_19_201801_munkireportinfo
Migrated:  2017_12_19_201801_munkireportinfo
Migrating: 2017_12_19_234707_printer
Migrated:  2017_12_19_234707_printer
Migrating: 2017_12_20_142858_detectx
Migrated:  2017_12_20_142858_detectx
Migrating: 2017_12_22_143049_usage_stats
Migrated:  2017_12_22_143049_usage_stats
Migrating: 2017_12_23_223838_homebrew
Migrated:  2017_12_23_223838_homebrew
Migrating: 2017_12_23_230338_power
Migrated:  2017_12_23_230338_power
Migrating: 2017_12_24_084408_servermetrics
Migrated:  2017_12_24_084408_servermetrics
Migrating: 2017_12_24_085405_applications
Migrated:  2017_12_24_085405_applications
Migrating: 2018_01_01_234951_timemachine
Migrated:  2018_01_01_234951_timemachine
Migrating: 2018_02_06_000001_mdm_status_initialize
Migrated:  2018_02_06_000001_mdm_status_initialize
Migrating: 2018_02_08_000001_caching_high_sierria
Migrated:  2018_02_08_000001_caching_high_sierria
Migrating: 2018_02_08_000001_fan_temps_add_smc_columns
Migrated:  2018_02_08_000001_fan_temps_add_smc_columns
Migrating: 2018_02_08_000001_timemachine_apfs_snapshots
Migrated:  2018_02_08_000001_timemachine_apfs_snapshots
Migrating: 2018_02_08_000001_usage_stats_fix_column_types
Migrated:  2018_02_08_000001_usage_stats_fix_column_types
Migrating: 2018_02_09_165033_wifi_fix_nullable_columns
Migrated:  2018_02_09_165033_wifi_fix_nullable_columns
Migrating: 2018_02_09_165342_power_fix_nullable_columns
Migrated:  2018_02_09_165342_power_fix_nullable_columns
Migrating: 2018_02_12_162424_security_add_ssh_groups
Migrated:  2018_02_12_162424_security_add_ssh_groups
Migrating: 2018_02_12_164431_extensions_add_teamid
Migrated:  2018_02_12_164431_extensions_add_teamid
Migrating: 2018_02_14_215000_tag_add_index
Migrated:  2018_02_14_215000_tag_add_index
Migrating: 2018_02_14_215734_usb_add_index
Migrated:  2018_02_14_215734_usb_add_index
Migrating: 2018_02_14_220729_fonts_add_index
Migrated:  2018_02_14_220729_fonts_add_index
Migrating: 2018_02_14_221501_network_shares_add_index
Migrated:  2018_02_14_221501_network_shares_add_index
Migrating: 2018_02_14_222918_homebrew_add_index
Migrated:  2018_02_14_222918_homebrew_add_index
Migrating: 2018_02_14_223731_servermetrics_add_index
Migrated:  2018_02_14_223731_servermetrics_add_index
Migrating: 2018_03_12_000001_certificate_null_columns
Migrated:  2018_03_12_000001_certificate_null_columns
Migrating: 2018_03_12_165507_filevault_escrow_encrypt_plaintext_keys
Migrated:  2018_03_12_165507_filevault_escrow_encrypt_plaintext_keys
Migrating: 2018_04_11_000001_gpu_add_metal
Migrated:  2018_04_11_000001_gpu_add_metal
Migrating: 2018_04_12_000001_displays_info_add_extended_columns
Migrated:  2018_04_12_000001_displays_info_add_extended_columns
Migrating: 2018_04_12_055955_user_sessions_add_user_uid
Migrated:  2018_04_12_055955_user_sessions_add_user_uid
Migrating: 2018_04_12_064804_reportdata_add_uid
Migrated:  2018_04_12_064804_reportdata_add_uid
Migrating: 2018_04_15_042618_directory_service_add_bound_column
Migrated:  2018_04_15_042618_directory_service_add_bound_column
Migrating: 2018_04_28_162424_sentinelone
Migrated:  2018_04_28_162424_sentinelone
Migrating: 2018_05_03_152424_sentinelone_add_quarantine_files
Migrated:  2018_05_03_152424_sentinelone_add_quarantine_files
Migrating: 2018_06_09_115534_Sophos
Migrated:  2018_06_09_115534_Sophos
Migrating: 2018_07_03_162424_security_add_ard_groups
Migrated:  2018_07_03_162424_security_add_ard_groups
Migrating: 2018_07_27_0000001_ibridge
Migrated:  2018_07_27_0000001_ibridge
Migrating: 2018_08_17_094300_detectx_add_statuscolumns
Migrated:  2018_08_17_094300_detectx_add_statuscolumns
Migrating: 2018_11_08_191137_localadmin_add_count_column
Migrated:  2018_11_08_191137_localadmin_add_count_column
Migrating: 2019_01_09_165546_security_root_user
Migrated:  2019_01_09_165546_security_root_user
Migrating: 2019_02_11_144341_ibridge_add_version_column
Migrated:  2019_02_11_144341_ibridge_add_version_column
Migrating: 2019_02_22_000001_softwareupdate_rewrite_columns
Migrated:  2019_02_22_000001_softwareupdate_rewrite_columns
Migrating: 2019_03_11_000003_fan_temps_json_rewrite
Migrated:  2019_03_11_000003_fan_temps_json_rewrite

So the SQLite database is created.  But no matter what I do otherwise, such as

`sudo chmod 777 app/db/db.sqlite`
`sudo chown -R www-data:www-data /path/to/munkireport`

I can't get past the same error message when I login:

>Fatal error
>Connection failed: SQLSTATE[HY000] [14] unable to open database file
>
>Try again

There's nothing in either the NGINX access or error log files to help indicate where the problem is.  In fact, there's NOTHING in the error log file AT ALL.  So whatever this is, it's not PHP kicking out errors as I'd typically see in other webapps.  And I'm highly doubting it's a permissions issue at this point.

The last time I setup munkireport-php, it was an older version (v2?).  But I never had issues like this.  It worked rock solid.  I would just like to have some kind of feedback to point me in the right direction.  But as it stands now, I can't figure out what's keeping it from working.

**Comment by bochoven** [comment]
Could you try using the full path to the database file?

**Comment by bochoven** [comment]
Thanks for reporting, I know this is from a long time ago, but did you get your issues fixed?
