### ISSUE TITLE
Mojave Updates Not Showing in MSC

### ISSUE THREAD

**Issue by KLEPTOROTH** [munkireport/munkireport-php#1250]
I've noticed that Mojave OS updates don't show up in MSC:

![image (2)](https://user-images.githubusercontent.com/32179141/58841159-7ebd0080-861d-11e9-9e34-d6e5db38222a.png)

As you can see, there is an OS update available, and the Mac updater is seeing it, but MSC is not.

**Comment by tuxudo** [comment]
Hi KLEPTOROTH, this Github is for MunkiReport. You may want to ask in https://github.com/munki/munki for questions about MSC.

**Comment by kevinmcox** [comment]
Also join us in the MacAdmins Slack if you aren't there already, you'll be able to get help about this in the #munki channel.

But it looks like you might not have Munki configured to install Apple updates: https://github.com/munki/munki/wiki/Apple-Software-Updates-With-Munki

**Comment by KLEPTOROTH** [comment]
Doy, sorry, must have picked the wrong tab!  Was jumping back and forth between Gits.  Will repost in munki.

**Comment by KLEPTOROTH** [comment]
@kevinmcox It is configured to get Apple updates - this same Mac was getting updates previously with MSC.

**Comment by ofirgalcon** [comment]
Make sure you use -bool for the key
