### ISSUE TITLE
10.15 bug - 0B free storage

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/munkireport-php#1251]
![image](https://user-images.githubusercontent.com/16665880/59289611-58771080-8c6e-11e9-8151-cac7076095bf.png)

Currently displays 0 bytes free, which is incorrect.

**Comment by bochoven** [comment]
Storage is rounded to .5GB

**Comment by ofirgalcon** [comment]
But I have 450GB free - it's showing 0B

**Comment by bochoven** [comment]
Oh, it’s 10.15

**Comment by WardsParadox** [comment]
Believe this is related to 10.15's change of the diskutil info command.
To get size you may need to reference:
```
        <key>APFSContainerFree</key>
        <integer>98044719104</integer>
        <key>APFSContainerReference</key>
        <string>disk1</string>
        <key>APFSContainerSize</key>
        <integer>250790436864</integer>
```

**Comment by rickheil** [comment]
Fixed with https://github.com/munkireport/disk_report/pull/5 - update with composer to get the latest bits :)
