### ISSUE TITLE
App Versions report does not populate with data

### ISSUE THREAD

**Issue by cdhw2018** [munkireport/munkireport-php#1260]
MunkiReport Version 4.2.2.3809:

Things seem to be working well with the exception of the App Versions report, as follows.

The report displays the applications specified in the APPS_TO_TRACK list in .env but does not populate with the versions and number of clients.

Clicking the list link following a name, e.g.

https://FQDN/munkireports/index.php?/module/inventory/items/LibreOffice

displays the Apple Remote Desktop Report in all cases.

On the other hand, the 'Listings > Applications' works fine. The list includes all the data needed to generate the versions report.

Running postflight on the client gives an error that may be relevant:

WARNING: Munkireport: Can't open /usr/local/munki/preflight.d/cache/servermetrics.json
    Munkireport: Need to update inventory (143KB)
WARNING: Munkireport: Can't open /usr/local/munki/preflight.d/cache/malwarebytes.plist
WARNING: Munkireport: Can't open /var/root/crypt_output.plist
    Munkireport: Sending items (143KB)
    Munkireport: Server info: starting: reportdata
Server An error occurred while processing: \Inventory_processor
Server Error: SQLSTATE[HY000]: General error: 1 too many SQL variables (SQL: insert into "inventoryitem" ("bundleid", "bundlename", "name", "path", "serial_number", "version") select com.apple.print.AirScanLegacyDiscovery as "bundleid", AirScanLegacyDiscovery as "bundlename", AirScanLegacyDiscovery as "name", /Library/Image Capture/Support/LegacyDeviceDiscoveryHelpers/AirScanLegacyDiscovery.app as "path", DGKV1HBJH7VF as "serial_number", 14.4 as "version"
  union all [...]

where the [...] is a list of several hundred similar entries.

I'm upgrading from 3.1.1. The Application Versions report was displaying 'legacy values' until I reset the database by deleting it and using the migrate command.

So,I suspect that the clients are not populating the database with the necessary information but It's not clear to me how to go about diagnosing/fixing the problem.

Any help or pointers would be most welcome.

TIA

Charles

**Comment by bochoven** [comment]
Thanks for reporting, this seems to be an issue with SQLite, it cannot insert more that 999 rows at a time. Ill try to add a chunking method.

**Comment by cdhw2018** [comment]
Just to confirm that version 4.3.2 has resolved this issue.

Many thanks.

Charles

**Comment by bobwithanx** [comment]
I'm experiencing this issue on 4.3.4.3846. Could it have been unpatched in an update, or am I experiencing some other issue on my end?

Empty App Versions Report:
<img width="1273" alt="appversions" src="https://user-images.githubusercontent.com/1720670/63290864-31911800-c277-11e9-85ea-12385ba106a7.png">

Populated Applications Listing:
<img width="1272" alt="appreport" src="https://user-images.githubusercontent.com/1720670/63290925-571e2180-c277-11e9-8ec5-e06496e18a17.png">
