### ISSUE TITLE
Quotes in .env.example file causes exception

### ISSUE THREAD

**Issue by hfike** [munkireport/munkireport-php#1263]
I copied the contents of the .env.example file for use with the instance I am setting up in docker. I am using the sqlite db, and received the following Fatal error:

Fatal error: Uncaught Exception: Unknown driver: "sqlite" in /var/munkireport/app/config/db.php:35 Stack trace: #0 /var/munkireport/app/helpers/config_helper.php(82): require() #1 /var/munkireport/bootstrap/app.php(38): configAppendFile('/var/munkirepor...', 'connection') #2 /var/munkireport/public/index.php(7): require_once('/var/munkirepor...') #3 {main} thrown in /var/munkireport/app/config/db.php on line 35

Changing the line in the .env file from CONNECTION_DRIVER="sqlite" to CONNECTION_DRIVER=sqlite fixed this issue.

I also found in slack where @flammable was having the same issue with the mysql driver: https://macadmins.slack.com/archives/C066NK3K5/p1548005965938100

I would suggest changing the .env.example file to remove those quotes, however, I'm not sure how far beyond the issues with the quote @flammable and I noticed one would need to go to remove this problem.

**Comment by hfike** [comment]
I'm seeing this same issue on other variables as well as I continue through the setup. Is this an issue related to my environment potentially?

**Comment by kevinmcox** [comment]
@hfike It might be related to Docker. I have no problem with those quotes in my non-docker setup.

**Comment by bochoven** [comment]
https://github.com/docker/compose/issues/3702

**Comment by flammable** [comment]
Sorry @hfike, I should really update my blog post to cover MunkiReport v4 in Docker (or frankly, the wiki). I had to eliminate all quotes from my env file, since they just don't work with Docker Compose.

**Comment by hfike** [comment]
I plan on making some notes on the wiki, however, if quote are removed, does this break non-docker usage?

**Comment by bochoven** [comment]
Leaving out quotes caused some preferences not being parsed correctly. We would need to test if that’s still the case.
