### ISSUE TITLE
App Versions Report Not Populating in 4.3.4.3846

### ISSUE THREAD

**Issue by bobwithanx** [munkireport/munkireport-php#1271]
I recently made some major changes to my Munki server and decided to clear out the DB and start from scratch. My clients are connecting and appear to be reporting data just fine:

<img width="1272" alt="appreport" src="https://user-images.githubusercontent.com/1720670/63290925-571e2180-c277-11e9-8ec5-e06496e18a17.png">

However, my App Versions Report continues to be empty:

<img width="1273" alt="appversions" src="https://user-images.githubusercontent.com/1720670/63290864-31911800-c277-11e9-85ea-12385ba106a7.png">

It appears that this has been patched on a recent version: https://github.com/munkireport/munkireport-php/issues/1260

Is there a chance it have been unpatched in the most recent version, or am I experiencing some other issue on my end?

Any help would be appreciated, thanks!

**Comment by joncrain** [comment]
Did you create a new installer for 4.3.4 and push out to your clients?

**Comment by bochoven** [comment]
App Versions Report is using the items from the `inventory_item` table. Could you check if that table contains data?

**Comment by bobwithanx** [comment]
The table DID contain data. I ended up just wiping the DB and rebuilding everything. I manage 30 Macs, so while it was tedious, it wasn't insurmountable. Just wanted to close the loop on this.
