### ISSUE TITLE
Empty clients

### ISSUE THREAD

**Issue by crsleeth** [munkireport/munkireport-php#1281]
Although I previously had MunkiReport working I had to re-setup from scratch using version 5.0.1.3895 and now as my clients are reporting in their info is blank. The only info to come through is serial numbers, which I've edited out of this screenshot. ![Screen Shot 2019-09-24 at 11 02 28 AM](https://user-images.githubusercontent.com/13802587/65524274-8699fc80-debb-11e9-9452-c15eaa0d5b86.png)

PHP 7.2.19-0ubuntu0.18.04.2 and mysql Ver 15.1 Distrib 10.4.8-MariaDB.

MODULES='directory_service, disk_report, filevault_escrow, filevault_status, findmymac, gpu, homebrew, homebrew_info, installhistory, inventory, localadmin, managedinstalls, munkiinfo, munkireport, munkireportinfo, network, network_shares, power, printer, security, smart_stats, softwareupdate, supported_os, timemachine, usagestats, usb, user_sessions, warranty, wifi'

Things I've tried: resetting up from scratch, utf8 vs. utf8mb4 database, recreating database and redoing migration, updating MunkiReport on clients with newly generated pkg.

**Comment by bochoven** [comment]
Could you check if 5.1.0 fixes your issue?

**Comment by crsleeth** [comment]
The solution was to install php-soap and php-xml!
