### ISSUE TITLE
SAML

### ISSUE THREAD

**Issue by digitalhealer** [munkireport/munkireport-php#1282]
I just tried updating to 5.1 from 4.3.4.  In 4.3.4 SAML was working correctly.  In 5.1 SAML returns a invalid response error 

Its possibly related to the  onelogin/php-saml v3.3 change "Set true as the default value for strict setting"

**Comment by bochoven** [comment]
Yes, you now need to make sure you match the response from the IDP exactly. I’ve been thinking about allowing for a non-strict option, but strict is the only production worthy setting.
