### ISSUE TITLE
After Upgrade Installation is broken

### ISSUE THREAD

**Issue by b-reich** [munkireport/munkireport-php#1284]
After upgrading to Munkireport 5.1.0 i got the following errors in apache2:

```
[Mon Oct 07 09:58:30.556252 2019] [:error] [pid 473] [client 192.168.188.60:59510] PHP Warning:  Class 'Tightenco\\Collect\\Support\\LazyCollection' not found in /srv/munkireport-php/vendor/tightenco/collect/src/Collect/Support/alias.php on line 19

[Mon Oct 07 09:58:30.556289 2019] [:error] [pid 473] [client 192.168.188.60:59510] PHP Parse error:  syntax error, unexpected '=' in /srv/munkireport-php/vendor/tightenco/collect/src/Collect/Support/LazyCollection.php on line 573
```

**Comment by bochoven** [comment]
Did you update the dependencies? 

https://github.com/munkireport/munkireport-php/wiki/Server-setup#install-and-run-composer

**Comment by b-reich** [comment]
Yeah, I updated the dependencies.

**Comment by bochoven** [comment]
Oh, I should look better at the error message. It seems there's an error in a vendor package

**Comment by bochoven** [comment]
What's your output of ```composer info tightenco/collect```

**Comment by b-reich** [comment]
Sorry for the late reply..

I rebuild the softrware and using the docker image,

**Comment by bochoven** [comment]
Did you built the docker image yourself or are you using the one from dockerhub?

**Comment by b-reich** [comment]
The broken Installation was a baremetal installation with php and apache on a Debian 9.

Now I am using the Image from dockerhub which is working.

I know this bad when I cant retrigger the failure anymore. I am sorry for this.
If you want, I can close the bug too.
