### ISSUE TITLE
macOS 10.15 clients & <5GB Free Disk Space

### ISSUE THREAD

**Issue by paulashbrook** [munkireport/munkireport-php#1285]
My MunkiReport server and clients are running latest version - 5.1.0 
Clients running macOS 10.15 Catalina repory less than 5GB free disk space, despite that not being the case when checked on the client itself.

**Comment by rickheil** [comment]
This change addresses the issue - https://github.com/munkireport/disk_report/pull/5

You will need to update the module with composer to get the latest version and create a new client package to have your machines start reporting properly again.
