### ISSUE TITLE
Please increase the timeout in purl.py

### ISSUE THREAD

**Issue by pexner** [munkireport/munkireport-php#1291]
Please increase the timeout in `/usr/local/munkireport/munkilib/purl.py` to
`self.connection_timeout = options.get('connection_timeout', 30)`
This doesn't hurt at all but prevents the
`Download error -1001: The request timed out.` when running `munkireport-runner`.
Thanks in advance.

**Comment by pexner** [comment]
Further testing showed that when having more modules loaded, the timeout of even 30 isn't enough.
Since I put it on 60, everything is OK.
Please increase the default timeout to 60.

**Comment by bochoven** [comment]
https://github.com/munkireport/munkireport-php/blob/0e64b470a8f185327ad59c061b6b947450569e93/public/assets/client_installer/payload/usr/local/munkireport/munkilib/reportcommon.py#L76
