### ISSUE TITLE
Managedinstalls stopped working

### ISSUE THREAD

**Issue by sprtm** [munkireport/munkireport-php#1292]
On some of our clients, the managedinstalls processor stopped working. It's not reporting any data to munkireport. This is the error in munkireport-runner:

```
Server An error occurred while processing: \Managedinstalls_processor
Server Error: SQLSTATE[HY000]: General error: 1 too many SQL variables...
```

I've removed and re-installed munkireport on a some test clients, but no success.

I also tried to delete all content from /Library/Managed Installs after reading this post: https://groups.google.com/forum/#!topic/munkireport/x0J0xwGtv30, but still no success.

This issue affects all clients except one, in one specific machine group. No client in our other machine group have any issues.

Running version 5.1.3.3919 of Munkireport (WIP branch upgrade was a mistake by me, 5.1.2 was my intention. The upgrade MIGHT be when the issue started) and sqlite 3.15.1.

**Comment by bochoven** [comment]
I released a new version of the managedinstalls module here: https://github.com/munkireport/managedinstalls/releases/tag/V2.3
Would you be able to check if that fixes your issue?

**Comment by sprtm** [comment]
Yes! Clients are now reporting correctly. Thank you!
