### ISSUE TITLE
Reporting runs twice in a row

### ISSUE THREAD

**Issue by macsimom** [munkireport/munkireport-php#1297]
5.1.2 on a Catalina 10.15.1 client always runs reporting twice when `touch`'ing `/Users/Shared/.com.github.munkireport.run` possibly because the launchd job gets triggered when the file is created and again when the file is removed by `/usr/local/munkireport/munkireport-runner` 

Simply comment out the `os.remove(touchfile)` (circa line 65) statement from `/usr/local/munkireport/munkireport-runner` and it seems to work as expected

This ancient blog post by Greg Neagle discusses the use of the `WatchPaths` key in launchd job definitions which may or may not be relevant today.

Also a suggestion (unless it's intended that non-admin users be able to trigger the report run) is that the trigger file may have a more appropriate location in `/private/var/run` instead of `/Users/Shared` But admittedly that may be more a question of style/taste.

**Comment by bochoven** [comment]
Fixed in latest release
