### ISSUE TITLE
MunkiReport 5.x, PHP and MariaDB/MySQL

### ISSUE THREAD

**Issue by jelockwood** [munkireport/munkireport-php#1303]
I currently (still) run MunkiReport 4.01 with it connected to a separate MariaDB server and using SSL encryption for the SQL traffic. This is working fine and using PHP 7.1.33

I am starting to try and upgrade to MunkiReport 5.x and as sadly typical when moving to a major version change hitting issues. I am sure a lot of this is my fault.

Could you clarify what dependencies I need to install first to get 5.x to use MariaDB (or MySQL)?

I believe MunkiReport 5.x uses PHP 7.3 so will need new libraries.

I seem to have gotten as far as via git installing the new version, and successfully running composer.

I have a sneaking suspicion the issue is down to the use of SSL for MariaDB/MySQL as this is what was a problem last time.

**Comment by jelockwood** [comment]
@bochoven 
Ok, I turned off SSL for my MariaDB connection temporarily and was then able to do the php database/migrate.php this appears to have run successfully as below.

```
php database/migrate.php
Migrating: 2018_02_06_000001_mdm_status_initialize
Migrated:  2018_02_06_000001_mdm_status_initialize (0.17 seconds)
Migrating: 2018_02_08_000001_fan_temps_add_smc_columns
Migrated:  2018_02_08_000001_fan_temps_add_smc_columns (0.57 seconds)
Migrating: 2018_02_08_000001_timemachine_apfs_snapshots
Migrated:  2018_02_08_000001_timemachine_apfs_snapshots (0.21 seconds)
Migrating: 2018_02_20_000001_network_add_dns
Migrated:  2018_02_20_000001_network_add_dns (0.57 seconds)
Migrating: 2019_02_07_000001_filevault_status_add_more_columns
Migrated:  2019_02_07_000001_filevault_status_add_more_columns (0.85 seconds)
Migrating: 2019_02_11_144341_ibridge_add_version_column
Migrated:  2019_02_11_144341_ibridge_add_version_column (0.11 seconds)
Migrating: 2019_02_22_000001_softwareupdate_rewrite_columns
Migrated:  2019_02_22_000001_softwareupdate_rewrite_columns (1.55 seconds)
Migrating: 2019_03_11_000003_fan_temps_json_rewrite
Migrated:  2019_03_11_000003_fan_temps_json_rewrite (4.65 seconds)
Migrating: 2019_03_18_000001_network_rewrite
Migrated:  2019_03_18_000001_network_rewrite (2.7 seconds)
```

With SSL still disabled for MariaDB/MySQL I can then login. If however I re-enable SSL when I try logging in to Munkireport afterwards it still immediately redirects to the Admin -> Upgrade database page. If I force it to go the Dashboard I get the following error.

`Request Failed: parsererror, SyntaxError: JSON Parse error: Unrecognized token '<'`

It seems therefore that currently (my) MunkiReport-PHP 5.1.3.3919 does not work with SSL for MariaDB/MySQL. The entries I had in my .env for this are still present but I suspect the MR 5.x code is not utilising them.

This is what I was expecting so I am hoping we can work together to resolve this. For what it's worth my relevant setting in my .env are as follows. It would be the later section that seems most relevant. My guess is that the standard code is not utilising these settings.

```
CONNECTION_DRIVER="mysql"
CONNECTION_HOST="it-db.domain.com"
CONNECTION_PORT="3306"
CONNECTION_DATABASE="munkireport"
CONNECTION_USERNAME="munkireport"
CONNECTION_PASSWORD="munkipassword"
CONNECTION_CHARSET="utf8mb4"
CONNECTION_COLLATION="utf8mb4_unicode_ci"
CONNECTION_STRICT=TRUE
CONNECTION_ENGINE="InnoDB"

CONNECTION_SSL_ENABLED='true'
CONNECTION_SSL_KEY='/etc/mysql/ssl/munki.domain.com.key'
CONNECTION_SSL_CERT='/etc/mysql/ssl/munki.domain.com.crt'
CONNECTION_SSL_CA='/etc/mysql/ssl/CompanyCA.crt'
CONNECTION_SSL_CAPATH='/etc/ssl/certs'
CONNECTION_SSL_CIPHER='DHE-RSA-AES256-SHA:AES128-SHA'
```

**Comment by bochoven** [comment]
I see that your settings should be used:

https://github.com/munkireport/munkireport-php/blob/0e64b470a8f185327ad59c061b6b947450569e93/app/config/db.php#L14

and

https://github.com/munkireport/munkireport-php/blob/0e64b470a8f185327ad59c061b6b947450569e93/app/helpers/site_helper.php#L147

I don’t have a server with ssl so cannot reproduce the issue.

**Comment by jelockwood** [comment]
As my db.php and site_helper.php are the ones included with MR 5.x they do have those lines. However I think I have found the issue.

I had when I originally added SSL support to my MR config for 4.x used variable names matching those used in another PHP project called Snipe-IT so as per my post above the variables are called CONNECTION_SSL_KEY etc.

I think your code is looking for SSL_KEY etc. that is without the prefix CONNECTION_

I added duplicate copies without the CONNECTION_ prefix and it appears to be working. I will leave it running a little longer to test further and if it stays working I will close this issue.

**Comment by bochoven** [comment]
I’m pretty sure the code requires the CONNECTION_ prefix.

`      'ssl_key' => env('CONNECTION_SSL_KEY'), `

**Comment by jelockwood** [comment]
Yes your right (I had left both in). Further testing shows the real problem and triggered my memory from way back when I originally got MR 4.x working.

The problem is that one of your files probably site_helper.php is not correctly processing logic based on CONNECTION_SSL_ENABLED as a result it then does not choose to read the options and therefore does not do a valid SSL connection. I confirmed this by temporarily editing site_helper.php to force it to always in effect be true as follows.

```
  //if($conn['ssl_enabled']){
    foreach(['key', 'cert', 'ca', 'capath', 'cipher'] as $ssl_opt){
      if($conn['ssl_'. $ssl_opt]){
        $conn['options'][constant('PDO::MYSQL_ATTR_SSL_'.strtoupper($ssl_opt))] = $conn['ssl_'. $ssl_opt];
      }
    }
  //}
```
The above will always therefore be true.

I obviously did find the logic error and fix it originally in 4.x and will try and do so again but you might want to have a look yourself as currently it would always regards it as being false.

Ah! I think I have found it, your standard …/app/config/db.php contains the following line

`      'ssl_enabled' => env('CONNECTION_SSL_ENABLED', false),
`
This is hard coding the value to be false regardless of what the .env contains. My old MR 4.x db.php contain the line

`      'ssl_enabled' => env('CONNECTION_SSL_ENABLED'),
`
I therefore think this is the cause and you need to adjust (for the future) your db.php file to remove the hardcoding to false.

This looks good from my testing.

**Comment by bochoven** [comment]
Could you try removing the quotes around ‘true’ in your config?

**Comment by jelockwood** [comment]
That looks promising. I have edited my .env as requested to =TRUE and reverted my db.php

It seems to be working correctly. I will update you tomorrow to give it a longer test.

**Comment by jelockwood** [comment]
@AaronBurchfield 
Yes that seems to have been the problem and is of course now fixed. Many thanks for your assistance. I am now closing this issue.
