### ISSUE TITLE
failed to load locales (FR)

### ISSUE THREAD

**Issue by pexner** [munkireport/munkireport-php#1304]
When switching to french, error:
**failed to load locales, please check for syntax errors**
v5.1.3.3919

**Comment by bochoven** [comment]
Hi Patrick, thanks for reporting. Could you send the list of modules you are using?

**Comment by pexner** [comment]
`MODULES="applications, appusage, ard, backup2go, bluetooth, disk_report, fan_temps, installhistory, inventory, localadmin, managedinstalls, munkiinfo, munkireport, munkireportinfo, network, network_shares, power, printer, softwareupdate, supported_os, timemachine, usage_stats, usb, user_sessions, wifi"`

**Comment by pexner** [comment]
PS: All other proposed languages are working. It's just the french one which gives the error here.

**Comment by bochoven** [comment]
You could troubleshoot by removing modules from your config until the error disappears. That will pinpoint the troubled module.

**Comment by coobs1** [comment]
Looks like the issue stems from the fan_temps module and that the [bug](https://github.com/munkireport/fan_temps/issues/5) was reported back in April. Appears to be fixed by an [open pull request](https://github.com/munkireport/fan_temps/pull/7) that removes a double comma.

**Comment by bochoven** [comment]
Fixed, I assume
