### ISSUE TITLE
Feature Request - Report Secureboot configuration

### ISSUE THREAD

**Issue by jelockwood** [munkireport/munkireport-php#1305]
T2 chip equipped Mac models i.e. MacBook Pro 2018 onwards, Mac mini 2018, Mac Pro 2019 and iMac Pro as standard have a feature called secureboot turned on which prevents them booting from external drives.

This can be configured to alternatively allow booting from external drives or only booting trusted operating systems.

As far as I can see MunkiReport does not currently report the status of this setting.

Obviously I could write my own script to report this but I feel it would be worthwhile this was added as standard to the security listing report since this is security related.

The following is a script used for Jamf that might help as a starting point.

```
#!/bin/bash

# Test Secure Boot status EA for Jamf.

function securebootstatus {
test=$(nvram 94b73556-2197-4702-82a8-3e1337dafbfb:AppleSecureBootPolicy 2>/dev/null )
	if [ "$test" ]
	then
test=$( nvram 94b73556-2197-4702-82a8-3e1337dafbfb:AppleSecureBootPolicy | awk '{ print $2 }' )
	fi
}

securebootstatus

case "$test" in
    %02)
        echo "<result>Full</result>"
    ;;

    %01)
        echo "<result>Medium</result>"
    ;;

    %00)
        echo "<result>Disabled</result>"
    ;;

    *)
        echo "<result>Secure Boot Not Present</result>"
    ;;
esac
```

**Comment by poundbangbash** [comment]
This feature has been implemented in the `security` module.  See https://github.com/munkireport/security/pull/11
