### ISSUE TITLE
Post upgrade to version 5.1.3.3919 some reports not working

### ISSUE THREAD

**Issue by jelockwood** [munkireport/munkireport-php#1307]
In December 2019 I upgraded from MR 4.x to MR 5.1.3.3919. This apparently succeeded and I can login and see data and _some_ data is being successfully updated by Macs which have via Munki also been updated to the matching client.

However recently it has become obvious that all Macs running the 5.x client are failing to upload new data for some reports in particular the Sophos report.

Having investigated this further I can see that the /usr/local/munkireport/scripts/sophos.py script does seem to run successfully and is creating updated information in /usr/local/munkireport/scripts/cache/sophos.plist I can also see log entries showing this is listed as needing to be uploaded to Munkireport.

Unfortunately this is not then appearing.

Other reports like Security, Storage etc. are working but several are not. The following appears to be the ones not working - there maybe others.

Battery, Extensions, FileVault, Munki Facts, Network, Power, Sophos Anti-Virus, Usage Stats

Note: Older Macs which previously ran the MR 4.x client show old data for the above. Newly added Macs which have only ever run the 5.x client show nothing.

To confirm the relevant modules are still enabled here is the MunkiReport listing for a Mac that has only used the 5.1.3.3919 client.

Version | 5.1.42
Passphrase | --
Installed Modules |
appusage, ard, backup2go, bluetooth, caching, certificate, crashplan, deploystudio, detectx, devtools, directory_service, disk_report, displays_info, extensions, fan_temps, filevault_escrow, filevault_status, findmymac, fonts, gpu, homebrew, homebrew_info, installhistory, inventory, localadmin, managedinstalls, mbbr_status, munki_facts, munkiinfo, munkireport, munkireportinfo, network, network_shares, power, printer, profile, security, smart_stats, softwareupdate, sophos, supported_os, timemachine, usage_stats, usb, user_sessions, warranty, wifi

Is this a fault in MR 5.1.3.3919?
Might it be signifying a problem with the database?

**Comment by bochoven** [comment]
I can't replicate this issue with 5.1.4. Any output from a client that does not report back?

**Comment by jelockwood** [comment]
@bochoven 
What specific output do you want me to check for? The /usr/local/munkireport/scripts/cache/sophos.plist or something else?

**Comment by bochoven** [comment]
Could you post the contents of /Library/MunkiReport/Logs/MunkiReport.log

**Comment by jelockwood** [comment]
Here is a copy from a Mac known to be exhibiting this problem. This particular Mac is also confirmed as running the 5.x client. For what its worth this Mac is running Mojave 10.14.6.

[MunkiReport.zip](https://github.com/munkireport/munkireport-php/files/4102378/MunkiReport.zip)

**Comment by tuxudo** [comment]
It looks like the DeployStudio module is broken (again). Do you use DeployStudio? If not, disable it and rebuild the MunkiReport pkg for the clients

**Comment by jelockwood** [comment]
Yes we do use DeployStudio but I don't need its report. It has never worked although I have never investigated properly setting it up. It might actually be a network connectivity issue as the MunkiReport server is on a different network to DeployStudio and the clients.

Knowing that it has always had these errors I don't feel this is the cause of the problem especially as other reports alphabetically after DeployStudio are being uploaded. However I can disable DeployStudio. 

What is the easiest way to push that change of enabled modules to clients?

**Comment by tuxudo** [comment]
Change the .env on the server to remove the deploystudio module from the list of enabled modules, then generate a new pkg following the same process that you used to create the initial pkg. Might have to bump the version number. This page details how: https://github.com/munkireport/munkireport-php/wiki/Client-setup

If you want to fix the deploystudio module, you'll have to enable the `php_curl` extension in your server's php.ini file and possibly install the `php-curl` package on if it isn't already installed. After that you'll have to configure the .env in the deploystudio module

**Comment by jelockwood** [comment]
I have MunkiReport added to AutoPkg it auto extracts a new client and adds it to Munki. I will see if I can kill two birds with one stone and upgrade the server.

**Comment by jelockwood** [comment]
Ok, after installing the tiny version change for MunkiReport server, disabling the DeployStudio module and having it generate a new client installer via AutoPkg and having that installed on the same test client Mac I am happy to report that all the missing reports are working.

I will therefore close this ticket as the problem seems solved.
