### ISSUE TITLE
SAML memberOf 

### ISSUE THREAD

**Issue by danner26** [munkireport/munkireport-php#1313]
Hello,

So I am integrating SAML for our MR instance, and everything is setup correctly except for group privileges. In our Shibboleth instance I have released email and memberOf, which looks like this (CN=MunkiReport_Admins,OU=FSMunki,OU=Groups,OU=Admins,OU=Root,DC=ac,DC=REDACTED)

The release looks like this:
```
        <saml2:AttributeStatement>
            <saml2:Attribute FriendlyName="mail" Name="urn:oid:0.9.2342.19200300.100.1.3" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml2:AttributeValue>REDACTED ( email was here )</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute FriendlyName="memberOf" Name="http://schemas.xmlsoap.org/claims/Group" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml2:AttributeValue>CN=MunkiReport_Admins,OU=FSMunki,OU=Groups,OU=Admins,OU=Root,DC=ac,DC=REDACTED</saml2:AttributeValue>
            </saml2:Attribute>
        </saml2:AttributeStatement>
```

In my env config, I have: 
AUTH_SAML_GROUP_ATTR=http://schemas.xmlsoap.org/claims/Group
AUTH_SAML_ALLOWED_GROUPS="CN=MunkiReport_Admins,OU=FSMunki,OU=Groups,OU=Admins,OU=Root,DC=ac,DC=REDACTED"

I am not able to get the env config working, and I have 3 groups I need to add, MunkiReport_Admins being one of them. I have tried every combination of just CN=MunkiReport_Admins, just MunkiReport_Admins, and the full string like above. 

Any assistance in figuring out how to troubleshoot this/set it up correctly would be great. Thank you.

**Comment by bochoven** [comment]
Github issues are for bugs in the code, please use the mailing list or slack for support questions

**Comment by danner26** [comment]
I will inquire there, but there is a clear lack of documentation in the Wiki, which I believe would belong here

**Comment by bochoven** [comment]
SAML setups vary wildly, usually working with your SAML admin helps to sort out the issues.

**Comment by danner26** [comment]
I am one of the SAML admins and we know SAML inst the issue. My team and I can't figure out what the code you have implemented is looking for and how it should be put in the configuration. The SAML data released isn't an issue and we believe either we do not have the config written properly (most likely the case), or less likely the code isn't supporting the string we release.
