### ISSUE TITLE
OpenLDAP not working

### ISSUE THREAD

**Issue by northalpha** [munkireport/munkireport-php#1322]
Hi there,

i am using `MunkiReport Version 5.3.0.3990` and just wanted to enable LDAP Access (via OpenLADP) in my org, with no success, after digging around it came to my attention:

1. https://github.com/munkireport/munkireport-php/blob/99a327f1d3f16f7ac8d141b7f1f7a46645a68b90/app/lib/munkireport/AuthLDAP.php#L20

the var `APP_PATH` is not defined and therefore it throws an error. (workaround: set absolute path)

2.    https://github.com/munkireport/munkireport-php/blob/99a327f1d3f16f7ac8d141b7f1f7a46645a68b90/app/lib/munkireport/AuthLDAP.php#L7

the var `auth_status` is not beeing used in later checks, it is called `authStatus`. (workaround: change name)

3. https://github.com/munkireport/munkireport-php/blob/99a327f1d3f16f7ac8d141b7f1f7a46645a68b90/app/lib/munkireport/AuthLDAP.php#L21

this instance is not called, for whatever reason, i just changed it to 
```
            $ldap_auth_obj = new \Auth_ldap($this->config);
```
but this should not be needed, i guess.

3. I am a bit confused with how to set the LDAP config options in `.env` file. Looking through https://github.com/munkireport/munkireport-php/blob/master/.env.example it seems t have to use `AUTH_LDAP_XXX` the wiki suggest using `LDAP_AD` with slightly different options.

I am happy to help here, but my programming skils are limited, i just want to connect munkireport to an secure openldap server with a bind user / bin pass on port 636. Any help is appreciated.

**Comment by bochoven** [comment]
You need to use the AD connector: https://github.com/munkireport/munkireport-php/wiki/LDAP-Authentication-%28AD%2C-OpenLDAP%2C-FreeIPA%29

**Comment by northalpha** [comment]
Sorry for re-opening this again, even with the `LDAP_AD` config settings in the `.env` file it is not working, also, you might want to recheck my changes that i had to make in order just to get this to the point were i can clearly eliminate error in the latest release.

Also i am missing, where the the log file for the option `AUTH_AD_DEBUG=TRUE` is beeing written to or where to configure it. I am happy to create an Pull Request for documentation once i got this working.

**Comment by bochoven** [comment]
Just to be clear: the old AUTH_LDAP library will be removed in the next version of MunkiReport, it was not functional anymore for some time. The GitHub issues are only used for bug-reports that's why I don't want to reopen it. For general advice/help setting up MunkiReport, please use the #munkireport channel at https://macadmins.slack.com or the Munkireport mailinglist.
