### ISSUE TITLE
curl: (23) Failed writing body (0 != 741)

### ISSUE THREAD

**Issue by g4fa** [munkireport/munkireport-php#1331]
Hello ,

since I upgrade 5.3.5, I have this error when in install MunkiReport on my client (sudo /bin/bash -c "$(curl -s http://192.168.1.83/report/index.php?/install)")

 # Preparing /usr/local/munkireport/
BaseURL is http://192.168.1.83/report/
# Retrieving munkireport scripts
/Library/LaunchDaemons/.AppleDouble/com.github.munkireport.runner.plist
curl: (23) Failed writing body (0 != 741)
/Library/LaunchDaemons/com.github.munkireport.runner.plist
/usr/local/munki/.AppleDouble/postflight
curl: (23) Failed writing body (0 != 741)
/usr/local/munki/.AppleDouble/report_broken_client
curl: (23) Failed writing body (0 != 741)
/usr/local/munki/postflight
/usr/local/munki/report_broken_client
/usr/local/munkireport/.AppleDouble/munkireport-runner
/usr/local/munkireport/munkilib/.AppleDouble/__init__.py
curl: (23) Failed writing body (0 != 741)
/usr/local/munkireport/munkilib/.AppleDouble/constants.py
curl: (23) Failed writing body (0 != 741)
/usr/local/munkireport/munkilib/.AppleDouble/display.py
curl: (23) Failed writing body (0 != 741)
/usr/local/munkireport/munkilib/.AppleDouble/FoundationPlist.py
curl: (23) Failed writing body (0 != 741)
/usr/local/munkireport/munkilib/.AppleDouble/munkilog.py
curl: (23) Failed writing body (0 != 741)
/usr/local/munkireport/munkilib/.AppleDouble/phpserialize.py
curl: (23) Failed writing body (0 != 741)
/usr/local/munkireport/munkilib/.AppleDouble/prefs.py
curl: (23) Failed writing body (0 != 741)
/usr/local/munkireport/munkilib/.AppleDouble/purl.py
curl: (23) Failed writing body (0 != 741)
/usr/local/munkireport/munkilib/.AppleDouble/reportcommon.py
curl: (23) Failed writing body (0 != 741)
/usr/local/munkireport/munkilib/.AppleDouble/reports.py
curl: (23) Failed writing body (0 != 741)
/usr/local/munkireport/munkilib/.AppleDouble/utils.py
curl: (23) Failed writing body (0 != 741)
/usr/local/munkireport/munkilib/__init__.py
/usr/local/munkireport/munkilib/constants.py
/usr/local/munkireport/munkilib/display.py
/usr/local/munkireport/munkilib/FoundationPlist.py
/usr/local/munkireport/munkilib/munkilog.py
/usr/local/munkireport/munkilib/phpserialize.py
/usr/local/munkireport/munkilib/prefs.py
/usr/local/munkireport/munkilib/purl.py
/usr/local/munkireport/munkilib/reportcommon.py
/usr/local/munkireport/munkilib/reports.py
/usr/local/munkireport/munkilib/utils.py
/usr/local/munkireport/munkireport-runner
Failed to download all required components! Cleaning up..

**Comment by bochoven** [comment]
Your filesystem creates .AppleDouble directories, what kind of server are you using?

**Comment by g4fa** [comment]
I install munkireport on my Raspberry 3 . My client is a Mac

**Comment by bochoven** [comment]
I guess you put the MunkiReport installation files on the Pi via a Netatalk share? Anyway, it should be fixed In the latest wip commit
