### ISSUE TITLE
Different names for pre-/postflight scripts

### ISSUE THREAD

**Issue by gniemetz** [munkireport/munkireport-php#1335]
First, you could put your master scripts in preflight.d and postflight.d.

Second, if you want to pursue this, I think it would be less confusing to just put the name of the target scripts in `config_default.php`:

```php
$conf['preflight_script'] = 'preflight-munkireport';
$conf['postflight_script'] = 'postflight-munkireport';
$conf['report_broken_client_script'] = 'report_broken_client';
```

So people can override the name with wathever they like.

_Originally posted by @bochoven in https://github.com/munkireport/munkireport-php/pull/867#issuecomment-328451004_

I had to rename the file `public/assets/client_installer/payload/usr/local/munki/postflight` to `public/assets/client_installer/payload/usr/local/munki/postflight-munkireport` manually because the variables aren't used in the installer script

**Comment by bochoven** [comment]
Not sure what this is referring to, but `config_default.php` has long seized to exist.

**Comment by gniemetz** [comment]
I have set
```
PREFLIGHT_SCRIPT="preflight-munkireport"
POSTFLIGHT_SCRIPT="postflight-munkireport"
```
in the `.env` file, but when i create the install package, a `postflight` instead of a `postflight-munkireport` is built

**Comment by gniemetz** [comment]
munkireport makes use of a postflight-script named `postflight`. The installation of the munkireport client package overwrites my own postflight script. Times ago i made a pull request (https://github.com/munkireport/munkireport-php/pull/873) you merged for renaming the pre- and postflight scripts munkireport rolls out, which is controlled by the two variables `PREFLIGHT_SCRIPT` and `POSTFLIGHT_SCRIPT` in the `.env` file. Unfortunately this is not working, the `config_default.php` does not read the variables anymore. Can you implement this again, would be very nice, thank you!

PS: These are the places i found `POSTFLIGHT_SCRIPT`
```
find munkireport-php -type f -exec grep -H POSTFLIGHT_SCRIPT {} +
munkireport-php/tests/fixtures/env.fixture:POSTFLIGHT_SCRIPT=FOOBAR
munkireport-php/build/config/config_to_env.yml:postflight_script: POSTFLIGHT_SCRIPT
munkireport-php/.env:POSTFLIGHT_SCRIPT="postflight-munkireport"
munkireport-php/app/views/install/install_script.php:POSTFLIGHT_SCRIPT="<?php echo conf('postflight_script'); ?>"
munkireport-php/app/views/install/install_script.php:chmod a+x "${INSTALLROOT}/usr/local/munki/"{${POSTFLIGHT_SCRIPT},${REPORT_BROKEN_CLIENT_SCRIPT}}
munkireport-php/app/config/app.php:    'postflight_script' => env('POSTFLIGHT_SCRIPT', 'postflight'),
```
