### ISSUE TITLE
SAML munkireport error

### ISSUE THREAD

**Issue by salihzett** [munkireport/munkireport-php#1353]
i used DEBUG=TRUE for getting more information. (but get only the first line below)
when I visit my munkireport page, it forwards me to Microsoft, i can login, i can use MFA, then i get this on the page:
```
Unable to extract public key
invalid_response
Not authenticated
```
I doublechecked the cert and configuration, in Microsoft I am pretty sure, it is correct. 
And also env looks similar to the related munkireport page. 
So an issue?
![Screen Shot 2020-05-25 at 15 12 16](https://user-images.githubusercontent.com/15154678/82815769-24eebf80-9e9a-11ea-8ba2-7fa01b7f4e4e.png)

**Comment by bochoven** [comment]
There's something wrong with your certificate. Github issues are for bugs, so closing..
