### ISSUE TITLE
Unable to rename business units

### ISSUE THREAD

**Issue by rickheil** [munkireport/munkireport-php#1362]
When I attempt to edit the name of an business unit, the UI doesn't do anything. The javascript console shows the following:

index.php?/admin/show/business_units:1271 Uncaught TypeError: Cannot read property 'length' of undefined
    at HTMLButtonElement.save (index.php?/admin/show/business_units:1271)
    at HTMLButtonElement.dispatch (jquery.js:3)
    at HTMLButtonElement.r.handle (jquery.js:3)
save @ index.php?/admin/show/business_units:1271
dispatch @ jquery.js:3
r.handle @ jquery.js:3

**Comment by bochoven** [comment]
Should be fixed with 1d57f11f39d8d8cd27c765a32b585c012ce69b10

**Comment by rickheil** [comment]
Fixed the reported issue, however, I'm getting the same issue when trying to edit managers/users inside business units.
