### ISSUE TITLE
Vuln in illuminate/database

### ISSUE THREAD

**Issue by daisukixci** [munkireport/munkireport-php#1396]
![image](https://user-images.githubusercontent.com/4062883/105219997-63d33300-5b57-11eb-9694-03eab413e58e.png)
Did you see the dependabot security report about illuminate/database? Is it something that we can bump up or will it break things within Munkireport ?

**Comment by daisukixci** [comment]
Hi, did you get a chance to take a look ?

**Comment by mosen** [comment]
Hi,
Current composer requires Illuminate/database ^7.0 but i dont think the lockfile is published
so running `composer update` should be sufficient to get >= 7.30.3

**Comment by daisukixci** [comment]
it does indeed, since munkireport 5.6.5
