### ISSUE TITLE
AppVersions always empty

### ISSUE THREAD

**Issue by cemkoker** [munkireport/munkireport-php#1401]
Using 5.6.4.4224 I can see the the App that I have added in "APPS_TO_TRACK" in .env and they /show/report/inventory/appVersions but empty.
Going to /show/listing/applications/applications shows everything with right version.

What am I missing here ?

**Comment by cemkoker** [comment]
Quid ?

**Comment by rickheil** [comment]
Mine works fine on the same version - can you post the "APPS_TO_TRACK" line here?

**Comment by cemkoker** [comment]
Sure : 
APPS_TO_TRACK="Zoom, Zoom.us, zoom.us, zoom"

**Comment by rickheil** [comment]
The app should be put in as it would be seen on the file system without ".app", so "zoom.us" that you have in there should do it. When I put that into my array I am seeing things pop up as expected on the page:
![image](https://user-images.githubusercontent.com/8959676/112163259-3d675d80-8bc3-11eb-8f55-330192d63799.png)

 If you put something like Safari in the list, does that show up properly?

**Comment by cemkoker** [comment]
Changed to APPS_TO_TRACK="zoom.us" as you suggested. 
No luck. it's the same. Adding Safari gives the same result.

![image](https://user-images.githubusercontent.com/13544103/112290230-4e7da080-8c8f-11eb-8502-dee468fde1d4.png)

**Comment by gmarnin** [comment]
I have `Zoom.us` in my config. 

Maybe [clear local storage](https://github.com/munkireport/munkireport-php/wiki/Troubleshooting#blank-listings-page)?

**Comment by cemkoker** [comment]
Tried every variation possible; Safari is always still empty as well. Cleared local storage as well. 
In the /show/listing/applications/applications I see them. Nothing on deashboard, nothing in inventory.
Is there another way to flush and force refresh maybe ?

**Comment by bochoven** [comment]
Did you enable the inventory module?

**Comment by cemkoker** [comment]
Yes. 

`MODULES="applications, appusage, directory_service, disk_report, displays_info, extensions, filevault_status, installhistory, inventory, localadmin, managedinstalls, munkiinfo, munkireport, munkireportinfo, network, power, profile, security, softwareupdate,  supported_os, usage_stats, user_sessions, warranty, wifi, fan_temps, usage_stats"`

**Comment by bochoven** [comment]
So did you create and install a new client package after you enabled the modules?

**Comment by cemkoker** [comment]
Wait a second, it doesn't pull back the changes each time ?

**Comment by bochoven** [comment]
No it does not. There's a FR for that but not implemented as of yet.

**Comment by bochoven** [comment]
Check the note here: https://github.com/munkireport/munkireport-php/wiki/Module-Overview#client-side-setup

**Comment by cemkoker** [comment]
Ok so I ran the installer again, and still no luck
 
```
sudo /bin/bash -c "$(curl -s https://MY_URL/index.php?/install)"


# Retrieving munkireport scripts
/Library/LaunchDaemons/com.github.munkireport.runner.plist
/usr/local/munki/postflight
/usr/local/munki/report_broken_client
/usr/local/munkireport/munkilib/__init__.py
/usr/local/munkireport/munkilib/constants.py
/usr/local/munkireport/munkilib/display.py
/usr/local/munkireport/munkilib/FoundationPlist.py
/usr/local/munkireport/munkilib/munkilog.py
/usr/local/munkireport/munkilib/phpserialize.py
/usr/local/munkireport/munkilib/prefs.py
/usr/local/munkireport/munkilib/purl.py
/usr/local/munkireport/munkilib/reportcommon.py
/usr/local/munkireport/munkilib/reports.py
/usr/local/munkireport/munkilib/utils.py
/usr/local/munkireport/munkireport-runner
Configuring munkireport
+ Installing applications
+ Installing appusage
+ Installing directory_service
+ Installing disk_report
+ Installing displays_info
+ Installing extensions
+ Installing fan_temps
+ Installing filevault_status
+ Installing installhistory
+ Installing inventory
+ Installing managedinstalls
+ Installing munkiinfo
+ Installing munkireport
+ Installing munkireportinfo
+ Installing network
+ Installing power
+ Installing profile
+ Installing security
+ Installing softwareupdate
+ Installing supported_os
+ Installing usage_stats
+ Installing user_sessions
+ Installing warranty
+ Installing wifi
- Uninstalling ard
- Uninstalling backup2go
- Uninstalling bluetooth
- Uninstalling caching
- Uninstalling certificate
- Uninstalling crashplan
- Uninstalling detectx
- Uninstalling devtools
- Uninstalling findmymac
- Uninstalling firewall
- Uninstalling fonts
- Uninstalling gpu
- Uninstalling homebrew
- Uninstalling homebrew_info
- Uninstalling ibridge
- Uninstalling laps
- Uninstalling location
- Uninstalling mbbr_status
- Uninstalling mdm_status
- Uninstalling munki_facts
- Uninstalling network_shares
- Uninstalling printer
- Uninstalling sccm_status
- Uninstalling sentinelone
- Uninstalling sentinelonequarantine
- Uninstalling smart_stats
- Uninstalling sophos
- Uninstalling timemachine
- Uninstalling usb
- Uninstalling users
Preparing /Library/Preferences/MunkiReport
Setting preferences
Loading MunkiReport LaunchDaemon
Installation of MunkiReport v5.6.4 complete.

```

**Comment by bochoven** [comment]
It will need some time to populate. Do you see anything in listing inventory?

**Comment by cemkoker** [comment]
In "/show/listing/inventory/inventory" i see the serial number and username populated but Name and versions are empty.

**Comment by bochoven** [comment]
The inventory module collects data from `/Library/Managed Installs/ApplicationInventory.plist` which is populated by munki. Can you see what's in there? Do you use munki?

**Comment by cemkoker** [comment]
Ok getting there; after investigations I found : 

```
Mar 25 2021 08:40:23 +0100 WARNING: Can't open /usr/local/munkireport/scripts/cache/munkiinfo.plist
Mar 25 2021 08:45:09 +0100 WARNING: inventory_add_plugins.py return code: 1
Mar 25 2021 08:45:10 +0100 WARNING: munkiinfo.py return code: 1
Mar 25 2021 08:45:23 +0100 WARNING: Can't open /Library/Managed Installs/ApplicationInventory.plist
Mar 25 2021 08:45:23 +0100 WARNING: Can't open /usr/local/munkireport/scripts/cache/munkiinfo.plist
Mar 25 2021 08:50:08 +0100 WARNING: inventory_add_plugins.py return code: 1
Mar 25 2021 08:50:09 +0100 WARNING: munkiinfo.py return code: 1
Mar 25 2021 08:50:23 +0100 WARNING: Can't open /Library/Managed Installs/ApplicationInventory.plist
Mar 25 2021 08:50:23 +0100 WARNING: Can't open /usr/local/munkireport/scripts/cache/munkiinfo.plist
```

I don't have any "/Library/Managed Installs" folder; what do you mean by 'do you use munki ?'
Thank you

**Comment by bochoven** [comment]
The inventory plugin only works when you are using munki. 

https://en.wikipedia.org/wiki/Munki_(software)?wprov=sfti1
