### ISSUE TITLE
Client with serial number xxx does not exist

### ISSUE THREAD

**Issue by b-reich** [munkireport/munkireport-php#1403]
Hi,

we got a number of clients which report "No Name" in the client overview. When you click on the client it report "Client with serial number xxx does not exist".
Has anyone a clue?

![](https://user-images.githubusercontent.com/1573025/111434705-25de2f80-8700-11eb-90cc-943145a2654a.png)

![](https://user-images.githubusercontent.com/1573025/111434387-c7b14c80-86ff-11eb-94eb-3e892f35d7ba.png)

**Comment by MichalMMac** [comment]
I have this problem only with M1 devices. Somebody reported there is problem with one module (firewall?) causing this.
I am unable to teste since I don't have any M1 for testing purposes.

**Comment by b-reich** [comment]
This could be a thing.

**Comment by dan-snelson** [comment]
@b-reich Are the "No Name" computers able to successfully complete `/usr/local/munkireport/munkireport-runner` ?

(After increasing my PHP settings for `post_max_size` and `upload_max_filesize` the problematic computers displayed as expected.)

**Comment by b-reich** [comment]
@dan-snelson I will check this, I am using the DockerImage. But This Problem has only a few client ~10. We already have 100+ Clients in there.

**Comment by b-reich** [comment]
@MichalMMac we have M1 Macs wich works without problems.

**Comment by b-reich** [comment]
My Problem was the upload size and the config for our kubernetes ingress.
