### ISSUE TITLE
support for php 8

### ISSUE THREAD

**Issue by ABrdfd** [munkireport/munkireport-php#1416]
Is there a timeline projected for support for php 8?

**Comment by flammable** [comment]
I'd imagine that would be tied to mosen's rewrite, and this wouldn't happen to the 5.x codebase.

PHP 7 is still supported for a while longer, so we're in the clear for a bit:

https://www.php.net/supported-versions.php

**Comment by flammable** [comment]
I mean, only @mosen and @bochoven can say for sure, just theorizing. :)

**Comment by ABrdfd** [comment]
Thanks!  Mostly satisfying curiosity :)
