### ISSUE TITLE
Bluetooth Widget

### ISSUE THREAD

**Issue by gmarnin** [munkireport/munkireport-php#142]
I'm attempting to write a bluetooth widget to show all keyboard, mouse and trackpad devices with battery levels under 15%. The query is working but I'm not sure the correct (rawurlencode, i think) syntax to filter out the results when you click on one of the devices. 

Any help is greatly appreciated. 

My code: https://github.com/gmarnin/munkireport-php/compare/bluetooth-widget?expand=1

**Comment by bochoven** [comment]
Widget available in latest release
