### ISSUE TITLE
Delete machine in Client list | General error: 11 database disk image is malformed 

### ISSUE THREAD

**Issue by opus-nbo** [munkireport/munkireport-php#1420]
When trying to delete a machine in the clients list, i get a browser dialog stating:

`
Remove failed: Error: Delete failed for table user_sessions: SQLSTATE[HY000]: General error: 11 database disk image is malformed
`

MunkiReport Version 5.6.6.4225

Installed modules: applications, appusage, ard, bluetooth, caching, devtools, directory_service, disk_report, displays_info, extensions, fan_temps, filevault_status, findmymac, firewall, fonts, gpu, homebrew, homebrew_info, icloud, installhistory, inventory, launchdaemons, localadmin, location, managedinstalls, munki_facts, munkiinfo, munkireport, munkireportinfo, network, network_shares, power, printer, profile, security, softwareupdate, sophos, supported_os, timemachine, usage_stats, usb, users, user_sessions, warranty, wifi'

sqlite driver
Apache 2.4.88
PHP 7.4.21

**Comment by bochoven** [comment]
This means that your database is corrupt. Not something that is due to MunkiReport. If you're running a production environment MySQL is recommended. A little googling found some info that may be of use: https://sqliteviewer.com/blog/database-disk-image-malformed/

**Comment by opus-nbo** [comment]
Thanks for pointing that out @bochoven
