### ISSUE TITLE
help starting up my report

### ISSUE THREAD

**Issue by mikafletcher** [munkireport/munkireport-php#1426]
hi, I've just followed this demo
https://github.com/munkireport/munkireport-php/wiki/Quick-demo

my server works, and it can see my local mac, but how do I spread it out to get my clients to show on my report ?

I must have missed something, my munki server works for my packages, but I just can't get my clients in my report...

thank for your help

**Comment by bochoven** [comment]
Github is for tracking bugs, for general support please reach out to the macadmins Slack munkireport channel:

https://app.slack.com/client/T04QVKUQG/C066NK3K5

**Comment by mikafletcher** [comment]
Hi, thank you for you answer... but how do I connect to that Slack channel ?

**Comment by gmarnin** [comment]
Sign up here:

https://www.macadmins.org




From: mikafletcher ***@***.***>
Reply-To: munkireport/munkireport-php ***@***.***>
Date: Friday, December 3, 2021 at 10:44 AM
To: munkireport/munkireport-php ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [munkireport/munkireport-php] help starting up my report (Issue #1426)


Hi, thank you for you answer... but how do I connect to that Slack channel ?

**Comment by mikafletcher** [comment]
Hi, I’v requested an invitation an invitation with your link but I still haven't received it… how long should it take ?

**Comment by kevinmcox** [comment]
It should be instantaneous, but I see a post that the automatic sign-up link was giving them trouble recently. Give it another try and hopefully you'll get the email right away.

**Comment by kevinmcox** [comment]
In that case I'd just try signing in (resetting your password if needed): https://macadmins.slack.com

**Comment by mikafletcher** [comment]
I don’t understand, but it still doesn’t work…
now I get this mail :
Is this the right email?
It looks like there isn’t an account on MacAdmins tied to this email address.

but the macadmins site tells me This email already registered… i’m sorry about this….

**Comment by cgoIT** [comment]
Same problem here. Registered at about 10 a.m. CET and didn't get an invite email till now. A new try to register leads to the same error message :(

Then I tried to reset my password in the macadmins slack channel. In the email response I'm told, that my email address is not linked to any account in this workspace.

**Comment by kevinmcox** [comment]
Looks like there is a problem with automatic invites. A workspace admin just checked and says he manually approved y'all, hopefully you got the email now.

**Comment by mikafletcher** [comment]
Hi, I never was able to connect to slack.
my email address was not found…

thanks.

**Comment by kevinmcox** [comment]
@mikafletcher It sounds like they are still having problems with the automated invites.

One of us can invite you manually, but we'll need your email.

If you want to send me a message via my website, linked on my GitHub profile, I'll be happy to do so.
