### ISSUE TITLE
MunkiReport does not run on macOS 12.3

### ISSUE THREAD

**Issue by gdarm** [munkireport/munkireport-php#1457]
With macOS 12.3 Beta 1, Apple removed Python entirely.

I tried to fix it for myself by replacing the current shebang of all Python files with the one from munki, but it doesn't work. I think all or at least some Python files are written for 2.7 but not with the one munki installs.

**Comment by kevinmcox** [comment]
This is a known issue being actively worked on. Discussion is ongoing in the #munkireport-dev channel of the MacAdmins Slack.

**Comment by renantea** [comment]
This has been fixed on Munki 5.7.0 but broke MacOS 12.2.1 and below apparently because Munki now uses the third-party python install.

**Comment by bochoven** [comment]
For 5.7 we decided to use munkireport-python2 and not an autodetect script to keep things simple

**Comment by kevinmcox** [comment]
As highlighted in the release notes, MunkiReport now requires the installation of MunkiReport Python2 for all clients for 5.7.0 on all versions of macOS: https://github.com/munkireport/munkireport-php/releases/tag/v5.7.0

The wiki has been updated, but please let us know if any additional clarifying details could be added: https://github.com/munkireport/munkireport-php/wiki/Client-setup#python-2

I also wrote a blog post about the change that I hope is helpful: https://www.kevinmcox.com/2022/02/munkireport-and-python-2/
