### ISSUE TITLE
MunkiReport Client Runner for version 5.7.0 no longer works on Macs with 12.2.1 and below

### ISSUE THREAD

**Issue by renantea** [munkireport/munkireport-php#1463]
Client runner is apparently using the third-party Python install and failed to detect or use the built-in MacOS Python install.

**Comment by kevinmcox** [comment]
As highlighted in the release notes, MunkiReport now requires the installation of MunkiReport Python2 for all clients for 5.7.0 on all versions of macOS: https://github.com/munkireport/munkireport-php/releases/tag/v5.7.0

The wiki has been updated, but please let us know if any additional clarifying details could be added: https://github.com/munkireport/munkireport-php/wiki/Client-setup#python-2

I also wrote a blog post about the change that I hope is helpful: https://www.kevinmcox.com/2022/02/munkireport-and-python-2/

**Comment by renantea** [comment]
Thank you @kevinmcox. 

It didn't say there though... Only mentioned that Apple removed Python from MacOS 12.3. :) Would have been easier if the autodetect script was present so one wouldn't have to install Python to hundred of Macs on existing setup after installing the update.

I can still use the built-in Python though after upgrading to 5.7 by creating a symbolic link to the python executable.

Thanks! :)
