### ISSUE TITLE
Inconsistent formatting on client summary tab

### ISSUE THREAD

**Issue by dcoobs** [munkireport/munkireport-php#1464]
After updating v5.7.0, we're seeing a minor issue where the formatting of some text on the client summary page is inconsistent for various modules (most notably the alternating colored bars behind the text). It looks like it's tied to the update of JQuery to 3.6.0 (eb40d1cb9cf54e16ec59c08f3044e939f3ade8b2) to patch an XSS vulnerability (#1454) as reverting public/assets/js/jquery.js back to JQuery 2.10 appears to fix the issue.

**Before:**
<kbd>
![MR_5 7_before](https://user-images.githubusercontent.com/12276948/154733238-93d22bc0-8ca1-41c6-9a47-6701bb0647e9.png)
</kbd>

**After:**
<kbd>
![MR_5 7_after](https://user-images.githubusercontent.com/12276948/154733251-e8261bf6-b573-44f8-9bba-58a4a6d84d5d.png)
</kbd>

**Comment by flammable** [comment]
+1, this is happening here, too.
