### ISSUE TITLE
docker image is not building/outdated

### ISSUE THREAD

**Issue by b-reich** [munkireport/munkireport-php#1465]
Hi,

the docker image in [docker hub](https://hub.docker.com/r/munkireport/munkireport-php) is realy outdated.
I can provide github acctions tasks for rebuilding the image.

**Comment by b-reich** [comment]
Ahh i see. The Github registry now is used.

**Comment by lolipale** [comment]
Hello,

Any idea when this problem will be solved?
I thank you for your work and support

**Comment by jsharpe** [comment]
It'd be good if the docker hub page could be updated to signpost users to the github registry.

**Comment by bochoven** [comment]
I removed the docker hub munkireport repository. Please use
 ```
docker pull ghcr.io/munkireport/munkireport-php:5.x
```
instead
