### ISSUE TITLE
munkireport installer target to old python in macos monterrey

### ISSUE THREAD

**Issue by xastherion** [munkireport/munkireport-php#1471]
Hello,

I understand that the old python2 from apple is out of date. I know it is the new munkireport-python. I install it, in my clients, but by download the munkireport-install script, the script don´t work in the line 525:

+ Installing inventory
+ munkireport_install.sh: line 525: /usr/bin/python: No such file or directory

i look what is there and:

+ Find out where the munki directory is to set accordingly.
+ munki_install_dir=$(/usr/bin/python -c 'import CoreFoundation; print CoreFoundation.CFPreferencesCopyAppValue("ManagedInstallDir", "ManagedInstalls")')
+ munki_install_dir=$(echo ${munki_install_dir} | sed 's/\/$//')

I change manually the script with the new path to munkireport-python and then is all right, but i don´t know what is the best way to change the script automatic.

Can you help me?

Thanks!

xastherion

**Comment by kevinmcox** [comment]
You also need to upgrade your MunkiReport server install to version 5.7.1, and then generate a new client installation package, which will include all the updated scripts that point to the new MunkiReport Python.

**Comment by xastherion** [comment]
Thank you very much Kevin! Then I do it next week.
