### ISSUE TITLE
Hardware listing incorrect M1 speed

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/munkireport-php#1474]
All my M1 devices incorrectly report a CPU speed of 2.4GHz

<img width="890" alt="image" src="https://user-images.githubusercontent.com/16665880/166394183-6b0c0424-96e0-4686-8a6f-02207a5cba9d.png">

**Comment by tuxudo** [comment]
This is not a MunkiReport issue. The command that generates that data `/usr/sbin/system_profiler SPHardwareDataType -xml` reports those speeds.
