### ISSUE TITLE
Missing Munkireport module

### ISSUE THREAD

**Issue by jelockwood** [munkireport/munkireport-php#1484]
I have Munkireport 5.7.1.4264 operational and I have ensured all the modules are enabled and updated, this in particular includes the 3rd party ms_defender module. See the following from the Munkireport module marketplace.

![Screenshot 2022-09-12 at 11 07 15](https://user-images.githubusercontent.com/4300786/189629669-f5178bb2-62f8-42a4-b107-9ab1884db82f.png)

However despite this and despite the fact we have explicitly included it in the MODULES="" variable it does not show up in the report produced using the 
```
https://example.com/index.php?/install/dump_modules/env
```
This shows as follows in our case
```
MODULES="applications, appusage, ard, bluetooth, caching, certificate, detectx, devtools, directory_service, disk_report, displays_info, extensions, fan_temps, filevault_escrow, filevault_status, findmymac, firewall, fonts, gpu, homebrew, homebrew_info, ibridge, installhistory, inventory, laps, location, managedinstalls, mbbr_status, mdm_status, munki_facts, munkiinfo, munkireport, munkireportinfo, network, network_shares, power, printer, profile, sccm_status, security, sentinelone, sentinelonequarantine, smart_stats, softwareupdate, supported_os, timemachine, usage_stats, usb, user_sessions, users, warranty, wifi"
```
As you can see it is missing the ms_defender entry. This then means the install script (and pkg) are also missing this module.

Any ideas why it is missing? Despite the fact we have defined it to be in the MODULES variable?

**Comment by tuxudo** [comment]
Something is wrong with the module's folder and structure on the server. 

Module Marketplace lists a module as enabled by directly comparing `MODULES` in .env. `dump_modules/env` defines an enabled module by one that has a `ms_defender_model.php` or `install.sh`, which make it a valid module.

Verify that the module has `tuxudo/ms_defender/ms_defender_model.php` and `tuxudo/scripts/install.sh`

**Comment by jelockwood** [comment]
@tuxudo 
As additional information we are running MunkiReport on an AWS EC2 instance. I got our DevOps team to enable using a ssh session to allow interactive debugging via a shell. Via this we did an export of the MODULES variable and it does contain ms_defender.

The vendor/munkireport/ directory does contain an ms_defender folder which contains amongst others ms_defender_model.php and a subdirectory called scripts which contains both an install.sh and uninstall.sh

**Comment by jelockwood** [comment]
@tuxudo I have been working with our DevOps engineer and it looks like the module was int eh right place, was installed properly and the modules was int he enabled list but we had not added the module director to the MODULE_SEARCH_PATHS

Now seems to show up.
