### ISSUE TITLE
Battery status on Apple Silicon not correct

### ISSUE THREAD

**Issue by mariuslangz** [munkireport/munkireport-php#1486]
Checked battery status on the fleet of Mac's we are managing today, and was baffled by all the devices which seemed to have poor battery. Looks like all M1/2 machines have 100 mAh capacity, which of course is not correct :)

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/12494526/190257115-3a417c09-0db7-4c0f-a6bc-0a508a50c612.png">

**Comment by tuxudo** [comment]
As @joncrain noted in the MacAdmins Slack, you need to update the power module to the latest version and then create a new client pkg with the new module.

**Comment by mariuslangz** [comment]
Aah, must've missed that post. Thanks for the quick reply!
