### ISSUE TITLE
local_users table group_memership field too short

### ISSUE THREAD

**Issue by jeffreydn** [munkireport/munkireport-php#1493]
I received an error from munkireport-runner saying the length of the group_memership field in local_users was too short. If I increase the length of the field in the table, everything works as far as I can tell.

**Comment by tuxudo** [comment]
I'm guessing this happens when running the `users` module? This should be fixed with version v2.3 of the `users` module that was released on March 22, 2022. Can you verify that the `users` module is at least v2.3 and run database migrations?

**Comment by jeffreydn** [comment]
Yes, I apologize I forgot the modules have versions and upgrades independent of the overall system, so I thought I was up to date but I was not! Thank you.
