### ISSUE TITLE
Error reported for missing /Library/Managed Installs/AppleUpdates.plist

### ISSUE THREAD

**Issue by ericholtam** [munkireport/munkireport-php#1495]
I’m seeing some Errors show up in MR with Munki 6.0.1+ regarding `Error reading: /Library/Managed Installs/AppleUpdates.plist`

It looks like Munki 6.0.1 changed behavior to remove the file if no updates are available.  https://github.com/munki/munki/commit/2d4bafe694de588e3b2be7e73a09dbc459adbf41

MR should also check/validate for existence first before trying to read that file so it doesn't report false positive errors.

**Comment by tuxudo** [comment]
Is this a MunkiReport issue? I don't think any of the modules' scripts use or access that file.

**Comment by ericholtam** [comment]
I guess this is just a Munki "error" that MunkiReport is reporting on. There have been a few mentions of this issue in the macadmins slack, but no root cause or remediation.  Others have just ignored it as it doesn't happen consistently on endpoints.

**Comment by flammable** [comment]
Could the Events module filter out those messages, if they're normal behavior?
