### ISSUE TITLE
MunkiReport and Python3 versions

### ISSUE THREAD

**Issue by jelockwood** [munkireport/munkireport-php#1549]
I have set MunkiReport up previously at several companies and I am now beginning the same process at my current employer.

I found the following article by @kevinmcox which lists a concern over which version of Macadmins Python3 installer to use with MunkiReport. This article is however now a bit dated and there have been further updates to the Macadmins Python3 pkg since it was written.

https://www.kevinmcox.com/2023/06/munkireport-python-3-and-php-8/#more-1761

Is there a new recommended version to use or should one still stick with 3.10.9.80716?

**Comment by tuxudo** [comment]
For the time being, you have to use Python 3.10, but any version of 3.10 will work properly with MunkiReport 5.8.

**Comment by jelockwood** [comment]
Thanks, yes 3.10 is working fine, I have configure my Munki repo not to enable newer versions at this time.
