### ISSUE TITLE
Internet Plug-Ins in inventory items

### ISSUE THREAD

**Issue by mattiasvdm** [munkireport/munkireport-php#160]
It would be nice if the internet pug-ins would also be visible in the inventory items. Plugins like flash player and Java need to be updated regularly...

**Comment by nbalonso** [comment]
I think the new AppVersions report in v2.3 addresses your needs.

As explained in the [config_default.php](https://github.com/munkireport/munkireport-php/blob/master/config_default.php#L421) you can specify some apps for easy tracking.

To be more specific the following will track Flash Player, Java and the most common web browsers:
```php
$conf['apps_to_track'] = array('Safari',
                        'Firefox',
                        'Google Chrome',
                        'Flash Player',
                        'Java');
```

**Comment by bochoven** [comment]
And I think Internet Plugin reporting has been added to inventory since 2522b95c1d6f6881e05569f08bb0ae4cd913b786

**Comment by nbalonso** [comment]
The combination of both is 👌

**Comment by mattiasvdm** [comment]
Nice one! So I guess this issue can be closed?

**Comment by bochoven** [comment]
Be my guest!

**Comment by mattiasvdm** [comment]
Thanks guys! :)
