### ISSUE TITLE
Bug? Managed Installs list appears in random order

### ISSUE THREAD

**Issue by diwanicki** [munkireport/munkireport-php#178]
On the Managed Software tab (tab_munki) of the Client Detail page, the list of Managed Installs appears to have no particular order... I've noticed this in the past, but never paid much attention to it. Now my list of items has grown large enough for this to be a minor issue when scanning for a particular item on that particular machine.

Would it be possible to order Managed Installs in alpha order by "Display Name"?

**Comment by bochoven** [comment]
Fixed with #211
