### ISSUE TITLE
SSL Error on OS X Yosemite Server

### ISSUE THREAD

**Issue by joshua-d-miller** [munkireport/munkireport-php#179]
Hello,

I'm running MunkiReport-PHP on OS X Yosemite Server with an SSL Apache server.  Since the upgrade I can no longer submit data as I receive this error:

ERROR: Munkireport: https://server/munkireport/index.php?/report/hash_check
ERROR: Munkireport: We failed to reach a server
ERROR: Munkireport: Reason: [Errno 8] _ssl.c:507: EOF occurred in violation of protocol

I'm assuming that this is because the only thing that would have changed would have been the version of Apache 2.4.9 and a fix for the POODLE vulnerability which disables SSLv3.  I'm wondering if MunkiReport-PHP is trying to use SSLv3 and with it disabled it cannot.  Any insight would be helpful.

Thank you!

Also I'm running MunkiReport-2.1.0 from the Main repository.

**Comment by TrentLewisAU** [comment]
Hi Guys,

I have this same error but can't quite work out how to implement a fix. @joshua-d-miller would you be able to advise where might I find the reportcommon.py file to implement this fix? Or, the the more inexperienced githubbers out there, how might I access and use the pull request you put up (I don't really know how it all works sorry!)

Thanks heaps.

**Comment by joshua-d-miller** [comment]
@TrentLewisAU I believe my pull request was just merged so if you clone the WIP branch you should get the update.
