### ISSUE TITLE
Munkireport 2.2.0 Migration error

### ISSUE THREAD

**Issue by SailorMars** [munkireport/munkireport-php#196]
After a git pull and $conf['allow_migrations'] = TRUE;
I get this message in the dashboard:
Migration error: machine: Failed: SQLSTATE[HY000]: General error: 1 unrecognized token: "` VARCHAR(255))"

A result of the 003_machine_add_cpu.php ?

**Comment by bochoven** [comment]
SQLite or MySQL? What version were you migrating from?

**Comment by SailorMars** [comment]
Sorry for the incomplete information
SQLite and MunkiReport Version 2.1.0.926

**Comment by bochoven** [comment]
Should be fixed with 1bec9b610560bca0c3bd386101f00572052cfa88, could you check?

**Comment by SailorMars** [comment]
did a new pull but the same result
Migration error: machine: Failed: SQLSTATE[HY000]: General error: 1 unrecognized token: "` VARCHAR(255))"

**Comment by bochoven** [comment]
The commit was on the bugfix branch, I've merged bugfix with master now. So please try again.

**Comment by SailorMars** [comment]
Works like charm, thanks
Migrated Machine_model to version 4
