### ISSUE TITLE
After Upgrade errors

### ISSUE THREAD

**Issue by adambarnett52** [munkireport/munkireport-php#197]
Hi 

After and upgrade from 2.0 to latest release i get the following errors

 `Migration error: inventoryitem: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes`
`Migration error: network: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes`

Using MySQL

Thanks

**Comment by bochoven** [comment]
MySQL complains that a key is too long. This could be either serialnumber or name+version. If you have access to your MySQL database, please run:

```sql
select id, serial, CONCAT(name, version), CHAR_LENGTH(CONCAT(name, version)) as keylength from inventoryitem order by keylength DESC LIMIT 10
```

This will give you the top 10 entries with the longest name+version strings.
Likewise you could run a query for the longest serial_number:

```sql
select id, serial, CONCAT(name, version), CHAR_LENGTH(serial) as keylength from inventoryitem order by keylength DESC LIMIT 10
```

**Comment by adambarnett52** [comment]
Hi here is the output

| id      | serial       | CONCAT(name, version)
      | keylength |
+---------+--------------+-------------------------------------------------------+-----------+
| 8457159 | C02NT3TVG3QP | License Transfer Utility(Simplified
Chinese)0.0.0.0.0 |        53 |
| 8265958 | C02N26GDG3QD | License Transfer Utility(Simplified
Chinese)0.0.0.0.0 |        53 |
| 4854453 | W8050018HE6  | License Transfer Utility(Simplified
Chinese)0.0.0.0.0 |        53 |
| 8460623 | C02M41VJFD59 | Default
aohghmighlieiainnegkcijnfilokake36.0.1985.125 |        53 |
| 8234437 | C02HFGVWDV7L | Default
bepbmhgboaologfdajaanbcjmnhjmhfn35.0.1916.114 |        53 |
| 8444714 | C02N837UG3QP | Default
ngljgiikbpkpfacabheampboanbppiee38.0.2125.122 |        53 |
| 8444607 | C02N837UG3QP | Default
fahmaaghhglfmonjliepjlchgpgfmobi38.0.2125.122 |        53 |
| 8444648 | C02N837UG3QP | Default
fahmaaghhglfmonjliepjlchgpgfmobi38.0.2125.122 |        53 |
| 8209948 | C02N14QMFD57 | License Transfer Utility(Simplified
Chinese)0.0.0.0.0 |        53 |
| 8280426 | W80489GEDAS  | Default
aohghmighlieiainnegkcijnfilokake35.0.1916.114 |        53 |
+---------+--------------+-------------------------------------------------------+-----------+


looks like this is the issues


On Mon, Feb 2, 2015 at 10:35 AM, Arjen van Bochoven <
notifications@github.com> wrote:

> MySQL complains that a key is too long. This could be either serialnumber
> or name+version. If you have access to your MySQL database, please run:
>
> select id, serial, CONCAT(name, version), CHAR_LENGTH(CONCAT(name, version)) as keylength from inventoryitem order by keylength DESC LIMIT 10
>
> This will give you the top 10 entries with the longest name+version
> strings.
> Likewise you could run a query for the longest serial_number:
>
> select id, serial, CONCAT(name, version), CHAR_LENGTH(serial) as keylength from inventoryitem order by keylength DESC LIMIT 10
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/197#issuecomment-72436029>
> .
>



-- 
Adam Barnett

**Comment by bochoven** [comment]
Your longest key is 53 that is less than 1000, could you run the other query as well?

```sql
select id, serial, CONCAT(name, version), LENGTH(serial) as keylength from inventoryitem order by keylength DESC LIMIT 10
```

**Comment by adambarnett52** [comment]
mysql> select id, serial, CONCAT(name, version), LENGTH(serial) as
keylength from inventoryitem order by keylength DESC LIMIT 10;
+---------+---------------------------+-------------------------------+-----------+
| id      | serial                    | CONCAT(name, version)         |
keylength |
+---------+---------------------------+-------------------------------+-----------+
| 8273895 | VMWVk1p9AQmtHLcDORVh3j5IQ | dynamiclinkmanager7.1.0       |
   25 |
| 8273908 | VMWVk1p9AQmtHLcDORVh3j5IQ | Microsoft Query12.0.0         |
   25 |
| 8273854 | VMWVk1p9AQmtHLcDORVh3j5IQ | LogTransport1.0               |
   25 |
| 8273905 | VMWVk1p9AQmtHLcDORVh3j5IQ | dynamiclinkmediaserver7.0.1   |
   25 |
| 8273859 | VMWVk1p9AQmtHLcDORVh3j5IQ | ImporterREDServer7.1.0        |
   25 |
| 8273858 | VMWVk1p9AQmtHLcDORVh3j5IQ | relaunch1.0                   |
   25 |
| 8273906 | VMWVk1p9AQmtHLcDORVh3j5IQ | Microsoft Upload Center14.3.9 |
   25 |
| 7807857 | VMWVk1dY3wpRaTxH2s3Jv2Vew | EPSON Scanner5.6.0            |
   25 |
| 7807865 | VMWVk1dY3wpRaTxH2s3Jv2Vew | Microsoft Clip Gallery14.3.9  |
   25 |
| 7807864 | VMWVk1dY3wpRaTxH2s3Jv2Vew | Microsoft Query12.0.0         |
   25 |
+---------+---------------------------+-------------------------------+-----------+
10 rows in set (0.16 sec)


On Mon, Feb 2, 2015 at 11:14 AM, Arjen van Bochoven <
notifications@github.com> wrote:

> Your longest key is 53 that is less than 1000, could you run the other
> query as well?
>
> select id, serial, CONCAT(name, version), LENGTH(serial) as keylength from inventoryitem order by keylength DESC LIMIT 10
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/197#issuecomment-72440826>
> .
>



-- 
Adam Barnett

**Comment by bochoven** [comment]
What version of MySQL?

**Comment by adambarnett52** [comment]
I did a restart of mysql and it all seems fine now
Thanks


On Mon, Feb 2, 2015 at 11:50 AM, Arjen van Bochoven <
notifications@github.com> wrote:

> What version of MySQL?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/197#issuecomment-72444508>
> .
>



-- 
Adam Barnett

**Comment by bochoven** [comment]
Hmm, maybe closed too early. What do you mean by 'all seems fine now' Did you actually migrate?

**Comment by adambarnett52** [comment]
Yes. I am now running the new version and the migration completed

**Comment by bochoven** [comment]
Ok, thanks!

**Comment by adambarnett52** [comment]
Hi 

This error has come up again after doing an upgrade

Same output for the command as above

Any ideas?

**Comment by bochoven** [comment]
Restart MySQL?

**Comment by bochoven** [comment]
Do you get both inventoryitem and network migration errors?

Could you post the output of:

```sql
SHOW TABLE STATUS LIKE 'inventoryitem';
SHOW CREATE TABLE `inventoryitem`;
```

**Comment by adambarnett52** [comment]
```
mysql> SHOW TABLE STATUS LIKE 'inventoryitem';
+---------------+--------+---------+------------+--------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+---------------------+-----------------+----------+----------------+---------+
| Name          | Engine | Version | Row_format | Rows   | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time         | Update_time         | Check_time          | Collation       | Checksum | Create_options | Comment |
+---------------+--------+---------+------------+--------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+---------------------+-----------------+----------+----------------+---------+
| inventoryitem | MyISAM |      10 | Dynamic    | 113429 |            187 |    21325052 | 281474976710655 |      2020352 |     10668 |       10805517 | 2014-07-01 09:11:53 | 2015-03-13 16:11:10 | 2014-07-01 09:11:54 | utf8_general_ci |     NULL |                |         |
+---------------+--------+---------+------------+--------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+---------------------+-----------------+----------+----------------+---------+


+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table         | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                             |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| inventoryitem | CREATE TABLE `inventoryitem` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `serial` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `version` varchar(255) DEFAULT NULL,
  `bundleid` varchar(255) DEFAULT NULL,
  `bundlename` varchar(255) DEFAULT NULL,
  `path` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `inventoryitem_serial` (`serial`)
) ENGINE=MyISAM AUTO_INCREMENT=10805517 DEFAULT CHARSET=utf8 |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

```
