### ISSUE TITLE
Doc: client setup options

### ISSUE THREAD

**Issue by clburlison** [munkireport/munkireport-php#199]
I didn't want to create a wiki page in case you wanted to modify the information. Instead I copied from the setup docs and added to it... Hopefully this helps?

Thanks!

----

Munkireport is versatile in how you are able to add client machines to the reporting server. The manual option is used mostly for testing however the following two methods are the recommended way to distribute the setup to client machines. You can use either the _nopkg_ install option or the _pkg_ option however you should not use both.

Setting up a client manually
---

To verify that your reporting server is setup correctly, on a client machine, run the following:

1. Open Terminal.app
2. Type: `sudo /bin/bash -c "$(curl -s http://example.com/index.php?/install)"`

Setting up clients with munki (nopkg)
---

When the manual test above goes well, you can add a pkginfo (nopkg install) file to your munki repo:

1. Download the pkginfo file  
    `curl -s http://example.com/index.php?/install/plist -o ~/Desktop/MunkiReport.plist`.
2. Copy _MunkiReport.plist_ into your Munki repository (in your pkgsinfo directory).
3. Run makecatalogs, and be sure to add it to a manifest as well.

Setting up clients with munki (pkg)
---
With the release of [v2.2.0](https://github.com/munkireport/munkireport-php/releases/tag/v2.2.0.beta1) we can create an installer package using the following:

1. Create the installer ``bash -c "$(curl http://example.com/index.php?/install)" bash -i ~/Desktop``.
2. Run ``/usr/local/munki/munkiimport ~/Desktop/munkireport-2.2.0.pkg`` (changing the version number as needed).
3. Run makecatalogs, and be sure to add the newly imported package to a manifest.

**Comment by diwanicki** [comment]
done

**Comment by bochoven** [comment]
Ok, thanks!
