### ISSUE TITLE
Pending Install Dashboard Number Doesn't Match Pending Install Report

### ISSUE THREAD

**Issue by dingerkingh** [munkireport/munkireport-php#200]
Hi There:

The widget in the Dashboard that shows pending installs for a given package doesn't match what the report actually shows. Meaning - AdobeFlashPlayer shows 20 pending installs. I click on AdobeFlashPlayer in the Pending install list which brings me to the link http://munki.sad1.org/report/index.php?/module/munkireport/pending#AdobeFlashPlayer which actually lists 42 pending installs. It appears that none of the pending numbers are correct. 

MunkiReport Version 2.2.0.975

**Comment by bochoven** [comment]
If you hover over the 'Pending installs' header, you'll see that it shows 'Pending installs for this week'. If you go to the list view (by clicking on an item in the pending installs widget), you'll get all pending installs. This is expected behaviour.

**Comment by dingerkingh** [comment]
Yup - I am dumb. Sorry

**Comment by bochoven** [comment]
Don't feel dumb, it's not that obvious. I'm glad you took the time to report an issue.
