### ISSUE TITLE
Snow Leopard does clients only seem to report to server when TLS-based transmission is used

### ISSUE THREAD

**Issue by darren-bdf** [munkireport/munkireport-php#202]
In testing version 2.2.0 of MunkiReport, I found that our Snow Leopard clients refused were only able to report back to our MunkiReport server when information is being transmitted to it insecurely. It should be noted that in my tests, I had set up our server to use a self-signed certificate.

I brought this issue to the MunkiReport group (see https://groups.google.com/forum/#!topic/munkireport/lAriRM1pUmA), and it was determined that by setting TLS to False in reportcommon.py, I was able to work around this problem, meaning that I'd have to make that change on all 10.6 computers in our organisation.

Having to modify that file every time I deploy MunkiReport to Snow Leopard computers seems like a bug. Could you see whether it's possible to resolve this issue for Snow Leopard computers?

**Comment by bochoven** [comment]
Could you check if this issue is fixed with this commit? 02fdf868e851389644a7d70ca29a6b32f274d0f1
It fixed the issue on 10.6 clients (using python 2.6) in my environment.

**Comment by mathias01** [comment]
This commit fixed our 10.6 clients as well.

**Comment by darren-bdf** [comment]
I've merged this commit, and it appears to work in our environment as well. I'll set about applying the fix to all machines.

**Comment by bochoven** [comment]
Fixed with 02fdf86
