### ISSUE TITLE
Network Report 

### ISSUE THREAD

**Issue by AlroneRhyn** [munkireport/munkireport-php#203]
Hello,
Munkireport fails to display correctly Network Report when a lot of networks (vlans) are used. cf jpg.
Version 2.1.0.926

Thx a lot for your great job !

![networkwierdreport](https://cloud.githubusercontent.com/assets/8383459/6390589/e164ae5a-bdad-11e4-9882-24ba32b6f087.png)

**Comment by bochoven** [comment]
A pie chart may not be the best way to represent this data

**Comment by bochoven** [comment]
You know you can group IP ranges together?

```php
$conf['ip_ranges']['Location1'] = array('211.88.12.', '211.88.13.');
$conf['ip_ranges']['Location2'] = array('211.88.14.', '211.88.15.');
```

**Comment by AlroneRhyn** [comment]
For sure i can. I did. I've gote multiple vlans. too much to be handled be mukireport, that's my issue.

**Comment by bochoven** [comment]
Your issue should be fixed with the latest release.

**Comment by AlroneRhyn** [comment]
Hi ! 
Thx new Network Location is (nearly) AWESOME. The double click effect to isolate the items is insane ;)
BUT, it's still hard to read : graph is too small and the legend is too space consuming (cf jpg)
![network](https://cloud.githubusercontent.com/assets/8383459/7116352/482fc482-e1f1-11e4-9d31-c571491ed481.png)
It would be great too to be able to view a list thx to a click on the location or Network chart/graph.

Thx a lot !

**Comment by bochoven** [comment]
Could you check the latest preview release and see if that solves your issue?

https://github.com/munkireport/munkireport-php/releases/tag/v2.4.0
