### ISSUE TITLE
Leopard clients does not connect to MRphp anymore

### ISSUE THREAD

**Issue by gdarm** [munkireport/munkireport-php#209]
Since newest version of MRphp clients with 10.5.8 does not connect to MRphp anymore because of an import error. The ssl module is not available on Python 2.5.1 which is installed on 10.5.8 clients by default.

![screen shot 2015-03-09 at 11 33 36](https://cloud.githubusercontent.com/assets/8056453/6553465/48a7975c-c651-11e4-9a59-12bbc3c25532.png)

I tried to install Python 2.6.1 but then I received a new error: "Python is missing ObjC bindings."

So I decided to setup an older version of MRphp to support the old clients.

Because this is only related to 10.5.8 clients maybe we should drop support for this system and update the install_plist.php to minimum_os_version of 10.6.8?
Or if there is a fix available just let me know I'll test it on my last five clients. ;)

**Comment by nbalonso** [comment]
which version of Munki do you use?

According to [this](https://github.com/munki/munki/wiki#munki-versions) 10.5 clients should use v1.0.x

**Comment by gdarm** [comment]
On my old clients I only install the last munki version for 10.5 clients: munkitools-1.0.0.1864.0.

I haven't tested the latest munkitools on 10.5 clients, but I think the installation will fail because of the system requirements.

**Comment by bochoven** [comment]
I have no access to a 10.5 machine anymore, but could you check if python 2.6 exists here:

```
/usr/bin/python2.6
```

if it exists, you could change the 'hashbang' at the top of the preflight and postflight scripts to

```
#!/usr/bin/python
```

**Comment by gdarm** [comment]
Good point, but there is no version 2.6 :(

![screen shot 2015-03-09 at 14 17 08](https://cloud.githubusercontent.com/assets/8056453/6555520/0ac41986-c667-11e4-8c6a-f5593b99d5c5.png)

**Comment by bochoven** [comment]
Bummer, you can also disable the TLS fixing code (if your server does not need it): in /usr/local/munki/munkilib/reportcommon.py delete/comment out

```
import httplib
import socket
import ssl
```
and change
```
TLS = True
```
to
```
TLS = False
```

**Comment by nbalonso** [comment]
So you know that munki without munkireport works fine on this client, right?

**Comment by gdarm** [comment]
@nbalonso 
Yes, it's working well without munkireport.

As @bochoven  suggested I've commented out
```
import httplib
import socket
import ssl
```

and set TLS to
```
TLS = False
```

But munkireport needs httplib so I removed the comment at
```
import httplib
```

I also removed the comment at
```
import socket
```

Then I added some code and removed the line with ```TLS = True``` This will test for ssl module and if available set TLS to true. Otherwise TLS is false.

```
try:
	__import__('imp').find_module('ssl')
	import ssl
	TLS = True
except ImportError:
	TLS = False
```

Could we add this to the reportcommon.py?

**Comment by bochoven** [comment]
Looks ok to me, file a pull request with your changes.

I'm beginning to wonder if we should look at [gurl](https://github.com/munki/munki/blob/master/code/client/munkilib/gurl.py) as a replacement of urllib2

**Comment by nbalonso** [comment]
I'm not sure if all the module will work as expected on 10.5.x

Plus, in my opinion, running 10.5 is a terrible thing due to security issues and you should consider upgrading those clients. Even if it means getting newer hardware.

**Comment by gdarm** [comment]
I'm with you @nbalonso . But the project the users are working on can only run on 10.5 clients. Several years ago they tried to convert their files to a newer software version, but that failed horribly. So they decided to leave the project on 10.5...

That's why I asked in my initial post: Should we drop support for 10.5 clients?

In my case I could setup an older version of munkireport and leave the clients until the project is completed, which is hopefully this year. ;)

**Comment by nbalonso** [comment]
I understand that business mandates this things rather than "good practices".

Support for 10.5 might imply some manual adjustments on those clients. Eg. disabling some modules that don't work, modifying the scripts...

Hopefully you won't have many old clients and those won't be formatted often
