### ISSUE TITLE
Power status reports bogus info on non-portable machines

### ISSUE THREAD

**Issue by 48kRAM** [munkireport/munkireport-php#212]
The 2.3 release includes a new status for battery info - "power". This listing reports bogus information (1mAh, manufactured 35 years ago) for machines that are not portables and not equipped with a battery. It would be nice to display that there is no battery present on non-portables.

**Comment by bochoven** [comment]
Already fixed in 0323d161d8e5342434c81f51f4026f10c6482ba2
