### ISSUE TITLE
OS Breakdown Widget Duplicate Entries

### ISSUE THREAD

**Issue by vincentw8460** [munkireport/munkireport-php#214]
MunkiReport version 2.3.0.1010
Host OS: Mac OS X Yosemite 10.10.2

It seems that I'm having an issue with the OS breakdown widget.

There are two graphs for the same `10.9.5` OS version:

![screen shot 2015-03-14 at 10 59 04 pm](https://cloud.githubusercontent.com/assets/6693452/6654634/733d09ec-ca9e-11e4-8a53-2849ac347f10.png)

Also, it seems that when I click on the `10.10.2` OS version button, it takes me to an empty view:

![screen shot 2015-03-14 at 10 59 13 pm](https://cloud.githubusercontent.com/assets/6693452/6654637/aa0e0a02-ca9e-11e4-8aab-dc0785d725da.png)

**Comment by rickheil** [comment]
This is happening with 10.10.1 and 10.10.2 as well for me:

**Comment by bochoven** [comment]
Could you post the outcome of 

https://your_munkireport_server/optional_path/index.php?/module/machine/os

**Comment by rickheil** [comment]
I have the following:

[{"label":"10.10.1","data":[[4,0]]},{"label":"10.10.2","data":[[4,1]]},{"label":"10.6.8","data":[[2,2]]},{"label":"10.7.5","data":[[1,3]]},{"label":"10.9.4","data":[[1,4]]},{"label":"10.9.5","data":[[41,5]]},{"label":100905,"data":[[4,6]]},{"label":101000,"data":[[1,7]]},{"label":101001,"data":[[2,8]]},{"label":101002,"data":[[33,9]]},{"label":101003,"data":[[2,10]]}]

**Comment by vincentw8460** [comment]
I have the following:

[{"label":100608,"data":[[2,0]]},{"label":100705,"data":[[1,1]]},{"label":100805,"data":[[8,2]]},{"label":100902,"data":[[2,3]]},{"label":100903,"data":[[1,4]]},{"label":100904,"data":[[2,5]]},{"label":100905,"data":[[72,6]]},{"label":101000,"data":[[6,7]]},{"label":101001,"data":[[6,8]]},{"label":101002,"data":[[74,9]]}]

On a side note, since my setup was a test instance, I removed all entries in the database and let them re-create themselves and everything looks happy now.

**Comment by bochoven** [comment]
It looks like you did not migrate the db.

-Arjen

**Comment by rickheil** [comment]
Hmm, I thought I had left migrate as true. I'll look into it tomorrow and manually correct the bad ones if that's the case.

**Comment by rickheil** [comment]
Yep, looks like that part of the migrate either didn’t run or didn’t finish. Thanks for the pointer.
