### ISSUE TITLE
Network location report looks weird with two locations...

### ISSUE THREAD

**Issue by rickheil** [munkireport/munkireport-php#217]
I get this fun little thing instead of a nice looking pie chart or oval chart...

![screenshot 2015-03-16 16 08 33](https://cloud.githubusercontent.com/assets/8959676/6675435/bab3df54-cbf6-11e4-9cde-fc63e48511ff.png)

**Comment by nbalonso** [comment]
can you please share the [Dashboard - IP Ranges](https://github.com/munkireport/munkireport-php/blob/master/config_default.php#L351) you have in your own `config.php` ?

**Comment by bochoven** [comment]
This is a rendering issue with de nvd3 donut chart, I'll take a look if they fixed it already.
