### ISSUE TITLE
Warranty in latest WIP version says "No Information Found"

### ISSUE THREAD

**Issue by joshua-d-miller** [munkireport/munkireport-php#227]
Hello,

Just as the title says all my clients say "No Information Found" with the latest WIP version.  I'm wondering if there is an issue with how it is pulling the warranty as I checked the warranty.txt file on a client and it just says the last time it checked.

Thanks!

**Comment by bochoven** [comment]
You can check the warranty yourself: go to https://selfsolve.apple.com/agreementWarrantyDynamic.do and fill out the serial number.

**Comment by bochoven** [comment]
Could you check if my latest commit fixes your issue?

**Comment by joshua-d-miller** [comment]
Just checked this morning in the WIP branch and YES it fixed the issue.  Thank you very much!! :+1:
