### ISSUE TITLE
Computer description changes to model_lookup_failed

### ISSUE THREAD

**Issue by nbalonso** [munkireport/munkireport-php#228]
Every couple of days we have ~4-5 machines that loose the description.

Eg. a computer that used to be `MacBook Pro (15-inch, Early 2011) ` becomes `model_lookup_failed` until we re-check the warranty status.

We should prevent updating the field when Apple servers are not responding

**Comment by bochoven** [comment]
I think we should also decouple the warranty lookup from the model lookup.
