### ISSUE TITLE
Servermetrics

### ISSUE THREAD

**Issue by stefan-vogel** [munkireport/munkireport-php#229]
Dear all
Although there are other tools like nagios or cacti, we'd like to have server infos in munkireport and then have the ability to make a summary of it. The logs can be found in /private/var/log/servermetricsd/. Server.app is cool, but not flexible enough. Furthermore we'd like to see the evolution of the TimeMachine status and TimeMachineServer status. And the amount of free strage in %. And when the certificats run out. And Crashplan if possible. Perhaps even more, but let's start easy.

Now the problem. I have no idea how to code it and I'm looking for someone who could do it for me (not for free of corse).

Thanks for inputs, Stefan.

**Comment by bochoven** [comment]
Hi Stefan,

Could you contact me directly about this?

-Arjen

**Comment by stefan-vogel** [comment]
Dear Arjen
Well yes - but how? You could call me at 0041 76 3776773 or send me an email at s.vogel@powersolutions.ch

Stefan =:-)
