### ISSUE TITLE
Switch page

### ISSUE THREAD

**Issue by AlroneRhyn** [munkireport/munkireport-php#238]
Hello !
When selecting more records than my browser can diplay, i'm scrolling down to switch pages. Once i'm going next page, it would be great to get a "go to top" fonction. Right now app is leaving me on the bottom.

Thx !

**Comment by bochoven** [comment]
Not scrolling when you get the next result set is intended behaviour. Would you like a 'Go to top' button?

**Comment by AlroneRhyn** [comment]
Hello, i don't know if i was able to clearly explain what's happening. Here is 3 screenshots. Current behaviour is ss1.png -> ss2.png and intented behaviour should be ss1.png -> ss3.png. Next page action should bring me to next page top result. Am i wrong ? 

![ss1](https://cloud.githubusercontent.com/assets/8383459/7248050/234ff05e-e810-11e4-8f7d-5e06d2805ac6.png)
![ss2](https://cloud.githubusercontent.com/assets/8383459/7248051/2350f1fc-e810-11e4-8a8e-42373e63bdec.png)
![ss3](https://cloud.githubusercontent.com/assets/8383459/7248052/23560fd4-e810-11e4-8e8a-b88136ac7f82.png)

And it's not the case.

**Comment by bochoven** [comment]
I understand your issue, but I can't fix it. You should either
- use the paging feature
- use scrolling
