### ISSUE TITLE
Show OS Build Numbers

### ISSUE THREAD

**Issue by gmarnin** [munkireport/munkireport-php#240]
Display the OS build number on the OS breakdown widget and the client details page.

**Comment by bochoven** [comment]
Before we show the build number, we must first collect and store it!

**Comment by hunty1** [comment]
#!/bin/bash

os_build=`sw_vers | awk '/BuildVersion/ {print $2}'`

Now how to store it sql? I'm guessing thats all fancy php voodoo ;)

**Comment by gmarnin** [comment]
In bash that works but the rest of the hardware_info code is in [python] (https://github.com/munkireport/munkireport-php/blob/783c245bfa5e75da3b9507ee6c08d14cf19dd436/assets/client_installer/submit.preflight#L29-L30)

and there's all that php voodoo...

**Comment by hunty1** [comment]
Ahh.. 
what about 
```
import os
print(os.popen("sw_vers -buildVersion").read().strip())
```

**Comment by gmarnin** [comment]
Reporting on OS build version has been added in v2.5.3: https://github.com/munkireport/munkireport-php/releases/tag/v2.5.3

Thanks!
