### ISSUE TITLE
version question

### ISSUE THREAD

**Issue by henningkessler** [munkireport/munkireport-php#243]
Hello,

i just installed the last version via git clone. Now it is reporting version 2.4.0.1067 in the browser and the client installer is also 2.4.0 but the Change.log says something about version 2.4.1? Is there a newer version somewhere? I am asking because I am very interested in the profile reporting part but unfortunately it says: "no data available in table" while there are actually profiles installed on the clients.

**Comment by bochoven** [comment]
You need to send a new package to your clients if you want to add profile reporting.

See https://github.com/munkireport/munkireport-php/blob/master/docs/setup.md#setting-up-clients-with-munki <https://github.com/munkireport/munkireport-php/blob/master/docs/setup.md#setting-up-clients-with-munki>

-Arjen

**Comment by henningkessler** [comment]
thats what I did. The package that was created had version number 2.4.0

**Comment by bochoven** [comment]
Do you see these files:
```
/usr/local/munki/preflight.d/profile.py 
cat /usr/local/munki/preflight.d/cache/profile.txt
```
 Does
```
defaults read /Library/Preferences/MunkiReport.plist ReportItems
```
contain the line
```
    profile = "/usr/local/munki/preflight.d/cache/profile.txt";
```

**Comment by henningkessler** [comment]
Yes those files are existent and the MunkiReport.plist contains the mentioned line.
```
system_profiler -xml SPConfigurationProfileDataType
```
shows the details of the installed profiles but a manual run of profile.py produces no output in profile.txt.

**Comment by bochoven** [comment]
I did not write the profiles module so you might have to sort this out yourself. Just to check: are you running this on a 10.7 or higher machine?

**Comment by henningkessler** [comment]
the machines are all 10.9.5 ;-) but probably the issue is more system_profiler related...
It did a couple of tests and result was surprising: there is a difference in the result of the command
```
system_profiler SPConfigurationProfileDataType
```
wether it is run as root or not on 10.9.5 machine. When run as root there is no result, when run as normal user I see the profile related informations
on a 10.10.3 machine the result of the command is the same wether run as root or not.
Strange.

**Comment by bochoven** [comment]
There is a difference between a user profile and a device profile

**Comment by henningkessler** [comment]
yes I know i just was surprised by the fact that in 10.9 user profiles don't appear when run system_profiler as root but in 10.10 the do. And that my login window EAP auth profile seams to count as user profile as well as it does not appear when run system_profiler as root.
But I all this is definitely no issue with your wonderful tool :-)
