### ISSUE TITLE
Enhancement request - Export current view to CSV

### ISSUE THREAD

**Issue by poundbangbash** [munkireport/munkireport-php#246]
I see this was brought up https://groups.google.com/forum/#!topic/munkireport/4125dvFKCec but I don't see a request here so I'll post it.

This is a request for the ability to export the current view from Listings.

My suggestion would be to export the search results data and export all columns. 

The export format, at least for my needs, could be csv or xls.
Another product I've used that exports web based php reports uses the php-excel.class.php code at https://code.google.com/p/php-excel/source/browse/trunk/

-Eric

**Comment by TryTryAgain** [comment]
I made something very hacky to achieve this, probably also a security risk?

For Example, added it to the Listings --> Displays; http://MUNKISERVER/report/index.php?/show/listing/displays

Created a script:
/Library/Server/Web/Data/Sites/Default/report/app/db/exportdisplays.sh 
> #!/bin/bash
> 
> sqlite3 db.sqlite <<!
> .headers on
> .mode csv
> .output displays_export.csv
> select * from displays;
> !

> header('Content-disposition: attachment; filename=/Library/Server/Web/Data/Sites/Default/report/app/db/displays_export.csv');

Modified app/views/listing/displays.php to run the script via a new php file:

> <form target="_blank" action="exportscript.php" method="POST">
>     <input type="submit" name="submit" value="Export Displays">
> </form>


And created the new exportscript.php  

> <html>
> 
> <?php
> $old_path = getcwd();
> chdir('/Library/Server/Web/Data/Sites/Default/report/app/db/');
> $output = shell_exec('./exportdisplays.sh');
> chdir($old_path);
> ?>

> <head>
>     <script type="text/javascript">
>     function doStuff()
>     {
>         setTimeout(load, 15000) //wait ten seconds before continuing
>     }
>     function load()
>     {
>     window.location.href = "http://MUNKISERVER/report/app/db/displays_export.csv";
> 
>     }
>     </script>
>     </head>
> 
>     <body onload="load()">
> <body>
> <br>
> </body>
> </html>

**Comment by bochoven** [comment]
There's no need to do this via a shell script, and this will break on non-unix systems and MySQL databases. Also, the request is to export the current (filtered) view, so the solution needs to take the search results and export those.

I would send the current data tables query to an export script in php which would respond with a csv file and a proper header: 

```php
header('Content-Type: text/csv');
header('Content-Disposition: attachment; filename="export_some_tablename.csv"');
```

**Comment by jhowe-sgs** [comment]
https://www.datatables.net/extensions/tabletools/

**Comment by computeronix** [comment]
:+1:  to this solution :)

**Comment by bochoven** [comment]
Table tools is deprecated, maybe take a look at https://www.datatables.net/extensions/buttons/

**Comment by bochoven** [comment]
Exporting CSV, etc. is added in the latest release
