### ISSUE TITLE
Bound to a Directory Service

### ISSUE THREAD

**Issue by cashxx** [munkireport/munkireport-php#247]
Under "Bound to a Directory Service" I have 130 clients Bound and 1 Not Bound.    If I click on Not Bound button it lists all the computers.   Seems to be the same for if i click on Bound as well in that it shows all the computers instead of only the ones bound.  Running version 2.3.0.1010.   If I click on "Not Bound" it should only show the one machine that isn't bound to a directory correct?   If I click on "Bound" it should only show the machines bound to a directory correct?

**Comment by bochoven** [comment]
Yes, you're right, someone should write a filter for those.
