### ISSUE TITLE
Munkireport Versions among all clients

### ISSUE THREAD

**Issue by cashxx** [munkireport/munkireport-php#251]
On the main page of Munkireports there is a widget that shows "Munki Versions" installed among all clients.  Wouldn't it be helpful to have another one showing the same data for Munkireports-php so you know that the clients are updated with it as well?

**Comment by rickheil** [comment]
There is already a widget for this - munki_versions_widget (https://github.com/munkireport/munkireport-php/blob/master/app/views/widgets/munki_versions_widget.php <https://github.com/munkireport/munkireport-php/blob/master/app/views/widgets/munki_versions_widget.php>)

You can set $conf['dashboard_layout’] in config.php to include this on your front page.

-R

**Comment by rickheil** [comment]
Ignore that last, I completely mis-read your question. Sorry about that.

**Comment by bochoven** [comment]
Not very high on my priorities list at the moment. You can try and create one yourself...

**Comment by cashxx** [comment]
No hurry, just a thought as I was upgraded to the latest version today and wondering if the clients are getting the updates.  Thought I would add it for an enhancement request if others thought it may be useful.  Thanks.

**Comment by bochoven** [comment]
Fixed with 1e899b378e3dca7da8f1dffb84a7562939c156ab
