### ISSUE TITLE
'No Battery' label not shown in Battery Condition widget

### ISSUE THREAD

**Issue by jimrt** [munkireport/munkireport-php#252]
Running MR 2.4.3, the Battery Condition widget on the dashboard does not show the label for 'No Battery'. The count is displayed correctly along with the other rows.

![screen shot 2015-06-18 at 10 23 28 am](https://cloud.githubusercontent.com/assets/5981714/8233496/89721e0e-15a4-11e5-9367-73fcba2596a9.png)

**Comment by bochoven** [comment]
You might be experiencing a caching issue in your browser. Could you open safari, press alt-cmd-c to bring up the console, and enter 
```js
localStorage.clear();
```

**Comment by jimrt** [comment]
You are absolutely correct, and I learned a new trick in Safari. Thank you.
