### ISSUE TITLE
Unknown Column 'reportdata.machine_group' in 'where clause'

### ISSUE THREAD

**Issue by fridomac** [munkireport/munkireport-php#254]
Hello!

Tried out the current wip branch (Version 2.5.0.1294), seems to work OK, I only get the message above in the Web GUI, although I did not enable machine groups (tried that, too, but changed nothing).
I did not see the table when checking the Database (MySQL) with phpmyadmin.
Do I have to create the table by hand to remedy this?

Bye, Frido.

**Comment by fridomac** [comment]
Checked the database again, the table IS there. Must have overlooked it...

Bye, Fridolin.

**Comment by bochoven** [comment]
Did you enable migrations?

**Comment by fridomac** [comment]
That was the first thing I checked, migrations are set to TRUE (is there any harm in alwaysmleaving it on TRUE?)

Bye, Frido.

**Comment by bochoven** [comment]
No harm. just another database query before each server request.

"reportdata.data.machine_group" is a weird column name, it should read reportdata.machine_group.

In which view do you get it?

**Comment by fridomac** [comment]
Sorry, the column name is reportdata.machine_group (the rest came from autocorrect :-). Can I trigger the migration manually?

Bye, Frido.

**Comment by bochoven** [comment]
Yes you could trigger it manually, but it would be good to know why this happened. What version were you migrating from?
Could you send the output of
SELECT * FROM migration

**Comment by fridomac** [comment]
I was migrating from 2.4.3.1149, the output of SELECT * FROM migration is:

Host: localhost
Datenbank: munkireport
Erstellungszeit: 24. Jun 2015 um 08:42
Erstellt von: phpMyAdmin 3.5.8.2 / MySQL 5.1.73
SQL-Befehl: SELECT * FROM `migration` LIMIT 0, 30 ; 
Datensätze: 24

id	|table_name|	version
---|---|---
1|migration|	0
2|reportdata|	3
3	|diskreport|	2
4	|munkireport|	2
5	|machine|	4
6	|warranty|	0
7	|filevault_status|	2
8	|hash|	1
9	|localadmin|	0
10	|directoryservice|	2
11	|installhistory|	1
12	|inventoryitem|	1
13	|network|	2
14	|filevault_escrow|	0
15	|displays|	0
16	|bluetooth|	0
17	|ard|	0
18	|power|	0
19	|profile|	0
20	|machine_group|	0
21	|business_unit|	0
22	|timemachine|	0
23	|certificate|	0
24	|service|	0

Bye, Fridolin.

**Comment by bochoven** [comment]
reportdata is on version 3, so it should have the machine_group column. Not sure what happened there. You could try set the version on the migration table to 2 and let munkireport try to upgrade itself to version 3 again.

**Comment by fridomac** [comment]
Tried to set reportdata to 2, then I got the following errors:

Migration error: reportdata: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'machine_group'
Uncaught Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'reportdata.machine_group' in 'where clause'

Set it to 3 again, maybe I will have to start with a fresh db....

**Comment by bochoven** [comment]
On which page do you get the error?

**Comment by fridomac** [comment]
Right on the Dashboard page:

![bildschirmfoto 2015-06-25 um 09 15 17](https://cloud.githubusercontent.com/assets/6088818/8349158/dd6e9b4c-1b1a-11e5-8746-5cb4a6e081cb.png)

**Comment by bochoven** [comment]
Which widgets do you have on your dashboard?

**Comment by fridomac** [comment]
My dashboard layout is:

$conf['dashboard_layout'] = array(
                array('client', 'munki'), /*client is actually two widgets*/
                array('disk_report', 'installed_memory', 'bound_to_ds'),
                array('uptime', 'pending_apple', 'pending_munki'),
                array('new_clients', 'munki_versions', 'pending'),
                array('warranty','power_battery_condition','power_battery_health')

Bye, Frido.

**Comment by bochoven** [comment]
Ok I found the problem: the pending_widget had a litlle error. Fixed in wip

**Comment by fridomac** [comment]
Worked perfectly, thank you!
