### ISSUE TITLE
Enhancement: Please Add DataTables::TableTools plug-in to the UI

### ISSUE THREAD

**Issue by jhowe-sgs** [munkireport/munkireport-php#255]
DataTables has a nice plugin TableTools. This allows for a one-click export to CSV/Excel/PDF.

  https://www.datatables.net/extensions/tabletools/

ColVis might be another nice UI enhancement.

  https://www.datatables.net/extensions/colvis/

Thanks!

**Comment by jhowe-sgs** [comment]
Whoops, should have read #246.

**Comment by bochoven** [comment]
Exporting CSV, etc. is added in the latest release
