### ISSUE TITLE
Incomplete database client entries causing reports to not load and other issues

### ISSUE THREAD

**Issue by cbrherms** [munkireport/munkireport-php#257]
When a munki run hasn't done a full pre and postflight, the resulting incomplete database entry (specifically no computer name) for that client is causing the munki-report listing to not show any entries and just hang. Runs fine once client has been deleted.

Also, the resulting no-name client causes a collapsed, half height, box in the area where it should be in modules.

**Comment by bochoven** [comment]
Could you check if this is fixed in the wip branch?

**Comment by cbrherms** [comment]
Apologies Arjen, didn't have an instance to check while in wip branch, moved back to master with the recent merge and had an instance of one machine that slipped through the net previously report in without a name.... Safe to say reports are now displaying correctly. Cheers
