### ISSUE TITLE
Custom warranty period

### ISSUE THREAD

**Issue by MichalMMac** [munkireport/munkireport-php#258]
Is it possible to set custom warranty period?

I have a few Macs in testing setup that have 2 year warranty (specified by law in my country). MunkiReport shows 3 year warranty which is incorrect.

**Comment by bochoven** [comment]
Warranty lookup is done by scraping the value off the pages from Apple. Is the Estimated Expiration Date from this page
https://selfsolve.apple.com/agreementWarrantyDynamic.do
correct for the machines you mentioned?

**Comment by MichalMMac** [comment]
I looked in webpage's source code and I can't find anything related to end of warranty.

Your script probably goes into this branch:

    if( ! $warranty_model->end_date)
	{
		$man_time = strtotime($warranty_model->purchase_date);
		// If we're within 3 years, after man_date we did not have AppleCare
		// So end_date = man_date + 1 year
		if(strtotime('+3 years', $man_time) > time())
		{
			$warranty_model->end_date = date('Y-m-d', strtotime('+1 year', $man_time));
		}
		else // end_date = man_date + 3 yrs (assume we had 3 yrs of AppleCare)
		{
			$warranty_model->end_date = date('Y-m-d', strtotime('+3 years', $man_time));
		}
	}

and since their warranty is expired 3 year warranty is assumed.
Not sure if this is all that significant. I just wondered why it shows 3 yeas.
Consider my question aswered :-)
