### ISSUE TITLE
Menu items missing

### ISSUE THREAD

**Issue by pkpowell** [munkireport/munkireport-php#259]
This is a minor browser issue I haven't been able to solve.
Two of my machines are having problems displaying the new menu items in google chrome (see attachment. The missing menu items are between 'network', 'security' and 'warranty'). Also missing are title elements e.g 'Storage' on the client detail page 

In Safari everything looks fine. Chrome on my work computer also has no problem displaying the new elements. I've deleted the cache but to no avail.
Anyone know what's going on here? Could this be a font issue? This is with the latest wip (2.5.0.1311). 

![screen shot 2015-06-29 at 15 36 33](https://cloud.githubusercontent.com/assets/869936/8409486/82ccc6b2-1e78-11e5-83b3-92180cb73b90.png)

**Comment by bochoven** [comment]
Clearing localstorage will probably solve your issue

**Comment by pkpowell** [comment]
Perfect, thanks!
