### ISSUE TITLE
Add install script support for HTTP Basic Authorization

### ISSUE THREAD

**Issue by ghost** [munkireport/munkireport-php#260]
To add Basic Authorization to your install scripts currently I manually edited all curl commands and added the parameter

--user 'user:password'

This works for when you have Basic Authorization enabled on sites (such as IIS)

**Comment by bochoven** [comment]
If you make it a configurable option I will be happy to merge!

**Comment by bochoven** [comment]
Maybe it's better to leave this one open as enhancement request.

**Comment by bochoven** [comment]
Closing as there is support to override the curl cmd in config.php
