### ISSUE TITLE
MySQL DataTables - Illegal mix of collations

### ISSUE THREAD

**Issue by joelsamuel** [munkireport/munkireport-php#262]
We were running 2.0.8 (MySQL, config as per config_defaults.php recommendations including:

    $conf['pdo_opts'] = array(PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8');

and then pulled 2.4.3.1083 and set allow_migrations to true. As this is a test virtual machine, pointed a single client to it and re-ran the install (curl/bash the /install).

pre/post flights run, no errors in client-side Munki2 logs. Using latest stable Safari (10.10.4, 8.0.7 10600.7.12) and Chrome (43.0.2357.130 x64) shows a MySQL collation error when viewing new Listings whereas dashboard widgets work fine. (New being, lists that did not exist before, such as Power; Displays; ARD - but Profiles works fine.)

![attachment](https://cloud.githubusercontent.com/assets/12532881/8595128/81bdf31c-263f-11e5-9e7b-44490549d84a.png)

Any ideas?

**Comment by bochoven** [comment]
It looks like you have different collations on your tables, not sure how that happened. Munkireport does not set collations (but maybe it should)

**Comment by joelsamuel** [comment]
Indeed, before I tinkered just wanted to address. Something in the 2.0.8 > 2.4.3.xxxx did it. Still looking to narrow it down.

**Comment by bochoven** [comment]
You haven't changed the default collation on the db/migrated the db from another server?

**Comment by joelsamuel** [comment]
Nope, the MySQL is hosted on another VM, hasn't been changed/updated etc since 2.0.8 deployment. We'll commit a brief amount of time to this when the Linux/DB guy has some time, but we're going to start from scratch in production and just let the clients repopulate.

**Comment by bochoven** [comment]
could you paste the output of

```mysql
SHOW CREATE TABLE `power`;
SHOW CREATE TABLE `machine`;
SHOW CREATE TABLE `reportdata`;
```
