### ISSUE TITLE
TLS v1.1 & v1.2 Compatibility

### ISSUE THREAD

**Issue by joelsamuel** [munkireport/munkireport-php#263]
We've found 2.4.3.xxxx and below requires TLS 1.0 in our Nginx configuration in order to function. Leaving only 1.1/1.2 results in pre/post-flight errors.

> ERROR: Munkireport: https://munki.****.***/munki_report/index.php?/report/hash_check
> ERROR: Munkireport: We failed to reach a server
> ERROR: Munkireport: Reason: [Errno 54] Connection reset by peer

At first I assumed it was a cURL issue (Stock 10.10.4) but the Munki2 elements work just fine, and a verbose cURL on the hash_check URL works fine too (only errors due to missing passphrase).

I assume this is explicit Python2.6 TLS1 implementation in munkireport-php/assets/client_installer/reportcommon ? And we need to work on the migration to a different SSL Python module?

**Comment by bochoven** [comment]
The ssl module in Python 2.6 supports up to TLS 1.0 only. Not sure how to add support for TLS 1.1 and up.

**Comment by joelsamuel** [comment]
I played around with some libs, you can't :(
However >=2.7.5 supports TLS1.1/1.2 and >=2.7.9 will let you explicitly define it with SSLContext.

The test machine I am running at the moment pointed to the 2.4.3.xxxx installation is 2.7.6 (and has the fat Xcode and Xcode CLI on 10.10.4) so will give it a shot but would be hacking bits together.

**Comment by bochoven** [comment]
There's also gurl, the python bridge to the native OSX url handlers that Greg Neagle wrote for munki:

https://github.com/munki/munki/blob/master/code/client/munkilib/gurl.py

**Comment by bochoven** [comment]
Should be fixed with 1f8331131077fb32ccb9095966b58544d1b9d1bf and 693a0f1a9b55c6f7724c939f0846deab0e8ca44e

**Comment by joelsamuel** [comment]
Apologies for the delay. I have scheduled this for testing and will feed back.

**Comment by bochoven** [comment]
If you use the latest wip, the curl wrapper is replaced with Purl, a superclass of Gurl. It should handle https connections transparently.

**Comment by bochoven** [comment]
This should be fixed in the latest release
