### ISSUE TITLE
Business Unit 

### ISSUE THREAD

**Issue by WardsParadox** [munkireport/munkireport-php#265]
Bumped the send button,
If the business unit's option is disabled, the 'Button' still shows in munkireport.
The profile and time machine option in the Drop down under listings is also missing.

**Comment by WardsParadox** [comment]
Sorry about issue #264 I bumped the CMD+Enter and it submitted. I thought I had closed it.

Drop downs not populating labels :
nav.admin.business_units
nav.listings.certificate
nav.listings.power
nav.listings.profile

**Comment by bochoven** [comment]
I think you need to clear the LocalStorage (which contains an old version of the localization files)

In Safari, press alt-cmd-c to bring up the console, and enter 
```js
localStorage.clear();
```
Other browsers work similar

**Comment by WardsParadox** [comment]
Oh. Wow. Thanks arjen. Adding this to my list of things to do for MR-PHP
upgrades.


Zack McCauley

Tech. Specialist, Bozeman School District #7

406-522-6025

**Comment by bochoven** [comment]
I assume your interface issues are solved? As for the other issue: I'm not sure what to put instead of the 'Manage Business Units' dropdown. Maybe 'Manage Machine Groups'?

**Comment by WardsParadox** [comment]
No it wasn't displaying and as soon as I cleared the localstorage in chrome
with localstorage.clear it showed that Manage Business Units option.


Zack McCauley

Tech. Specialist, Bozeman School District #7

406-522-6025

**Comment by bochoven** [comment]
Ok, closing..
