### ISSUE TITLE
machine stuck in business  unit 

### ISSUE THREAD

**Issue by adambarnett52** [munkireport/munkireport-php#266]
Hi 

I create a new unit. Add the PassPhrase to one host and it appears ( the filter is not working)
I then want to remove that machine from that unit. 
I remove the PassPhrase from that machine, try and delete the unit but every time i refresh it keeps appearing

![buninessunit](https://cloud.githubusercontent.com/assets/5599251/8657035/301cdb34-2993-11e5-9023-b62746e6640b.png)

I had a look in the mysql DB and the business_unit table it empty 
Thanks

**Comment by bochoven** [comment]
__Filter is not working__
Could you tell why you think the filter is not working?

__Remove machine from group__
The machine won't be removed unless it checks in again, that may not be desirable. Could you file a separate issue for that?

Machine Groups and Business Units are two different things. You can have Machine Groups without business units. They will appear in 'Unassigned Groups'. Machine Groups are stored in a separate database table.

**Comment by adambarnett52** [comment]
I might be reading the docs wrong so please correct me when i get it wrong

**Filter is not working**
A test machine is in the test machine group, i click on the filter button but only thredefault group is shown 

**Remove Machine from group**
I manually checked the machine in a few times once i had removed the passphrase and it was still being shown as the test group.
I will open a separate issue for it 

I had a look in the DB at the  machine_group but it is also empty

```
mysql> select * from machine_group;
Empty set (0.00 sec)

mysql> 
```

**Comment by bochoven** [comment]
If you log off and logon again, is the test group shown in the filter?

**Comment by bochoven** [comment]
You could also open this in your browser:

index.php?/auth/set_session_props/show

which will refresh the groups in your list.

**Comment by adambarnett52** [comment]
Ok, we don't use authentication

On Mon, Jul 13, 2015 at 10:29 PM, Arjen van Bochoven <
notifications@github.com> wrote:

> You could also open this in your browser:
>
> index.php?/auth/set_session_props/show
>
> which will refresh the groups in your list.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/266#issuecomment-121065055>
> .
>



-- 
Adam Barnett

**Comment by bochoven** [comment]
Ok I added a change that will fix this.

**Comment by adambarnett52** [comment]
Thanks, i pulled the update,

Here is the output from index.php?/auth/set_session_props/show

```
Array
(
    [user] => admin
    [auth] => noauth
    [groups] => Array
        (
        )

    [role] => admin
    [role_why] => Matched on wildcard (*) in admin
    [machine_groups] => Array
        (
            [0] => 0
            [1] => 1
        )

    [filter] => Array
        (
            [machine_group] => Array
                (
                )

        )

)
```

On Tue, Jul 14, 2015 at 8:27 AM, Arjen van Bochoven <
notifications@github.com> wrote:

> Ok I added a change that will fix this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/266#issuecomment-121151800>
> .
>



-- 
Adam Barnett

**Comment by adambarnett52** [comment]
I am also seeing two entries for "Manage Business Unit" now 

See image
![buninessunit1](https://cloud.githubusercontent.com/assets/5599251/8669109/8c89d07c-2a09-11e5-9610-3a6b5df1fa1a.png)

**Comment by bochoven** [comment]
This update should address your issue where the filter would not update after you added/removed machine groups

**Comment by adambarnett52** [comment]
That is now working, thanks
Still got that one machine stuck in a machine group :(
And there are now two entries for "Manage Business Units"

On Tue, Jul 14, 2015 at 9:20 AM, Arjen van Bochoven <
notifications@github.com> wrote:

> This update should address your issue where the filter would not update
> after you added/removed machine groups
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/266#issuecomment-121164248>
> .
>



-- 
Adam Barnett

**Comment by bochoven** [comment]
How many files do you see in /app/views/admin?

**Comment by adambarnett52** [comment]
Just the one 

```
..app/views/admin $ ls                                                                    
business_units.php
```

**Comment by bochoven** [comment]
invisible perhaps?
```
..app/views/admin $ ls -la
```

**Comment by adambarnett52** [comment]
Nope

```
inker ..app/views/admin $ sudo ls -al                                                  
drwxrwxrwx  2 ab user  4096 Jul 14 09:51 .
drwxrwxrwx 12 ab user  4096 Jul 13 12:12 ..
-rw-rw-rw-  1 ab user 20162 Jul 14 09:12 business_units.php
```

**Comment by bochoven** [comment]
I can't replicate your issue, maybe you could reset your session by visiting:
```
index.php?/auth/set_session_props/show
```

**Comment by bochoven** [comment]
I meant 
```
index.php?/auth/logout
```

**Comment by adambarnett52** [comment]
That did the job, once to keep note off


Thanks for the help

A

On Tue, Jul 14, 2015 at 10:53 AM, Arjen van Bochoven <
notifications@github.com> wrote:

> I meant
>
> index.php?/auth/logout
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/266#issuecomment-121186578>
> .
>



-- 
Adam Barnett
