### ISSUE TITLE
Machine groups - Machine is not removed  until it checks in 

### ISSUE THREAD

**Issue by adambarnett52** [munkireport/munkireport-php#267]
As the title says, a machine is not removed from a machine group until it checks back in. Maybe there should be a way to manually remove it ?

**Comment by bochoven** [comment]
This commit should fix that 349cf26b06c695de5386f0df0022118b818f08df

**Comment by adambarnett52** [comment]
i can confirm that the 349cf26
<https://github.com/munkireport/munkireport-php/commit/349cf26b06c695de5386f0df0022118b818f08df>
fixed
it

Thanks
Adam

On Tue, Jul 14, 2015 at 10:39 AM, Arjen van Bochoven <
notifications@github.com> wrote:

> This commit should fix that 349cf26
> <https://github.com/munkireport/munkireport-php/commit/349cf26b06c695de5386f0df0022118b818f08df>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/267#issuecomment-121180956>
> .
>



-- 
Adam Barnett
