### ISSUE TITLE
strange entries in client view

### ISSUE THREAD

**Issue by adambarnett52** [munkireport/munkireport-php#268]
Hi

I am seeing two strange entries in the client view. The first is a blank entry that i cannot remove. The second is an entry for my machine that is not filling in some of the details, if i delete it, it comes back straight away without the machine checking in. 

![oddmachine](https://cloud.githubusercontent.com/assets/5599251/8674370/70ebcc4a-2a35-11e5-81a8-bc70a7a9d8a9.png)

I had a look in the DB in the reportdata table and can find my machine with the serial number

**Comment by bochoven** [comment]
Can you find your machine in the machine table?

**Comment by adambarnett52** [comment]
No
I has a look though the table, but i could not find my machine by serial.

**Comment by bochoven** [comment]
Ok, that's the reason you see the strange entry. Not sure how you got in this state, is this something that happened after the upgrade?

Munkireport uses a hash table to determine if your machine needs to upload new data. You can force munkireport to upload data for the machine table if you rename your machine and run managedsoftwareupdate. You can also drop the hash table, this will force all machines to upload their data.

**Comment by adambarnett52** [comment]
How do i drop the hash table?

**Comment by bochoven** [comment]
If you have access to the database, you could execute:

```mysql
DROP table hash;
```

**Comment by adambarnett52** [comment]
Ok do i need to remake the table after

**Comment by adambarnett52** [comment]
never mind, i see that is has 
This has also fix the issue with my machine, thanks

What about the first entry, that says that machine check-in 2 months ago, with no serial or any data?

**Comment by bochoven** [comment]
Not sure about that one, can you find that entry in another listing?

**Comment by adambarnett52** [comment]
Yes i can see it in other listing tool. For example Network report
If i try and remove it, it just pops straight back

On Tue, Jul 14, 2015 at 8:26 PM, Arjen van Bochoven <
notifications@github.com> wrote:

> Not sure about that one, can you find that entry in another listing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/268#issuecomment-121348529>
> .
>



-- 
Adam Barnett

**Comment by bochoven** [comment]
Could you get the serial number it registered with in Network report?

**Comment by adambarnett52** [comment]
no it is blank, and if i click it is i get "Client with serial number ""
does not exist"


On Wed, Jul 15, 2015 at 9:28 AM, Arjen van Bochoven <
notifications@github.com> wrote:

> Could you get the serial number it registered with in Network report?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/268#issuecomment-121527773>
> .
>



-- 
Adam Barnett

**Comment by bochoven** [comment]
You could get the mac address of the machine and look it up in the network table in the database. There should be a serial number associated with that entry. Can you find that?

**Comment by adambarnett52** [comment]
But I don't know what machine it is. There is now data about it.

**Comment by bochoven** [comment]
Is there a ethernet address in the network table for the machine without serial number?

**Comment by adambarnett52** [comment]
No. Just an empty line.

**Comment by adambarnett52** [comment]
It it helps i can open the old version of munkireport-php (2.4.3) and it
does not appear

On Wed, Jul 15, 2015 at 1:17 PM, <adambarnett52@gmail.com> wrote:

> No. Just an empty line.
>
> On 15 Jul 2015, at 13:13, Arjen van Bochoven <notifications@github.com>
> wrote:
>
> Is there a ethernet address in the network table for the machine without
> serial number?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/268#issuecomment-121598079>
> .
>
>


-- 
Adam Barnett

**Comment by bochoven** [comment]
I think you have a stray entry in reportdata. I think you should be able to find it like this:

```sql
SELECT * FROM reportdata LEFT JOIN machine USING (serial_number) WHERE machine.serial_number IS NULL
```

**Comment by bochoven** [comment]
Did you get this sorted out?

**Comment by adambarnett52** [comment]
Nope, still have the strange entry, that i cannot track down in the DB as
there is no data for it

On Wed, Jul 22, 2015 at 10:16 AM, Arjen van Bochoven <
notifications@github.com> wrote:

> Did you get this sorted out?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/268#issuecomment-123633023>
> .
>



-- 
Adam Barnett

**Comment by bochoven** [comment]
Did you run the query I suggested?

```sql
SELECT * FROM reportdata LEFT JOIN machine USING (serial_number) WHERE machine.serial_number IS NULL
```

**Comment by adambarnett52** [comment]
That does return an entry with a serial number, let me see if i can remove
it

On Wed, Jul 22, 2015 at 2:07 PM, Arjen van Bochoven <
notifications@github.com> wrote:

> Did you run the query I suggested?
>
> SELECT * FROM reportdata LEFT JOIN machine USING (serial_number) WHERE machine.serial_number IS NULL
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/268#issuecomment-123714195>
> .
>



-- 
Adam Barnett

**Comment by adambarnett52** [comment]
I tired removing it from the DB , and now i get two entries for it
returning :(

On Wed, Jul 22, 2015 at 3:28 PM, Adam Barnett <adambarnett52@gmail.com>
wrote:

> That does return an entry with a serial number, let me see if i can remove
> it
>
> On Wed, Jul 22, 2015 at 2:07 PM, Arjen van Bochoven <
> notifications@github.com> wrote:
>
>> Did you run the query I suggested?
>>
>> SELECT * FROM reportdata LEFT JOIN machine USING (serial_number) WHERE machine.serial_number IS NULL
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/munkireport/munkireport-php/issues/268#issuecomment-123714195>
>> .
>>
>
>
>
> --
> Adam Barnett
>



-- 
Adam Barnett

**Comment by adambarnett52** [comment]
never mine, i found them and deleted them :)
It nows looks correct

Thanks for all the help

On Wed, Jul 22, 2015 at 3:31 PM, Adam Barnett <adambarnett52@gmail.com>
wrote:

> I tired removing it from the DB , and now i get two entries for it
> returning :(
>
> On Wed, Jul 22, 2015 at 3:28 PM, Adam Barnett <adambarnett52@gmail.com>
> wrote:
>
>> That does return an entry with a serial number, let me see if i can
>> remove it
>>
>> On Wed, Jul 22, 2015 at 2:07 PM, Arjen van Bochoven <
>> notifications@github.com> wrote:
>>
>>> Did you run the query I suggested?
>>>
>>> SELECT * FROM reportdata LEFT JOIN machine USING (serial_number) WHERE machine.serial_number IS NULL
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/munkireport/munkireport-php/issues/268#issuecomment-123714195>
>>> .
>>>
>>
>>
>>
>> --
>> Adam Barnett
>>
>
>
>
> --
> Adam Barnett
>



-- 
Adam Barnett
