### ISSUE TITLE
How to query data 

### ISSUE THREAD

**Issue by adambarnett52** [munkireport/munkireport-php#270]
This is a question father than a issue.

So we all this data in the the gets shown on the dashboards. 
I want to know if there is an ideal way to query this data. I am looking to make some alerting based on this data. i.e machine is disk is getting full, no bound to AD 

I can just query the DB for the info, but is there a better way?

**Comment by gmarnin** [comment]
Something like https://github.com/munkireport/munkireport-php/issues/102

**Comment by bochoven** [comment]
I may have a sponsor to pay for a notification system, but I won't be able to work on that before the end of august.
Please feel free to try and build something for that.

**Comment by adambarnett52** [comment]
Thanks, i will give it a go, it was going to me external the
munkireport-php then having something built it, but i will see what i can
do

On Wed, Jul 15, 2015 at 3:57 PM, Arjen van Bochoven <
notifications@github.com> wrote:

> I may have a sponsor to pay for a notification system, but I won't be able
> to work on that before the end of august.
> Please feel free to try and build something for that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/270#issuecomment-121643330>
> .
>



-- 
Adam Barnett
