### ISSUE TITLE
Warranty Coverage

### ISSUE THREAD

**Issue by adambarnett52** [munkireport/munkireport-php#272]
Hi All 

(Sorry for mass of tickets, but testing out the new version) 

On the client details page, what am i meant to see in the warranty widget ?
See image below, is this correct? or is there meant to be something displayed under warranty coverage.

Thanks

![warranty](https://cloud.githubusercontent.com/assets/5599251/8729786/137c510e-2be5-11e5-8597-8e0fd4618829.png)

**Comment by bochoven** [comment]
Do you see any changes when you press 'Recheck Warranty Status'?

**Comment by adambarnett52** [comment]
nope, I am behind a firewall but have allowed the correct URL access
What should i expect?

On Thu, Jul 16, 2015 at 9:10 PM, Arjen van Bochoven <
notifications@github.com> wrote:

> Do you see any changes when you press 'Recheck Warranty Status'?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/272#issuecomment-122074251>
> .
>



-- 
Adam Barnett

**Comment by bochoven** [comment]
Do you think the firewall prevents your query? Could you use a prosy?

https://github.com/munkireport/munkireport-php/blob/d6a62fcbd31f45bf0cb669025452204764880763/config_default.php#L349-L364

**Comment by adambarnett52** [comment]
I have it set to use a proxy, and i can see the requets are being sent ok to selfsolve.apple.com
i have allowed the following url selfsolve.apple.com,support-sp.apple.com,km.support.apple.com

**Comment by bochoven** [comment]
You only have to allow https://selfsolve.apple.com on port 443

**Comment by adambarnett52** [comment]
That is what is open.
on the old version of MRP it did show the correct status

On Fri, Jul 17, 2015 at 10:00 AM, Arjen van Bochoven <
notifications@github.com> wrote:

> You only have to allow https://selfsolve.apple.com on port 443
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/272#issuecomment-122222794>
> .
>



-- 
Adam Barnett

**Comment by bochoven** [comment]
I don't believe the warranty lookup code has changed.. Are you sure your database is writable?

**Comment by adambarnett52** [comment]
Yup, the DB is writeable, all hosts are checking in and i can look at the warranty table and see entries

**Comment by bochoven** [comment]
And if you lookup this particular serial number on the apple website, does it give you results?

https://selfsolve.apple.com/agreementWarrantyDynamic.do

**Comment by adambarnett52** [comment]
It says it in warranty

if i choose listings -> warranty and search for a machine that i know if
in warranty it says warranty status 'Supported'  in green
It seems just the summary page is not showing it

On Mon, Jul 20, 2015 at 5:57 PM, Arjen van Bochoven <
notifications@github.com> wrote:

> And if you lookup this particular serial number on the apple website, does
> it give you results?
>
> https://selfsolve.apple.com/agreementWarrantyDynamic.do
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/272#issuecomment-122950171>
> .
>



-- 
Adam Barnett

**Comment by bochoven** [comment]
Ok, could you clear localStorage?

https://github.com/munkireport/munkireport-php/issues/265#issuecomment-121018811

**Comment by adambarnett52** [comment]
Clear the storage, I tired it two different browsers ( Chrome and FF, on
Linux ) and still the same

On Mon, Jul 20, 2015 at 6:36 PM, Arjen van Bochoven <
notifications@github.com> wrote:

> Ok, could you clear localStorage?
>
> #265 (comment)
> <https://github.com/munkireport/munkireport-php/issues/265#issuecomment-121018811>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/272#issuecomment-122963169>
> .
>



-- 
Adam Barnett

**Comment by bochoven** [comment]
Any messages in the javascript console?

**Comment by bochoven** [comment]
I think I see what's happening, could you run

https://your_addrss/index.php?/clients/get_data/SERIAL_NUMBER

substituting SERIAL_NUMBER with the serial number of the machine and your_addrss with your munkiserver address.

You should get a JSON response, please find the entry that says "status" and post the value here.

**Comment by adambarnett52** [comment]
here is the response

"status":"Supported"



On Tue, Jul 21, 2015 at 10:46 AM, Arjen van Bochoven <
notifications@github.com> wrote:

> I think I see what's happening, could you run
>
> https://your_addrss/index.php?/clients/get_data/SERIAL_NUMBER
>
> substituting SERIAL_NUMBER with the serial number of the machine and
> your_addrss with your munkiserver address.
>
> You should get a JSON response, please find the entry that says "status"
> and post the value here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/272#issuecomment-123244081>
> .
>



-- 
Adam Barnett

**Comment by bochoven** [comment]
Strange, could you post the rest of the JSON (without the serial_number)?

**Comment by adambarnett52** [comment]
[{"id":"251","serial_number":"removed","hostname":"trigger","machine_model":"MacBookPro11,3","machine_desc":"MacBook
Pro (Retina, 15-inch, Late
2013)","img_url":"","current_processor_speed":"2.6
GHz","cpu_arch":"x86_64","os_version":"100905","physical_memory":"16","platform_UUID":"D69C7977-B600-5CEF-8DEE-6466B5C00185","number_processors":"4","SMC_version_system":"2.19f3","boot_rom_version":"MBP112.0138.B02","bus_speed":"","computer_name":"trigger","l2_cache":"","machine_name":"MacBook
Pro","packages":"1","cpu":"Intel(R) Core(TM) i7-4960HQ CPU @
2.60GHz","console_user":"srl","long_username":"Steve
Lynn","remote_ip":"10.21.32.109","reg_timestamp":"1405522409","timestamp":"1437485354","uptime":"106820","machine_group":"0","purchase_date":"2014-05-12","end_date":"2017-05-12","status":"Supported","users":"admin
srl","TotalSize":"999116767232","FreeSpace":"739808116736","SMARTStatus":"Not
Supported","CoreStorageEncrypted":"0"}]

On Tue, Jul 21, 2015 at 5:02 PM, Arjen van Bochoven <
notifications@github.com> wrote:

> Strange, could you post the rest of the JSON (without the serial_number)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/272#issuecomment-123385406>
> .
>



-- 
Adam Barnett

**Comment by bochoven** [comment]
Displays fine on my side.. Could you check the javascript console of your browser for errors?

**Comment by adambarnett52** [comment]
This is in the console on chrome

currentLng set to: en i18next.min.js:5
loaded: /munkireport/assets/locales/en.json i18next.min.js:5
Uncaught TypeError: object is not a function
index.php?/clients/detail/C02PF0NEG3QC:6158
(anonymous function) index.php?/clients/detail/C02PF0NEG3QC:6158
j jquery.js:2
k.fireWith jquery.js:2
x jquery.js:4
(anonymous function)

On Tue, Jul 21, 2015 at 5:25 PM, Arjen van Bochoven <
notifications@github.com> wrote:

> Displays fine on my side.. Could you check the javascript console of your
> browser for errors?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/272#issuecomment-123392556>
> .
>



-- 
Adam Barnett

**Comment by adambarnett52** [comment]
I just pulled in your latest change

commit a13d9e6ac5c1ff2c5c60b6a178e003bbc0683e7e

And it fixed it, thanks


On a side notes( i can open a new ticket if you want ) but is there a way
to curl the json outputs?

I tired and got 'No authorised'

On Tue, Jul 21, 2015 at 5:29 PM, Adam Barnett <adambarnett52@gmail.com>
wrote:

> This is in the console on chrome
>
> currentLng set to: en i18next.min.js:5
> loaded: /munkireport/assets/locales/en.json i18next.min.js:5
> Uncaught TypeError: object is not a function
> index.php?/clients/detail/C02PF0NEG3QC:6158
> (anonymous function) index.php?/clients/detail/C02PF0NEG3QC:6158
> j jquery.js:2
> k.fireWith jquery.js:2
> x jquery.js:4
> (anonymous function)
>
> On Tue, Jul 21, 2015 at 5:25 PM, Arjen van Bochoven <
> notifications@github.com> wrote:
>
>> Displays fine on my side.. Could you check the javascript console of your
>> browser for errors?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/munkireport/munkireport-php/issues/272#issuecomment-123392556>
>> .
>>
>
>
>
> --
> Adam Barnett
>



-- 
Adam Barnett

**Comment by bochoven** [comment]
Not sure why your issue was fixed, it was probably fixed in an earlier commit.

As for getting the client info via curl, you first have to authenticate and store the session cookie:

```
curl --cookie-jar /tmp/cookie-jar -F 'login=root' -F 'password=root' http://example.com/index.php?/auth/login/
```

and then use that cookie to retrieve the JSON

```
curl --cookie /tmp/cookie-jar http://example.com/index.php?/clients/get_data/SERIAL_NUMBER
```
