### ISSUE TITLE
Enhancement: Archive machines from primary database but still be able to reference

### ISSUE THREAD

**Issue by poundbangbash** [munkireport/munkireport-php#273]
A feature I'd like to see added is a way to archive machines out of the primary database but still keep track of them (stolen, temporarily offline, upgraded hardware).  A scheduled run to check if a machine hasn't reported in could be set and auto archive the system.  Criteria could be set by the admin to automatically archive machines that haven't reported in in a set number of days if desired. The archived list would still contain the full system report for reference and tracking.  When a system is pulled from production use I don't want to delete it permanently from the database and lose all referencing information but I also don't want to have unused machines in my reports.  

Along with that, if a system that is archived does report in, it automatically moves out of the archived list and pulls back into the primary database as an active machine.

-Eric

**Comment by childrss** [comment]
I'd like to second this enhancement, but with the following change:

"Along with that, if a system that is archived does report in, it automatically moves out of the archived list and pulls back into the primary database as an active machine."

There should be some sort of alert, whole page pink or some such to indicate that it was resurrected from the archives -- we could potentially get this quite often at the University where I work at as one unit surpluses equipment to the unit on campus known as "Campus Surplus" and other units "go shopping" there for free and bring it back to their unit.  This alerting system would also be helpful when a lost or stolen device pops up -- it alerts that admins that "Hey, Look at me! I'm Baaaacccck!!!"

This is rapidly moving MR towards a role of inventory tracking, which is a *good* thing.  It could be an inventory tracking system that works for "the front line guys" instead of one that is built by the back office accounting/manager types (which typically never makes sense to me as an IT tech!).

**Comment by homebysix** [comment]
Yes, this would be a welcome feature addition for us as well.

**Comment by bochoven** [comment]
@Darkomen78 You can add 'tags' to machines. And find them in the tags listing

**Comment by Darkomen78** [comment]
I see the tag listing but don't see where I can add tag :-/

**Comment by bochoven** [comment]
You can add tags in the machine detail page. Just type something in the white box underneath the computer thumbnail.

**Comment by Darkomen78** [comment]
Wow so easy ! Thanks !

**Comment by Darkomen78** [comment]
Last question, is there a way to add a tag on several client in "one massive edit" ? (or a MySQL command ?)

**Comment by bochoven** [comment]
You should be able to do that, but maybe better to stop hijacking this Feature Request and continue in #slack?

**Comment by aysiu** [comment]
From a database standpoint, this would be fairly trivial to implement (a boolean archived flag that's either 1 or 0), but in terms of the web app in PHP, the logic would have to go across all the modules, no?

**Comment by davidmnelson** [comment]
I'd love to see this as well. It would be helpful to us since it would enable the overall counts/stats/etc to more accurately reflect current inventory, but without losing information on machines that have been retired from use.

**Comment by aysiu** [comment]
@bochoven: What do you think? We can certainly divvy up the work, but it'd be good to know what your thoughts are on this feature request. Any concerns? Potential downsides (apart from the work)?

**Comment by bochoven** [comment]
I’ve been playing around a lot with kibana lately, and I think adding a default time filter to MunkiReport would be the best way to address the issue of archiving old machines

**Comment by bochoven** [comment]
Then again, I just remembered some people retiring machines immediately. So an archived flag would be better for that purpose.

**Comment by aysiu** [comment]
I guess the question then is really is it about "Hasn't checked in in X time" or "We know this machine was retired, stolen, or sold"?

**Comment by davidmnelson** [comment]
I think there would be  lot of flexibility to having a simple manual flag that indicates an item is archived. Then it could be set programmatically based on whatever criteria you want. For example admins could create a script to set it either based on date *or* by pulling a list of retired/stolen items from their primary inventory database.

**Comment by childrss** [comment]
One of the things that I would like to see with this feature is that if suddenly the machine pops up and contacts the munkireport server again and has its archive flag set, that some sort of alert happens.

*any* form of archiving would be nice, but this could be helpful to us — as a State (government) University we have a department that handles surplussing of equipment and other department sometimes go grab stuff out of surplus.

Also useful if a machine presumed lost or stolen suddenly shows up checking in…

M@

**Comment by childrss** [comment]
I *think* I may've found a way to implement this in a somewhat existing manner -- if you create a business unit named "Archive" then you can deselect this unit from your main reporting and it won't show up in your reports.  Nothing too radical in this idea.

If there were an easy way on the Munkireport side to shift a machine from one business unit to another, that would be ideal.   The machine itself would still retain the old business unit/client passphrase, _but this should not be a problem_ (at least how I envision using it):

I realize that when the machine next checks in, it will go back to its original business unit.  For me this is a desirable behavior because if it ever checks back in again to the system I want it to be "active".   While it would be nice if it would set off some sort of alert that the machine "jumped" from archive to active, this solution gets us 90% there with no code, and 95% there if there is a way to make changing a machine's business unit via MunkiReport.

Thoughts?

**Comment by kevinmcox** [comment]
I like the sound of your last thought @childrss.

**Comment by joncrain** [comment]
I've been mulling this over as well. For our situation, I would want each business unit to have their own archived business unit.
My thought is to have a config that allows an auto-archive after one month that would simply update the machine_group of the stale record and moves it to an archive group. Once the machine checks in again, it should automatically move it back into the non-archive group.
If there could be a way to automate the creation and tagging of such archive groups in the machine_group table, I think that would be ideal.

**Comment by joncrain** [comment]
I've been trying a few things, and I believe I may have a decent workflow mapped out. First off, I think the length of time for machines to archive should be set in the `.env` file. 
Next, I believe that this should be controlled from the Business Units page (even if you don't have Business Units enabled, groups do show up here if created, the initial group for non business unit areas would have to show here automatically)
When clicking to view a machine group, an archive button should appear:
![image](https://user-images.githubusercontent.com/5123982/78380163-6ef5ac00-75a1-11ea-9d5b-c12ca8b5a33c.png)
If checked this would create a hidden group of the same name that has "- Archived" at the end. The group would not be hidden in the Filter and should show up there:
<img width="206" alt="image" src="https://user-images.githubusercontent.com/5123982/78380299-a49a9500-75a1-11ea-9049-1670d98327cb.png">
Behind the scenes, MunkiReport would be running a sql query like:
```sql
update reportdata set machine_group = 22
where timestamp < UNIX_TIMESTAMP(DATE_SUB(NOW(), INTERVAL 30 DAY)) and machine_group = 5;
``` 
(it would be different for Sqlite)

Machines older than the number of days set in env would move to this group. If a machine checks back in, the machine group automatically gets reset back to its original group.

Also, it would be nice to add a button in the "Edit" view to force an archive (i.e. move to the archive group)
![image](https://user-images.githubusercontent.com/5123982/78380552-0955ef80-75a2-11ea-8986-27cba5f96ebd.png)

**Comment by bochoven** [comment]
I like the idea! Having multiple archive groups per BU might be very tedious though (a long list of groups to filter). I would suggest just one Archive group per BU
18:06
Maybe like Mail.app: use this group for archiving checkbox (edited)

**Comment by kevinmcox** [comment]
I like it, but would personally like to see a way to manually archive a computer without having automatic archiving based on date. (Although I guess I could just set my threshold really, really high like 9999 days.)

Having a computer automatically reset back to the original group when it does check-in is great.

I'd be nervous putting the archive button next to the delete button though, too easy to click the wrong one.

**Comment by bochoven** [comment]
Would everyone have 'archive' rights?

**Comment by kevinmcox** [comment]
I'd think just admins. Same people who can delete can archive.

**Comment by joncrain** [comment]
> I like it, but would personally like to see a way to manually archive a computer without having automatic archiving based on date. (Although I guess I could just set my threshold really, really high like 9999 days.)
> 
> Having a computer automatically reset back to the original group when it does check-in is great.
> 
> I'd be nervous putting the archive button next to the delete button though, too easy to click the wrong one.

True, I wonder if a pop up confirmation would be in order for delete then. 🤔 

I also agree on the just admins.

**Comment by ofirgalcon** [comment]
Looks great, my only wish is that it would be one archive per BU rather than Group. I already have too many groups...

**Comment by bochoven** [comment]
Ok, started working on this in https://github.com/munkireport/munkireport-php/tree/feature/archive_machines

I don't have a fixed plan on how to tackle this, so I just started with the option to mark a machine_group for archiving.

There's a checkbox now where you can mark a machine_group as "Use for archiving"
- No code to prevent you from marking multiple groups as "Use for archiving"

**Comment by bochoven** [comment]
Using machine_groups for archiving is a very complex task. I think it will be easier to add a `status` field to the `machine` table and filter on that.

**Comment by kevinmcox** [comment]
What about just adding the ability the move a computer between machine groups from the web? Then admins can make an Archive Group (or multiples) and sort computers into them.

The existing filter function can then be used to hide these groups.

This would also take care of the feature for the computer moving itself back to the original group when it checks in again.

An added bonus is that now admins can also organize computers into groups even if that computer doesn’t have a passphrase set to place itself into a group.

**Comment by ofirgalcon** [comment]
> Using machine_groups for archiving is a very complex task. I think it will be easier to add a `status` field to the `machine` table and filter on that.

I also think it's going to make the filters window pretty messy. I vote for a status filed and the option to hide inactive/archived items by default.

Hopefully that is easier to implement too.
