### ISSUE TITLE
Add listing for InstallHistory (was Include "Third Party Software" in Inventory?)

### ISSUE THREAD

**Issue by TryTryAgain** [munkireport/munkireport-php#276]
There seems to be no place where Third Party Software can be viewed en mass, rather only from a single client view page one at a time. Is there a reason these are not included in Inventory? Are there plans to make another area where we can view ALL Third Party Software for ALL clients?

**Comment by bochoven** [comment]
All installed applications are available in the inventory listing. The 'Installed Third Party Software' tab in the client view is actually the parsed install log file. It shows when a software package was installed on a client. It may help to identify a problem e.g. 'I can't browse any websites' when the log shows the client has installed some firewall program.
I don't see the use of presenting this for all clients, could you give a good reason to do so?

**Comment by TryTryAgain** [comment]
My reason, and I can imagine useful for others is: Some installed packages, especially those crafted to do simple tasks like run scripts (although may have proper pkginfo, etc) may not be present in inventory, but they are present in Third Party Software. I'd like to track those for the entire user base for progress of the installs, or get overall status of particular versions, but there is no way to find that information for all users in one place. Ideally, I'd also like to add Third Party Software items to the AppVersions tracking feature. I can also see a use for having this all in one place to see in a sortable list for all users things like when apps were installed, installed versions, etc. Thanks for your consideration and time, and for the clarification on how Inventory and Third Party Software are intended to work.

**Comment by gmarnin** [comment]
This request fills a big hole in install apps reporting. Not being able to track apps in the app version reports page is becoming an issue. For example, apps like Outset, munkireport, osquery, dockutil, pinpoint, etc. can’t currently be tracked in one place.

**Comment by TryTryAgain** [comment]
@bochoven I think I'll clone the repo and give this a go; creating a "managed_installs" module (not promising anything, but I'd like to try)...anything I should look out for and/or be aware of? I saw creating an index in the db for better search (any direction on that)? Can you explain at all the logic behind how these managed installs are currently stored at the client detail level? I see the view, maybe I need to start at the DB? Any reason you disagree with adding a managed_installs module approach, am I way off?

**Comment by bochoven** [comment]
There is already a managed installs module in the wip branch. Please see if that accommodates your needs.

**Comment by TryTryAgain** [comment]
Very cool! It looks like it will, great work. I will give it a whirl when I get a moment. Is it ready for production, need help anywhere? I'm very excited to be able to use it, would be happy to help. Thank you.

**Comment by bochoven** [comment]
I use it in production, make sure you backup your db before you switch to the wip branch though.
