### ISSUE TITLE
Client listing reports error as of f1aa8b3

### ISSUE THREAD

**Issue by poundbangbash** [munkireport/munkireport-php#278]
In testing the disk size reporting issue addressed at https://github.com/munkireport/munkireport-php/issues/277 I updated the server and client installer to the build created in [f1aa8b3](https://github.com/munkireport/munkireport-php/commit/f1aa8b34e53328da1757bd1db7afc8222d392c7a).  I'm now getting the attached error when accessing the "Client" listing:

![screen shot 2015-07-23 at 10 09 17 pm](https://cloud.githubusercontent.com/assets/1416288/8866926/4f568c0a-3188-11e5-9255-26d0c5c4ebe0.png)

**Comment by bochoven** [comment]
The current code also contains a database change. You need to enable migrations in your config file.

**Comment by poundbangbash** [comment]
That was it.  Closed.
