### ISSUE TITLE
Enhancement: Free Disk Space widget report on percent, not GB free

### ISSUE THREAD

**Issue by poundbangbash** [munkireport/munkireport-php#279]
The Free Disk Space widget on the dashboard reports on how many gigs are available on a disk which isn't an accurate representation of problems.  Using a percentage would be a better indicator since 20GB free of a 1TB disk is a problem where as the dashboard widget would show it as "Green" or "Success".  

I'd suggest:
below 10% = danger
11-20% = warning
above 20% = success

**Comment by bochoven** [comment]
I'm not in favour of setting percentages for thresholds again, but I agree that the current reporting may not fit your environment. I committed some changes to the wip branch that make the thresholds configurable: a4de96d0be16651be4ec01579697142ebf994bf5

See for reference:

https://github.com/munkireport/munkireport-php/blob/a4de96d0be16651be4ec01579697142ebf994bf5/config_default.php#L505-L516

**Comment by bochoven** [comment]
Disk thresholds are in the latest release, closing..
