### ISSUE TITLE
Client check in error

### ISSUE THREAD

**Issue by putnajoe** [munkireport/munkireport-php#280]
When my client would run munki, I would get the following error when munkireport would attempt to submit:

postflight stderr: ERROR: Munkireport: https://myserver.name.here/index.php?/report/check_in
ERROR: Munkireport: We failed to reach a server
ERROR: Munkireport: Reason: Internal Server Error

Turning on debug mode yielded the following info:

Parse error: syntax error, unexpected '[' in var/www/app/modules/servermetrics/servermetrics_model.php on line 5

Removing the servermetrics module from the list of installed modules and reinstalling munkireport 2.52 corrects the issue with submitting data. Based on the error it appears to be an issue in the servermetrics module.

**Comment by bochoven** [comment]
Which version of php are you running?

**Comment by putnajoe** [comment]
Sorry for the delay in getting back to this. The PHP version I am running is PHP Version 5.3.10-1ubuntu3.19.

**Comment by bochoven** [comment]
Should be fixed in effec528d148d003094b16691f864a206f4decbd

**Comment by joelsamuel** [comment]
Also 5.3.10-1ubuntu3.19 w/ 2.5.3

but line 70.
Fixed by changing:
    $out = [];
to
    $out = '';

**Comment by putnajoe** [comment]
After updating to 2.5.3 today I also had an error reported on line 70 which was fixed by switching the [] to ''
Here is the error 
Parse error: syntax error, unexpected '[' in var/www/app/modules/servermetrics/servermetrics_model.php on line 70

**Comment by bochoven** [comment]
Fixed in the latest release
