### ISSUE TITLE
AppVersions Report not working anymore

### ISSUE THREAD

**Issue by cashxx** [munkireport/munkireport-php#282]
Did AppVersions Report stop working?   I am noticing I have Safari 6.2.7 pushed out across the clients and 6.2.6 is being reported on more than half.  I checked some clients manually and all with the ARD unix command using: grep -A 1 CFBundleShortVersionString /Applications/Safari.app/Contents/Info.plist | grep -v CFBundleShortVersionString

And the clients are actually all Safari 6.2.7 under OS 10.8.5.  Munki and Munkireports seem to be working fine other wise.

Munki: 2.2.4.2436
MunkiReport Version: 2.5.0.1323

**Comment by bochoven** [comment]
Please read https://github.com/munkireport/munkireport-php/blob/master/docs/setup.md#select-which-modules-to-install-on-the-client
