### ISSUE TITLE
HELP!  Uncaught Exception: SQLSTATE[HY000]: General error: 1 no such column: reportdata.machine_group

### ISSUE THREAD

**Issue by fseesink** [munkireport/munkireport-php#286]
Just followed the steps here:
https://github.com/munkireport/munkireport-php/wiki/How-to-upgrade

to upgrade from 2.4.2 to the current (2.5.3.1368).  I DID initially setup munkireport with git, and I've done an upgrade before that worked fine.

But this time, as the subject line shows, I'm getting this error message:

*Uncaught Exception: SQLSTATE[HY000]: General error: 1 no such column: reportdata.machine_group*

https://github.com/munkireport/munkireport-php/wiki/How-to-upgrade

Looking at db.sqlite (both backup version and production version), I can see that the schema for table reportdata indeed lacks a column named machine_group:
____
sqlite> .schema reportdata
CREATE TABLE `reportdata` (`id` INTEGER PRIMARY KEY AUTOINCREMENT,`serial_number` VARCHAR(255) UNIQUE,`console_user` VARCHAR(255),`long_username` VARCHAR(255),`remote_ip` VARCHAR(255),`uptime` INTEGER DEFAULT 0,`reg_timestamp` INTEGER,`timestamp` INTEGER);
CREATE INDEX reportdata_console_user ON `reportdata` (console_user);
CREATE INDEX reportdata_long_username ON `reportdata` (long_username);
CREATE INDEX reportdata_remote_ip ON `reportdata` (remote_ip);
CREATE INDEX reportdata_reg_timestamp ON `reportdata` (reg_timestamp);
CREATE INDEX reportdata_timestamp ON `reportdata` (timestamp);
____

So my next step was to simply delete ./app/db/db.sqlite and let munkireport rebuild it, which it did.  Error is now gone.  Just need to wait for clients to check in.

However, it would be nice that IF the db schema changes between versions, that either an update triggers appropriate table changes, or at least it pops up an option to delete/rebuild the db.  (Granted, if you're using MySQL, the former is likely easier.  As SQLite's ALTER TABLE command is more limited, not sure which way is best there.)

Also, might be a good idea to offer version branches vs. simply having a 'master' branch.  Just a thought.

**Comment by bochoven** [comment]
That's what migrations are for. Every time a database change is introduced, a corresponding migration script is added to munkireport (look in migrations). To enable migrations, set

```php
$conf['allow_migrations'] = TRUE;
```

in config.php. This is also mentioned in the release notes. (It should be added to the how to upgrade page as well)

**Comment by bochoven** [comment]
Updated the wiki: https://github.com/munkireport/munkireport-php/wiki/How-to-upgrade

**Comment by bochoven** [comment]
As for the branches, development happens in the wip branch. Master should be stable unless there's an imminent release. You can always check out a specific version in git.

**Comment by fseesink** [comment]
*(smacks forehead)*

Man, I totally missed that in the config[_default].php file.  Thanks for updating the upgrade wiki page all the same.

As for branches, ok, that makes sense.  I was simply clicking on CHANGELOG.md here:

https://github.com/munkireport/munkireport-php/blob/master/CHANGELOG.md

and it last listed 2.5.0 (still does), but when I did the pull, I was on 2.5.3, so thought there was just one branch as some projects do.  Again, my bad.  I use git enough to be dangerous, but haven't been paying careful attention to GitHub to notice the releases.  I was doing 'git branch -r' to see remote branches, but couldn't figure out how to see version releases.  My ignorance.  I'll work on that.

 Overall I really love munkireports.  It's been very useful.  So thanks for all the hard work.

**Comment by bochoven** [comment]
Good that you mention the CHANGELOG, I forgot to update it..

**Comment by bochoven** [comment]
Updated CHANGELOG, closing

**Comment by fseesink** [comment]
Just FYI, but you didn't update this changelog:

https://github.com/munkireport/munkireport-php/blob/master/CHANGELOG.md

That is, the one people see can can click on from the main munkireportphp page:
https://github.com/munkireport/munkireport-php

It still states 2.5.0 as latest.

**Comment by bochoven** [comment]
Yes I pushed them to wip, now also in master
