### ISSUE TITLE
See Application License - Parallels

### ISSUE THREAD

**Issue by computeronix** [munkireport/munkireport-php#288]
Enhancement Request:

Could you make it so we can see the application license key that is used as part of the App version report?

One example is Parallels, we have a corporate license and need to make sure all the Macs are using x License key instead of the personal one.

**Comment by bochoven** [comment]
How do you determine the application license key?

**Comment by computeronix** [comment]
/Library/Preferences/Parallels/licenses.xml

**Comment by bochoven** [comment]
Munkireport needs to know what to do with that data, you could write a module for it..

**Comment by bochoven** [comment]
I think this is too specific to be part of the project, closing
