### ISSUE TITLE
Stale Client Cleanup

### ISSUE THREAD

**Issue by ghost** [munkireport/munkireport-php#291]
Is there any feature currently to clean up stale clients?

Such as if a client has not reported in x amount of days (configurable via the server config settings) then remove from the inventory and all associated data for that machine.

**Comment by bochoven** [comment]
Someone requested an 'Archive' function, that will retain the data but remove it from all views.

**Comment by computeronix** [comment]
Second this   not sure if anyone has any ideas on this?   Would be useful to lets say clear out any mac computer older than 60 days of last checkin time?

**Comment by bryanzak** [comment]
I would just recommend that it be configurable. Our teachers won't check in over summer. So we'd need 90 or 120 days

Bryan

**Comment by computeronix** [comment]
attempting to implement this will see how it goes in my test environment

**Comment by computeronix** [comment]
Whats the recommended order to delete a machine entry

based on the serial number delete inventory then other tables or does it not really matter on the order?

**Comment by bryanzak** [comment]
60 days wont work in education we often have computers offline all summer. I'd rather see 120 or configurable

**Comment by gmarnin** [comment]
The number of days should be configurable as everyone has different environments

**Comment by computeronix** [comment]
it will be configurable via the config

**Comment by computeronix** [comment]
fyi here is the mysql command for those interested - just need to integrate it now into the PHP code

just replace 90 with however many days old you want.  Anything older than this timeframe will select those machines

SELECT serial_number, timestamp FROM munkireport WHERE UNIX_TIMESTAMP(STR_TO_DATE(timestamp,'%Y-%m-%d %h:%i:%s')) < UNIX_TIMESTAMP(DATE_SUB(NOW(), INTERVAL 90 day)) ORDER BY timestamp;

**Comment by computeronix** [comment]
Working on a helper script to wrap this up and will post tonight or tomorrow

**Comment by computeronix** [comment]
this should now be resolved with the latest PR

**Comment by computeronix** [comment]
Correction to query (military time :) )

SELECT serial_number, timestamp FROM munkireport WHERE UNIX_TIMESTAMP(STR_TO_DATE(timestamp,'%Y-%m-%d %H:%i:%s')) < UNIX_TIMESTAMP(DATE_SUB(NOW(), INTERVAL 90 day)) ORDER BY timestamp;

**Comment by bochoven** [comment]
These queries don't work on sqlite
