### ISSUE TITLE
SQL Errors (Unknown column 'buildversion' in 'field list')

### ISSUE THREAD

**Issue by joelsamuel** [munkireport/munkireport-php#292]
We have a clean install of 2.5.3.1368 and we're seeing upload errors on the client and server-side in the WebUI.

In the client logs we see (preflight):
````
Aug 14 2015 11:34:38 +0100     Munkireport: Server An error occurred while processing: Machine_model
Server Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'buildversion' in 'field list'
Server info: starting: machine
Server danger: Migration error: machine: SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'machine_hostname'
Server info: starting: reportdata
````
Then (postflight) HTML output in the client-side logs (debug enabled) effectively showing:
````
Uncaught Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'buildversion' in 'field list'
````
On the server-side in the WebUI we see various SQL errors (debug and migration mode enabled for the moment, as the DB is older, but scripts are clean)
````
Migration error: machine: SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'machine_hostname'
Migration error: filevault_status: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'filevault_users'
````
And from the listing/clients a popup
````
DataTables warning: table id=DataTables_Table_0 - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'machine.buildversion' in 'field list'
````

Any ideas? Could clean the DB but seems like we should be able to do upgrades/migrations etc, so seems better to address than skirt past.

**Comment by bochoven** [comment]
Did you enable migrations? 

https://github.com/munkireport/munkireport-php/wiki/How-to-upgrade#allow-for-migrations

**Comment by bochoven** [comment]
Hmm, I should have read your report better.. From what version are you migrating?

**Comment by joelsamuel** [comment]
I'm told we actually dropped the tables (I thought it was a 2.0.8 to 2.5.3 jump). Its actually a 2.5.0 pre-release to 2.5.3 now.

**Comment by bochoven** [comment]
Dropping the tables is not supported (but maybe it should). Now the migration table is out-of-sync with the actual database status. You can manually change the table version in the migration table, for the machine table the query should look like:

```sql
update migration set version = 5 where table_name = 'machine';
```

**Comment by joelsamuel** [comment]
Gave that a try, MySQL accepted it. Debug & migration still enabled.

Client preflight:
````
Aug 18 2015 10:10:09 +0100     Munkireport: Sending items
Aug 18 2015 10:10:10 +0100     Munkireport: Server An error occurred while processing: Machine_model
Server Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'buildversion' in 'field list'
Server info: starting: machine
Server info: starting: reportdata
Aug 18 2015 10:10:10 +0100 ### Beginning managed software check ###
````

Client postflight:
````
Aug 18 2015 10:10:44 +0100     Munkireport: Sending items
Aug 18 2015 10:10:44 +0100     Munkireport: Server info: starting: reportdata
Server info: starting: remotewipemonitor_model
Server An error occurred while processing: Machine_model
Server Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'buildversion' in 'field list'
Server info: starting: machine
Server info: starting: munkireport
Aug 18 2015 10:10:44 +0100 ### Ending managedsoftwareupdate run ###
````

WebUI listing/clients:
````
DataTables warning: table id=DataTables_Table_0 - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'machine.buildversion' in 'field list'
````

**Comment by bochoven** [comment]
Ok, that means you dropped the tables before version 5 of the machine table. Fix should be

```sql
update migration set version = 4 where table_name = 'machine';
```

**Comment by joelsamuel** [comment]
Worked a treat, thank you :+1: 

Is this DB now production friendly? I was going to take it out of migration/debug and then push a selected group of machines to it - it just has some legacy data in there it turns out we need (I see an enhancement request for keeping old machines but hiding them from view).

**Comment by bochoven** [comment]
I assume your DB is now up-to-date, can't say for sure as you made modifications to it outside munkireport. You could compare it with a new DB instance to be sure.

Closing
