### ISSUE TITLE
Enhancement: Uncheck/Check All in Set Filters menu

### ISSUE THREAD

**Issue by binkleybloom** [munkireport/munkireport-php#295]
An "Uncheck/Check all" action in the Set Filters window would be very desirable for organizations that have larger numbers of groups. Given the non-persistent nature of the selections, it's an annoyance to have to uncheck many groups each time you log in. A global "uncheck" followed by selecting the desired group would help optimize this.

**Comment by bochoven** [comment]
Good call, I did not foresee people creating a-lot-of-groups. I agree there should be a better way to handle them. Uncheck/Check all would not be hard to implement, but I may want to add other filtering options.

**Comment by bochoven** [comment]
Fixed here: 3ee08d41475c52e73441c20e027243529e19b3ee
