### ISSUE TITLE
Not matching AD Names - Autocorrect

### ISSUE THREAD

**Issue by ghost** [munkireport/munkireport-php#296]
Does it make sense to have this be autocorrected on the clients?  Assuming users would want the AD name to overwrite the local name you could have a configuration variable that says to overwrite local name with AD name?

If this does make sense here is the script to get this working based on the cached directoryservice.txt file

``````

#use the cached munki directory file
fil=/usr/local/munki/preflight.d/cache/directoryservice.txt

#test for existence of the Directory Service file
if [ -f $fil ]
then

  #read through the file looking for the word Computer Name && Active Directory Domain
  while read line
  do
    echo $line | grep -q "Computer Account"
    if [ $? == 0 ]; then
    	adComputerAccount=`echo $line | cut -d = -f2`
    	adComputerAccount=$(echo -e "${adComputerAccount}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
    	adComputerAccount=`echo $adComputerAccount | sed 's/\\$//g'`
    fi
    
    echo $line | grep -q "Active Directory Domain"
    if [ $? == 0 ]; then
     echo $line | grep -q "\."
        if [ $? == 0 ]; then
            domain=`echo $line | cut -d = -f2`
    		domain=$(echo -e "${domain}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
        fi
    fi
  done < $fil

hostName=`scutil --get HostName`
computerName=`scutil --get ComputerName`
localHostName=`scutil --get LocalHostName`

logger "Current Host Name: ${hostName}"
logger "Current Computer Name: ${computerName}"
logger "Current Local Host Name: ${localHostName}"

logger "Setting Computer Name Fields HostName, ComputerName, and LocalHostName"
sudo scutil --set HostName "${adComputerAccount}.${domain}"
sudo scutil --set ComputerName "${adComputerAccount}"
sudo scutil --set LocalHostName "${adComputerAccount}"

hostName=`scutil --get HostName`
computerName=`scutil --get ComputerName`
localHostName=`scutil --get LocalHostName`

logger "New Host Name: ${hostName}"
logger "New Computer Name: ${computerName}"
logger "New Local Host Name: ${localHostName}"

else

logger "${fil} does not exist, skipping..."

fi

``````

**Comment by bochoven** [comment]
Not sure what you're after, renaming the computer to the associated AD computer account? Do you want to integrate this in munkireport?

**Comment by computeronix** [comment]
Sorry I may have been a little vague, there is a widget in the configuration report, reports list called "Not matching AD Names"

My goal is to auto correct the clients in this list by having the affected ones run the script above.

**Comment by bochoven** [comment]
I think the DS reporting script uses the localhostname to look up the machine in AD:

https://github.com/munkireport/munkireport-php/blob/master/app/modules/directory_service/scripts/directoryservice.sh#L27-L37

Then you use that name to set the localhost name, sounds like a circular reference to me

**Comment by computeronix** [comment]
The DS script pulls AD information to a file,  this file is then parsed and imported into the munki report database

within this file is the computer account name used in this widget which is then compared to the local hostname by munki reports

from there the computers that dont match appear in this widget

right now those computers that appear I am manually pushing this script out to match the AD name to the local hostname to resolve the issue.

Hoping to automate this piece to prevent mismatches in the future :)

**Comment by bochoven** [comment]
Do you want to add this script to munkireport? If not maybe posting it on munkireport@googlegroups.com may get you more attention than filing an issue here.

**Comment by bochoven** [comment]
Munkireport is about reporting, not changing the clients.
