### ISSUE TITLE
Bug: model_lookup_failed

### ISSUE THREAD

**Issue by ghost** [munkireport/munkireport-php#298]
Receiving model_lookup_failed for one client in particular

MacBookAir5,2  is the current model

![screen shot 2015-08-19 at 9 47 56 am](https://cloud.githubusercontent.com/assets/11186939/9357908/6b5667ac-4657-11e5-8ad4-f4f599e544f3.png)
![screen shot 2015-08-19 at 9 48 03 am](https://cloud.githubusercontent.com/assets/11186939/9357911/6e732efc-4657-11e5-8cf0-ef5dfa9dd681.png)

**Comment by bochoven** [comment]
Sometimes the Apple Servers are down and a lookup fails. In time they should get populated.
