### ISSUE TITLE
Directory Services Widget not showing "not bound"

### ISSUE THREAD

**Issue by ghost** [munkireport/munkireport-php#299]
All my machines show as bound on the widget and not bound shows 0

However looking through the details I have three machines showing as null for Active Directory so "not bound"  but I think the widget does not account for this?

![screen shot 2015-08-19 at 3 13 04 pm](https://cloud.githubusercontent.com/assets/11186939/9366376/0347de56-4685-11e5-8207-b42dd852f35d.png)

![screen shot 2015-08-19 at 3 14 27 pm](https://cloud.githubusercontent.com/assets/11186939/9366382/077f838e-4685-11e5-90d4-cf5cecde262f.png)

**Comment by bochoven** [comment]
When you say '...looking through the details...' do you mean looking at the directory service listing? I did not write the widget, but the way I read the query it looks like it only queries machines that have set their DS status. The missing ones could be added as 'Unknown'.

**Comment by bochoven** [comment]
I'm setting the enhancement label as it could be debated if this is a bug.

**Comment by computeronix** [comment]
correct, looking through the details I meant directory service listing
