### ISSUE TITLE
Deleting clients from list

### ISSUE THREAD

**Issue by dodobyrd** [munkireport/munkireport-php#300]
Please excuse my lack of knowledge and this question if it's not a good one. I'm having a a hard time deleting clients from the list. I have four machines that report no data. No ip, host name or anything else for that matter. The manifest seems to exist but when I delete it eventually comes back. Is this a bad database?! Any help would be greatly appreciated.

**Comment by bochoven** [comment]
What version of Munkireport? The latest version has better support for incomplete entries.

**Comment by dodobyrd** [comment]
MunkiReport Version 2.5.2.1323. I'll try the update before I attempt anything else thanks!
