### ISSUE TITLE
Enhancement: Force Munki to sync

### ISSUE THREAD

**Issue by computeronix** [munkireport/munkireport-php#301]
Similar to mcafee wake-up call could you write something (perhaps a button next to remote vnc a machine) where you can force a sync of munkitools on an agent

Command to issue:
sudo /usr/local/munki/managedsoftwareupdate -a

This may be tricky because basically remote SSH would need to be opened and the traffic routeable through to the client.

Nice to have feature -- similar to McAfee's Wake-up call on it's agent

**Comment by bochoven** [comment]
Munkireport does not connect to clients, so I don't see how this could be accomplished.
