### ISSUE TITLE
Munki Warning and Error Details

### ISSUE THREAD

**Issue by ctdawe** [munkireport/munkireport-php#303]
I recently upgraded a server and clients from version 2.4 to version 2.5.1368, and I can no longer find detailed information on Munki warnings and errors in the detailed view of a machine. The fact that warnings and errors have been reported still shows up in the Munki report summary and in the list of machines, but the detail seems to no longer be visible. 

Did this information get omitted from the client display, did it move, or is there something that I need to do to re-enable display of the error information? Or am I missing it completely (always a possibility)?

**Comment by bochoven** [comment]
Are you looking at the 'Managed Software' tab in the client detail view?

<img width="225" alt="untitled" src="https://cloud.githubusercontent.com/assets/1429002/9387101/2fcf6284-475f-11e5-92f3-b8c7ed8ef478.png">

**Comment by ctdawe** [comment]
Got it. I was indeed looking in the wrong place. Thank you!
