### ISSUE TITLE
FileVault status broken in OS X 10.11

### ISSUE THREAD

**Issue by bochoven** [munkireport/munkireport-php#306]
FV status module is not reporting status on 10.11

**Comment by jlehikoinen** [comment]
Ahoy! :)

Rich has updated his FileVault status check script couple of weeks ago:
https://github.com/rtrouton/rtrouton_scripts/commit/03647a2c4339511f40c524b18084bf802726cbde

**Comment by bochoven** [comment]
Hey Janne! I'm moving away from the FileVault status scripts from Rich. I am integrating encryption detection to the disk_report module.

**Comment by bochoven** [comment]
This is from the latest wip: 
<img width="573" alt="screen shot 2015-10-06 at 09 50 49" src="https://cloud.githubusercontent.com/assets/1429002/10302856/d749de0c-6c0f-11e5-99e3-5a22bf888941.png">

**Comment by bochoven** [comment]
Would that be enough?

**Comment by jlehikoinen** [comment]
Yes, that's enough and looks good.
