### ISSUE TITLE
enhancement: link to everymac.com machine spec's page?

### ISSUE THREAD

**Issue by childrss** [munkireport/munkireport-php#307]
Was thinking that it would be useful to have a link generated to the everymac.com page for the machine you're looking at to see initial specifications.  Came across this trying to find out what version of the Apple Hardware Test to download for the machine...

**Comment by bochoven** [comment]
Should be easy enough, do you want to add the link on the detail page? In the dropdown menu? And then open a new page or contained in a tab?

**Comment by bochoven** [comment]
Addressed with 0f3910ab8ca0ad7fe19468657ae86c774537f2d4
