### ISSUE TITLE
FileVault Escrow page - Last Check In

### ISSUE THREAD

**Issue by computeronix** [munkireport/munkireport-php#308]
On the FileVault escrow page of a client it shows the following

![screen shot 2015-09-01 at 9 13 15 am](https://cloud.githubusercontent.com/assets/11186939/9605108/ba21202a-5089-11e5-8ba3-a9eeb21444ae.png)

Is this supposed to be the last check in time or maybe how long a key is valid for or is the time display bugged

**Comment by rickheil** [comment]
I am also getting the same thing – sometimes I feel my machines are that old but I don’t think so!!

From:  Bill McIlhargey
Reply-To:  munkireport/munkireport-php
Date:  Tuesday, September 1, 2015 at 9:14 AM
To:  munkireport/munkireport-php
Subject:  [munkireport-php] FileVault Escrow page - Last Check In (#308)


On the FileVault escrow page of a client it shows the following

Is this supposed to be the last check in time or maybe how long a key is valid for or is the time display bugged
