### ISSUE TITLE
Directory Service Password Change Interval blank

### ISSUE THREAD

**Issue by ghost** [munkireport/munkireport-php#309]
In Directory Service, my password change interval shows blank even though when I run

sudo dsconfigad -show

It shows 0 (zero)

**Comment by bochoven** [comment]
How is this related to munkireport?

**Comment by computeronix** [comment]
Directory Service module is in munki reports

https://github.com/munkireport/munkireport-php/tree/master/app/modules/directory_service

**Comment by bochoven** [comment]
I understand, but if the password change interval does not have a proper value, what do you expect Munkireport to do about that?

**Comment by computeronix** [comment]
after further review  the cache file populates properly and the database populates properly so purely a display bug

**Comment by bochoven** [comment]
Any way you could fix the bug and send a Pull Request?

**Comment by computeronix** [comment]
Digging into it

**Comment by computeronix** [comment]
Still getting familiar with the structure but if the value is a single digit number it will not display.  If more than two digits then it will display

**Comment by bochoven** [comment]
I can't reproduce the issue (I'm observing a single digit password interval in the tab)
