### ISSUE TITLE
Remote Control / Remote SSH role

### ISSUE THREAD

**Issue by computeronix** [munkireport/munkireport-php#312]
Can you add a role for the Remote SSH / Remote VNC links?  By default assign to admin

That way if a non-admin logs in these two links should not be shown

**Comment by bochoven** [comment]
In my environment the servicedesk uses the Remote VNC link a lot. They're not admins.

**Comment by computeronix** [comment]
aww fair enough  maybe assign the links a role then?  and then by default * get access to links?

**Comment by bochoven** [comment]
I think a better way is to hide the links with javascript if the role is not admin. You can this to a custom javascript file:

```js
$('span[data-i18n="remote_control"]').parent().hide()
```

Then you need a condition that determines if an admin is logged in or not

**Comment by bochoven** [comment]
And this would work in the latest wip:

```js
 $.getJSON( appUrl + '/auth/set_session_props/show', function( data ) {
        if(data.role != 'admin'){
            $('span[data-i18n="remote_control"]').parent().hide();
        }
 });
```
