### ISSUE TITLE
IP Ranges doesn't work as expected

### ISSUE THREAD

**Issue by hymmm** [munkireport/munkireport-php#314]
IP Ranges doesn't work as expected.

    $conf['ip_ranges']['MyOrg'] = array('192.168.1.',
                                        '192.168.3.',
                                        '192.168.4.',
                                        '192.168.5.',
                                        '192.168.10.',
                                        '192.168.11.');
    $conf['ip_ranges']['Alt'] = array('192.168.30.','192.168.31.');

and client IP adress is

172.16.0.100
172.16.0.100
192.168.1.10
192.168.11.20
192.168.3.100
192.168.30.29
192.168.30.30
192.168.30.31
192.168.30.32
192.168.30.36
192.168.30.37
192.168.30.42
192.168.30.44
192.168.30.46
192.168.30.47
192.168.30.58
192.168.30.61
192.168.30.70
192.168.30.72
192.168.30.74
192.168.30.8
192.168.31.26
192.168.31.28
192.168.31.34
192.168.31.43
192.168.31.46
192.168.31.61
192.168.4.104
192.168.4.141
192.168.4.164
192.168.4.165
192.168.4.171
192.168.4.173
192.168.4.174
192.168.4.179
192.168.4.185
192.168.4.202
192.168.4.215
192.168.4.223
192.168.4.235
192.168.4.251
192.168.4.255
192.168.4.27
192.168.4.34
192.168.4.37
192.168.4.44
192.168.4.50
192.168.4.80
192.168.4.83
192.168.4.90
192.168.4.93
192.168.4.98
192.168.5.25
192.168.5.31
192.168.5.45
192.168.5.60
192.168.5.64
192.168.5.67
192.168.5.77
192.168.5.80
192.168.10.117
192.168.10.121
192.168.10.146
192.168.10.16
192.168.10.169
192.168.10.174
192.168.10.184
192.168.10.186
192.168.10.189
192.168.10.196
192.168.10.20
192.168.10.205
192.168.10.208
192.168.10.213
192.168.10.221
192.168.10.222
192.168.10.227
192.168.10.229
192.168.10.24
192.168.10.243
192.168.10.25
192.168.10.3
192.168.10.60
192.168.10.61
192.168.10.62
192.168.10.75
192.168.10.84
192.168.10.87
192.168.10.91
192.168.10.92
192.168.10.93
192.168.11.105
192.168.11.12
192.168.11.125
192.168.11.144
192.168.11.159
192.168.11.16
192.168.11.174
192.168.11.186
192.168.11.19
192.168.11.191
192.168.11.196
192.168.11.205
192.168.11.205
192.168.11.208
192.168.11.208
192.168.11.21
192.168.11.23
192.168.11.28
192.168.11.42
192.168.11.63
192.168.11.73
192.168.11.77

then

MyOrg:46
Alt:17
other:17

why 17 clients are showed as "other"?

**Comment by bochoven** [comment]
I cannot reproduce your issue. From which view did you get the IP addresses?

**Comment by poundbangbash** [comment]
Could the "Other" be a 2nd IP from a wireless device picking up a 3rd party wireless network?

**Comment by bochoven** [comment]
This particular plot only uses the IP the client uses to connect to the MR server. So that's only logging one IP.

**Comment by hymmm** [comment]
Probably listing→Network

**Comment by bochoven** [comment]
The plot only shows the ip addresses that come from listing->munki
