### ISSUE TITLE
No data available in table on all tabs

### ISSUE THREAD

**Issue by mattiasvdm** [munkireport/munkireport-php#315]
I've recently updated the munkireport server and pushed out the new client. However on newly installed machines there is no data uploaded to the server. Almost every tab shows a message like no data available or no install history. Only the summary screen shows some information.
The preflight.d directory only has the submit.preflight script. The postflight.d directory stays empty.
I've been searching for a while now but I can't solve it and I'm not sure where to look anymore.

MunkiReport Version 2.5.3.1368

**Comment by bochoven** [comment]
You need to enable the modules you want to run on the client. Please read https://github.com/munkireport/munkireport-php/blob/master/docs/setup.md#select-which-modules-to-install-on-the-client
