### ISSUE TITLE
Managed Software Tab not reflecting Munki listing Runtype

### ISSUE THREAD

**Issue by sphen13** [munkireport/munkireport-php#316]
Ive noticed with the latest release of munkireport and munki - that the Munki listing does not jive 100% with the Managed Software Tab on the client page.  I have attached a couple screenshots - but even though it states that software was installed and some is pending - on the detail page it shows all as pending.  Also i noticed that no mater what on this page if things were installed, pending etc they all seem to have the same size for all packages.

Just wanted to pass along - anything else that needs clarification please let me know.

<img width="1655" alt="screen shot 2015-09-09 at 10 53 36 am" src="https://cloud.githubusercontent.com/assets/524607/9765313/a43ba9d4-56e1-11e5-8837-575026ae2f18.png">

<img width="1647" alt="screen shot 2015-09-09 at 10 53 47 am" src="https://cloud.githubusercontent.com/assets/524607/9765302/9581c374-56e1-11e5-80f7-4ba508316978.png">

**Comment by sphen13** [comment]
Not sure if i should add this as a new one or here -  but one more thing with the "Munki" listing.  The column for "Latest Run" seems to be off as well.  I have attached a screenshot of a machine that checked in 6 minutes ago yet in the listing it reports "an hour ago".  i can look further but it almost seems like an hour is the smallest value - after that it reflects properly.
<img width="1278" alt="screen shot 2015-09-17 at 12 16 18 pm" src="https://cloud.githubusercontent.com/assets/524607/9939056/47168cf0-5d36-11e5-987f-2d65f06152a7.png">
<img width="1101" alt="screen shot 2015-09-17 at 12 16 27 pm" src="https://cloud.githubusercontent.com/assets/524607/9939061/4add8e1a-5d36-11e5-81e6-0e3946a81041.png">

**Comment by sphen13** [comment]
it does reflect properly on the "Client" listing... :)
<img width="1494" alt="screen shot 2015-09-17 at 12 21 25 pm" src="https://cloud.githubusercontent.com/assets/524607/9939133/af2cac02-5d36-11e5-8fba-3636256259ec.png">

**Comment by bochoven** [comment]
I don't see this issue, hasn't this been fixed in the wip branch yet?

**Comment by sphen13** [comment]
Didn't test wip. Will do!

On Sep 17, 2015, at 3:56 PM, Arjen van Bochoven <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't see this issue, hasn't this been fixed in the wip branch yet?

-

**Comment by sphen13** [comment]
the wip branch is beautiful! :)

**Comment by bochoven** [comment]
Does that mean your issue is resolved?

**Comment by sphen13** [comment]
yes thanks
