### ISSUE TITLE
login window always shows red unlock after OS X server 5.0.3 update

### ISSUE THREAD

**Issue by mohremail** [munkireport/munkireport-php#317]
I don't know what changed but for some reason whenever I go to the login page of Munkireport, I get the red lock that says I'm insecure... this didn't used to be so... my site is auto redirected to my https SSL site that has a godaddy ssl but with that, and even after I click the lock, it and it goes again to my SSL site (lock shows up on the browser)... and still gives the red lock logo....
My web browsers have no problem getting a secure SSL connection to my munkireport site, and they show that it using the valid cert... but the munkireport login window is what shows the red lock... my browser(s) (all that I use) say the SSL connection is good and the cert is good, its just the munkireport login windows showing the red lock as not being secure... 

Is this related to how the new server puts a proxy in front of the website? 

I already restarted the server, and tried to reinstall the latest munkireport and still have the same issue.

**Comment by mohremail** [comment]
After 5.0.4 update the issue still persists.

**Comment by rickheil** [comment]
This is almost certainly related to the reverse proxy crap that the new version employs. If the check is port-based it should be looking for 34543 for HTTPS and 34580 for plain HTTP.

**Comment by bochoven** [comment]
Should be fixed in the latest release
