### ISSUE TITLE
Detect a Bootcamp Partition

### ISSUE THREAD

**Issue by gmarnin** [munkireport/munkireport-php#320]
Add some code like [this] (https://github.com/chilcote/pyfacts/blob/master/pyfacts#L476-L482)

**Comment by bochoven** [comment]
Could be added to the disk module

**Comment by bochoven** [comment]
Could you provide a plist that contains a Bootcamp partition? I would need the result of

```
diskutil list -plist
```

**Comment by gmarnin** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>AllDisks</key>
	<array>
		<string>disk0</string>
		<string>disk0s1</string>
		<string>disk0s2</string>
		<string>disk0s3</string>
		<string>disk0s4</string>
		<string>disk1</string>
	</array>
	<key>AllDisksAndPartitions</key>
	<array>
		<dict>
			<key>Content</key>
			<string>GUID_partition_scheme</string>
			<key>DeviceIdentifier</key>
			<string>disk0</string>
			<key>Partitions</key>
			<array>
				<dict>
					<key>Content</key>
					<string>EFI</string>
					<key>DeviceIdentifier</key>
					<string>disk0s1</string>
					<key>DiskUUID</key>
					<string>7D51CCB9-F4A5-48C9-B2FB-590A38DD8FD3</string>
					<key>Size</key>
					<integer>209715200</integer>
					<key>VolumeName</key>
					<string>EFI</string>
					<key>VolumeUUID</key>
					<string>0E239BC6-F960-3107-89CF-1C97F78BB46B</string>
				</dict>
				<dict>
					<key>Content</key>
					<string>Apple_CoreStorage</string>
					<key>DeviceIdentifier</key>
					<string>disk0s2</string>
					<key>DiskUUID</key>
					<string>E47CEE0F-FD3F-4AE9-BBBB-8A6C5FCD7553</string>
					<key>Size</key>
					<integer>204371206144</integer>
				</dict>
				<dict>
					<key>Content</key>
					<string>Apple_Boot</string>
					<key>DeviceIdentifier</key>
					<string>disk0s3</string>
					<key>DiskUUID</key>
					<string>ACEDE673-2500-4D0E-9240-6BCF2B74515F</string>
					<key>Size</key>
					<integer>650002432</integer>
					<key>VolumeName</key>
					<string>Recovery HD</string>
					<key>VolumeUUID</key>
					<string>CA2E06ED-D91C-3B8D-AA9F-1725C17013CB</string>
				</dict>
				<dict>
					<key>Content</key>
					<string>Microsoft Basic Data</string>
					<key>DeviceIdentifier</key>
					<string>disk0s4</string>
					<key>DiskUUID</key>
					<string>4C58B293-FEC3-4305-B371-FA69FEC76895</string>
					<key>MountPoint</key>
					<string>/Volumes/BOOTCAMP</string>
					<key>Size</key>
					<integer>45768245248</integer>
					<key>VolumeName</key>
					<string>BOOTCAMP</string>
					<key>VolumeUUID</key>
					<string>5799B5F6-F775-4B1B-ACF6-DB183685123D</string>
				</dict>
			</array>
			<key>Size</key>
			<integer>251000193024</integer>
		</dict>
		<dict>
			<key>Content</key>
			<string>Apple_HFS</string>
			<key>DeviceIdentifier</key>
			<string>disk1</string>
			<key>MountPoint</key>
			<string>/</string>
			<key>Size</key>
			<integer>204000002048</integer>
			<key>VolumeName</key>
			<string>Hard Drive</string>
		</dict>
	</array>
	<key>VolumesFromDisks</key>
	<array>
		<string>BOOTCAMP</string>
		<string>Hard Drive</string>
	</array>
	<key>WholeDisks</key>
	<array>
		<string>disk0</string>
		<string>disk1</string>
	</array>
</dict>
</plist>

**Comment by bochoven** [comment]
Bootcamp detection was added here https://github.com/munkireport/munkireport-php/commit/a926f5bdf943449a3f1eab169bd0642933fcddcc
