### ISSUE TITLE
Network locations not showing up on Network Report

### ISSUE THREAD

**Issue by RedClawx** [munkireport/munkireport-php#324]
Hello,
I have a brand new installation of MunkiReport 2.5.3. After getting some data into MySQL I notice that on the Network Report page the Network Locations is not showing anything. When I goto https://munkireport.example.com/index.php?/module/reportdata/ip I get the following error:
`Uncaught Exception: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ELSE 0 END) AS r2 FROM reportdata WHERE reportdata.machine_group IN (0)' at line 1`

We just started to use MunkiReport, so everything except Mac OS X Server is a fresh install.

Mac OS X Server 10.10.5
MunkiReport 2.5.3
MySQL 5.6.26
phpMyAdmin 4.5.0.2

**Comment by bochoven** [comment]
Did you enable the time machine module? Please read the install manual? Especially 
Select which modules to install on the client

You can file an issue on the github site for the error you're seeing

**Comment by RedClawx** [comment]
As per the install instructions we ran `http://munkireport.example.com/index.php?/install/dump_modules/config` and added in all the modules including "network" and "time machine". Though I don't understand what "time machine" have to do with the Network Locations. We did this during the setup process of MunkiReport. If I go into MySQL I can see entries in the MunkiReport Network table.

**Comment by bochoven** [comment]
Sorry about that, I think I mixed up two calls.
Can you see data in the listings->network report?

**Comment by bochoven** [comment]
What do you set `$conf['ip_ranges']` to in your config.php file to define the networks?

**Comment by RedClawx** [comment]
When I go to Network Report in Listings the correct information is returned.

**Hey**, I found it. In one of my $conf['ip_ranges']  I forgot to put a single quote into the array. Seeing as how we are just setting everything up we don't have a complete list of of IPs that we would want to track, so the list read `$conf['ip_ranges']['Off Campus'] = array();` instead of `$conf['ip_ranges']['Off Campus'] = array('');` After putting the single quote in, the graph is now being presented correctly.

It's always the simple things that get you hung up. Thank you for your time.
