### ISSUE TITLE
MR-PHP doesn't keep search when going back a page

### ISSUE THREAD

**Issue by WardsParadox** [munkireport/munkireport-php#326]
Steps to Reproduce:
Open a client listing page, Perform a search for a subset of computers, choose one computer, then hit back. The search is not saved as an available option to return too. 

Additional Info:
Not really a bug per say, more of a feature request. When I'm searching for one a set of labs, and checking on individual machines and returning to the search would be really nice to have.

**Comment by bochoven** [comment]
Search is saved on my machine, what version of munkireport are you using and in what browser do you see the problem?

**Comment by WardsParadox** [comment]
MR-PHP MunkiReport Version 2.5.3.1368
Chrome and Safari.

Ok interesting. I completely cleared out chrome this morning and it works
when I search via the Clients Listing. I realize that my typical search is
when I choose the errors, warnings, pending from the Munki listings.

**Comment by bochoven** [comment]
Issue resolved?

**Comment by WardsParadox** [comment]
Yup. Forgot to come back and close the issue.
