### ISSUE TITLE
DiskReport module fails on OSX10.6 (not python2.7)

### ISSUE THREAD

**Issue by hymmm** [munkireport/munkireport-php#327]
munkireport above 2.3 fails to report diskinfo on OSX10.6
  
>    Munkireport: Running disk_info
>    Munkireport: disk_info Error: Traceback (most recent call last):
>     File "/usr/local/munki/preflight.d/disk_info", line 203, in <module>      plistlib.writePlist(DiskReport(), "%s/disk.plist" % cachedir)
>      File "/usr/local/munki/preflight.d/disk_info", line 132, in DiskReport
>        for disk in AllDisksAndPartitions():
>      File "/usr/local/munki/preflight.d/disk_info", line 95, in AllDisksAndPartitions
>        raise Exception("Unable to list all partitions.")
>    Exception: Unable to list all partitions.
>        Munkireport: Running displays.py
>        Munkireport: Running filevaultstatus
>        Munkireport: filevaultstatus Error: /usr/local/munki/preflight.d/filevaultstatus: line 15: fdesetup: command not found
>       Munkireport: Running localadmin
>       Munkireport: Running networkinfo.sh
>        Munkireport: Running power.sh
>        Munkireport: Running profile.py
>        Munkireport: OS X not 10.7 or higher
>        Munkireport: Running servermetrics.py
>        Munkireport: servermetrics.py Error: Traceback (most recent call last):
>      File "/usr/local/munki/preflight.d/servermetrics.py", line 12, in <module>
>        import ccl_asldb
>      File "/usr/local/munki/munkireportlib/ccl_asldb.py", line 33, in <module>
>        import argparse
>    ImportError: No module named argparse

then

>    postflight stderr: ERROR: Munkireport: https://macserver.example.com/report/index.php?/report/hash_check
>ERROR: Munkireport: The server couldn't fulfill the request.
>ERROR: Munkireport: Error code: 500
>Done.

**Comment by bochoven** [comment]
Is this munkireport 2.5.3?

**Comment by hymmm** [comment]
Ah, yes, munkireport 2.5.3 is runnning.

**Comment by bochoven** [comment]
Could you check if this is fixed with 733e224d0d3110b704d736c89dd3c4490b5336c9
