### ISSUE TITLE
Munki Stats widget not display 

### ISSUE THREAD

**Issue by adambarnett52** [munkireport/munkireport-php#330]
Hi 

Running MunkiReport 2.6.0.1482 and the widget for munki stats is not displaying anything. The numbers are all 0

**Comment by bochoven** [comment]
Could you check in the Javascript console of your browser what's causing an error?

**Comment by adambarnett52** [comment]
from loading the console in Google Chrome ( right click, inspect element, console) 
i get the following

```
currentLng set to: en i18next.min.js:5
loaded: /munkireport/assets/locales/en.json
```

**Comment by bochoven** [comment]
Hmm, that's not an error. Could you check the result of:

index.php?/module/munkireport/get_stats/168

**Comment by adambarnett52** [comment]
```
{
error: "15",
warning: "0",
pending: "1",
installed: "3"
}
```

**Comment by bochoven** [comment]
That looks ok, maybe quit and restart the browser?

**Comment by adambarnett52** [comment]
It is happening on two different browsers, Chrome and Firefox. On Firefox i cleared everything and force reloaded the page

**Comment by bochoven** [comment]
Do you have groups filtered out? (The filter symbol at the top of the page)

**Comment by adambarnett52** [comment]
So i deselected all my filters ( i have 4 ) and then selected them again and now the numbers are correct

**Comment by bochoven** [comment]
So the issue is resolved?

**Comment by adambarnett52** [comment]
nope, everytime i leave the page i have to do the same again , it dose not
seem to like have filters applied

On Thu, Oct 8, 2015 at 4:09 PM, Arjen van Bochoven <notifications@github.com
> wrote:

> So the issue is resolved?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/330#issuecomment-146574326>
> .
>



-- 
Adam Barnett

**Comment by bochoven** [comment]
Just to make sure, when the numbers are zero, you still get results when calling

```
index.php?/module/munkireport/get_stats/168
```

**Comment by adambarnett52** [comment]
Yup

**Comment by bochoven** [comment]
An you're looking at the munki report page and not at the dashboard, right?

**Comment by adambarnett52** [comment]
It was the dashboard, on the home page
It's still the same even after the fix

On Sat, Oct 17, 2015 at 10:05 PM, Arjen van Bochoven <
notifications@github.com> wrote:

> Closed #330 <https://github.com/munkireport/munkireport-php/issues/330>
> via 84f5fbb
> <https://github.com/munkireport/munkireport-php/commit/84f5fbbe9494908fc8584486337c13c0a8662c83>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/330#event-438322488>
> .
>



-- 
Adam Barnett

**Comment by bochoven** [comment]
Does the view on the munki report page show the correct amounts?

**Comment by adambarnett52** [comment]
yup, on the munki report page show the correct thing

On Tue, Oct 20, 2015 at 12:02 PM, Arjen van Bochoven <
notifications@github.com> wrote:

> Reopened #330 <https://github.com/munkireport/munkireport-php/issues/330>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/330#event-440196336>
> .
>



-- 
Adam Barnett

**Comment by bochoven** [comment]
Which widgets do you have on the dashboard, and do you have any custom javascript?

**Comment by adambarnett52** [comment]
```
<?$this->view('widgets/munki_widget')?>
```

Is what is on the dashboard, it is the same as the report page
Nope, no custom javascript

what is strange is that when i refresh i can see the correct values  for a
second but then back to the 0's


On Tue, Oct 20, 2015 at 3:50 PM, Arjen van Bochoven <
notifications@github.com> wrote:

> Which widgets do you have on the dashboard, and do you have any custom
> javascript?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/330#issuecomment-149590865>
> .
>



-- 
Adam Barnett

**Comment by bochoven** [comment]
Could you post your $conf['dashboard_layout']

**Comment by adambarnett52** [comment]
```
tinker /opt/munkiweb/app/views/dashboard # cat custom_dashboard.php
<?$this->view('partials/head')?>

<div class="container">

        <div class="row">

                <?$this->view('widgets/client_widget')?>

                <?$this->view('widgets/disk_report_widget')?>

                <?$this->view('widgets/munki_widget')?>


                <?#$this->view('widgets/munki_versions_widget')?>
                <?$this->view('widgets/installed_memory_widget')?>

                <?$this->view('widgets/bound_to_ds_widget')?>



        </div> <!-- /row -->

        <div class="row">

        </div> <!-- /row -->

        <div class="row">

                <?$this->view('widgets/new_clients_widget')?>
                <?$this->view('widgets/hardware_warranty_widget')?>
 <?$this->view('widgets/munki_versions_widget')?>
<?$this->view('widgets/duplicated_computernames_widget')?>



        </div> <!-- /row -->

</div>  <!-- /container -->

<?$this->view('partials/foot')?>
```

On Tue, Oct 20, 2015 at 4:48 PM, Arjen van Bochoven <
notifications@github.com> wrote:

> Could you post your $conf['dashboard_layout']
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/330#issuecomment-149610880>
> .
>



-- 
Adam Barnett

**Comment by bochoven** [comment]
Ahhh, you have a *custom* dashboard!

Please add this line before the footer:

```
<script src="<?php echo conf('subdirectory'); ?>assets/js/munkireport.autoupdate.js"></script>
```

**Comment by adambarnett52** [comment]
Perfect,its  working now

Thanks for all the help

A

On Tue, Oct 20, 2015 at 5:28 PM, Arjen van Bochoven <
notifications@github.com> wrote:

> Ahhh, you have a *custom* dashboard!
>
> Please add this line before the footer:
>
> <script src="<?php echo conf('subdirectory'); ?>assets/js/munkireport.autoupdate.js"></script>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/330#issuecomment-149623427>
> .
>



-- 
Adam Barnett
