### ISSUE TITLE
Mixing up Models, Views and Controllers

### ISSUE THREAD

**Issue by Hansfreddy** [munkireport/munkireport-php#332]
Hey 

First of all, it's not directly an issue but something I noticed: It seems that on some points the MVC-Pattern is violated. For example, the widget in "views/widgets/duplicated_computernames_widget.php" contains SQL statements which, I believe, belong into the corresponding model.
However, this isn't really an issue but just something I noticed and wanted to mention.

I do have some more questions about the tool in general (not about the useage but more about contributing and the general "direction" it's heading) but I couldn't find an address to write to?

Regards
Hansfreddy

**Comment by bochoven** [comment]
You're right, I'm converting the current codebase to better match the MVC design pattern. My goal is to get most of the ui to use rest queries. There's a munkireport-dev mailing list to discuss future development. For a quick back-and-forth you could also check out the macadmins.org which has a #munkireport slack channel
