### ISSUE TITLE
Convert widgets to use REST

### ISSUE THREAD

**Issue by bochoven** [munkireport/munkireport-php#336]
Convert all widgets to use REST calls instead of doing SQL queries. These widgets are already converted:

- [x] app_widget.php
- [x] bluetooth_battery_widget.php
- [x] bound_to_ds_widget.php
- [x] certificate_widget.php
- [x] client_widget.php
- [x] disk_report_widget.php
- [x] duplicated_computernames_widget.php
- [x] external_displays_count_widget.php
- [x] filevault_widget.php
- [x] hardware_age_widget.php
- [x] hardware_model_widget.php
- [x] hardware_type_widget.php
- [x] hardware_warranty_widget.php
- [x] installed_memory_widget.php
- [x] manifests_widget.php
- [x] memory_widget.php
- [x] modified_computernames_widget.php
- [x] munki_versions_widget.php
- [x] munki_widget.php
- [x] network_location_widget.php
- [x] network_vlan_widget.php
- [x] new_clients_widget.php
- [x] os_widget.php
- [x] pending_apple_widget.php
- [x] pending_munki_widget.php
- [x] pending_widget.php
- [x] power_battery_condition_widget.php
- [x] power_battery_health_widget.php
- [x] registered_clients_widget.php
- [x] smart_status_widget.php
- [x] timemachine_widget.php
- [x] uptime_widget.php
- [x] warranty_widget.php

**Comment by bochoven** [comment]
And done

**Comment by nbalonso** [comment]
I'm going to put MR on a server temporarily just to see how much you are doing these days. Looks awesome!

**Comment by bochoven** [comment]
@nbalonso: It runs great on Linux! :smile:
