### ISSUE TITLE
Preflight and Postflight Python Scripts Error

### ISSUE THREAD

**Issue by AlroneRhyn** [munkireport/munkireport-php#338]
Hi Guys !

We are fond of Munkireport. But following version 2.6.1 install, i tried to update munki scripts on my client test machine. I hadn't till v0.9 for some of them and v2.4 for others. This is the following messages i get with v2.6.1 :

bash-3.2# /bin/bash -c "$(curl -s https://munkireport.example.fr/index.php?/install)"
Preparing /usr/local/munki/ and /Library/Preferences/MunkiReport
BaseURL is https://munkireport.example.fr/
Retrieving munkireport scripts
Configuring munkireport
+ Installing munkireport
Setting preferences
Installation of MunkiReport v2.6.1 complete.
Running the preflight script for initialization
    Munkireport: # Executing scripts in preflight_abort.d
    Munkireport: # Executing scripts in preflight.d
    Munkireport: Running submit.preflight
    Munkireport: submit.preflight Error: 2015-10-21 10:36:11.691 Python[1258:56972] connection_willSendRequestForAuthenticationChallenge_
2015-10-21 10:36:11.692 Python[1258:56972] Authentication challenge for Host: munkireport.example.fr Realm: None AuthMethod: NSURLAuthenticationMethodServerTrust
2015-10-21 10:36:11.692 Python[1258:56972] Allowing OS to handle authentication request

I tried with another host. Same result. Data seems to be correctly sent to munkireport server...but each preflight and postflight script running is displaying the stderr msg. Here is my ManagedInstalls Plist :

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>AppleSoftwareUpdatesOnly</key>
	<false/>
	<key>ClientIdentifier</key>
	<string>users</string>
	<key>InstallAppleSoftwareUpdates</key>
	<false/>
	<key>LastCheckDate</key>
	<date>2015-10-21T09:21:13Z</date>
	<key>LastCheckResult</key>
	<integer>0</integer>
	<key>LogFile</key>
	<string>/Library/Managed Installs/Logs/ManagedSoftwareUpdate.log</string>
	<key>LogToSyslog</key>
	<false/>
	<key>LoggingLevel</key>
	<integer>1</integer>
	<key>ManagedInstallDir</key>
	<string>/Library/Managed Installs</string>
	<key>PackageVerificationMode</key>
	<string>hash</string>
	<key>PendingUpdateCount</key>
	<integer>0</integer>
	<key>ShowRemovalDetail</key>
	<false/>
	<key>SoftwareRepoURL</key>
	<string>https://deploy.example.fr/</string>
	<key>SoftwareUpdateServerURL</key>
	<string></string>
	<key>SuppressAutoInstall</key>
	<false/>
	<key>SuppressStopButtonOnInstall</key>
	<true/>
	<key>SuppressUserNotification</key>
	<true/>
	<key>UseClientCertificate</key>
	<false/>
</dict>
</plist>

Here is my https://munkireport.example.fr/index.php?/install) variables:

BASEURL="https://munkireport.example.fr/"
TPL_BASE="${BASEURL}/assets/client_installer/"
MUNKIPATH="/usr/local/munki/" # TODO read munkipath from munki config
CACHEPATH="${MUNKIPATH}preflight.d/cache/"
PREFPATH="/Library/Preferences/MunkiReport"

It seels to be linked to a certificate matter. I'm using an official CA signed certificate.

Thx a lot !

**Comment by bochoven** [comment]
Munkireport uncorrectly states that this is an error, this needs to be corrected.

Please file an issue on github

-Arjen

**Comment by AlroneRhyn** [comment]
Hi,

Is there any test i can run to check if it's a false positive ?

Thx
