### ISSUE TITLE
Tags Displays text after clicking.

### ISSUE THREAD

**Issue by WardsParadox** [munkireport/munkireport-php#339]
After entering a Tag, the tag field displays additional parts of the text entered in that tag.
Here is a gif showing the behavior as I do know exactly the way to explain it.
![mrphptagbug](https://cloud.githubusercontent.com/assets/8117192/10642803/dea9f8f2-77dc-11e5-87b8-3a9778ce571c.gif)

**Comment by bochoven** [comment]
This is a bug in the bootstrap-tags plugin: https://github.com/timschlechter/bootstrap-tagsinput/issues/386
