### ISSUE TITLE
MunkiReport Client Listings blank after update to 2.6.1

### ISSUE THREAD

**Issue by DRCeccato** [munkireport/munkireport-php#340]
MunkiReport 2.6.1 -> Upgrade from 2.5.3
MySQL DB
OS X 10.11/Server 5.0.4

Backed up the 2.5.3 data and Created a new blankDB, verified permissions are right for the DB User.
updated client on test machine.  
Client appears to be reporting fine, although I am getting those python errors others are reporting at end of munki run):

2015-10-21 14:24:04.036 Python[9873:150254] connection_willSendRequestForAuthenticationChallenge_
2015-10-21 14:24:04.036 Python[9873:150254] Authentication challenge for Host: munki.ncdsb.com Realm: None AuthMethod: NSURLAuthenticationMethodServerTrust
2015-10-21 14:24:04.037 Python[9873:150254] Allowing OS to handle authentication request

When I open the dashboard page everything looks right, but when I go to Listings > Clients all I see is "Loading data from server"

![screen shot 2015-10-21 at 2 31 53 pm](https://cloud.githubusercontent.com/assets/11381665/10646584/d2846ae2-7801-11e5-8e4b-b977deef658d.png)

I even went ahead and backed up my old config.php, moved the 2.6.1 config_default.php to config and copied over my custom settings, but I'm seeing the same "Loading data from server" error.  

Any ideas?

**Comment by keneff** [comment]
I saw this same thing after updating to 2.6.1.  It was my uBlock Origin ad blocker that was causing it.  I whitelisted our munkireport and it all shows up normally.  Do you have any ad blockers enabled?

**Comment by DRCeccato** [comment]
Interestingly enough it appears to only happen in safari (running 9.0 on my machine).   I just double checked and there are no extensions installed in safari either.

When i try using Firefox or Chrome its runs fine.

**Comment by DRCeccato** [comment]
So after updating to 10.11.1 and Safari 9.0.1 it looks like everything fixed itself... Sorry to bother everyone.*hangs head in shame*
