### ISSUE TITLE
LDAP warning on failed login

### ISSUE THREAD

**Issue by rickheil** [munkireport/munkireport-php#341]
On incorrect password, the following is returned:

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in /Library/Server/Web/Data/Sites/munkireports.partnersandsimons.com/app/lib/authLDAP/authLDAP.php on line 432

This is running on latest OS X Server that came out yesterday.

**Comment by bochoven** [comment]
Could you check if https://github.com/munkireport/munkireport-php/commit/b0cb5518bfffa5f40eee9b85f5a0cbdc2d27567c resolves the issue? I don't have an LDAP server at hand at the moment.

**Comment by rickheil** [comment]
Yep - that does resolve the issue and auth still works as expected.
