### ISSUE TITLE
Group LDAP login Issue

### ISSUE THREAD

**Issue by AlroneRhyn** [munkireport/munkireport-php#342]
Hello !

Here is a wierd issue: me.admin is a member of munkireportadmins Active Directory group.
This line alone get me in : 
`$conf['auth']['auth_AD']['mr_allowed_users'] = 'me.admin';`
BUT this line alone returns a non logged error :
 `$conf['auth']['auth_AD']['mr_allowed_groups'] = 'munkireportadmins';`

It seems that the mr_allowd_groups param doesn't work properly, or do i use it the wrong way ?

Thanks a lot for your great work !

**Comment by gmarnin** [comment]
Try changing munkireportadmins to domain\munkireportadmins

Marnin

**Comment by bochoven** [comment]
What do you mean by 'non logged error'?

**Comment by AlroneRhyn** [comment]
@gmarnin It still doesn't work
@bochoven There is no output in apache error logs.

**Comment by bochoven** [comment]
What version of Munkireport?

**Comment by AlroneRhyn** [comment]
This is the last one : MunkiReport Version 2.6.1.1487

**Comment by bochoven** [comment]
Login with me.admin, `https://yourserver/path/to/munkireport/index.php?/auth/set_session_props/true` wil show you all AD groups where you are a member of according to MunkiReport

**Comment by bochoven** [comment]
AD groups are case-sensitive in MR

**Comment by AlroneRhyn** [comment]
Once login with me.admin thanks to the mr_allowd_users, there is the result of https://myserver/path/to/munkireport/index.php?/auth/set_session_pros/true :
`{"user":"me.admin","groups":[],"auth":"AD","role":"admin",[...]}`

**Comment by bochoven** [comment]
It looks like me.admin is not a member of any group. Maybe your BaseDN not right?

**Comment by clburlison** [comment]
@AlroneRhyn The other thing that could be happening is your LDAP setup requires you to pass a username/password for lookups. Do you have the following fields in your `config.php`? That could be why your `mr_allowed_groups` isn't working.

```php
$conf['auth']['auth_AD']['admin_username'] = 'USERNAME'; //if needed to perform the search
$conf['auth']['auth_AD']['admin_password'] = 'PASSWORD'; //if needed to perform the search
```

**Comment by AlroneRhyn** [comment]
@clburlison the user is a read only one, but yes, i'm using those attributes. 
@bochoven Me.admin is one of the Active Directory domain admin and is member of 10 groups. 

If i change the account_suffix by a fake one, i got :
`An error ocurred while contacting AD
Bind to Active Directory failed. Check the login credentials and/or server details. AD said: Invalid credentials`
Which is fine ! 

The error i get is : `Not authorized`

Here is my whole conf :
` $conf['auth']['auth_AD']['account_suffix'] = '@my.pinky.magical.domain';`
`$conf['auth']['auth_AD']['base_dn'] = 'DC=my,DC=pinky,DC=magical,DC=domain'; //set to NULL to auto-detect`
`$conf['auth']['auth_AD']['domain_controllers'] = 'ad.my.pinky.magical.domain'; //can be an array of servers`
`$conf['auth']['auth_AD']['admin_username'] = 'ro_user'; //if needed to perform the search`
`$conf['auth']['auth_AD']['admin_password'] = 'ro_user_passwd'; //if needed to perform the search`
` //$conf['auth']['auth_AD']['mr_allowed_users'] = 'me.admin';`
` $conf['auth']['auth_AD']['mr_allowed_groups'] = 'CN=munkireportadmins,OU=Groupes,DC=my,DC=pinky,DC=magical,DC=domain'`

**Comment by AlroneRhyn** [comment]
OK, this is solved. I knew i didn't do what i should have to : `$conf['auth']['auth_AD']['mr_allowed_groups'] = array('munkireportadmins');` is working, `$conf['auth']['auth_AD']['mr_allowed_groups'] = 'munkireportadmins';` is not. 

But `$conf['auth']['auth_AD']['mr_allowed_users'] = 'me.admin';` and `$conf['auth']['auth_AD']['mr_allowed_users'] = array('me.admin');`is working the same way.

**Comment by bochoven** [comment]
For me setting `$conf['auth']['auth_AD']['domain_controllers']` and `$conf['auth']['auth_AD']['base_dn']` is enough.

Don't use de DN in $conf['auth']['auth_AD']['mr_allowed_groups'], just the group name

**Comment by bochoven** [comment]
Just to be sure, do you see the groups now when you visit `https://myserver/path/to/munkireport/index.php?/auth/set_session_pros/true`?

**Comment by AlroneRhyn** [comment]
@bochoven I've got an `Error Page Not Found`
But every users member of my group can log in.

**Comment by bochoven** [comment]
Sorry copied badly. ```https://yourserver/path/to/munkireport/index.php?/auth/set_session_props/true```

Also you should be able to set the group without an array.

**Comment by AlroneRhyn** [comment]
Oui ! Yes ! I can now see my AD groups. Group without array = fail :) I'll try again.
