### ISSUE TITLE
stripslashes() error on datatables query

### ISSUE THREAD

**Issue by denmoff** [munkireport/munkireport-php#344]
When attempting to open a report, receiving error:
DataTables warning: table id=DataTables_Table_0 - SQLSTATE[HY000]: General error: 1 near "LIMIT": syntax error

Debugging output of index.php:
http://pastebin.com/16vfKS6s

**Comment by bochoven** [comment]
Although this is a legacy problem, it stems from the removed get_magic_quotes_gpc(), I think the function `clean_post_data()`should be fixed.
