### ISSUE TITLE
Timezone error?

### ISSUE THREAD

**Issue by mattiasvdm** [munkireport/munkireport-php#346]
If I click on Errors in the Munki Widget, a lot of clients show wrong information in the "Latest Run" column.
![schermafbeelding 2015-11-09 om 11 19 03](https://cloud.githubusercontent.com/assets/8159258/11031485/20127894-86d5-11e5-90ac-38c385fb2612.png)

I must add that these clients are also in a different timezone (+ 1 hour), so that probably explains the error. If I visit the MunkiReport page on a machine in the same timezone, this issue does not occur.

However, if I go to "Listings - Clients" I see the right information in the "Check-in" column. Both screenshots are from the same client.
![schermafbeelding 2015-11-09 om 11 20 19](https://cloud.githubusercontent.com/assets/8159258/11031486/2029df0c-86d5-11e5-9722-5ade8d254add.png)

**Comment by bochoven** [comment]
We should change this to show the server time.
