### ISSUE TITLE
Warranty "Lookup failed"

### ISSUE THREAD

**Issue by Darkomen78** [munkireport/munkireport-php#347]
Since I migrate munki report to mySQL (with new info upload by client) all Warranty make a "Lookup failed"

Is there something to check or test ?

**Comment by bochoven** [comment]
This is a known issue, since Apple added a captcha to the warranty lookup page, we can't do automated lookups anymore.

**Comment by jessepeterson** [comment]
@Darkomen78: Please send apple [feedback](http://bugreport.apple.com). (Like @chilcote did [here](https://openradar.appspot.com/23164334)). Let them know this is something you want to work!

**Comment by aysiu** [comment]
Is it possible to simply remove the column from reporting, then, if all the clients are reporting back "Lookup failed"?
