### ISSUE TITLE
Errors when using sql_mode=only_full_group_by (Default in mysql 5.7.9)

### ISSUE THREAD

**Issue by WardsParadox** [munkireport/munkireport-php#351]
You get an error when trying to access most panes:
Uncaught Exception: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'munkireport.profile.payload_data' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

which causes the whole dashboard to lock up.

**Comment by bochoven** [comment]
Could you check if this fixes your issue?

**Comment by aysiu** [comment]
In the meantime, not a fix, exactly, but a workaround is to temporarily disable that mode on the server. For example:

mysql> set global sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
mysql> set session sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

This error, by the way, didn't show up until I upgraded from MySQL 5.6 to MySQL 5.7.

**Comment by aysiu** [comment]
P.S. I tried out your fix, and it does work, even with ONLY_FULL_GROUP_BY set.
