### ISSUE TITLE
Feature request: custom lists

### ISSUE THREAD

**Issue by flammable** [munkireport/munkireport-php#357]
We're using machine groups to separate different types of computers (labs, podiums, faculty/staff, etc.).  Along the same lines, I'd love to be able to create and edit lists of Macs - even if they span multiple machine groups.  This would be useful for:

- Monitoring individual computer labs.  I'd probably create a single list per lab, so I can easily check up on a lab without needing to do a search or memorize computer names.
- Checking up on problematic Macs.  Machines tend to end up on my radar for a short amount of time.  I keep a tab open with the machine's details, but it'd help to be able to temporarily bookmark them.
- More things!

I use ARD lists for this sort of thing right now, but I'm trying to rely less on ARD (especially because it's very glitchy at this point).

Thanks!

Mike

**Comment by bochoven** [comment]
Would adding 'tags' to machines solve your issue? I know we need to add a listing for tags

**Comment by flammable** [comment]
I think so!  Could a machine have multiple tags?

**Comment by bochoven** [comment]
Sure, as many as you like! You can add tags to machines in the current release version.

**Comment by flammable** [comment]
Perfect!  This looks great!

Would it be possible to add a report where you could see a list of all of the tags, then click that to get a 'Clients' listing of all Macs with that tag?

Thanks, Arjen!

**Comment by bochoven** [comment]
Yes, that would not be very hard to implement. I had bigger plans for tags (use them to filter everything, just like machine groups), but I may do the simple list view first.

**Comment by flammable** [comment]
That sounds pretty sweet, too!

**Comment by bochoven** [comment]
tag widget and list view is in 2.7.3

**Comment by flammable** [comment]
Awesome!  Thanks, Arjen!  I'll get the server upgraded! :+1:
