### ISSUE TITLE
Uncaught Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'serial_number' in 'where clause' Show 

### ISSUE THREAD

**Issue by adambarnett52** [munkireport/munkireport-php#360]
I get the above error after upgrading to the new version

- Version: 2.7.1.1642
- I set $conf['allow_migrations'] = TRUE

I can load the front page dashboard  but i cannot load any client info

**Comment by bochoven** [comment]
Could you paste the full error?

**Comment by adambarnett52** [comment]
All i get is

"Uncaught Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'serial_number' in 'where clause'
Show " 
At the top of the page when i click on any of the clients

**Comment by adambarnett52** [comment]
if i set migration back to true i get these errors

Migration error: reportdata: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'machine_group'
Migration error: inventoryitem: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
Uncaught Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'serial_number' in 'where clause'

DB is mysql

**Comment by bochoven** [comment]
Sounds like a bad migration, what version did you migrate from?
What version of MySQL?

**Comment by adambarnett52** [comment]
Sorry i cannot remmeber what version it was, i was the latest before this one
mysql 5.1.71
Can i redo the migration?

**Comment by adambarnett52** [comment]
And news on how i can fix this?

Thanks


On Fri, Dec 11, 2015 at 12:23 PM, Arjen van Bochoven <
notifications@github.com> wrote:

> Sounds like a bad migration, what version did you migrate from?
> What version of MySQL?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/360#issuecomment-163925935>
> .
>



-- 
Adam Barnett

**Comment by bochoven** [comment]
Sorry about that, I got distracted. You can fix this error:

Migration error: reportdata: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'machine_group'

By setting the version = 3  on the migration table where table_name = reportdata

**Comment by adambarnett52** [comment]
Hi

Sorry but how would i do this? my msql is a bit rusty

Thanks
Adam


On Sat, Dec 12, 2015 at 10:13 PM, Arjen van Bochoven <
notifications@github.com> wrote:

> Sorry about that, I got distracted. You can fix this error:
>
> Migration error: reportdata: SQLSTATE[42S21]: Column already exists: 1060
> Duplicate column name 'machine_group'
>
> By setting the version = 3 on the migration table where table_name =
> reportdata
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/360#issuecomment-164197696>
> .
>



-- 
Adam Barnett

**Comment by bochoven** [comment]
Do you have a MySQL editor available? Sequel Pro? You can edit the database with an editor.
On the MySQL console you could run 
<code sql>
UPDATE migration SET version = 3 WHERE table_name = 'reportdata';
</code>

**Comment by adambarnett52** [comment]
I have updated and turn migration back on ( was not sure if i had to or not)
with migration on i get this error


    Migration error: inventoryitem: SQLSTATE[42000]: Syntax error or access
violation: 1071 Specified key was too long; max key length is 1000 bytes
    Uncaught Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown
column 'serial_number' in 'where clause'


Thanks
Adam

On Sat, Dec 12, 2015 at 10:23 PM, Arjen van Bochoven <
notifications@github.com> wrote:

> Do you have a MySQL editor available? Sequel Pro? You can edit the
> database with an editor.
> On the MySQL console you could run
>
> UPDATE migration SET version = 3 WHERE table_name = 'reportdata';
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/360#issuecomment-164198843>
> .
>



-- 
Adam Barnett

**Comment by adambarnett52** [comment]
Also to note that with 'migration' of i get a blank page with just the
search bar

Thanks
Adam

On Sat, Dec 12, 2015 at 10:30 PM, Adam Barnett <adambarnett52@gmail.com>
wrote:

> I have updated and turn migration back on ( was not sure if i had to or
> not)
> with migration on i get this error
>
>
>     Migration error: inventoryitem: SQLSTATE[42000]: Syntax error or
> access violation: 1071 Specified key was too long; max key length is 1000
> bytes
>     Uncaught Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown
> column 'serial_number' in 'where clause'
>
>
> Thanks
> Adam
>
> On Sat, Dec 12, 2015 at 10:23 PM, Arjen van Bochoven <
> notifications@github.com> wrote:
>
>> Do you have a MySQL editor available? Sequel Pro? You can edit the
>> database with an editor.
>> On the MySQL console you could run
>>
>> UPDATE migration SET version = 3 WHERE table_name = 'reportdata';
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/munkireport/munkireport-php/issues/360#issuecomment-164198843>
>> .
>>
>
>
>
> --
> Adam Barnett
>



-- 
Adam Barnett

**Comment by bochoven** [comment]
For the second error, please paste the output of

<code sql>
SHOW CREATE TABLE `inventory item`;
</code>

**Comment by adambarnett52** [comment]
mysql> SHOW CREATE TABLE inventoryitem\G

*************************** 1. row ***************************

       Table: inventoryitem

Create Table: CREATE TABLE `inventoryitem` (

  `id` int(11) NOT NULL AUTO_INCREMENT,

  `serial` varchar(255) DEFAULT NULL,

  `name` varchar(255) DEFAULT NULL,

  `version` varchar(255) DEFAULT NULL,

  `bundleid` varchar(255) DEFAULT NULL,

  `bundlename` varchar(255) DEFAULT NULL,

  `path` varchar(255) DEFAULT NULL,

  PRIMARY KEY (`id`),

  KEY `inventoryitem_serial` (`serial`)

) ENGINE=MyISAM AUTO_INCREMENT=27778476 DEFAULT CHARSET=utf8

1 row in set (0.00 sec)




On Sat, Dec 12, 2015 at 10:34 PM, Arjen van Bochoven <
notifications@github.com> wrote:

> For the second error, please paste the output of
>
>
> SHOW CREATE TABLE inventory item;
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/360#issuecomment-164199376>
> .
>



-- 
Adam Barnett

**Comment by bochoven** [comment]
I think you need to change the engine to innodb for all tables.

**Comment by adambarnett52** [comment]
I have updated

mysql> SHOW CREATE TABLE inventoryitem\G

*************************** 1. row ***************************

       Table: inventoryitem

Create Table: CREATE TABLE `inventoryitem` (

  `id` int(11) NOT NULL AUTO_INCREMENT,

  `serial` varchar(255) DEFAULT NULL,

  `name` varchar(255) DEFAULT NULL,

  `version` varchar(255) DEFAULT NULL,

  `bundleid` varchar(255) DEFAULT NULL,

  `bundlename` varchar(255) DEFAULT NULL,

  `path` varchar(255) DEFAULT NULL,

  PRIMARY KEY (`id`),

  KEY `inventoryitem_serial` (`serial`)

) ENGINE=InnoDB AUTO_INCREMENT=27778476 DEFAULT CHARSET=utf8

1 row in set (0.00 sec)



But i am still getting the same error


    Uncaught Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown
column 'serial_number' in 'where clause'
Thanks
Adam

On Sun, Dec 13, 2015 at 1:10 PM, Arjen van Bochoven <
notifications@github.com> wrote:

> I think you need to change the engine to innodb for all tables.
>
> Sent from my iPhone
>
> > On 13 Dec 2015, at 13:19, adambarnett52 <notifications@github.com>
> wrote:
> >
> > mysql> SHOW CREATE TABLE inventoryitem\G
> >
> > *************************** 1. row ***************************
> >
> > Table: inventoryitem
> >
> > Create Table: CREATE TABLE `inventoryitem` (
> >
> > `id` int(11) NOT NULL AUTO_INCREMENT,
> >
> > `serial` varchar(255) DEFAULT NULL,
> >
> > `name` varchar(255) DEFAULT NULL,
> >
> > `version` varchar(255) DEFAULT NULL,
> >
> > `bundleid` varchar(255) DEFAULT NULL,
> >
> > `bundlename` varchar(255) DEFAULT NULL,
> >
> > `path` varchar(255) DEFAULT NULL,
> >
> > PRIMARY KEY (`id`),
> >
> > KEY `inventoryitem_serial` (`serial`)
> >
> > ) ENGINE=MyISAM AUTO_INCREMENT=27778476 DEFAULT CHARSET=utf8
> >
> > 1 row in set (0.00 sec)
> >
> >
> >
> >
> > On Sat, Dec 12, 2015 at 10:34 PM, Arjen van Bochoven <
> > notifications@github.com> wrote:
> >
> > > For the second error, please paste the output of
> > >
> > >
> > > SHOW CREATE TABLE inventory item;
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/munkireport/munkireport-php/issues/360#issuecomment-164199376
> >
> > > .
> > >
> >
> >
> >
> > --
> > Adam Barnett
>
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/issues/360#issuecomment-164255869>
> .
>



-- 
Adam Barnett

**Comment by adambarnett52** [comment]
WAITT!!

I restarted mysql and it is all working now

Thanks for all the help


On Sun, Dec 13, 2015 at 1:25 PM, Adam Barnett <adambarnett52@gmail.com>
wrote:

> I have updated
>
> mysql> SHOW CREATE TABLE inventoryitem\G
>
> *************************** 1. row ***************************
>
>        Table: inventoryitem
>
> Create Table: CREATE TABLE `inventoryitem` (
>
>   `id` int(11) NOT NULL AUTO_INCREMENT,
>
>   `serial` varchar(255) DEFAULT NULL,
>
>   `name` varchar(255) DEFAULT NULL,
>
>   `version` varchar(255) DEFAULT NULL,
>
>   `bundleid` varchar(255) DEFAULT NULL,
>
>   `bundlename` varchar(255) DEFAULT NULL,
>
>   `path` varchar(255) DEFAULT NULL,
>
>   PRIMARY KEY (`id`),
>
>   KEY `inventoryitem_serial` (`serial`)
>
> ) ENGINE=InnoDB AUTO_INCREMENT=27778476 DEFAULT CHARSET=utf8
>
> 1 row in set (0.00 sec)
>
>
>
> But i am still getting the same error
>
>
>     Uncaught Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown
> column 'serial_number' in 'where clause'
> Thanks
> Adam
>
> On Sun, Dec 13, 2015 at 1:10 PM, Arjen van Bochoven <
> notifications@github.com> wrote:
>
>> I think you need to change the engine to innodb for all tables.
>>
>> Sent from my iPhone
>>
>> > On 13 Dec 2015, at 13:19, adambarnett52 <notifications@github.com>
>> wrote:
>> >
>> > mysql> SHOW CREATE TABLE inventoryitem\G
>> >
>> > *************************** 1. row ***************************
>> >
>> > Table: inventoryitem
>> >
>> > Create Table: CREATE TABLE `inventoryitem` (
>> >
>> > `id` int(11) NOT NULL AUTO_INCREMENT,
>> >
>> > `serial` varchar(255) DEFAULT NULL,
>> >
>> > `name` varchar(255) DEFAULT NULL,
>> >
>> > `version` varchar(255) DEFAULT NULL,
>> >
>> > `bundleid` varchar(255) DEFAULT NULL,
>> >
>> > `bundlename` varchar(255) DEFAULT NULL,
>> >
>> > `path` varchar(255) DEFAULT NULL,
>> >
>> > PRIMARY KEY (`id`),
>> >
>> > KEY `inventoryitem_serial` (`serial`)
>> >
>> > ) ENGINE=MyISAM AUTO_INCREMENT=27778476 DEFAULT CHARSET=utf8
>> >
>> > 1 row in set (0.00 sec)
>> >
>> >
>> >
>> >
>> > On Sat, Dec 12, 2015 at 10:34 PM, Arjen van Bochoven <
>> > notifications@github.com> wrote:
>> >
>> > > For the second error, please paste the output of
>> > >
>> > >
>> > > SHOW CREATE TABLE inventory item;
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <
>> https://github.com/munkireport/munkireport-php/issues/360#issuecomment-164199376
>> >
>> > > .
>> > >
>> >
>> >
>> >
>> > --
>> > Adam Barnett
>>
>> > —
>> > Reply to this email directly or view it on GitHub.
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/munkireport/munkireport-php/issues/360#issuecomment-164255869>
>> .
>>
>
>
>
> --
> Adam Barnett
>



-- 
Adam Barnett
