### ISSUE TITLE
Clients don't report to Server

### ISSUE THREAD

**Issue by xinput** [munkireport/munkireport-php#361]
Hello,

i finally got munkireport working now. But i'm stuck on the reporting.

The Webinterface only shows up 12 Clients of 200 Active.

<img width="1654" alt="bildschirmfoto 2015-12-11 um 15 10 25" src="https://cloud.githubusercontent.com/assets/11652924/11746043/39593a58-a01c-11e5-80b4-d151a053d630.png">

i've manually run /usr/local/munki/preflight on 4 clients and the db.sqllite isn't filling data.

i've inspectet the database but there are only this 12 clients.
My config.php looks like this:

<img width="567" alt="bildschirmfoto 2015-12-11 um 15 24 56" src="https://cloud.githubusercontent.com/assets/11652924/11746086/6fb95c4a-a01c-11e5-91d8-91c9a09b9241.png">

maybe i misconfigured smth or is this a bug in version 2.7.0?

**Comment by bochoven** [comment]
Is this a new installation?

**Comment by bochoven** [comment]
Do you have output for a /usr/local/munki/preflight run?

**Comment by xinput** [comment]
we've had version 2.2 before. but i tried to do a fresh reinstall of munkireport.
so i didn't migrate the old sqllite db.

yeah my output looks like this:

<img width="568" alt="bildschirmfoto 2015-12-11 um 15 37 17" src="https://cloud.githubusercontent.com/assets/11652924/11746196/19555268-a01d-11e5-871c-859a49313345.png">

seems to be no error.

**Comment by bochoven** [comment]
and /usr/local/munki/postflight?

**Comment by bochoven** [comment]
Did you change anything on the server, or is it the same address? The clients connect to a specific server address and path.

**Comment by xinput** [comment]
output is like followed:
<img width="799" alt="bildschirmfoto 2015-12-11 um 15 40 41" src="https://cloud.githubusercontent.com/assets/11652924/11746329/f1cf8ef6-a01d-11e5-946d-ae2ad2afc8b4.png">

The server is the same. i didn't changed anything. only the docroot of the munkireport files.
