### ISSUE TITLE
Visual bug in uptime

### ISSUE THREAD

**Issue by killahquam** [munkireport/munkireport-php#363]
<img width="490" alt="screen shot 2015-12-12 at 2 58 20 am" src="https://cloud.githubusercontent.com/assets/3904230/11761548/17d667ba-a07c-11e5-9d57-ba9362a4c66c.png">
There is an inconsistency in the way MR shows the uptime of clients

**Comment by bochoven** [comment]
We should hide the buttons that don't have a value or display a zero

**Comment by poundbangbash** [comment]
I believe this is resolved in https://github.com/munkireport/munkireport-php/pull/780
