### ISSUE TITLE
inventory and profiles to serverside loading

### ISSUE THREAD

**Issue by clburlison** [munkireport/munkireport-php#369]
Please, convert the "inventory" page and "profiles" page to load from the serverside. Currently, these views are loading all the data from the server to the browser, and then filtering what needs to be shown.

This scales pretty poorly and can result in large wait times.

Thanks.

**Comment by bochoven** [comment]
Thanks!

**Comment by clburlison** [comment]
This might be fixed in wip? https://github.com/munkireport/munkireport-php/commit/94c9048c949eb7d643ca411fe01f39a8e989d3a4

I know the profiles loading is much faster with the updated SQL query. I'll let you close at your discretion.

**Comment by bochoven** [comment]
Inventory is still rendered client side, rhough
