### ISSUE TITLE
Add System Integrity Protection Status

### ISSUE THREAD

**Issue by xinput** [munkireport/munkireport-php#371]
Is it possible to add a Report with the status of System Integrity Protection unter the "security" listing?

Maybe by adding the 
csrutil status 

command in one of the preflight scripts?

**Comment by bochoven** [comment]
Could be part of a 'security' module

**Comment by xinput** [comment]
Update:
i found this https://derflounder.wordpress.com/2015/12/18/updated-system-integrity-protection-status-reporting-script/

maybe this could be implemented in some way.

**Comment by bochoven** [comment]
Sure, it would need to be added to a module, I'm not planning on writing one at the moment, but you can give it a shot: https://github.com/munkireport/munkireport-php/wiki/How-to-create-a-module

**Comment by bochoven** [comment]
See the new security module by @gmarnin !
