### ISSUE TITLE
Hardware age widget wrong scale

### ISSUE THREAD

**Issue by pexner** [munkireport/munkireport-php#373]
The Hardware age widget has a scale of 0.5 machines, looks strange. Could this be corrected to full numbers?

**Comment by bochoven** [comment]
The graph uses an automatic scale, not sure how to make it use integers only. I also want to convert all graphs to nvd3. I'll leave this issue open as a reminder.

**Comment by pexner** [comment]
STrangely, the RAM and age widget use integers. Thanks a lot anyway.

**Comment by bochoven** [comment]
I think this has been fixed a long time ago
