### ISSUE TITLE
Usage of curl --insecure in install_script.php 

### ISSUE THREAD

**Issue by MichalMMac** [munkireport/munkireport-php#374]
We have munkireport accessible only via HTTPS (TLS 1.0+). We have our own CA with it's certificates installed on all machines -> certs signed by CA are trusted.

When I want to create package for clients with install_script fails 3 times with 

    curl: (56) SSLRead() return error -9841

This happens because of --insecure flag. I found this [thread](https://groups.google.com/forum/#!topic/munkireport/z0NsJCuwE7U) in google group.
My current solution is to remove --insecure flag from install_script.

> I'm not sure why this happens (Do you have a client certificate request on the server?), but I think we need an extra config item to control the --insecure flag in curl. 

In regards to this comment. How did you solve this?

Right now I agree with this statement. Should it be implemented via script parameter in query string?

**Comment by gmarnin** [comment]
I remove --insecure. If I leave it in I get:

sudo /bin/bash -c "$(curl -s http://domain/munkireport-php/index.php?/install)"
2016-01-04 09:41:38.981 defaults[10116:232872] 
The domain/default pair of (/Library/Preferences/MunkiReport, UseMunkiAdditionalHttpHeaders) does not exist
Preparing /usr/local/munki/ and /Library/Preferences/MunkiReport
BaseURL is https://domain/munkireport-php/
Retrieving munkireport scripts
curl: (56) SSLRead() return error -9841
curl: (56) SSLRead() return error -9841
curl: (56) SSLRead() return error -9841
Failed to download all required components!

**Comment by bochoven** [comment]
Could you test if the recent addition to wip helps to address your issue?

**Comment by gmarnin** [comment]
I did some initial testing and this change looks good.

**Comment by MichalMMac** [comment]
Just updated affected munkireport app to 2.8.4.
I still get `curl: (56) SSLRead() return error -9841` 3 times because of `--insecure` curl flag.

I guess we will solve this eventualy by moving to trusted let's encrypt certificates but for now I have to remove `--insecure` flag from build script to be able to build package.

**Comment by bochoven** [comment]
The change is still in the wip branch, it will be merged in the next release of munkireport (2.9.x)

**Comment by MichalMMac** [comment]
Whops sorry. I've just tested it in wip branch. 

Works. Looks good.

**Comment by MichalMMac** [comment]
I am no longer able to test this since we switched to Let's Encrypt certificates. Should we mark this as "fixed in wip"?
