### ISSUE TITLE
MySQL integers gets returned as strings in JSON data response

### ISSUE THREAD

**Issue by Steffan-Ravn** [munkireport/munkireport-php#375]
In my environment I am experiencing a strange behavior; under the client-view in the Storage-tab it showed that ALL drives where encrypted and that ALL drives where internal - which is certainly not the case, so I started digging into the code.

I seems that when assets/js/munkireport.storageplot.js receive the JSON data response from the MySQL database, all of the values are returned as strings in my case, and as obj.CoreStorageEncrypted and obj.Internal (among others) expect an integer, these values get set to true always.

I haven't experienced this in my initial test-setup and it seems that nobody else has reported this behavior, but as I've followed the setup-guide, and to my knowledge I haven't configured anything differently, that could cause these symptoms - I can't seem to find a way to fix this problem.

I am currently running:
MunkiReport version 2.6.1.1487 on a Ubuntu 14.04.3 Server with PHP 5.5.9, MySQL Server 5.5.44 and Apache 2.4.7.

I'm accessing the web interface via Safari 9.0.1 or Firefox 42.0.

If you need anymore information, please tell me.

Thanks in advantage.

Sincerely
Steffan Ravn Edwardsen

**Comment by bochoven** [comment]
Not sure why this happens, but to mitigate this, we need to add type conversion before outputting to JSON

**Comment by bochoven** [comment]
Could you check if this change 9dfb38c4d768ef84dda2f8d2553c9a208b53d8ff fixes your issue? It's a client side fix.

**Comment by Steffan-Ravn** [comment]
Hi Arjen,

That actually seems to solve the problem - tested in both Safari and Firefox. Thanks!
