### ISSUE TITLE
FileVault 2 status incorrect

### ISSUE THREAD

**Issue by mrcamuti** [munkireport/munkireport-php#378]
Totally possible that I'm screwing something up, but "Encryption Status" on the Storage module is reporting "Encrypted" for disks that do not have encryption turned on.

Affected OS in my setup includes 10.9.5, 10.10.5, and 10.11.2.
I'm running MunkiReport Version 2.7.3.1648

**Comment by mrcamuti** [comment]
![encryption mismatch](https://cloud.githubusercontent.com/assets/11513137/12365358/1bd7abf8-bb89-11e5-92aa-1d416ae89305.png)
I used ARD to run Trouton's filevault_2_status_check.sh to verify, for this example.

**Comment by bochoven** [comment]
Could you please look at #375 as I think that is the same issue

**Comment by mrcamuti** [comment]
Absolutely could be the issue. I'm not familiar enough with the underlying
pieces to say, but my setup matches his description of the symptoms.

**Comment by bochoven** [comment]
Could you please test if the latest commit fixes the issue?

**Comment by mrcamuti** [comment]
The Storage tab is still incorrectly reporting all drives as "Encrypted".

But... the Security report is correctly tagging computers as unencrypted.
Not sure if this is new behavior or not (I had not found the security
report before troubleshooting this issue).

**Comment by mrcamuti** [comment]
I just cross-referenced the unencrypted tag in the security report with
actual encryption state on the machines, and it's good, but not perfect.

So far: "Encyrpted" TAG in the security report correlates perfectly with
actual encryption status.
"Unencrypted" TAG is not perfectly correlated with unencrypted status
(10.10.5 rMBP with FV2 on, still reporting as "unencrypted")

**Comment by bochoven** [comment]
Could you post the output of

   /usr/local/munki/preflight.d/cache/disk.plist 

from the 10.10.5 rMBP with FV2 on, still reporting as "unencrypted"

**Comment by mrcamuti** [comment]
[diskplist.zip](https://github.com/munkireport/munkireport-php/files/96321/diskplist.zip)

Sorry, holiday weekend here in the States. Here's the file you requested. It was captured a full day after the reported behavior, but hoping it's still got what you're looking for.

**Comment by bochoven** [comment]
This machine is not reporting on encryption status which may be a fault in the disk reporting script. Do you have a current version of the disk_reporting script installed? Could you check if ```/usr/local/munki/preflight.d/disk_info```
is the same as
https://github.com/munkireport/munkireport-php/blob/master/app/modules/disk_report/scripts/disk_info

**Comment by mrcamuti** [comment]
I used diff to compare the two scripts and they're identical line by line.
I did just verify that the encryption status is still mis-reporting in the
Security report, as well as the Storage report. (Both say unencrypted, but
on the device, I verified it is encrypted **note that I just thought of, we
do use an institutional key, not an individual key for encryption** )

**Comment by bochoven** [comment]
Could you post the output of 

    diskutil info -plist /

**Comment by mrcamuti** [comment]
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "
http://www.apple.com/DTDs/PropertyList-1.0.dtd">

<plist version="1.0">

<dict>

<key>Bootable</key>

<true/>

<key>BusProtocol</key>

<string>SATA</string>

<key>CanBeMadeBootable</key>

<false/>

<key>CanBeMadeBootableRequiresDestroy</key>

<false/>

<key>Content</key>

<string>Apple_HFS</string>

<key>DeviceBlockSize</key>

<integer>512</integer>

<key>DeviceIdentifier</key>

<string>disk1</string>

<key>DeviceNode</key>

<string>/dev/disk1</string>

<key>DeviceTreePath</key>

<string>IODeviceTree:/PCI0@0/SATA@1F,2/PRT0@0/PMP@0</string>

<key>Ejectable</key>

<false/>

<key>FilesystemName</key>

<string>Journaled HFS+</string>

<key>FilesystemType</key>

<string>hfs</string>

<key>FilesystemUserVisibleName</key>

<string>Mac OS Extended (Journaled)</string>

<key>FreeSpace</key>

<integer>34652688384</integer>

<key>GlobalPermissionsEnabled</key>

<true/>

<key>IOKitSize</key>

<integer>249804886016</integer>

<key>Internal</key>

<true/>

<key>JournalOffset</key>

<integer>365596672</integer>

<key>JournalSize</key>

<integer>25165824</integer>

<key>LowLevelFormatSupported</key>

<false/>

<key>MediaName</key>

<string>Macintosh HD</string>

<key>MediaType</key>

<string>Generic</string>

<key>MountPoint</key>

<string>/</string>

<key>OS9DriversInstalled</key>

<false/>

<key>ParentWholeDisk</key>

<string>disk1</string>

<key>RAIDMaster</key>

<false/>

<key>RAIDSlice</key>

<false/>

<key>RecoveryDeviceIdentifier</key>

<string>disk0s3</string>

<key>SMARTStatus</key>

<string>Not Supported</string>

<key>SolidState</key>

<true/>

<key>SupportsGlobalPermissionsDisable</key>

<true/>

<key>SystemImage</key>

<false/>

<key>TotalSize</key>

<integer>249804886016</integer>

<key>VolumeName</key>

<string>Macintosh HD</string>

<key>VolumeUUID</key>

<string>FD9F3E62-738F-3DF6-9E50-57F1C27C5434</string>

<key>WholeDisk</key>

<true/>

<key>Writable</key>

<true/>

<key>WritableMedia</key>

<true/>

<key>WritableVolume</key>

<true/>

</dict>

</plist>

**Comment by bochoven** [comment]
This is not an encrypted disk. Why do you think it is encrypted? What does it say in the 'Security and Privacy' preference pane?

**Comment by mrcamuti** [comment]
FileVault is On. Institutional key, the usual.

**Comment by mrcamuti** [comment]
I can send a screenshot, if that would help.

**Comment by bochoven** [comment]
What does 

    fdesetup status 

report?

**Comment by mrcamuti** [comment]
FileVault is turned on.

**Comment by bochoven** [comment]
And

    diskutil cs list

**Comment by mrcamuti** [comment]
Redacted LVVM info.

**Comment by mrcamuti** [comment]
And just to make super sure I'm not missing something obvious with the
 /usr/local/munki/preflight.d/disk_info
comparison, I used diff -yI /github_version_local_copy
/emailed_version_from_client and got no output, which, as I understand it,
means they're identical. Please confirm I haven't gone nuts.

**Comment by bochoven** [comment]
The corestorage output did not come through

**Comment by mrcamuti** [comment]
Just added it on GH to the comment that mentioned it.

**Comment by bochoven** [comment]
I would like some output from this machine to see what's going on with the disk_reporting script. Would you be able to provide the output of:

     /usr/sbin/diskutil list -plist
     /usr/sbin/diskutil info -plist disk1
     /usr/sbin/diskutil cs info -plist disk1

With unredacted ID strings (or globally replaced by another string)

**Comment by bochoven** [comment]
Any progress on this?

**Comment by mrcamuti** [comment]
I had zipped the files you asked for and then uploaded them through the
github web interface. I'm hoping you got them, yeah?

**Comment by bochoven** [comment]
I don't have those files (maybe I lost them), could you send them again?

**Comment by mrcamuti** [comment]
I'm traveling right now, but once I'm home next week I will see if I have
them still.

And thanks for following up on this.

**Comment by bochoven** [comment]
Please open this issue again if this is still relevant.
