### ISSUE TITLE
Reporting on NOPKG and MobileConfig Profiles

### ISSUE THREAD

**Issue by viggen9** [munkireport/munkireport-php#383]
Feature Request - would love to be able to pull a report of NOPKG install status and MobileConfig Profile install status.  Thanks!

**Comment by bochoven** [comment]
This will need a rewrite of the munkireport module, so the installs are in a separate table.

**Comment by bochoven** [comment]
There *is* a profile module available that reports on profiles.

**Comment by viggen9** [comment]
I've looked at the profiles report, but I don't seem to get accurate data out of it.  Not sure why or what the common denominator is there.

**Comment by bochoven** [comment]
If the profile module/report is not accurate, please file a separate issue.

**Comment by bochoven** [comment]
Should be addressed in the managed installs module
