### ISSUE TITLE
location report map height change

### ISSUE THREAD

**Issue by rfitzwater** [munkireport/munkireport-php#413]
I see the map size is set to 500px for height.  I made a change to my code to set it up so it fills the browsers window.  Here is the code I changed in location.php:

line 9:`<div class="row" style="height: calc(100vh - 136px);">`

line 11:    `<div class="col-md-12" id="map" style="height: 100%; position: relative; background-color: rgb(229, 227, 223); overflow: hidden; transform: translateZ(0px);">`

I tested in Safari 9, Firefox 43 and Chrome 48.

**Comment by bochoven** [comment]
If you could send a Pull Request with your code, we can review your changes. Testing on iPhone recommended as well.

**Comment by rfitzwater** [comment]
I just did the pull request with changes.  Hopefully I did it correctly.
