### ISSUE TITLE
service_check

### ISSUE THREAD

**Issue by trekkim** [munkireport/munkireport-php#422]
Hi i have this issue on client site
Starting...
    Performing preflight tasks...
    preflight stderr: WARNING: Munkireport: service_check return code: 1
Checking for available updates...

Maybe some one knows this , thx

**Comment by bochoven** [comment]
Don't install the service_check module unless you want to report on a server. See also

https://github.com/munkireport/munkireport-php/wiki/Modules#module-descriptions

**Comment by trekkim** [comment]
thx
