### ISSUE TITLE
The accounting of the number of client seems false

### ISSUE THREAD

**Issue by lolipale** [munkireport/munkireport-php#426]
I tried to start with a blank database.
But, the numbers of clients seems false ... 8 customers instead of 5
See the screenshot ... Any idea ?
![screenshot 2016-03-09](https://cloud.githubusercontent.com/assets/13834698/13638510/dec3da76-e60c-11e5-904c-7e3688d19dea.png)

**Comment by bochoven** [comment]
Munkireport adds clients on preflight, but sends other reports on postflight. You might see a difference because of this. If munki fails to run (can't reach the munki server) postflight does not get triggered.

**Comment by lolipale** [comment]
Thanks for the explanation.
And sorry for the inconvenience !
Have a nice day

**Comment by bochoven** [comment]
No problem!
