### ISSUE TITLE
Migration error: reportdata: SQLSTATE[HY000]: General error: 1 duplicate column name: uptime

### ISSUE THREAD

**Issue by lolipale** [munkireport/munkireport-php#431]
Hello,
I start with a blank database for this version of munkireport (v.2.8.2).
I have this message when I want to show some listing :
<img width="1399" alt="screenshot" src="https://cloud.githubusercontent.com/assets/13834698/13694360/e82c6ee0-e754-11e5-835a-b66768810e7d.png">
Any idea ?
Thanks for your help and support

**Comment by bochoven** [comment]
Are uou sure the database does not contain any tables?

**Comment by lolipale** [comment]
Hello,

Yes. I started yesterday with a completely new database. 
I have had this problem. This is why I started with a new database because I have less than 100 customers. I thought it will fix the case. But ...

**Comment by bochoven** [comment]
My point is that if you start with a fresh database that you should not see any migration errors because a migration only happens if you upgrade munkireport with an existing database. What database backend do you use?

**Comment by lolipale** [comment]
The database by default : sqlite.db
config.php is set with migration True

**Comment by bochoven** [comment]
Could you remove the database and try again?

**Comment by lolipale** [comment]
Yes. Of course ... But I will have some results only on next monday.
All my users went skiing today ... except me ;-)

**Comment by bochoven** [comment]
Any news?

**Comment by lolipale** [comment]
Hello,
Sorry for the delay ...
Currently, I cannot reproduce this issue. You can close this case
Thanks a lot for your patience

**Comment by bochoven** [comment]
No problem!
