### ISSUE TITLE
Historic Munki Errors

### ISSUE THREAD

**Issue by childrss** [munkireport/munkireport-php#432]
It would be handy to have a history of munki client errors for a machine to be able to see if it's an error that reoccurs every run, or just periodically.  Also a means of acknowledging the error (and resolution, and tech id) would be swell.  Aggregating the same errors would be ideal, e.g. 

```
 Softwareupdate error 100 (3)
 Rejected item MSExcel 2016 min os required 10.10.0 (50)
```

Thanks so much for the best reporting out there!

**Comment by bochoven** [comment]
I think munkireport is not suitable for dealing with historic data. It may be smarter to use something like logstash (which has a SQL handler)
