### ISSUE TITLE
After updating Munkireport summary tab of clients has no values

### ISSUE THREAD

**Issue by snowwalker1988** [munkireport/munkireport-php#437]
After updating Munkireport to version 2.8.4 the summary tab of clients has no values.
Allow for migrations of database $conf['allow_migrations'] = TRUE; is set.

**Comment by bochoven** [comment]
What version did you migrate from?

**Comment by snowwalker1988** [comment]
From version 2.7.3

**Comment by bochoven** [comment]
Could you check the error console in your browser?

**Comment by snowwalker1988** [comment]
There is only a warning:
maps.googleapis.com/maps-api-v3/api/js/24/3/intl/de_ALL/util.js:218 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys

**Comment by bochoven** [comment]
What if you visit

http://YOURSERVER/MUNKIREPORTPATH/index.php?/clients/get_data/SERIAL_NUMBER

**Comment by snowwalker1988** [comment]
Then i get:
Uncaught Exception: SQLSTATE[HY000]: General error: 1 no such table: security

**Comment by bochoven** [comment]
And can you view the security listing?

http://YOURSERVER/MUNKIREPORTPATH/index.php?/show/listing/security

**Comment by snowwalker1988** [comment]
No then i get the same mistake as above.

**Comment by bochoven** [comment]
Did you enable debug? You might have a permissions issue if you're using SQLite.

**Comment by snowwalker1988** [comment]
Now I enabled it in config.php.
Where can I see such errors and the results of debug enabled?
Sorry that is new for me.

**Comment by bochoven** [comment]
Visit the url mentioned above, does it give more info?

**Comment by snowwalker1988** [comment]
No there aren't more informations.
But I looked with an SQLLite Browser into the database and there aren't no security and no munkiinfo table.

**Comment by bochoven** [comment]
Make sure your webbrowser has write access to db.sqlite *and* the enclosing directory

**Comment by snowwalker1988** [comment]
Thanks for this hint with the enclosing directories.
After the update the right of the _www user was missing on the file share in the OS X server app.
Now I can see all values.

I also have another question, but for another topic. Maybe it is better to open a new issue?
I want to update the clients with the new munkireport.pkg for the new version.
For other Apps in Munki I use the installs key to show Munki the version changes.
But for the munkireport.pkg I think this is not possible or?
Do you have an example as you would make it?

**Comment by bochoven** [comment]
For overriding the version, please look here: https://github.com/munkireport/munkireport-php/wiki/Client-setup#setting-up-clients-with-munki-pkg
