### ISSUE TITLE
Documentation edit:  adding new users

### ISSUE THREAD

**Issue by childrss** [munkireport/munkireport-php#438]
Under "Create first user" if we could put something ala the following:

After initial setup, additional new users can be created by going to this URL on the website

   http://server/munkireport-php/index.php?/auth/generate

And then adding the resulting string to your configuration file.

Thanks!

**Comment by bochoven** [comment]
The wiki is open for editing!

**Comment by childrss** [comment]
Ahh.. oops.

**Comment by childrss** [comment]
And done. Please edit to taste ;-)  Thanks bochoven!

**Comment by bochoven** [comment]
Thank you sir!
