### ISSUE TITLE
Documentation:  broken link

### ISSUE THREAD

**Issue by childrss** [munkireport/munkireport-php#439]
http://munkireport.github.io/munkireport-php/ linked to off the main github source repository takes you to a page that has a link that is 404'ing:

     Setup
         Setup is easy, you could be running your own reportingserver within minutes!
         Please read the install manual

The link to the install manual (http://munkireport.github.io/munkireport-php/docs/setup.md) is broken/404.

**Comment by bochoven** [comment]
We should also abandon the docs directory and document in github.
