### ISSUE TITLE
wifi update table module error

### ISSUE THREAD

**Issue by ghost** [munkireport/munkireport-php#445]
When enabling the wifi module and having migration set to True in the configuration; the wifi module has an issue updating the table when running the managed software center client check for updates.

Server An error occurred while processing: Wifi_model
Server Error: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'agrctlrssi' at row 1
Server info: starting: wifi

**Comment by tuxudo** [comment]
What version of MunkiReport are you using? This was fixed in the bug fix branch, but may not have made it to the 2.8 branch. Try using the bug fix branch and see if that resolves your problem. You may have to update the clients to fully fix it.

**Comment by computeronix** [comment]
MunkiReport Version 2.8.4.1826

Just updated our production server today :)

**Comment by tuxudo** [comment]
You're going to have to use the bug fix branch. The master branch doesn't have the WiFi bug fix merged into it yet.

**Comment by computeronix** [comment]
sounds good thanks!  will leave this opened till merged

**Comment by tuxudo** [comment]
You may want to close this issue, the bugfix branch was merged into the master branch a few days ago.
