### ISSUE TITLE
Location Module (noob)

### ISSUE THREAD

**Issue by computeronix** [munkireport/munkireport-php#446]
Just enabled the location module however our clients receive this information in the table: pinpoint has not ran or been installed

What else needs to be done to get this working :)

I looked around but did not see anything in the manuals

**Comment by bochoven** [comment]
https://github.com/munkireport/munkireport-php/blob/master/app/modules/location/README.md

**Comment by computeronix** [comment]
Thank you so much!! didn't look deep enough :)
