### ISSUE TITLE
CSS does not take into account menubar filter icon

### ISSUE THREAD

**Issue by MichalMMac** [munkireport/munkireport-php#448]
Minor problem with CSS.

![screen shot 2016-03-26 at 23 32 51](https://cloud.githubusercontent.com/assets/3882687/14062758/1ac9b76a-f3ab-11e5-8266-f252f47b3d49.png)

**Comment by bochoven** [comment]
I think we may need to rearrange the top menubar items. The language switch can be incorporated in the user dropdown, perhaps the filter icon too.
