### ISSUE TITLE
Feature request: show Apple SUS prefs

### ISSUE THREAD

**Issue by mattiasvdm** [munkireport/munkireport-php#450]
I'd like to be able to see the Apple SUS prefs in MunkiReport. Maybe this info could be placed in the Reports - Configuration report.

These prefs I have in mind:

/Library/Preferences/ManagedInstalls SoftwareUpdateServerURL
/Library/Preferences/ManagedInstalls InstallAppleSoftwareUpdates (true or false)
/Library/Preferences/com.apple.SoftwareUpdate CatalogURL

**Comment by MichalMMac** [comment]
I belive all of those featurea are actually included in 2.8.4 `munkiinfo` module. I have small [issue](https://github.com/munkireport/munkireport-php/pull/449) with `CatalogURL` but apart from that I can see all information in question.

**Comment by mattiasvdm** [comment]
You're right, I see it now. I was on an older version. Thanks, this is very useful.
