### ISSUE TITLE
Migration error: reportdata: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'uptime'

### ISSUE THREAD

**Issue by mattiasvdm** [munkireport/munkireport-php#451]
Hello,

I've got this error when I set `$conf['allow_migrations'] = True`. I've seen this error before and I wonder if there's a way to fix this without creating a new database.

I'm using mysql and MR version 2.8.4.1826 although this error appeared on the previous versions.

**Comment by bochoven** [comment]
Somehow (maybe by running a beta version) your database got out of sync with Munkireport. You can fix this error by telling munkireport that the table for report data is up-to-date. Use an SQL program to run the following query:

```sql
UPDATE migration SET version = 2 WHERE table_name = 'reportdata';
```

**Comment by mattiasvdm** [comment]
Thanks! The error is gone but now there's a new one...

Migration error: reportdata: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'machine_group'

Not sure how the DB got out of sync by the way, haven't used a beta version. I did switch to mysql 2 months ago but I rebuild the DB from scratch.

**Comment by bochoven** [comment]
Ok, reportdata should be on version three:

```sql
UPDATE migration SET version = 3 WHERE table_name = 'reportdata';
```

**Comment by mattiasvdm** [comment]
Yes, that did the trick. Is there somewhere I can find the current versions? Could come in handy if I run into this again.

**Comment by bochoven** [comment]
All models have a schema version: https://github.com/munkireport/munkireport-php/blob/master/app/modules/reportdata/reportdata_model.php#L19

But you should not run into this issue at all.
