### ISSUE TITLE
Filter Window Needs Check All/Uncheck All buttons

### ISSUE THREAD

**Issue by bryanzak** [munkireport/munkireport-php#457]
Our school district has more than 80 schools, we use groups and the "passphrase" key to assign each of them a unique key so that building techs can look at just specific buildings by using the filter.

However, checking or unchecking 80 boxes is tedious. A Check All and Uncheck All would improve the quality of life when using this window.

**Comment by bochoven** [comment]
Should be addressed with de2fc04f491b8cededdf612f9862b0386804352a

**Comment by bryanzak** [comment]
Just tested the wip branch on a test machine and seemed to work fine -obviously not my production server with 80+ groups, but in limited testing seems to work as intended so far.
