### ISSUE TITLE
Issues with multiple filters

### ISSUE THREAD

**Issue by MichalMMac** [munkireport/munkireport-php#460]
Our client with user access to munkireport found few issues with filtering:

- clicking on **Installed Memory** -> **4GB+** does not include machines with 4GB
    /munkireport/index.php?/show/listing/hardware/#5GB%20memory%207GB
Is this by design? (5GB memory 7GB)

- **Hardware Report** -> **External Display Count** gives me listing with **ALL** displays (even Apple built-in LCDs)
    munkireport/index.php?/show/listing/displays

- **Hardware Report** ->  **Hardware Age** -> **some year** gives me listing with all clients. This should be described in issue #364 
    munkireport/index.php?/show/listing/warranty

- **Munki Report** -> **Munki Protocol** -> **something** gives me listing with all clients
     munkireport/index.php?/show/listing/munki

**Comment by bochoven** [comment]
I fixed the first 2 issues in the wip branch. The third issue is a duplicate. Please file a separate issue for the last one.

**Comment by MichalMMac** [comment]
Thank you. 
Done. Issue for last one is #462
