### ISSUE TITLE
Munki Protocol filter does not work

### ISSUE THREAD

**Issue by MichalMMac** [munkireport/munkireport-php#462]
When click on: Munki Report -> Munki Protocol -> something
Result is listing with all clients (munkireport/index.php?/show/listing/munki)
It should be probably filtered.

This issue was separated from #460

**Comment by erikng** [comment]
Not to beat a dead horse, but this feature was initially in my original work and removed. I won't have time to work on it, (for the foreseeable future) but perhaps someone else can.
