### ISSUE TITLE
Manually send data 

### ISSUE THREAD

**Issue by adambarnett52** [munkireport/munkireport-php#465]
Hi

Not really an issue. but i am trying to figure out how clients send data to munkireport
Is there a manual cli i can use to send the data? 

I am trying to push  data from a non OSX machine into MPR 

Thanks
Adam

**Comment by clburlison** [comment]
MR is mainly using CURL to send the data back to the database. See: https://github.com/munkireport/munkireport-php/blob/master/assets/client_installer/reportcommon#L56-L130

It might be possible to do what you want using the API? Although the following examples are retrieving data it might be possible to upload data as well (I haven't looked very closely into this). https://github.com/munkireport/munkireport-php/wiki/API

**Comment by adambarnett52** [comment]
Thanks
