### ISSUE TITLE
Question first use

### ISSUE THREAD

**Issue by zesa111** [munkireport/munkireport-php#470]
Hello guys,

i have different questions and hope that u can help me.

1.  I couldn't use munkireport.pkg, i created and install it manually (also without MSC) but It doesn't work. It works only with sudo /bin/bash -c "$(curl -s http://example.com/index.php?/install)"
Do you have any idea?

2. When reported munki to the server? Is it possibile to do that f.e. every 12 hours? f.e. when anyone disable Bluetooth? I notice that munki report is updated when I install software by MSC.

3. IPv6 vs. IPv4, when I want to use vnc / ssh over munki , I always take IPv6 what doesn't work in my network. Also I take IPv6 under Remote IP Adresse.
How can I change it in Ipv4? 

Thanks.
<img width="490" alt="example" src="https://cloud.githubusercontent.com/assets/15154678/14579819/6cbc17c6-03b8-11e6-96fc-0a0c0ace494a.png">

**Comment by bochoven** [comment]
Please ask questions on the munkireport mailinglist:

http://groups.google.com/group/munkireport

Github issues are for bugs and enhancement requests
