### ISSUE TITLE
Lot of httpd processes

### ISSUE THREAD

**Issue by mattiasvdm** [munkireport/munkireport-php#471]
Hi,

This is probably not really a munkireport issue, but I hope you guys can help out.

I've got two Mac Mini's running MunkiReport.

Mac Mini 1:
10.10.5
2,3 GHz i5 4GB
Number of clients: aprox 100

Mac Mini 2:
10.10.5
2,6 GHz i5 8GB
Number of clients: aprox 300

Both use a MySQL database for MR. Both Macs are also used for Munki and Apple SUS. So they have a similar setup. Only the hardware is slightly different and the number of clients differ.

Mac Mini 1 weekly shows almost 300 httpd processes and at the same time also around the same number of xssendevent processes. At that time my monitoring system begins to send out warnings that it can't reach the MR site and the Munki repo. I've compared the web preferences and the seem similar. Rebooting the server solves the problem for another week.
Mac Mini 2 with a triple number of clients never shows any problems regarding httpd.

I've searched Google but most of these problems occur on Linux systems which are slightly different. My knowledge about Apache is limited so I'm not sure where to look.

Hope you guys can help.

**Comment by bochoven** [comment]
Hi Matthias,

We would like to reserve the github issues for bugs and enhancement requests. If you want to discuss your issue, please post it to http://groups.google.com/group/munkireport
