### ISSUE TITLE
Preflight Script Timeout moved to config file varible

### ISSUE THREAD

**Issue by childrss** [munkireport/munkireport-php#472]
Please move the preflight script timeout to a variable that can be configured in the main config file.  It would be nice if this could be set "per script" but just being able to increase it outside of the main code (so updates don't nuke the change) would be good enough for now.

Thanks!

[Line 275/276 in reportcommon](https://github.com/munkireport/munkireport-php/blob/master/assets/client_installer/reportcommon#L275)

**Comment by bochoven** [comment]
Adding a pref to //L/P/Munkireport.plist should be enough.

**Comment by ofirgalcon** [comment]
Is this the correct syntax for config.php ?

$conf['scriptTimeOut'] = '30';

**Comment by bochoven** [comment]
No, you should add that preference to the client:

```
defaults write /Library/Preferences/MunkiReport scriptTimeOut 30
```
