### ISSUE TITLE
Ambiguous User / Group Filter variable names in config_default.php

### ISSUE THREAD

**Issue by lfitzsimmons** [munkireport/munkireport-php#474]
in config_default.php: 

`$default_conf['userfilter']  = '(&(uid=%{user})(objectClass=posixAccount))'; // LDAP filter to search for user accounts.
$default_conf['groupfilter'] = '(&(objectClass=posixGroup)(memberUID=%{uid}))'; // LDAP filter to search for groups.`

Variables should be named:

$conf['auth']['auth_ldap']['groupfilter'] 
$conf['auth']['auth_ldap']['userfilter']

**Comment by bochoven** [comment]
This was already fixed here https://github.com/munkireport/munkireport-php/commit/b22d9d6d6d8990737261217e94d9f169b24ab1b0
