### ISSUE TITLE
Inventory path character limit of 255

### ISSUE THREAD

**Issue by poundbangbash** [munkireport/munkireport-php#478]
Due to autopkg being on my machine it has some long path names to applications like "/Users/eholtam/Library/AutoPkg/Cache/com.github.poundbangbash.eholtam-recipes.pkg.SuspiciousPackageApp/SuspiciousPackageAppPkg/Applications/SuspiciousPackage.app/Contents/Library/QuickLook/SuspiciousPackage.qlgenerator/Contents/SharedSupport/UpdateCheckerHost.app" which is 266 characters.  With that in my home directory I get the following when munkireport tries to report the inventory back in.

```
 Munkireport: Server info: starting: reportdata
Server An error occurred while processing: Inventory_model
Server Error: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'path' at row 1
Server info: starting: inventory
```

As a workaround I've added `$conf['bundlepath_ignorelist'] = array('.*/Library/AutoPkg.*');` to config.php but it may be worth looking at increasing the path character limit and if it impacts db speeds.

**Comment by LukeAndrews** [comment]
I ran the following command on my MySQL db to fix it:
`ALTER TABLE inventoryitem MODIFY path VARCHAR(512);`
