### ISSUE TITLE
AppVersion detail listings don't respect machine group filters

### ISSUE THREAD

**Issue by bryanzak** [munkireport/munkireport-php#484]
We have 80+ machine groups: one for each school

We have Microsoft Word as an app to report version info on in Report > AppVersions

If I configure the machine group filters to show just one school and then go to Report > AppVersions it properly shows the number of each version of Word installed at that one school. (For example 395 instances of version 14.6.3 and 6 of version 14.6.2).  If I then click the 14.6.2 entry in that report, it opens a listing for 14.6.2, but shows me ALL computers in our MunkiReport with 14.6.2, not just the six from the one school that I've set as my machine group filter.

This is MR 2.9.0.1983

**Comment by bochoven** [comment]
Inventory is using retrieve_many:

https://github.com/munkireport/munkireport-php/blob/master/app/modules/inventory/inventory_controller.php#L57-L60
