### ISSUE TITLE
Question: See changes 

### ISSUE THREAD

**Issue by adambarnett52** [munkireport/munkireport-php#488]
Hi All

This is more of a question, than a issue
We are currently updating our fleet to 10.11. Is there a way of seeing which machine that have check in  in say the last 24 hour have been upgrade?

They will not appear in the new client widget as they already exist in MR 

Thanks

PS: how do i tag it as a question?

**Comment by bochoven** [comment]
Hi Adam,

please ask questions in the mailing list for munkireport:

http://groups.google.com/group/munkireport

-Arjen

PS I do the tagging :-)

**Comment by adambarnett52** [comment]
will do
