### ISSUE TITLE
Profiles Query

### ISSUE THREAD

**Issue by homer7198** [munkireport/munkireport-php#491]
The profile query for the profile listing view takes an extremely long time. Processing this query takes an average of 10min and maxes all CPU usage. I'm guessing because my profiles table has 50,000 rows but only 30 unique types of profiles so the counts for each profile takes a ridiculous amount of processing. 

`profile_name, (select COUNT(DISTINCT serial_number) from profile p2 where profile.profile_name = p2.profile_name) AS num_profiles, payload_name, serial_number, GROUP_CONCAT(payload_data) as payload_data', '1 GROUP BY profile_name, payload_name, serial_number`

**Comment by bochoven** [comment]
Should be fixed with d11586e2390cabe51251a5b1ff5b86e01d680b32
