### ISSUE TITLE
Migration error in WIP

### ISSUE THREAD

**Issue by fridomac** [munkireport/munkireport-php#503]
Hello!
Maybe only my install, but I get a migration error when using the current WIP (2.9.2009):

`Migration error: munkireport: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'report_plist' in 'where clause'`

Can I do something to fix that?

Bye, Frido.

**Comment by bochoven** [comment]
Should be fixed in the latest wip, could you please confirm?

**Comment by fridomac** [comment]
Yes, its is fixed... Thank you!
