### ISSUE TITLE
-0400 ERROR: Munkireport: The certificate for this server is invalid

### ISSUE THREAD

**Issue by nlscott** [munkireport/munkireport-php#506]
I just updated from version 2.4.2 to 2.85. My client is running munki 2.7.0.2753 on OS X 10.11.5

When I run Managed Software Center on a client I get the following errors and client doesn't report back to MunkiReport.

> Jul 12 2016 12:06:14 -0400 ERROR: Munkireport: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “munki.kenyon.edu” which could put your confidential information at risk.

When I run "sudo /usr/local/munki/managedsoftwareupdate -vvv" I get this error and the client never reports back to MunkiReport:

> Performing postflight tasks...
>     postflight stdout:     Munkireport: # Executing scripts in postflight.d
>     Munkireport: Requesting munkireport
>     Munkireport: connection_willSendRequestForAuthenticationChallenge_
>     Munkireport: Authentication challenge for Host: munki.kenyon.edu Realm: None AuthMethod: NSURLAuthenticationMethodServerTrust
>     Munkireport: Allowing OS to handle authentication request
>     Download error -1202: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “munki.kenyon.edu” which could put your confidential information at risk.
>     Munkireport: SSL error detail: (-9813L, u'Cert chain not verified by root')
>     Munkireport: Headers: None
>     postflight stderr: 2016-07-12 11:52:55.799 Python[82823:4097913] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9813)
> ERROR: Munkireport: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “munki.kenyon.edu” which could put your confidential information at risk.
> Done.

If I run sudo /usr/local/munki/preflight --debug, I see this:

  

>   Munkireport: # Executing scripts in preflight_abort.d
>     Munkireport: # Executing scripts in preflight.d
>     Munkireport: Running submit.preflight
>     Munkireport: submit.preflight Error: 2016-07-12 12:38:34.070 Python[3141:45326] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9813)
> ERROR: Munkireport: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “munki.kenyon.edu” which could put your confidential information at risk.
> 

It seems to suggest that the certificate for the MunkiReport is invalid? I'm using a self-signed cert for https traffic that doesn't expire until 2018. I'm not using client certificates for munki.

I don't get this error on my clients running MunkiReport 2.4.2. If I uninstall 2.8.5 and reinstall 2.4.2 my client goes back to checking into MunkiReport with no error messages. Any ideas on how I can troubleshoot this?

**Comment by bochoven** [comment]
You need to 'trust' this cert on the client. You would see the same error when visiting your munkireport server in Safari.

-Arjen

**Comment by nlscott** [comment]
I got a clean machine, just imaged. installed munki and munkireport 2.4.2. Pulls software from munki and checks into munkireport. No issues.

I installed 2.8.5. and Then added the certificate to the system key chain on the client and trusted it. So I can log into the web interface for munkireport with no certificate warnings, but running munki I get the same errors in the Managed Installs logs, and it never runs the postflight for munkireport.

I have not trusted the cert on my other clients in the field and they don't have an issue reporting back to munkireport. But all of them are using 2.4.2. It's only the 1 test client with 2.8.5.

**Comment by bochoven** [comment]
You may have something not set up properly with the certificate. If you get the self-signed CA root certificate properly into the client system keychain, munkireport should work without issue.
What OS version is your client?

**Comment by nlscott** [comment]
Client is OSX 10.11.5. But I have about 40 other machines on 10.11.5 that are checking in. And about 250 clients in total.

It's strange because it's not a new cert. it got renewed in May of this year. So it's been in use for over 2 years and I've never had an issue with it. 

Reading some post about munki, there was a conversation about moving from curl to NSURLSession, and how the checking for NSURLSession is stricter when it comes to certs?

Since I'm not using the cert for client authentication for munki, only to secure web traffic to munkireport. At some point I can blow the cert away and create a new one. But that may take me a couple weeks.

**Comment by bochoven** [comment]
Munkireport moved to NSURLSession in 2.6.0 because of better support for TLSv1.2.

**Comment by bochoven** [comment]
I'm closing this, if you need more help setting up the certificates, please ask in munkireport@googlegroups.com
