### ISSUE TITLE
Crashplan module displaying Nil value destination over destination with populated values. 

### ISSUE THREAD

**Issue by weswhet** [munkireport/munkireport-php#507]
Currently the crashplan module returns only one backup destination in the GUI. Sometimes one of the destination can contain a bunch of nil values for backup times even though there is a valid backup destination with good values. We should probably chose to skip a destination if it contains nil values when a destination with real values is present. The below log file will create a false backup destination with values of `[1],0,0,0,0,`

`I 07/12/16 02:23PM [wesbooktest15 Backup] Scanning for files to back up
I 07/12/16 02:23PM [1] Scanning for files stopped
I 07/12/16 02:23PM [1] Configured to backup the following:
I 07/12/16 02:23PM  + /Users
I 07/12/16 02:23PM * but will NOT backup the following:
I 07/12/16 02:23PM  - /Users/wes/Library/Caches
I 07/12/16 02:23PM [1] Scanning for files to back up
I 07/12/16 02:23PM [1] Scanning for files stopped`

**Comment by weswhet** [comment]
@bochoven this works much better but the crashplan.backup_failed event can be rather spammy especially if it gets call on a failed backup reason of 'Nothing to do' My entire event feed is nothing but failed crashplan backup events. :(

**Comment by bochoven** [comment]
Could you open a new issue for that?
