### ISSUE TITLE
Track ARD and SSH Access 

### ISSUE THREAD

**Issue by gmarnin** [munkireport/munkireport-php#509]
New a new module to report on which users have ARD and SSH access. Maybe this data could be apart of the security module.

**Comment by rickheil** [comment]
The SSH access would fit well as part of Security. Would the ARD parts fit with the existing ARD module or within Security? I'm taking a stab at this.

**Comment by gmarnin** [comment]
Oh nice. Good question. It think as part of security. The current ARD data is just text info fields 1-4.

**Comment by rickheil** [comment]
See PR #582 for these changes.
