### ISSUE TITLE
Location Map reports requires Google Apps API Key

### ISSUE THREAD

**Issue by bgradidge** [munkireport/munkireport-php#510]
Google maps now requires an API key to be entered for using their maps feature as outlined here: https://developers.google.com/maps/documentation/javascript/get-api-key#key , we'll need a way to neatly enter this into the config file.

Map feature will look like the attached when currently loaded 
![munkireportslocationmaperror](https://cloud.githubusercontent.com/assets/14946293/17120378/b6425506-5280-11e6-8314-a3d2d73ebdd0.png)

**Comment by bgradidge** [comment]
This is probably working for 99% of people out there -- turned out to be related that I was hosting it on an amazon ec2 instance which had it flagged by google apps

Still would be super useful to put the API key into the config file.

Future generations setting it up, you want to go to here: https://console.developers.google.com, create a project, and get a BROWSER api key and whitelist your site

**Comment by bochoven** [comment]
Could you confirm 89ee8acd6b1376b5817f03cc02788aceaa769014 is working for you?

**Comment by bgradidge** [comment]
Sure is!
