### ISSUE TITLE
10.11.6 getting ImportError: No module named munkilib

### ISSUE THREAD

**Issue by TryTryAgain** [munkireport/munkireport-php#512]
Is this a known issue? Installing munkireport via pkg or the curl method works for all previous OS's and I've verified again using the same 2.8.5 munkireport version on them. With 10.11.6 though, I'm getting an ImportError, not sure why. Tried using brew to get another python to see if that would help to no avail.

Output from running curl method:
```
...
...
+ Installing wifi
Setting preferences
Installation of MunkiReport v2.8.5 complete.
Running the preflight script for initialization
Traceback (most recent call last):
  File "/usr/local/munki/preflight", line 6, in <module>
    from munkilib import reportcommon
ImportError: No module named munkilib
```

Also, it is in fact in the python path:
```
>>> import sys
>>> print sys.path
['', '/usr/local/munki',
```

**Comment by bochoven** [comment]
Does munki run on that machine?

**Comment by TryTryAgain** [comment]
It does not, the preflight fails and nothing gets initialized to run. I've tried manually running in many ways as well. Tried importing from sys paths manually. Turned of verbose logging, not seeing anything.

**Comment by bochoven** [comment]
Does /usr/local/munki/munkilib exist?

**Comment by TryTryAgain** [comment]
It does, everything that comes before the preflight works and "Installation of MunkiReport v2.8.5 complete." comes after all the files are actually put in place, permissions changed what have you, logs look good, dirs/files look good.

**Comment by TryTryAgain** [comment]
Just tried upgrading a known to work 10.11.5 machine to 10.11.6 and it does not experience the same problem. Must be in the new build, it's quite bare. Possible I'm missing some dependencies?

**Comment by bochoven** [comment]
The only dependency should be a correctly installed munki. If you remove the preflight script, does managedsoftwareupdate execute normally?

**Comment by TryTryAgain** [comment]
Hmm, I thought that was part of the preflight/postflight setup, managedsoftwareupdate doesn't exist.

**Comment by TryTryAgain** [comment]
Only reference in logs that's related, I'm guessing, is this: 7/28/16 1:44:33.994 PM com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.domain.system) Service "com.apple.ManagedClient.startup" tried to hijack endpoint "com.apple.ManagedClient.agent" from owner: com.apple.ManagedClient

**Comment by bochoven** [comment]
You need to install munki first, then munkireport. If managedsoftwareupdate does not exist, munki is not correctly installed.

**Comment by TryTryAgain** [comment]
Oh my, been a while since I've had a bare base given to me. Thank you, all good. Sorry about that.

**Comment by bochoven** [comment]
No problem!
