### ISSUE TITLE
runCheck error

### ISSUE THREAD

**Issue by pkpowell** [munkireport/munkireport-php#515]
My notifications don't seem to update the way they used to. I just get the odd warning message (always from the same client), but no 'Installed' messages. This is on wip, MunkiReport Version 2.9.0.2042.
This message appears in the console every couple of seconds:

```[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (index.php, line 0)  http://osx.pkpowell.net/index.php?/module/notification/runCheck ```

The 'Pending Installs' info also looks stale.
Any idea how I can get the events back?

Cheers
Phil

**Comment by bochoven** [comment]
The runCheck message should not influence the events listing on the dashboard. Did you enable migrations when updating to the latest wip? There is a extensive change regarding the way munkireport stores information about managed installs.

**Comment by pkpowell** [comment]
Oh, that could be it.

Do I just add  "$conf['allow_migrations'] = TRUE;”?
Just tried that on my private Munkireport but nothing changed .

**Comment by bochoven** [comment]
You should check the munkireport listing page.

-=Arjen

**Comment by pkpowell** [comment]
Hey Arjen

Data seems to be coming in, but I never saw the popup you usually get when a db migration occurs (tried this on two munkireport-servers). Is there an other way to 'jump-start' the migration?
I still only get warning events, and "Pending Installs" etc don't seem to update.
Both of these servers run on OpenShift, so I had a quick look at phpMyAdmin there and it has this warning:

Your PHP MySQL library version 5.1.73 differs from your MySQL server version 5.5.50. This may cause unpredictable behaviour.

Do you think it's related, or is that just a phpMyAdmin warning? The server's running PHP 5.4 and MySQL 5.5. 
It's been like that ever since I set things up and been running great until recently.

**Comment by bochoven** [comment]
Oh, you *need* to be an admin for this migration. It won't happen on a regular account.

-Arjen

**Comment by pkpowell** [comment]
I'm pretty sure I'm admin.

I have this in config.php

$conf['authorization']['delete_machine'] = array('admin', 'manager');
$conf['authorization']['global'] = array('admin');
$conf['roles']['admin'] = array('phil');
$conf['groups']['admin_group'] = array('phil');
$auth_config['phil'] = 'xxxxxxxxxxxx';

There's just the one user, and I can see the 'Admin' menu when I log in.

btw I also enabled 
$conf['debug'] = TRUE; 
at one point, but get no debug information (as far as I can tell).
It's as if some of the config settings are being ignored!

I created a regular user just for kicks, and this user displays no data when I log in, just empty panels!
Is a user with no role a regular user? I guess I don't really understand the user-system...
(the user config above has worked for me for the last couple of years)

**Comment by bochoven** [comment]
In phpMyAdmin, can you check if
- The table managedinstalls exists and contains data
- In the migrations table the munkireport table is on version 4

**Comment by pkpowell** [comment]
Both check out.
Could I re-trigger migration by setting the munkireport migration vers. to 3, or is that asking for trouble?

I checked the events table, and it seems like quite a few of the timestamps are from last November (see below). The current warnings also aren’t listed there.

The data in 'install history’ and a few other tables I checked is current!

**Comment by bochoven** [comment]
So do you aee new data in the  managedinstalls table?

**Comment by pkpowell** [comment]
Hey Arjen

The data seems to be current/up to date for the most part (only for some machines).
So I checked the modules segment in config.php for “managedinstalls" and it wasn’t there!
I added it in and it looks like things are back to normal.
It’s all a bit weird because I really don't remember changing anything in config.php before a few days ago when it all started, especially not on two servers. I guess it must have been a silly copy/paste ‘incident’ a while back…

Anyway thanks for your time and patience

Cheers
Phil

**Comment by bochoven** [comment]
> On 12 Aug 2016, at 19:45, Philip Powell <notifications@github.com> wrote:
> 
> The data seems to be current/up to date for the most part (only for some machines).
> So I checked the modules segment in config.php for “managedinstalls" and it wasn’t there!
> I added it in and it looks like things are back to normal.

I still don't know what caused your issue but here's some background info on the managedinstalls module:

If you want to take advantage of the new managedinstalls module, you should push a new client installer to your clients containing at least managedinstalls *and* munkireport.
Meanwhile, the managedinstalls module receives data from the munkireport module in 'legacy mode', which means that clients that don't have the new munkireport and managedinstalls scripts are still reporting correctly.

-Arjen

**Comment by pkpowell** [comment]
ah, so ‘legacy mode’ somehow wasn’t working in my case.

I have a question re updating the clients.
What I usually do is create a pkg like so:

bash -c "$(curl http://fqdn/index.php?/install)" bash -v [current munkireport version] -i ~/

and import it into munki the usual way and it installs, but when I look in /usr/local/munki on the client the file munkireport-x.x.x will often be terribly outdated (see below). 

If on the other hand I do 
sudo bash -c "$(curl http://fqdn/index.php?/install)” on the client, the file will be updated ('munkireport-2.9.0’).

Is there something wrong with the way I’m generating the munkireport update pkg?

Cheers
Phil

-rwxr-xr-x   1 root  wheel   8.2K Aug 14 10:51 iconimporter
-rwxr-xr-x   1 root  wheel   2.2K Aug 14 10:51 launchapp
-rwxr-xr-x   1 root  wheel   7.5K Aug 14 10:51 logouthelper
-rwxr-xr-x   1 root  wheel    15K Aug 14 10:51 makecatalogs
-rwxr-xr-x   1 root  wheel    47K Aug 14 10:51 makepkginfo
-rwxr-xr-x   1 root  wheel    42K Aug 14 10:51 managedsoftwareupdate
-rwxr-xr-x   1 root  wheel    37K Aug 14 10:51 manifestutil
-rwxr-xr-x   1 root  wheel    45K Aug 14 10:51 munkiimport
drwxr-xr-x  42 root  wheel   1.4K Aug 14 12:08 munkilib
-rw-r--r--   1 root  wheel     0B Jul 20  2015 munkireport-2.5.0
drwxr-xr-x   3 root  wheel   102B Aug 10 23:55 munkireportlib
-rwxr-xr-x   1 root  wheel   2.2K Aug 14 11:49 postflight
drwxr-xr-x   3 root  wheel   102B Aug 14 12:08 postflight.d
-rwxr-xr-x   1 root  wheel   1.1K Aug 14 11:49 preflight
drwxr-xr-x  21 root  wheel   714B Aug 14 12:08 preflight.d
drwxr-xr-x   2 root  wheel    68B Aug 14 12:08 preflight_abort.d
-rwxr-xr-x   1 root  wheel   3.1K Aug 14 10:51 ptyexec
-rwxr-xr-x   1 root  wheel   952B Aug 14 11:49 report_broken_client
-rwxr-xr-x   1 root  wheel    11K Aug 14 10:51 supervisor

**Comment by bochoven** [comment]
Using the package installer is the preferred method. The package leaves a receipt behind for versioning. The munkireport-x.x.x file is legacy from the time Munkireport did not use a proper installer package.

**Comment by pkpowell** [comment]
Is there a way to determine the current Munkireport version installed on the client?

I also noticed there seems to be a bit of a time lag between munki runs and events appearing. 
e.g. after a successful install (managedsoftwareupdate ; managedsoftwareupdate --installonly ) the machine will be listed at the top of munki listings, but 'Managed Installs' still lists the files as 'pending'. Then after an extra 'managedsoftwareupdate' the entries update.
The same seems true for 'auto' runs.
Is there a reason for this? 

btw thanks again for an awesome reporting tool!

**Comment by pkpowell** [comment]
that's just for 'munki, not 'munkireport' right?

**Comment by bochoven** [comment]
I'm closing this issue, for general questions about munkireport please use the mailing list.

http://groups.google.com/group/munkireport
