### ISSUE TITLE
Add Captcha Support

### ISSUE THREAD

**Issue by computeronix** [munkireport/munkireport-php#516]
Add Captcha Support to the login screen

Google reCaptcha is free to integrate
https://www.google.com/recaptcha/intro/index.html

**Comment by gmarnin** [comment]
I’m ok with this as long as it’s a configurable option that can be turned off (and off by default).

**Comment by computeronix** [comment]
Ok!  I am adding the code as we speak, will supply a pull once tested

**Comment by computeronix** [comment]
PR 517 takes care of this

https://github.com/munkireport/munkireport-php/pull/517
