### ISSUE TITLE
DeployStudio listing syntax error

### ISSUE THREAD

**Issue by MichalMMac** [munkireport/munkireport-php#525]
I've just upgrade my testing home munkireport setup to 2.9.0 beta.
When accessing DeployStudio listing I get following error every time:

`Create table 'deploystudio' failed: SQLSTATE[HY000]: General error: 1 near "-": syntax error`

DB type is `sqlite`. `allow_migrations` is set to `TRUE`.
I don't use deploystudio module on clients.

**Comment by bochoven** [comment]
We have to replace the dashes (-) in the column names with underscores (_) to be compatible with sqlite
