### ISSUE TITLE
Server Error: SQLSTATE[42S22]: Column not found

### ISSUE THREAD

**Issue by adambarnett52** [munkireport/munkireport-php#533]
Hi 
I have just updated to 2.9.0.2122 and i am getting this error from a client

Server Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'battery_percent' in 'field list'

Also i am not sure if it part of it, but once software was installed the  Managed Installed page still says pending update, even though munki has installed it 

Thanks
adam

**Comment by adambarnett52** [comment]
Ok, i turned on migration again and that error has now gone away, but i am still getting the issue with a pending install is still shown even though it has installed and i have run another munki /usr/local/munki/managedsoftwareupdate

**Comment by adambarnett52** [comment]
This might be why 
 ` Munkireport: /Library/Managed Installs/ManagedInstallReport.plist is missing.`

What generates this?

**Comment by adambarnett52** [comment]
sorry, ignore last comment, that error has now gone, but still getting it shown as pending install on the dashboard

**Comment by clburlison** [comment]
@adambarnett52 You've got at least three things going on in this issue. Let's break them down:

1. As you found this error `Server Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'battery_percent' in 'field list'` was related to you needing to do a migration after the upgrade. 
> Managed Installed page still says pending update, even though munki has installed it

1. The above is a fundamental component to how MunkiReport and Munki operate and function together. When a client checks in with the background daemon it does a full report of all modules updating all of the information. When you ran `/usr/local/munki/managedsoftwareupdate` alone this is considered a manual run which does not upload all information. Please attempt to run `/usr/local/munki/managedsoftwareupdate --auto` and see if that fixes your pending update issue.

1. `Munkireport: /Library/Managed Installs/ManagedInstallReport.plist is missing.` this file is generated by munki. When a run happens this plist is updated. For this file to be missing something weird would have to be going on with your device (from my experience).

**Comment by adambarnett52** [comment]
Hi

Sorry about the confusion

The only out standing issue is that on the dashboard it says pending install, i have tired running `/usr/local/munki/managedsoftwareupdate --auto` but it does not change

**Comment by bochoven** [comment]
If you delete that machine from munkireport, does it get created again when you run managedsoftwareupdate?

**Comment by adambarnett52** [comment]
Yes it does come back, but the Managed Installs section under Manged software is empty

**Comment by bochoven** [comment]
If you installed this client with the updated munkireport scripts, make sure you also have the managedinstalls module enabled. That module is responsible for uploading the managed installs list.

**Comment by adambarnett52** [comment]
So you are right i did not have managedinstalls module enabled, how could i have missed that...
But it still shows `Munkireport Install and config`	as pending

**Comment by adambarnett52** [comment]
never mind, its all good, please ignore, lets call it a Friday thing and move on :P
