### ISSUE TITLE
Postflight Bug 2.9.1

### ISSUE THREAD

**Issue by xinput** [munkireport/munkireport-php#544]
Since the update to 2.9.1 the following error appears in our environment:
`ERROR: Munkireport: http://munki.mycompany.com/index.php?/report/check_in failed, HTTP returncode 500 (internal server error)`

Apache log doesn't record any errors. Turning on debug mode in the MR config.php file ends in this behaviour:
Postflight is completed as it should be but shows following error

```
Munkireport: Server info: starting: reportdata
Server info: starting: munkireport
Fatal error:  Call to undefined function munkireport\module\deploystudio\curl_init() in /var/www/munkireport-php/app/modules/deploystudio/lib/deploystudio_helper.php on line 65
Done.
```

PHP-Curl is installed and active.

BTW: This errors only appear when yopu create a new .pkg with the 2.9.1 server Version. If you use the Installer of Version 2.9.0 it's working fine.

**Server:**
Running: Ubuntu 12.04
PHP 5.5

**Client:**
Tested and Reproduced on OS X 10.11.6 and MacOS Sierra

**Comment by bochoven** [comment]
I investigated the issue and it looks like curl is not (correctly) installed for php. The reference to 'munkireport\module\deploystudio' means that curl_init() cannot be found in the global namespace.

Could you post the result of this one liner?

```php -r 'printf("Curl: %s\n", function_exists("curl_init") ? "Enabled" : "Disabled");'```

**Comment by xinput** [comment]
that's the output of the one liner:

```
root@optimusprime:~# php -r 'printf("Curl: %s\n", function_exists("curl_init") ? "Enabled" : "Disabled");'
Curl: Enabled
```

**Comment by bochoven** [comment]
I wonder how to detect that Curl is not working correctly, did you run the oneliner after you installed `libcurl3` or before?

**Comment by xinput** [comment]
i ran the one liner before i installed `libcurl3`
