### ISSUE TITLE
Dashboard showing incorrect errors?

### ISSUE THREAD

**Issue by nlscott** [munkireport/munkireport-php#545]
I upgraded to Version 2.9.0.2122, a couple days ago. The only thing I moved over was my config.php file. I decided to start a new db.sqlite. Everything seems to be running ok, clients are reporting back. Except the dashboard reports that every client has an error and a warning. So at the moment when I log into the dashboard I see 181 errors and 181 warnings. 

![screen shot 2016-09-15 at 12 24 45 pm](https://cloud.githubusercontent.com/assets/3018699/18558308/9b6bb7ac-7b40-11e6-9048-c26149dd7d1b.png)

But when I click on the errors button to get a break down of the clients with errors. None of the clients checking in have errors listed

![screen shot 2016-09-15 at 12 27 09 pm](https://cloud.githubusercontent.com/assets/3018699/18558339/aeb4f2e2-7b40-11e6-9be6-0534dfce0852.png)

I don't see any errors in the Managed install logs on the clients. Is there is there somewhere else I can look to troubleshoot this further?

**Comment by bochoven** [comment]
You found a bug in the munkireport model. I issued a fix in the master branch, could you test that? You would need to delete the 'munkireport' table and let Munkireport recreate it in the proper format.

**Comment by nlscott** [comment]
I updated to 2.9.1.2146, and I"m getting the same behavior. So far 40
clients checked in and 40 errors on the dashboard.

**Comment by bochoven** [comment]
Please download the latest master https://github.com/munkireport/munkireport-php/archive/master.zip and try again or if you're using git, git pull should also get you the latest version. I bumped the version to 2.9.2.2150

**Comment by nlscott** [comment]
You got it. Thanks.

[image: Inline image 1]

[image: Inline image 2]
