### ISSUE TITLE
Deploy Studio Workflow Does Not Exist

### ISSUE THREAD

**Issue by inventari** [munkireport/munkireport-php#554]
Uncaught Exception: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF3\xB3\x06\x00' for column 'dstudio_last_workflow' at row 1

This happens if the last workflow was deleted or was changed.
The fix would be to check if ($workflow_title != NULL)

**Comment by inventari** [comment]
I submitted a fix that will show the identifier if the workflow no longer exists.

**Comment by tuxudo** [comment]
This was fixed in PR #596
