### ISSUE TITLE
timemachine.sh doesn't work in  macOS Sierra

### ISSUE THREAD

**Issue by szuta** [munkireport/munkireport-php#556]
Possible fix involves using the 'log' command. See http://superuser.com/questions/1126990/how-to-view-time-machine-log-in-macos-sierra/1127145

**Comment by bochoven** [comment]
There's also #513 which tries to accumulate data for multiple TM destinations.

**Comment by szuta** [comment]
Would it make sense to use `tmutil destinationinfo` and `tmutil latestbackup` to get data for both destinations, and last-backup-time? We'd be making an assumption about the format of `tmutil latestbackup`, and also lose backup duration data. If someone OKs that approach, I can possibly work on some code.

**Comment by tuxudo** [comment]
Should be fixed with PR #650
