### ISSUE TITLE
munkireport postflight causing nginx error code 499

### ISSUE THREAD

**Issue by vikaskedia** [munkireport/munkireport-php#562]
As per nginx documentation 499 is for client closing the connection.
Ref: https://httpstatuses.com/499
## Server side inside nginx access-log

172.18.0.35 - - [22/Oct/2016:09:32:33 +0000] "POST /v3/app/munki-report/index.php?/report/hash_check HTTP/1.0" 200 85 "-" "Python/2.7.10 CFNetwork/807.0.4 Darwin/16.0.0 (x86_64)"
172.18.0.35 - - [22/Oct/2016:09:32:43 +0000] "POST /v3/app/munki-report/index.php?/report/check_in HTTP/1.0" 499 0 "-" "Python/2.7.10 CFNetwork/807.0.4 Darwin/16.0.0 (x86_64)"
## Client side

bash-3.2$ time sudo /usr/local/munki/postflight
    Munkireport: # Executing scripts in postflight.d
    Munkireport: Running inventory_add_plugins.py
    Munkireport: Adding 7 plugins
    Munkireport: Running managedinstalls.py
    Munkireport: Running munkireport.py
    Munkireport: Requesting filevault_status
    Munkireport: Requesting location
    Munkireport: Requesting profile
    Munkireport: Requesting ard
    Munkireport: Requesting inventory
    Munkireport: Requesting printer
    Munkireport: Requesting gsx
    Munkireport: Requesting timemachine
    Munkireport: Requesting certificate
    Munkireport: Requesting localadmin
    Munkireport: Requesting directory_service
    Munkireport: Requesting munkireport
    Munkireport: Requesting bluetooth
    Munkireport: Requesting servermetrics
    Munkireport: Requesting disk_report
    Munkireport: Requesting displays_info
    Munkireport: Requesting managedinstalls
    Munkireport: Requesting findmymac
    Munkireport: Requesting power
    Munkireport: Requesting installhistory
    Munkireport: Requesting service
    Munkireport: Requesting warranty
    Munkireport: Requesting network
    Munkireport: Requesting wifi
    Munkireport: Requesting munkiinfo
    Munkireport: Requesting security
    Munkireport: Requesting deploystudio
    Munkireport: Requesting crashplan
    Munkireport: connection_willSendRequestForAuthenticationChallenge_
    Munkireport: Authentication challenge for Host: www.xyz.com Realm: None AuthMethod: NSURLAuthenticationMethodServerTrust
    Munkireport: Allowing OS to handle authentication request
    Status: 200
    Headers: {u'Content-Encoding': u'gzip', u'Transfer-Encoding': u'Identity', u'Server': u'nginx', u'Connection': u'keep-alive', u'Date': u'Sat, 22 Oct 2016 09:32:33 GMT', u'Content-Type': u'text/html; charset=UTF-8'}
    Munkireport: Need to update reportdata
    Munkireport: Need to update inventory
    Munkireport: Sending items
    Download error -1001: The request timed out.
    Munkireport: Headers: None
ERROR: Munkireport: The request timed out.

real    0m13.440s
user    0m0.992s
sys     0m0.571s

**Comment by bochoven** [comment]
So the server times out for the client. Any idea why it takes so long for the server to respond?

**Comment by vikaskedia** [comment]
@bochoven i do not think that the server is timing out. Reasons:

1. Status code 499 documentation states that client is closing the connection.

2. This is a pristine nginx installation without any modifications.

3. The same server runs the munkireport web interface and all the pages load fine.

**Comment by bochoven** [comment]
The connection timeout for the client is 10 seconds, if the server does not respond within that time limit, the client closes the connection. You can increase the time limit by editing ```/usr/local/munki/munkilib/purl.py```

https://github.com/munkireport/munkireport-php/blob/master/assets/client_installer/purl#L132

change `self.connection_timeout = options.get('connection_timeout', 10)` to `self.connection_timeout = options.get('connection_timeout', 60)` and see if that fixes your issue.

**Comment by vikaskedia** [comment]
Making the above change allows the client to submit the data.

But,

the server does not have any load and it is definitely not taking more than a couple of milliseconds to reply.

Any idea what else might be causing this ?

If you want I can give you access to the production server to help you debug ?

**Comment by bochoven** [comment]
Maybe inventory is very large? I pushed a new commit to wip that shows the sizes of the files that munkireport uploads.

**Comment by bochoven** [comment]
Timed out because of very large install.log files
