### ISSUE TITLE
'Check-in' field in Client report sorting is mis-evaluating 'a few seconds ago'

### ISSUE THREAD

**Issue by wildeep** [munkireport/munkireport-php#574]
In the Client report, The munki-related 'check-in' field sorts the value 'a few seconds ago' as a larger value than 'n months ago'.
![image](https://cloud.githubusercontent.com/assets/892364/20797222/d3e8cb62-b7a7-11e6-82f5-799096a1d156.png)

**Comment by bochoven** [comment]
I believe the 'a few seconds ago' is actually a wrong/missing date.

**Comment by wildeep** [comment]
Where should I look to investigate this further?

**Comment by wildeep** [comment]
Where is the date/time being pulled from? Managedinstalls.plist has a 'LastCheckDate' value...

**Comment by bochoven** [comment]
It is the time the server recorded the last check-in. It is the timestamp field in the reportdata table.
