### ISSUE TITLE
Pending Installs error: <?=$name?> (<?=$version?>)

### ISSUE THREAD

**Issue by diabolicpride** [munkireport/munkireport-php#575]
When selecting to view any pending installs I get this
<?=$name?> (<?=$version?>)
with 0 results.

![screen shot 2016-12-09 at 11 46 35](https://cloud.githubusercontent.com/assets/11214541/21048057/2619b834-be05-11e6-8eab-ac6c0b8cc11e.png)

Ive looked around online and cant seem to find any information. What did I break?

**Comment by bochoven** [comment]
What version of php are you running?

-Arjen

**Comment by diabolicpride** [comment]
PHP 5.3.3

**Comment by bochoven** [comment]
I’m not sure if it matters (it should not), but is short tags enabled in php?

You can check in Munkireport	under Admin->Show System Status and then open ‘Extended PHP Info'

look for short_open_tag

-Arjen

**Comment by diabolicpride** [comment]
I dont seem to get nay information from that page:
![screen shot 2016-12-09 at 12 33 19](https://cloud.githubusercontent.com/assets/11214541/21049275/d4ec3ad4-be0b-11e6-9f90-a03ce1b4bc45.png)

**Comment by bochoven** [comment]
Ah interesting, you’re the second person that does not get PHP information reliably. You should be able to get the RAW data here:

index.php?/system/phpInfo

I would be interested in that output for debugging purposes.

-Arjen

**Comment by diabolicpride** [comment]
{"phpinfo":{"0":"PHP Version 5.3.3","System":"Linux v0515 2.6.32-504.16.2.el6.x86_64 #1 SMP Wed Apr 22 06:48:29 UTC 2015 x86_64","Build Date":"Aug 11 2016 20:34:18","Configure Command":" &#039;.\/configure&#039;  &#039;--build=x86_64-redhat-linux-gnu&#039; &#039;--host=x86_64-redhat-linux-gnu&#039; &#039;--target=x86_64-redhat-linux-gnu&#039; &#039;--program-prefix=&#039; &#039;--prefix=\/usr&#039; &#039;--exec-prefix=\/usr&#039; &#039;--bindir=\/usr\/bin&#039; &#039;--sbindir=\/usr\/sbin&#039; &#039;--sysconfdir=\/etc&#039; &#039;--datadir=\/usr\/share&#039; &#039;--includedir=\/usr\/include&#039; &#039;--libdir=\/usr\/lib64&#039; &#039;--libexecdir=\/usr\/libexec&#039; &#039;--localstatedir=\/var&#039; &#039;--sharedstatedir=\/var\/lib&#039; &#039;--mandir=\/usr\/share\/man&#039; &#039;--infodir=\/usr\/share\/info&#039; &#039;--cache-file=..\/config.cache&#039; &#039;--with-libdir=lib64&#039; &#039;--with-config-file-path=\/etc&#039; &#039;--with-config-file-scan-dir=\/etc\/php.d&#039; &#039;--disable-debug&#039; &#039;--with-pic&#039; &#039;--disable-rpath&#039; &#039;--without-pear&#039; &#039;--with-bz2&#039; &#039;--with-exec-dir=\/usr\/bin&#039; &#039;--with-freetype-dir=\/usr&#039; &#039;--with-png-dir=\/usr&#039; &#039;--with-xpm-dir=\/usr&#039; &#039;--enable-gd-native-ttf&#039; &#039;--without-gdbm&#039; &#039;--with-gettext&#039; &#039;--with-gmp&#039; &#039;--with-iconv&#039; &#039;--with-jpeg-dir=\/usr&#039; &#039;--with-openssl&#039; &#039;--with-pcre-regex=\/usr&#039; &#039;--with-zlib&#039; &#039;--with-layout=GNU&#039; &#039;--enable-exif&#039; &#039;--enable-ftp&#039; &#039;--enable-magic-quotes&#039; &#039;--enable-sockets&#039; &#039;--enable-sysvsem&#039; &#039;--enable-sysvshm&#039; &#039;--enable-sysvmsg&#039; &#039;--with-kerberos&#039; &#039;--enable-ucd-snmp-hack&#039; &#039;--enable-shmop&#039; &#039;--enable-calendar&#039; &#039;--without-sqlite&#039; &#039;--with-libxml-dir=\/usr&#039; &#039;--enable-xml&#039; &#039;--with-system-tzdata&#039; &#039;--with-apxs2=\/usr\/sbin\/apxs&#039; &#039;--without-mysql&#039; &#039;--without-gd&#039; &#039;--disable-dom&#039; &#039;--disable-dba&#039; &#039;--without-unixODBC&#039; &#039;--disable-pdo&#039; &#039;--disable-xmlreader&#039; &#039;--disable-xmlwriter&#039; &#039;--without-sqlite3&#039; &#039;--disable-phar&#039; &#039;--disable-fileinfo&#039; &#039;--disable-json&#039; &#039;--without-pspell&#039; &#039;--disable-wddx&#039; &#039;--without-curl&#039; &#039;--disable-posix&#039; &#039;--disable-sysvmsg&#039; &#039;--disable-sysvshm&#039; &#039;--disable-sysvsem&#039;","Server API":"Apache 2.0 Handler","Virtual Directory Support":"disabled","Configuration File (php.ini) Path":"\/etc","Loaded Configuration File":"\/etc\/php.ini","Scan this dir for additional .ini files":"\/etc\/php.d","Additional .ini files parsed":"\/etc\/php.d\/curl.ini, \n\/etc\/php.d\/dom.ini, \n\/etc\/php.d\/fileinfo.ini, \n\/etc\/php.d\/json.ini, \n\/etc\/php.d\/ldap.ini, \n\/etc\/php.d\/mysql.ini, \n\/etc\/php.d\/mysqli.ini, \n\/etc\/php.d\/pdo.ini, \n\/etc\/php.d\/pdo_mysql.ini, \n\/etc\/php.d\/pdo_sqlite.ini, \n\/etc\/php.d\/phar.ini, \n\/etc\/php.d\/sqlite3.ini, \n\/etc\/php.d\/wddx.ini, \n\/etc\/php.d\/xmlreader.ini, \n\/etc\/php.d\/xmlwriter.ini, \n\/etc\/php.d\/xsl.ini, \n\/etc\/php.d\/zip.ini","PHP API":"20090626","PHP Extension":"20090626","Zend Extension":"220090626","Zend Extension Build":"API220090626, NTS","PHP Extension Build":"API20090626, NTS","Debug Build":"no","Thread Safety":"disabled","Zend Memory Manager":"enabled","Zend Multibyte Support":"disabled","IPv6 Support":"enabled","Registered PHP Streams":"https,  ftps,  compress.zlib,  compress.bzip2,  php,  file,  glob,  data,  http,  ftp,  phar,  zip","Registered Stream Socket Transports":"tcp,  udp,  unix,  udg,  ssl,  sslv3,  sslv2,  tls","Registered Stream Filters":"zlib.*,  bzip2.*,  convert.iconv.*,  string.rot13,  string.toupper,  string.tolower,  string.strip_tags,  convert.*,  consumed,  dechunk","1":"This program makes use of the Zend Scripting Language Engine:Zend&nbsp;Engine&nbsp;v2.3.0,&nbsp;Copyright&nbsp;(c)&nbsp;1998-2010&nbsp;Zend&nbsp;Technologies"},"apache2handler":{"Apache Version":"Apache\/2.2.15 (CentOS)","Apache API Version":"20051115","Server Administrator":"root@localhost","Hostname:Port":"v0515.nbi.ac.uk:0","User\/Group":"apache(48)\/48","Max Requests":"Per Child: 4000 - Keep Alive: off - Max Per Connection: 100","Timeouts":"Connection: 60 - Keep-Alive: 15","Virtual Server":"No","Server Root":"\/etc\/httpd","Loaded Modules":"core prefork http_core mod_so mod_auth_basic mod_auth_digest mod_authn_file mod_authn_alias mod_authn_anon mod_authn_dbm mod_authn_default mod_authz_host mod_authz_user mod_authz_owner mod_authz_groupfile mod_authz_dbm mod_authz_default util_ldap mod_authnz_ldap mod_include mod_log_config mod_logio mod_env mod_ext_filter mod_mime_magic mod_expires mod_deflate mod_headers mod_usertrack mod_setenvif mod_mime mod_dav mod_status mod_autoindex mod_info mod_dav_fs mod_vhost_alias mod_negotiation mod_dir mod_actions mod_speling mod_userdir mod_alias mod_substitute mod_rewrite mod_proxy mod_proxy_balancer mod_proxy_ftp mod_proxy_http mod_proxy_ajp mod_proxy_connect mod_cache mod_suexec mod_disk_cache mod_cgi mod_version mod_authz_ldap mod_php5","Directive":"Local Value (Master Value)","engine":"1 (1)","last_modified":"0 (0)","xbithack":"0 (0)"},"Apache Environment":{"Variable":"Value","HTTP_HOST":"mac-software.nbi.ac.uk","HTTP_CONNECTION":"keep-alive","HTTP_UPGRADE_INSECURE_REQUESTS":"1","HTTP_USER_AGENT":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit\/537.36 (KHTML,  like Gecko) Chrome\/54.0.2840.98 Safari\/537.36","HTTP_ACCEPT":"text\/html, application\/xhtml+xml, application\/xml;q=0.9, image\/webp, *\/*;q=0.8","HTTP_ACCEPT_ENCODING":"gzip,  deflate,  sdch","HTTP_ACCEPT_LANGUAGE":"en-US, en;q=0.8","HTTP_COOKIE":"PHPSESSID=fsv4uj96rtq5vkkkocs6q1pdh2; i18next=en","PATH":"\/sbin:\/usr\/sbin:\/bin:\/usr\/bin","SERVER_SIGNATURE":"&lt;address&gt;Apache\/2.2.15 (CentOS) Server at mac-software.nbi.ac.uk Port 80&lt;\/address&gt;","SERVER_SOFTWARE":"Apache\/2.2.15 (CentOS)","SERVER_NAME":"mac-software.nbi.ac.uk","SERVER_ADDR":"149.155.209.188","SERVER_PORT":"80","REMOTE_ADDR":"149.155.213.158","DOCUMENT_ROOT":"\/var\/www\/html","SERVER_ADMIN":"root@localhost","SCRIPT_FILENAME":"\/var\/www\/reports\/index.php","REMOTE_PORT":"57919","GATEWAY_INTERFACE":"CGI\/1.1","SERVER_PROTOCOL":"HTTP\/1.1","REQUEST_METHOD":"GET","QUERY_STRING":"\/system\/phpInfo","REQUEST_URI":"\/reports\/index.php?\/system\/phpInfo","SCRIPT_NAME":"\/reports\/index.php"},"HTTP Headers Information":{"Directive":"Local Value (Master Value)","allow_call_time_pass_reference":"Off (Off)","allow_url_fopen":"On (On)","allow_url_include":"Off (Off)","always_populate_raw_post_data":"Off (Off)","arg_separator.input":"&amp; (&amp;)","arg_separator.output":"&amp; (&amp;)","asp_tags":"Off (Off)","auto_append_file":"<i>no value<\/i> (<i>no value<\/i>)","auto_globals_jit":"On (On)","auto_prepend_file":"<i>no value<\/i> (<i>no value<\/i>)","browscap":"<i>no value<\/i> (<i>no value<\/i>)","default_charset":"<i>no value<\/i> (<i>no value<\/i>)","default_mimetype":"text\/html (text\/html)","define_syslog_variables":"Off (Off)","disable_classes":"<i>no value<\/i> (<i>no value<\/i>)","disable_functions":"<i>no value<\/i> (<i>no value<\/i>)","display_errors":"Off (Off)","display_startup_errors":"Off (Off)","doc_root":"<i>no value<\/i> (<i>no value<\/i>)","docref_ext":"<i>no value<\/i> (<i>no value<\/i>)","docref_root":"<i>no value<\/i> (<i>no value<\/i>)","enable_dl":"Off (Off)","error_append_string":"<i>no value<\/i> (<i>no value<\/i>)","error_log":"<i>no value<\/i> (<i>no value<\/i>)","error_prepend_string":"<i>no value<\/i> (<i>no value<\/i>)","error_reporting":"0 (22527)","exit_on_timeout":"Off (Off)","expose_php":"On (On)","extension_dir":"\/usr\/lib64\/php\/modules (\/usr\/lib64\/php\/modules)","file_uploads":"On (On)","highlight.bg":"<font style=\"color: #FFFFFF\">#FFFFFF<\/font> (<font style=\"color: #FFFFFF\">#FFFFFF<\/font>)","highlight.comment":"<font style=\"color: #FF8000\">#FF8000<\/font> (<font style=\"color: #FF8000\">#FF8000<\/font>)","highlight.default":"<font style=\"color: #0000BB\">#0000BB<\/font> (<font style=\"color: #0000BB\">#0000BB<\/font>)","highlight.html":"<font style=\"color: #000000\">#000000<\/font> (<font style=\"color: #000000\">#000000<\/font>)","highlight.keyword":"<font style=\"color: #007700\">#007700<\/font> (<font style=\"color: #007700\">#007700<\/font>)","highlight.string":"<font style=\"color: #DD0000\">#DD0000<\/font> (<font style=\"color: #DD0000\">#DD0000<\/font>)","html_errors":"Off (Off)","ignore_repeated_errors":"Off (Off)","ignore_repeated_source":"Off (Off)","ignore_user_abort":"Off (Off)","implicit_flush":"Off (Off)","include_path":".:\/usr\/share\/pear:\/usr\/share\/php (.:\/usr\/share\/pear:\/usr\/share\/php)","log_errors":"On (On)","log_errors_max_len":"1024 (1024)","magic_quotes_gpc":"Off (Off)","magic_quotes_runtime":"Off (Off)","magic_quotes_sybase":"Off (Off)","mail.add_x_header":"On (On)","mail.force_extra_parameters":"<i>no value<\/i> (<i>no value<\/i>)","mail.log":"<i>no value<\/i> (<i>no value<\/i>)","max_execution_time":"30 (30)","max_file_uploads":"20 (20)","max_input_nesting_level":"64 (64)","max_input_time":"60 (60)","max_input_vars":"1000 (1000)","memory_limit":"128M (128M)","open_basedir":"<i>no value<\/i> (<i>no value<\/i>)","output_buffering":"4096 (4096)","output_handler":"<i>no value<\/i> (<i>no value<\/i>)","post_max_size":"8M (8M)","precision":"14 (14)","realpath_cache_size":"16K (16K)","realpath_cache_ttl":"120 (120)","register_argc_argv":"Off (Off)","register_globals":"Off (Off)","register_long_arrays":"Off (Off)","report_memleaks":"On (On)","report_zend_debug":"On (On)","request_order":"GP (GP)","safe_mode":"Off (Off)","safe_mode_exec_dir":"<i>no value<\/i> (<i>no value<\/i>)","safe_mode_gid":"Off (Off)","safe_mode_include_dir":"<i>no value<\/i> (<i>no value<\/i>)","sendmail_from":"<i>no value<\/i> (<i>no value<\/i>)","sendmail_path":"\/usr\/sbin\/sendmail&nbsp;-t&nbsp;-i (\/usr\/sbin\/sendmail&nbsp;-t&nbsp;-i)","serialize_precision":"100 (100)","short_open_tag":"Off (Off)","SMTP":"localhost (localhost)","smtp_port":"25 (25)","sql.safe_mode":"Off (Off)","track_errors":"Off (Off)","unserialize_callback_func":"<i>no value<\/i> (<i>no value<\/i>)","upload_max_filesize":"2M (2M)","upload_tmp_dir":"<i>no value<\/i> (<i>no value<\/i>)","user_dir":"<i>no value<\/i> (<i>no value<\/i>)","user_ini.cache_ttl":"300 (300)","user_ini.filename":".user.ini (.user.ini)","variables_order":"GPCS (GPCS)","xmlrpc_error_number":"0 (0)","xmlrpc_errors":"Off (Off)","y2k_compliance":"On (On)","zend.enable_gc":"On (On)"},"ctype":{"ctype functions":"enabled"},"curl":{"cURL support":"enabled","cURL Information":"7.19.7","Age":"3","0":"Features","AsynchDNS":"No","Debug":"No","GSS-Negotiate":"Yes","IDN":"Yes","IPv6":"Yes","Largefile":"Yes","NTLM":"Yes","SPNEGO":"No","SSL":"Yes","SSPI":"No","krb4":"No","libz":"Yes","CharConv":"No","Protocols":"tftp,  ftp,  telnet,  dict,  ldap,  ldaps,  http,  file,  https,  ftps,  scp,  sftp","Host":"x86_64-redhat-linux-gnu","SSL Version":"NSS\/3.21 Basic ECC","ZLib Version":"1.2.3","libSSH Version":"libssh2\/1.4.2"},"date":{"date\/time support":"enabled","&quot;Olson&quot; Timezone Database Version":"0.system","Timezone Database":"internal","Default timezone":"UTC","Directive":"Local Value (Master Value)","date.default_latitude":"31.7667 (31.7667)","date.default_longitude":"35.2333 (35.2333)","date.sunrise_zenith":"90.583333 (90.583333)","date.sunset_zenith":"90.583333 (90.583333)","date.timezone":"<i>no value<\/i> (<i>no value<\/i>)"},"dom":{"DOM\/XML":"enabled","DOM\/XML API Version":"20031129","libxml Version":"2.7.6","HTML Support":"enabled","XPath Support":"enabled","XPointer Support":"enabled","Schema Support":"enabled","RelaxNG Support":"enabled"},"ereg":{"Regex Library":"Bundled library enabled"},"exif":{"EXIF Support":"enabled","EXIF Version":"1.4 $Id: exif.c 293036 2010-01-03 09:23:27Z sebastian $","Supported EXIF Version":"0220","Supported filetypes":"JPEG, TIFF","Directive":"Local Value (Master Value)","exif.decode_jis_intel":"JIS (JIS)","exif.decode_jis_motorola":"JIS (JIS)","exif.decode_unicode_intel":"UCS-2LE (UCS-2LE)","exif.decode_unicode_motorola":"UCS-2BE (UCS-2BE)","exif.encode_jis":"<i>no value<\/i> (<i>no value<\/i>)","exif.encode_unicode":"ISO-8859-15 (ISO-8859-15)"},"fileinfo":{"fileinfo support":"enabled","version":"1.0.5-dev"},"filter":{"Input Validation and Filtering":"enabled","Revision":"$Revision: 298196 $","Directive":"Local Value (Master Value)","filter.default":"unsafe_raw (unsafe_raw)","filter.default_flags":"<i>no value<\/i> (<i>no value<\/i>)"},"ftp":{"FTP support":"enabled"},"gettext":{"GetText Support":"enabled"},"gmp":{"gmp support":"enabled","GMP version":"4.3.1"},"hash":{"hash support":"enabled","Hashing Engines":"md2 md4 md5 sha1 sha224 sha256 sha384 sha512 ripemd128 ripemd160 ripemd256 ripemd320 whirlpool tiger128, 3 tiger160, 3 tiger192, 3 tiger128, 4 tiger160, 4 tiger192, 4 snefru snefru256 gost adler32 crc32 crc32b salsa10 salsa20 haval128, 3 haval160, 3 haval192, 3 haval224, 3 haval256, 3 haval128, 4 haval160, 4 haval192, 4 haval224, 4 haval256, 4 haval128, 5 haval160, 5 haval192, 5 haval224, 5 haval256, 5"},"iconv":{"iconv support":"enabled","iconv implementation":"glibc","iconv library version":"2.12","Directive":"Local Value (Master Value)","iconv.input_encoding":"ISO-8859-1 (ISO-8859-1)","iconv.internal_encoding":"ISO-8859-1 (ISO-8859-1)","iconv.output_encoding":"ISO-8859-1 (ISO-8859-1)"},"json":{"json support":"enabled","json version":"1.2.1"},"ldap":{"LDAP Support":"enabled","RCS Version":"$Id: ldap.c 299434 2010-05-17 20:09:42Z pajoye $","Total Links":"0\/unlimited","API Version":"3001","Vendor Name":"OpenLDAP","Vendor Version":"20440","SASL Support":"Enabled","Directive":"Local Value (Master Value)","ldap.max_links":"Unlimited (Unlimited)"},"libxml":{"libXML support":"active","libXML Compiled Version":"2.7.6","libXML Loaded Version":"20706","libXML streams":"enabled"},"mysql":{"MySQL Support":"enabled","Active Persistent Links":"0","Active Links":"0","Client API version":"5.1.73","MYSQL_MODULE_TYPE":"external","MYSQL_SOCKET":"\/var\/lib\/mysql\/mysql.sock","MYSQL_INCLUDE":"-I\/usr\/include\/mysql","MYSQL_LIBS":"-L\/usr\/lib64\/mysql -lmysqlclient","Directive":"Local Value (Master Value)","mysql.allow_local_infile":"On (On)","mysql.allow_persistent":"On (On)","mysql.connect_timeout":"60 (60)","mysql.default_host":"<i>no value<\/i> (<i>no value<\/i>)","mysql.default_password":"<i>no value<\/i> (<i>no value<\/i>)","mysql.default_port":"<i>no value<\/i> (<i>no value<\/i>)","mysql.default_socket":"\/var\/lib\/mysql\/mysql.sock (\/var\/lib\/mysql\/mysql.sock)","mysql.default_user":"<i>no value<\/i> (<i>no value<\/i>)","mysql.max_links":"Unlimited (Unlimited)","mysql.max_persistent":"Unlimited (Unlimited)","mysql.trace_mode":"Off (Off)"},"mysqli":{"MysqlI Support":"enabled","Client API library version":"5.1.73","Active Persistent Links":"0","Inactive Persistent Links":"0","Active Links":"0","Client API header version":"5.1.73","MYSQLI_SOCKET":"\/var\/lib\/mysql\/mysql.sock","Directive":"Local Value (Master Value)","mysqli.allow_local_infile":"On (On)","mysqli.allow_persistent":"On (On)","mysqli.default_host":"<i>no value<\/i> (<i>no value<\/i>)","mysqli.default_port":"3306 (3306)","mysqli.default_pw":"<i>no value<\/i> (<i>no value<\/i>)","mysqli.default_socket":"<i>no value<\/i> (<i>no value<\/i>)","mysqli.default_user":"<i>no value<\/i> (<i>no value<\/i>)","mysqli.max_links":"Unlimited (Unlimited)","mysqli.max_persistent":"Unlimited (Unlimited)","mysqli.reconnect":"Off (Off)"},"openssl":{"OpenSSL support":"enabled","OpenSSL Library Version":"OpenSSL 1.0.1e-fips 11 Feb 2013","OpenSSL Header Version":"OpenSSL 1.0.1e-fips 11 Feb 2013"},"pcre":{"PCRE (Perl Compatible Regular Expressions) Support":"enabled","PCRE Library Version":"7.8 2008-09-05","Directive":"Local Value (Master Value)","pcre.backtrack_limit":"100000 (100000)","pcre.recursion_limit":"100000 (100000)"},"PDO":{"PDO support":"enabled","PDO drivers":"mysql,  sqlite"},"pdo_mysql":{"PDO Driver for MySQL":"enabled","Client API version":"5.1.73"},"pdo_sqlite":{"PDO Driver for SQLite 3.x":"enabled","SQLite Library":"3.6.20"},"Phar":{"Phar: PHP Archive support":"enabled","Phar EXT version":"2.0.1","Phar API version":"1.1.1","SVN revision":"$Revision: 298908 $","Phar-based phar archives":"enabled","Tar-based phar archives":"enabled","ZIP-based phar archives":"enabled","gzip compression":"enabled","bzip2 compression":"enabled","Native OpenSSL support":"enabled","0":"Phar based on pear\/PHP_Archive, original concept by Davey Shafik.Phar fully realized by Gregory Beaver and Marcus Boerger.Portions of tar implementation Copyright (c) 2003-2009 Tim Kientzle.","Directive":"Local Value (Master Value)","phar.cache_list":"<i>no value<\/i> (<i>no value<\/i>)","phar.readonly":"On (On)","phar.require_hash":"On (On)"},"Reflection":{"Reflection":"enabled","Version":"$Revision: 300393 $"},"session":{"Session Support":"enabled","Registered save handlers":"files user","Registered serializer handlers":"php php_binary wddx","Directive":"Local Value (Master Value)","session.auto_start":"Off (Off)","session.bug_compat_42":"Off (Off)","session.bug_compat_warn":"Off (Off)","session.cache_expire":"180 (180)","session.cache_limiter":"nocache (nocache)","session.cookie_domain":"<i>no value<\/i> (<i>no value<\/i>)","session.cookie_httponly":"Off (Off)","session.cookie_lifetime":"0 (0)","session.cookie_path":"\/reports\/ (\/)","session.cookie_secure":"Off (Off)","session.entropy_file":"<i>no value<\/i> (<i>no value<\/i>)","session.entropy_length":"0 (0)","session.gc_divisor":"1000 (1000)","session.gc_maxlifetime":"1440 (1440)","session.gc_probability":"1 (1)","session.hash_bits_per_character":"5 (5)","session.hash_function":"0 (0)","session.name":"PHPSESSID (PHPSESSID)","session.referer_check":"<i>no value<\/i> (<i>no value<\/i>)","session.save_handler":"files (files)","session.save_path":"\/var\/lib\/php\/session (\/var\/lib\/php\/session)","session.serialize_handler":"php (php)","session.use_cookies":"On (On)","session.use_only_cookies":"On (On)","session.use_trans_sid":"0 (0)"},"shmop":{"shmop support":"enabled"},"SimpleXML":{"Simplexml support":"enabled","Revision":"$Revision: 299424 $","Schema support":"enabled"},"sockets":{"Sockets Support":"enabled"},"SPL":{"SPL support":"enabled","Interfaces":"Countable,  OuterIterator,  RecursiveIterator,  SeekableIterator,  SplObserver,  SplSubject","Classes":"AppendIterator,  ArrayIterator,  ArrayObject,  BadFunctionCallException,  BadMethodCallException,  CachingIterator,  DirectoryIterator,  DomainException,  EmptyIterator,  FilesystemIterator,  FilterIterator,  GlobIterator,  InfiniteIterator,  InvalidArgumentException,  IteratorIterator,  LengthException,  LimitIterator,  LogicException,  MultipleIterator,  NoRewindIterator,  OutOfBoundsException,  OutOfRangeException,  OverflowException,  ParentIterator,  RangeException,  RecursiveArrayIterator,  RecursiveCachingIterator,  RecursiveDirectoryIterator,  RecursiveFilterIterator,  RecursiveIteratorIterator,  RecursiveRegexIterator,  RecursiveTreeIterator,  RegexIterator,  RuntimeException,  SplDoublyLinkedList,  SplFileInfo,  SplFileObject,  SplFixedArray,  SplHeap,  SplMinHeap,  SplMaxHeap,  SplObjectStorage,  SplPriorityQueue,  SplQueue,  SplStack,  SplTempFileObject,  UnderflowException,  UnexpectedValueException"},"sqlite3":{"SQLite3 support":"enabled","SQLite3 module version":"0.7-dev","SQLite Library":"3.6.20","Directive":"Local Value (Master Value)","sqlite3.extension_dir":"<i>no value<\/i> (<i>no value<\/i>)"},"standard":{"Dynamic Library Support":"enabled","Path to sendmail":"\/usr\/sbin\/sendmail -t -i","Directive":"Local Value (Master Value)","assert.active":"1 (1)","assert.bail":"0 (0)","assert.callback":"<i>no value<\/i> (<i>no value<\/i>)","assert.quiet_eval":"0 (0)","assert.warning":"1 (1)","auto_detect_line_endings":"0 (0)","default_socket_timeout":"60 (60)","safe_mode_allowed_env_vars":"PHP_ (PHP_)","safe_mode_protected_env_vars":"LD_LIBRARY_PATH (LD_LIBRARY_PATH)","url_rewriter.tags":"a=href,area=href,frame=src,input=src,form=fakeentry (a=href,area=href,frame=src,input=src,form=fakeentry)","user_agent":"<i>no value<\/i> (<i>no value<\/i>)"},"tokenizer":{"Tokenizer Support":"enabled"},"wddx":{"WDDX Support":"enabled","WDDX Session Serializer":"enabled"},"xml":{"XML Support":"active","XML Namespace Support":"active","libxml2 Version":"2.7.6"},"xmlreader":{"XMLReader":"enabled"},"xmlwriter":{"XMLWriter":"enabled"},"xsl":{"XSL":"enabled","libxslt Version":"1.1.26","libxslt compiled against libxml Version":"2.7.6","EXSLT":"enabled","libexslt Version":"1.1.26"},"zip":{"Zip":"enabled","Extension Version":"$Id: php_zip.c 300470 2010-06-15 18:48:33Z pajoye $","Zip version":"1.9.1","Libzip version":"0.9.0"},"zlib":{"ZLib Support":"enabled","Stream Wrapper support":"compress.zlib:\/\/","Stream Filter support":"zlib.inflate,  zlib.deflate","Compiled Version":"1.2.3","Linked Version":"1.2.3","Directive":"Local Value (Master Value)","zlib.output_compression":"Off (Off)","zlib.output_compression_level":"-1 (-1)","zlib.output_handler":"<i>no value<\/i> (<i>no value<\/i>)"},"Additional Modules":["Module Name"]}

**Comment by bochoven** [comment]
Could you check if the latest wip fixes system status?

**Comment by diabolicpride** [comment]
Yes the system status page is working using the current wip.- Thanks :)
The Pending Installs is still not working correctly.

**Comment by bochoven** [comment]
Do you have short_tags enabled in php? http://stackoverflow.com/questions/2476072/tags-not-working-in-php-5-3-1

**Comment by diabolicpride** [comment]
Turns out Short_tags were not enabled.
They are now enabled and this has fixed the issue. Thank you very much :)
Only issue I'm getting now is pending installs which aren't actually pending:
![screen shot 2016-12-14 at 11 51 45](https://cloud.githubusercontent.com/assets/11214541/21181031/cb4fbf50-c1f3-11e6-8aa8-7c6eb01bda7c.png)

**Comment by diabolicpride** [comment]
These are very old installs.
I have released and installed Office versions 15.28 but these are still showing here. Any ideas?

**Comment by bochoven** [comment]
Maybe the machine has not checked in recently?

**Comment by diabolicpride** [comment]
This is on several machines including both of the Macs I use. All have been checked today.

**Comment by bochoven** [comment]
Any chance you could drop into the macadmins slack group to troubleshoot your issue quickly? https://macadmins.herokuapp.com
