### ISSUE TITLE
Pending installs, bad link?

### ISSUE THREAD

**Issue by scottlep** [munkireport/munkireport-php#580]
I just updated to 2.11.0. Now when I click on the name of any pending installs in the Pending Installs dashboard widget, I get the following (see screen shot). Any suggestion on how to fix. Same thing happens if I click on the name of an update in the Pending Apple Updates Widget.

Thanks!

![screen shot 2016-12-15 at 10 21 34 am](https://cloud.githubusercontent.com/assets/4138295/21229661/5fe8be98-c2b0-11e6-9b79-5495b012f0fb.jpg)

**Comment by bochoven** [comment]
Please upgrade php to 5.4.0 or higher or turn on short_open_tag if you need to run php < 5.4.0. See also http://php.net/manual/en/ini.core.php#ini.short-open-tag

**Comment by scottlep** [comment]
Got it, thanks!
