### ISSUE TITLE
Clients break when installed via munki pkg but work if installed manually

### ISSUE THREAD

**Issue by merced317** [munkireport/munkireport-php#590]
For a few versions now, I haven't been able to figure out why clients break when installing via the munki pkg.  If I install via the manual install method, the client works fine.  I used the instructions listed here:

https://github.com/munkireport/munkireport-php/wiki/Client-setup

The error in the Managed Software Center log when client is broken is:

Starting...
Performing preflight tasks...
Munkireport: # Executing scripts in preflight_abort.d
Munkireport: # Executing scripts in preflight.d
Munkireport: Running bluetooth.sh
Munkireport: Manual check: skipping
Munkireport: Running timemachine.sh
Munkireport: Manual check: skipping
Munkireport: Running submit.preflight
Download error -1004: Could not connect to the server.
Munkireport: Headers: None
ERROR: Munkireport: Could not connect to the server.
Munkireport: submit.preflight Error: ERROR: Munkireport: Could not connect to the server.

If the client is installed manually, I get this in the Managed Software Center log instead:

Starting...
Performing preflight tasks...
Munkireport: # Executing scripts in preflight_abort.d
Munkireport: # Executing scripts in preflight.d
Munkireport: Running bluetooth.sh
Munkireport: Manual check: skipping
Munkireport: Running timemachine.sh
Munkireport: Manual check: skipping
Munkireport: Running submit.preflight
Munkireport: Need to update reportdata (440B)
Munkireport: Sending items (440B)
Munkireport: Server info: starting: reportdata

I would really like to get this fixed and don't really know where to go to figure out what's going wrong.  Any assistance would be appreciated.

**Comment by bochoven** [comment]
As this is not a bug report (yet), could you please ask your question in the munkireport mailinglist?

https://groups.google.com/forum/#!forum/munkireport

Thanks!
