### ISSUE TITLE
Module to track admin-provided conditional items

### ISSUE THREAD

**Issue by flammable** [munkireport/munkireport-php#627]
In Slack today, we were discussing a possible module to track if a particular Mac can run 10.12 Sierra - and I realized we already deploy [this script](https://github.com/hjuutilainen/adminscripts/blob/master/check-10.12-sierra-compatibility.py) from Hannes Juutilainen.  Thus, that data is already recorded in /Library/Managed Installs/ManagedInstallReport.plist (though it doesn't display in Additional Munki Info, so I don't think it's in the MunkiReport database yet).

If there were a way to view, and sort, [admin-provided conditional items](https://github.com/munki/munki/wiki/Conditional-Items#admin-provided-conditions), that would take care of this particular request and possibly sidestep the need for many custom modules.  It would add expansion possibilities in the same way that the ARD module can be used to display custom data.

Do you think this would be possible to add?

Obviously up to you guys, but I'm thinking it could look like the Installation Ratio report, or the Inventory listing, where you can select individual items and view more information about them.  That way, the module would be able to support multiple conditions with multiple values (such as yes or no, or an array with more than two values).

Thanks for considering this!

**Comment by poundbangbash** [comment]
The module `munki-facts` has been implemented resolving this issue.
