### ISSUE TITLE
Page selection indicator is sometimes not on correct page.

### ISSUE THREAD

**Issue by nathanperkins** [munkireport/munkireport-php#647]
Hello,

The selection box indicating the current selected page on a report or listing is sometimes on the wrong page number. When this occurs, you can click on the actual page number to reset the selection box, which does not change the page.

I've linked a video to show what I'm talking about.

![screen shot 2017-03-02 at 5 39 21 pm](https://cloud.githubusercontent.com/assets/10337495/23534819/37aaec16-ff6f-11e6-9c06-7bb77f07a6a2.png)
(actual page selected is 8)

https://vimeo.com/206508447

**Comment by bochoven** [comment]
I think this has to do with the theme 'Darkly' where the active state colour is the same as the 'hover' state colour. Switch to the 'Default' theme to see the actual behaviour.

Please reopen if you still think this issue needs to be addressed.

**Comment by nathanperkins** [comment]
Hi bochoven,

I'm more talking about the blue box surrounding the last box you clicked. It's a bit misleading. I checked and it applies to other themes as well.

Best,
Nathan
