### ISSUE TITLE
php error when ldap results do not provide gidNumber

### ISSUE THREAD

**Issue by dansdrivers** [munkireport/munkireport-php#651]
I attempted to set up login using LDAP and had to do some tweaks to make it work. I got around the default **(objectClass=posixAccount)** by an override in config.php **(objectClass=person)**.

This one error seems like it cannot be over-ridden by a line in config.php though.

See the error message that was returned. 

> Notice: Undefined index: gidnumber in /WebSite/munki_reports/app/lib/authLDAP/authLDAP.php on line 243
> 
> Warning: session_regenerate_id(): Cannot regenerate session id - headers already sent in /WebSite/munki_reports/app/controllers/auth.php on line 227
> 
> Warning: Cannot modify header information - headers already sent by (output started at /WebSite/munki_reports/app/lib/authLDAP/authLDAP.php:243) in /WebSite/munki_reports/app/helpers/site_helper.php on line 171
> 

When the error happens, if I click the reload button on the browser url window, there is a typical message to resend the data. I choose "Send" and the login works. I am guessing it works because the authentication already succeeded when "session id - headers already sent ...". 

The missing info should be assigned here:
```
        // general user info
        $info['dn']   = $user_result['dn'];
        $info['gid']  = $user_result['gidnumber'][0];
        $info['mail'] = $user_result['mail'][0];
        ....
```

So tried to find why there is no **gidnumber** in my results. The LDAP results from a command line query do not provide any **gidnumber**. There is a **uidnumber**. And some possibility that might represent some form of the users group affiliation **ulinkUniversityEduOrganizationCode** and **universityEduOrganizationCode**. 

I did a hack to authLDAP.php that made the login work smoothly for me. 
```
        // general user info
        $info['dn']   = $user_result['dn'];
        $info['gid']  = '';
        if (isset($user_result['gidnumber']))
          $info['gid']  = $user_result['gidnumber'][0];
        $info['mail'] = $user_result['mail'][0];
```

Can you share any other idea to workaround it?

I do not need to authenticate any group. 

Let  me share a sample of the LDAP records that I got on the command line:

```
$ ldapsearch -h ldap.university.edu  -x -b uid=abc93,ou=people,dc=university,dc=edu -D "uid=special.auth,ou=Special Users,dc=university,dc=edu" -W -Z
# extended LDIF
#
# LDAPv3
# base <uid=abc93,ou=people,dc=university,dc=edu> with scope subtree
# filter: (objectclass=*)
# requesting: ALL
#

# abc93, people, university.edu
dn: uid=abc93,ou=People,dc=university,dc=edu
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: inetOrgPerson
objectClass: eduPerson
objectClass: universityEduPerson
objectClass: ulinkUniversityEduPerson
eduPersonPrincipalName: abc93@university.edu
universityEduRCPID: 987678
universityEduIID: abc93
universityEduStatus: active
ulinkUniversityEduStatus: active
universityEduAuth: default=##R#abc93
ulinkUniversityEduAuth: default=##R#abc93
mail: d.Fenceki@university.edu
givenName: Lattice
sn: Fenceki
cn: Lattice Fenceki
universityEduSORSource: university
postalAddress: Admn Services Bldg Annex$2 Main Street$New Village, OZ 00000
 0
employeeType: ALUMNI
employeeType: STAFF
eduPersonPrimaryAffiliation: staff
eduPersonAffiliation: staff
eduPersonAffiliation: alum
eduPersonAffiliation: member
eduPersonAffiliation: affiliate
eduPersonAffiliation: employee
uid: abc93
l: New Village
universityEduStaffLocation: Campus
ulinkUniversityEduStaffLocation: Campus
ou: VP Chief Info Officer:Department
title: Unit Administrator/Specialist
universityEduStaffDepartment: Department
ulinkUniversityEduStaffDepartment: Department
ulinkUniversityEduOrganizationCode: 10655
universityEduOrganizationCode: 10655
universityEduEmployeeType: 3
ulinkUniversityEduEmployeeType: 3
universityEduUID: 123454321
uidNumber: 34566543
universityEduCampusService: facstaff:nv:enabled
universityEduCampusService: facstaff:nextown:enabled
universityEduCampusService: student:google:enabled
ulinkUniversityEduCampusService: facstaff:nv:enabled
ulinkUniversityEduCampusService: facstaff:nextown:enabled
ulinkUniversityEduCampusService: student:google:enabled

# search result
search: 3
result: 0 Success

# numResponses: 2
# numEntries: 1
```

**Comment by bochoven** [comment]
I'm closing this as I want to retire the LDAP library in favour of ADLDAP
