### ISSUE TITLE
locale error in wip

### ISSUE THREAD

**Issue by pkpowell** [munkireport/munkireport-php#657]
I just updated my test munkireport server to the latest wip, and now get the following alert/error.
`failed to load locales, please check for syntax errors`
The console has this:
`GET http://[fqdn]/index.php?/locale/get/en 500 (Internal Server Error)`
Most text elements are missing except for the locale and style menu content, numbers and icons.

I also noticed that two config settings I have in config.php - `$conf['locale'] = 'en;` and `$conf['lang'] = 'en';` aren't listed in config_default.php anymore.

Have I broken something or is this just a temporary thing?
Cheers
Phil

**Comment by tuxudo** [comment]
Delete the` $conf['locale'] = 'en;` line from your config.php and try it again.

**Comment by pkpowell** [comment]
Yes, tried that. No change. 
Also ran my config.php through http://phpcodechecker.com/ to rule out typos (the missing quote mark at the end of `$conf['locale'] = 'en;` is from me mangling the code-quotes - it's not in the config file).

Just tailed the log on the server and this stood out
````
PHP Fatal error:  Cannot redeclare class Locale in /var/lib/openshift/53f507574382ec0c78000017/app-root/runtime/repo/app/controllers/locale.php on line 76, referer: http://[fqdn]/index.php?/show/dashboard
````
That error appears a 2nd x but references line 0, which also doesn't exist.
I don't know enough php to know what to do. 
Any ideas?

**Comment by bochoven** [comment]
Can you confirm that you see that error when visiting

`index.php?/locale/get/en`

**Comment by pkpowell** [comment]
Yes, I get 
````
Fatal error: Cannot redeclare class Locale in /var/lib/openshift/53f507574382ec0c78000017/app-root/runtime/repo/app/controllers/locale.php on line 0
````
I did a cursory search for any other declarations of `Locale` earlier, but only in munkireport...

**Comment by bochoven** [comment]
Could you check the latest wip and see if that fixes your issue?

**Comment by pkpowell** [comment]
yes, looks like it's back to normal.
If I go to the "Application Usage" Listing it errors out with `Uncaught TypeError: $(...).popover is not a function`, but apart from that it looks great. 
Awesome changes btw!
Thanks all
