### ISSUE TITLE
Uptime Widget display problem with zero value

### ISSUE THREAD

**Issue by kevinmcox** [munkireport/munkireport-php#669]
It appears that the Uptime Widget has a problem with displaying "0" values. Instead of displaying the zero digit the box is blank.

<img width="456" alt="uptime" src="https://cloud.githubusercontent.com/assets/25358601/24075316/d56db22a-0be6-11e7-88dc-8bd51e356242.png">

I've seen this across all three colored uptime squares.

**Comment by poundbangbash** [comment]
This is no longer an issue in at least 3.1
![image](https://user-images.githubusercontent.com/1416288/37805506-c75f0b3a-2e08-11e8-8eb9-6c8848f91e61.png)
