### ISSUE TITLE
Processor speed for 12" MacBooks reported incorrectly.

### ISSUE THREAD

**Issue by kevinmcox** [munkireport/munkireport-php#685]
I've only got two of them in house so can't provide much testing help, but both of them are reported as having this CPU:

**Intel(R) Core(TM) m7-6Y75 CPU @ 1.20GHz**

When in fact they have the 1.30 GHz processor.

**Comment by tuxudo** [comment]
MunkiReport is reporting them how Apple reports them. The CPUs are overclocked by Apple and what Apple reports them as being is what Intel states their default speed is. This means it isn't a problem with MunkiReport, but a problem with Apple.

**Comment by kevinmcox** [comment]
OK, gotcha.

So does Apple just have System Information configured to report the _marketing_ value instead of the actual one?

MachineProfile.app from Micromat reports the same 1.3 GHz, so just another workaround probably?

**Comment by tuxudo** [comment]
There are a few different places where the CPU speed can be gotten from. When I looked into this before MunkiReport pulls it from running "/usr/sbin/sysctl -n machdep.cpu.brand_string" which prints out the marketing information and speed of the CPU. There are other places that list the actual CPU speed. The Micromat app could be using that or it could be adjusting to be the real speed.

**Comment by kevinmcox** [comment]
Yep that is the command I ran and it reports 1.2 which I guess is the true speed whereas Apple markets it as having a 1.3 GHz processor.

**Comment by tuxudo** [comment]
It should also be noted that in the Hardware listing the CPU speed is correct. Only in the client tab summery where it shows the marketing name/speed is where it is incorrect.

**Comment by kevinmcox** [comment]
Interesting, I didn't notice that. Are those two listings pulling the data via different means?

**Comment by tuxudo** [comment]
Possibly, I haven't dug into where the current_processor_speed column data is sourced from.

**Comment by kevinmcox** [comment]
Gotcha. So either way this isn't a bug, MR is displaying what the system reports.

I guess it comes down to a question of consistency, do we want MR to show the same value in all places?
