### ISSUE TITLE
create table error in Listings > Power

### ISSUE THREAD

**Issue by markomili** [munkireport/munkireport-php#688]
When going to Listings > Power, on a fresh installation with mysql backend, it gives:

Create table 'power' failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'condition)' at line 1

**Comment by tuxudo** [comment]
This is fixed in PR #690
