### ISSUE TITLE
FR: Add module descriptions to the admin dropdown

### ISSUE THREAD

**Issue by nathanperkins** [munkireport/munkireport-php#714]
Hello,

In the past, I used `https://host/report/index.php?/install/dump_modules/config` to find the latest modules and add them to `config.php`. However, it only lists client-side modules. When combined with setting `$conf['hide_inactive_modules'] = TRUE`, MunkiReport ends up hiding views for server-only modules like `filevault_escrow`.

Bochoven suggests adding a page that shows the available modules and descriptions. It would help administrators discover new modules and configure as they like. I like that idea as well :)

Best,
Nathan

**Comment by tuxudo** [comment]
Maybe somehow have a link in the module's page that shows the ReadMe.md within module even.
