### ISSUE TITLE
Manufactured column sometimes wrong in Listing/Batteries

### ISSUE THREAD

**Issue by markomili** [munkireport/munkireport-php#716]
In /show/listing/power/batteries, when Designed column is "0 mAh" and Health is "0%", Manufactured column shows "Replace Now" instead of how long ago it was manufactured.

**Comment by tuxudo** [comment]
That is by design. The battery is not reporting any information correctly and OS X defaults to 1980-00-00 for the date of manufacture. Instead of reporting the 1980 value, it it changed to be Replace Now
