### ISSUE TITLE
Manifest editing

### ISSUE THREAD

**Issue by joshua-d-miller** [munkireport/munkireport-php#72]
Would there be a way we could add the ability to edit the manifest associated with the client like MunkiWebAdmin?

**Comment by gmarnin** [comment]
Has anyone started working on manifest reading / writing?

**Comment by bochoven** [comment]
@gmarnin Not that I know of, are you planning on writing an editor?

**Comment by gmarnin** [comment]
Writing an editor is currently above my current skill set. I would think the first step would be to do a read only view of the manifests similar to your catalog viewer. CFPropertyList is already available in munkireport as a starting place.

**Comment by mattiasvdm** [comment]
How about MunkiWebAdmin?

**Comment by bochoven** [comment]
I don't plan on adding this to MR in foreseeable future. MWA will handle this nicely
