### ISSUE TITLE
Model lookup failed

### ISSUE THREAD

**Issue by lolipale** [munkireport/munkireport-php#728]
Hello,

I started today with a new blank database.
Munkireport is unable to get the correct model of any workstation (see the file in attachment)
![screenshoot 11 21 03](https://cloud.githubusercontent.com/assets/13834698/24650222/d193bdc0-1929-11e7-8755-5cceecd688fc.png)
![capture d ecran 2017-04-04 a 11 32 44](https://cloud.githubusercontent.com/assets/13834698/24650458/892f4148-192a-11e7-9eef-a7857ad45ea0.png)

**Comment by bochoven** [comment]
Sometimes the apple servers are not reachable, if you press the reload button, does it get the model details?

**Comment by lolipale** [comment]
Not yet.
I will try later ... and post a new message.
Is it ok for you ?

**Comment by bochoven** [comment]
sure

**Comment by bochoven** [comment]
Hi Patrick,

Did you get this solved?

-Arjen

**Comment by davtay** [comment]
I'm getting this same issue.  Just got munkireport up and running today.

**Comment by bochoven** [comment]
@davtay this usually sorts itself out in a couple of hours, please let us know if it does not.

**Comment by davtay** [comment]
Still not sorted out.

**Comment by bochoven** [comment]
If you go to `https://km.support.apple.com/kb/index?page=categorydata&serialnumber=YOURSERIALNUMBER` replacing YOURSERIALNUMBER with the actual serial number, do you get the proper output?

**Comment by bochoven** [comment]
Oh and check if the server can reach the Apple servers as well

**Comment by davtay** [comment]
I do get the proper output from that url.  The server can also reach the Apple servers.  The server isn't accessible from the outside though.  Would that make a difference?

**Comment by davtay** [comment]
Here's the output too: { "id": "502599", "name": "MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports) ", "description": "", "urlpath": "macbookpro13inch2016fourthunderbolt3ports", "hasdownloads": false, "parent": "PL107" ,	"grandparent": "PF2", "greatgrandparent": "productcategory" }

It is supposed to be parsing the "name" field or the "description" field?

**Comment by bochoven** [comment]
You should be able to retrieve that url from the server, it should not matter if the server is not reachable.

**Comment by bochoven** [comment]
It retrieves the 'name' attribute

**Comment by davtay** [comment]
Any ideas about how to troubleshoot this more?

**Comment by bochoven** [comment]
Could you see what happens when you visit 

https://yourmrserver/index.php?/module/warranty/recheck_warranty/YOURSERIAL

**Comment by davtay** [comment]
It redirects me to the client details page. So http://yourmrserver/index.php?/clients/detail/YOURSERIAL

**Comment by bochoven** [comment]
And you still see the `model_lookup_failed` on the details page?

**Comment by davtay** [comment]
Yes I do.

**Comment by lolipale** [comment]
Hello,

Same problem and same answers

**Comment by bochoven** [comment]
Could you confirm that you have 'json support' enabled for php?

**Comment by davtay** [comment]
Yeah that is a standard part of macOS Server correct?  Is there a log file that would let me see what the error is exactly when the request for model is made?

**Comment by bochoven** [comment]
And also check for `allow_url_fopen` in 'Admin->System Status Extended PHP info

**Comment by davtay** [comment]
Confirmed that json support is enabled as is allow_url_fopen

**Comment by bochoven** [comment]
Could you test this standalone lookup script
[lookuptest.php.zip](https://github.com/munkireport/munkireport-php/files/977685/lookuptest.php.zip)

**Comment by gahel** [comment]
Same issue, tested you standalone lookup script and it returns:

`Array
(
    [appledata] => 
    [model] => model_lookup_failed
    [error] => 
)`

**Comment by diwanicki** [comment]
I can confirm I am getting the same results as gahel and davtay.

MR 2.15.2.2795 macOS 10.12.6 server 5.3.1

**Comment by diwanicki** [comment]
This is a macOS Sierra issue, as I can reproduce on my non-server MBP. The SSL options in config.php do not resolve - the cacert.pem from curl.haxx.se is treated as broken by keychain access and the security command, so resolutions using that option have failed for me as well.

**Comment by diwanicki** [comment]
so, for fun, I cloned my mac mini server to it's twin, upgraded to High Sierra, and the issue is resolved...

**Comment by realG** [comment]
I'm seeing the same issue on our system, and I *think* it only started after we upgraded our mac mini (acting as the backend server) from 10.12.4 to 10.12.6, or at least the first time I noticed the issue was on newly added clients a few days after the upgrade. Same as everyone else here I can also poll and get valid responses from **https://km.support.apple.com/kb/**

Is there anything we can do to fix this on 10.12.6? I don't want to jump on 10.13 just because of this issue.

On a slightly related note, is there a way to get rid of the warranty check completely from the client summary page:
![image](https://user-images.githubusercontent.com/1708326/33085585-f352d176-cedc-11e7-9427-71f39ef34eaa.png)
I don't have the warranty module enabled in the config and I have `$conf['hide_inactive_modules'] = TRUE;` set but if I understand the wiki correctly that only hides a dedicated Warranty "Listings" page...
