### ISSUE TITLE
Remove unsure menu items 

### ISSUE THREAD

**Issue by adambarnett52** [munkireport/munkireport-php#735]
Hi

It would be great if there was a way to remove unused menu items. For example the homebrew menu item. I don't use homebrew so I don't push that module out to clients, but it would be great if I could hide it in the menu. 

Thanks

**Comment by gmarnin** [comment]
You can do this now. Don't install modules you don't use and set `hide_inactive_modules` to TRUE -
https://github.com/munkireport/munkireport-php/blob/master/config_default.php#L85-L91

**Comment by adambarnett52** [comment]
Great, works perfectly

Thanks
