### ISSUE TITLE
Version number on the home page

### ISSUE THREAD

**Issue by lolipale** [munkireport/munkireport-php#741]
Hello,

It's seems that the version number is not up-to-date.
Isn't it ?

**Comment by bochoven** [comment]
Please upgrade to 2.13.2

**Comment by lolipale** [comment]
Hello,

Sure. I made this.
But the number is : MunkiReport Version 2.13.0.2657

**Comment by clburlison** [comment]
@lolipale You are correct. It was a minor text error with the release of 2.12.1. We simply forgot to bump the number before releasing. 2.12.2 has fixed this and included a secondary bug fix which is why we recommend updating to 2.12.2.
