### ISSUE TITLE
Support Microsoft SQL Server

### ISSUE THREAD

**Issue by gmarnin** [munkireport/munkireport-php#75]
In addition to SQLite and MySQL I would like to see full support for MS SQL (including database migrations)

**Comment by bochoven** [comment]
I don't see this created in the foreseeable future due to syntax differences between MSSQL and SQLite and MySQL. Most notable is the omission of the LIMIT clause http://stackoverflow.com/questions/603724/how-to-implement-limit-with-microsoft-sql-server
