### ISSUE TITLE
API documentation for HTTP REST requests

### ISSUE THREAD

**Issue by rsaeks** [munkireport/munkireport-php#751]
Current API documentation shows how to perform requests to the API via command line tools. Expanding these examples to HTTP REST formats would be very helpful.

**Comment by bochoven** [comment]
Could you be more precise in what you expect from these examples?

**Comment by rsaeks** [comment]
Would it be possible to show using a REST flow for getting inventory information about a device with serial number "SERIALNUMBER"? For example:

How to POST to obtain an auth cookie if that is used?
What is the URL format for performing a GET request?

Examples: 

- https://munkireportURL/index.php?/clients/detail/SERIALNUMBER for device inventory
- https://munkireportURL/index.php?/show/listing/power/batteries for battery 
- https://munkireportURL/index.php?/show/listing/network/network for network info

Even just a basic one on how to get device inventory would be a great start. I'm happy to work on some documentation, but just am not seeing the connection from command-line via bash / python. I've used the Chrome app Postman to work with REST APIs for jamfPRO and have had good luck.
