### ISSUE TITLE
Database Problem: Undefined index

### ISSUE THREAD

**Issue by DonHansDampf** [munkireport/munkireport-php#760]
I set up munkireport on CentOS 7 (SELinux disabled) with Apache2. Basic configuration so i am using sqlite:

```
<?php
$auth_config['xxx'] = 'xxx';

$conf['modules'] = array('appusage','ard','bluetooth','crashplan','directory_service','disk_report','displays_info','fan_temps','filevault_status','findmymac','fonts','gpu','homebrew','homebrew_info','installhistory','inventory','localadmin','managedinstalls','munkiinfo','munkireport','munkireportinfo','network','network_shares','power','printer','profile','sccm_status','security','softwareupdate','timemachine','usb','warranty','wifi');

$conf['auth_secure'] = FALSE;

$conf['debug'] = TRUE;
```

My clients didnt appear in munkireport so i enabled the debug mode. On the Dashboard i get the error: 

`Request Failed: parsererror, SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

The Apache2 error_log shows:

`[Wed Apr 26 12:47:36.530595 2017] [:error] [pid 22984] [client 10.0.100.2:49742] PHP Notice:  Undefined index: machine_groups in /var/www/html/app/helpers/site_helper.php on line 345, referer: http://munki.xxx.de/index.php?/show/dashboard`

I gave read/write access to the apache user so munkireport should be able to write to ./app/db/* (it also creates a db.sqlite so i think read/write access is not the problem).

Hope you can help me out!

**Comment by bochoven** [comment]
You probably need to log out and log in again.

**Comment by bochoven** [comment]
Do you have any updates on this issue?

**Comment by DonHansDampf** [comment]
Sorry for the super late answer... Somehow missed it. I wasn't able to get it working and also tried to log out/in so purged apache and tried it simply again. Now it works. I think i had some read/write problem in my apache-config.
