### ISSUE TITLE
GSX "Warranty Days Remaining" listing does not sort properly

### ISSUE THREAD

**Issue by flammable** [munkireport/munkireport-php#761]
Just noticed that if I view Listings > GSX, and sort by the Warranty Days Remaining column, the numbers don't sort properly - it doesn't recognize that 9 is a lower number than 989, for example.

Attaching screenshot.  Thanks!

<img width="248" alt="screen shot 2017-04-27 at 10 23 21 am" src="https://cloud.githubusercontent.com/assets/8499030/25487935/a187a24c-2b33-11e7-97ea-c95348a3d7f7.png">

**Comment by bochoven** [comment]
The `daysremaining` column should be an integer.

**Comment by tuxudo** [comment]
Should be fixed with PR #769

**Comment by flammable** [comment]
This one, too! Thanks, @tuxudo!
