### ISSUE TITLE
Localization issue with GSX/Warranty modules

### ISSUE THREAD

**Issue by flammable** [munkireport/munkireport-php#762]
We're using the GSX module, and, as recommended by @tuxudo, we have the Warranty module disabled (since Warranty would overwrite known-good data from GSX).  I've also set this in config.php:

`$conf['hide_inactive_modules'] = TRUE;`

I've noticed a visual bug when both of these things are true - viewing a machine's info page shows the warranty section is missing localization data.

Going to Show > GSX displays the correct warranty data, so that's been a good workaround - just reporting this, since it seems to be a bigger issue related to `hide_inactive_modules` and how GSX and Warranty share data.

Thanks!

<img width="497" alt="screen shot 2017-04-27 at 10 25 09 am" src="https://cloud.githubusercontent.com/assets/8499030/25488121/3564d7be-2b34-11e7-8ffc-51d7d0bd6b5e.png">

**Comment by tuxudo** [comment]
Should be fixed with PR #769. Fix is to enable Warranty and GSX modules. Warranty module has been changed to prevent processing if GSX module is also enabled.

**Comment by flammable** [comment]
Yep, fixed! Forgot to close this one. Thanks!
