### ISSUE TITLE
Security Listing: version numbers...

### ISSUE THREAD

**Issue by childrss** [munkireport/munkireport-php#773]
We took on a unit using an Apple software update server when their admin left (we get ours directly from Apple).

As such we have to stay on top of (more work) when Apple releases their antimalware updates. 

It would be very helpful if MunkiReport's security listing page included the version numbers of xprotext config data, Malware Removal Tool and Gatekeeper.

**Comment by tuxudo** [comment]
That information can currently be found in the Apple Software client tab. But having an Apple Software listing would be a good addition to MunkiReport.

**Comment by bochoven** [comment]
For XProtect: `defaults read /System/Library/CoreServices/XProtect.bundle/Contents/Resources/XProtect.meta.plist Version`

**Comment by childrss** [comment]
Thanks for the pointer! 

I checked out the Installed Apple Software on the individual client tab and found the following:

XProtectPlistConfigData -- always shows a version of 1.0
MRT Configuration Data -- appears to be valid @ 1.16
Gatekeeper - appears to be valid

While they're of use not having them in the security report/listing makes it difficult to see what is going on at the Enterprise level.  It could start by using Der Flounder/rtrouton's work here:

https://derflounder.wordpress.com/2016/03/28/checking-xprotect-and-gatekeeper-update-status-on-macs/

Which doesn't have everything, but DOES add in 'stat'ing the file to find out when it was last updated/appeared on the system, which seems very useful.

And adding in MRT.  
And if easiest dropping it into its own "Security - Apple" list would be ok.  But I think eventually having all of your Native OS security info all in one place/report would be the most logical.   Or at least that's what my guy that takes care of my daily ops (so I don't have to) tells me ;-)

Seeking input and I'll take a stab at it... thanks for the pointer Arjen!

**Comment by bochoven** [comment]
Gatekeeper: `defaults read /private/var/db/gkopaque.bundle/Contents/version CFBundleShortVersionString`
MRT.app: `defaults read /System/Library/CoreServices/MRT.app/Contents/version CFBundleShortVersionString`

**Comment by rickheil** [comment]
The XProtectPlistConfigData in the Installed Apple Software is reporting correctly - it pulls the version number out of /Library/Receipts/InstallHistory.plist. Looking in there, XProtect installs are shown with displayVersion key set to 1.0. The package identifier has a unique string but that doesn't correspond to the value in defaults read /System/Library/CoreServices/XProtect.bundle/Contents/Resources/XProtect.meta.plist Version, unfortunately.

I think it might be good to grab the three app versions independently in the security module instead of relying on InstallHistory, since it appears those are not 100% reliable. If you agree I can tinker with this later this week.

**Comment by childrss** [comment]
These methods work fine on 10.12 and 10.11, which I would say is enough for a good start on this module (thanks for the volunteer rickheil!).

On 10.10 and 10.9, it works only for Gatekeeper, not for MRT and Xprotect.  

From my recent background reading on the subject, for those versions admins were just checking for when the file was last updated:

https://gist.github.com/lazymutt/5a3e7b3631b073db5529722f857f54aa (outputs pretty formatted text)

Let me know if you need assistance debugging/testing!

**Comment by jelockwood** [comment]
@bochoven 
Any chance of you adding this as an additional module? I would certainly say that this information is becoming more useful. For example one could then more easily see which Macs have had the MRT update which protects against the Zoom dodgy web server vulnerability. :)

**Comment by tuxudo** [comment]
This data is collected and shown by the rewritten softwareupdate module shows this. I need to update the listing for it, but then it'll be ready to be merged

**Comment by jelockwood** [comment]
Thanks.
