### ISSUE TITLE
How can I remove a client from MunkiReport?

### ISSUE THREAD

**Issue by ado120** [munkireport/munkireport-php#775]
I have no idea how to remove a client on MunkiReport?

I am an admin in the php file. This is the version of MunkiReport that I am running:
MunkiReport Version 2.12.0.2338

Thanks!

**Comment by bochoven** [comment]
You need to be admin, then on any list view press the 'Edit' button. Now you can remove any client.

**Comment by ado120** [comment]
That's the problem.

I am an admin and I don't see the edit button on any list view?

**Comment by rickheil** [comment]
On any listing page, do you see these buttons on the top right side?

https://www.dropbox.com/s/2yvnzpj1xyi1pch/Screenshot%202017-05-09%2013.44.26.png?dl=0

**Comment by ado120** [comment]
https://snag.gy/qOlyp9.jpg

No edit button, that is all that I see. ^

**Comment by bochoven** [comment]
So you're not an admin user. Please check https://github.com/munkireport/munkireport-php/wiki/Authorization%2C-Roles-and-Groups

**Comment by ado120** [comment]
Hello Bochoven, I definitely set myself as an administrator in the config.php file

**Comment by ado120** [comment]
$conf['roles']['admin'] = array('auXXX, alexander');

Exactly how it looks in the config.php prior to opening this issue.. Any other ideas?

I Have enable business units set to false if that matters

**Comment by clburlison** [comment]
That could be the issue. Your array is incorrect php syntax. Try:

```php
$conf['roles']['admin'] = array('auXXX', 'alexander');
```

**Comment by ado120** [comment]
I was thinking that too after reviewing the documentation on git again. Let me try it and report back

**Comment by ado120** [comment]
Yep that fixed it, just a syntax issue.

Side-note if I delete a client that hasnt checked in for a few months, but the computer is turned on again and checks in.. will MunkiReport add it back?

**Comment by clburlison** [comment]
Yes if the computer tries to check back in MR will add it back to the database.

**Comment by ado120** [comment]
Awesome thanks everyone!
