### ISSUE TITLE
Munki Report through a reverse proxy

### ISSUE THREAD

**Issue by gigiwest123** [munkireport/munkireport-php#777]
Hi,
I have Munki set up internally across several sites, and at the moment I can only get pinpoint to send location services while on an internal network. I set up a reverse proxy but I can't make an installer to test it. 

laptop:~ admin$ bash -c "$(curl http://mywebsite.com/index.php?/install)" bash -i ~/Desktop -b http://mywebsite.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 33921    0 33921    0     0   148k      0 --:--:-- --:--:-- --:--:--  148k
Preparing /var/folders/jx/n92nzk9d4p1dmmvdw92ndr_c0000gq/T/mrpkg.Hy48MECg/install_root/usr/local/munki/
BaseURL is http://mywebsite.com
Retrieving munkireport scripts
curl: (7) Failed to connect to mywebsite.com port 8888: Connection refused
curl: (7) Failed to connect to mywebsite.com port 8888: Connection refused
curl: (7) Failed to connect to mywebsite.com port 8888: Connection refused
Failed to download all required components!

**Comment by bochoven** [comment]
You can customise the curl command in config.php

https://github.com/munkireport/munkireport-php/blob/master/config_default.php#L353-L369

**Comment by gigiwest123** [comment]
Hi Bochoven,
Thanks for answering. But I don't really understand how I would customise it. Is there further documentation I can refer to?

**Comment by bochoven** [comment]
You can add this line to `config.php` and add options where necessary:

```
$conf['curl_cmd'] = array(
		"/usr/bin/curl",
		"--fail",
		"--silent",
		"--show-error");
```

From the curl manpage:

```-x, --proxy <[protocol://][user:password@]proxyhost[:port]>

     Use the specified HTTP proxy. 
     If the port number is not specified, it is assumed at port 1080.```
