### ISSUE TITLE
Cache file creation after upgrade

### ISSUE THREAD

**Issue by zordanarres** [munkireport/munkireport-php#823]
With the latest 2.14.3 release, but also during earlier 2.13 releases, I'm experiencing an issue with the cache files located /usr/local/munki/preflight.d/cache when enabling additional modules as part of an upgrade.
munkireport does not create missing files, but rather fails with an "Can't open ..." error message. If I run the respective script manually using sudo, the cache file is created without issue. It also works if I do a fresh install on a new machine after enablement of the additional modules.

Is anyone experiencing the same issue or is there a best-practice approach to enable new modules on an existing installation base?

**Comment by tuxudo** [comment]
That is normal for machines that don't have the caching service turned on. The caching module is designed to only be used on a Mac running Server.app's caching service. Running it on a regular Mac will generate that harmless error.

**Comment by zordanarres** [comment]
Thanks. I might be wrong but to me it looks like that the files in the above directory are created by the various scripts in preflight.d as temp and used to upload the information to munkireport - rather than being specific to the caching service (e.g. /usr/local/munki/preflight.d/cache/displays.txt)?

**Comment by tuxudo** [comment]
I misread your first message. How are you running MunkiReport? It should always be run as root/sudo and is generally done so my Munki.

**Comment by zordanarres** [comment]
When running the scripts manually using sudo (e.g. sudo /usr/local/munki/preflight.d/wifi), the files get created as they should. 
Just leaving it to the regular munki-run seem to cause the issue. That said, I assume munki runs with privileged rights as well ...?

For reference, this is how the permissions in my /usr/local/munki/preflight.d look like:
`drwxr-xr-x  33 root  wheel  1122 26 Mai 10:14 .`
`drwxr-xr-x  21 root  wheel   714 26 Mai 10:12 ..`
`-rwxr-xr-x   1 root  wheel   915 26 Mai 09:54 appusage`
`-rwxr-xr-x   1 root  wheel  2595 26 Mai 09:54 bluetooth.py`
`drwxr-xr-x  28 root  wheel   952 31 Mai 20:09 cache`
`-rwxr-xr-x   1 root  wheel   508 26 Mai 09:54 caching`
`-rwxr-xr-x   1 root  wheel  3558 26 Mai 09:54 cert_check`
`-rwxr-xr-x   1 root  wheel  2035 26 Mai 09:54 directoryservice.sh`
`-rwxr-xr-x   1 root  wheel  8355 26 Mai 09:54 disk_info`
`-rwxr-xr-x   1 root  wheel  2962 26 Mai 09:54 displays.py`
`-rwxr-xr-x   1 root  wheel  5496 26 Mai 09:54 fan_temps.sh`
`-rwxr-xr-x   1 root  wheel   354 26 Mai 09:54 filevaultstatus`
`-rwxr-xr-x   1 root  wheel  1427 26 Mai 09:54 findmymac.sh`
`-rwxr-xr-x   1 root  wheel  4430 26 Mai 09:54 fonts.py`
`-rwxr-xr-x   1 root  wheel  2979 26 Mai 09:54 gpu.py`
`-rwxr-xr-x   1 root  wheel   504 26 Mai 09:54 localadmin`
`-rwxr-xr-x   1 root  wheel  4656 26 Mai 09:54 munkiinfo.py`
`-rwxr-xr-x   1 root  wheel  2311 26 Mai 09:54 network_shares.py`
`-rwxr-xr-x   1 root  wheel   561 26 Mai 09:54 networkinfo.sh`
`-rwxr-xr-x   1 root  wheel  7900 26 Mai 09:54 power.sh`
`-rwxr-xr-x   1 root  wheel  1829 26 Mai 09:54 printer.py`
`-rwxr-xr-x   1 root  wheel  2273 26 Mai 09:54 profile.py`
`-rwxr-xr-x   1 root  wheel  7096 26 Mai 09:54 security.py`
`-rwxr-xr-x   1 root  wheel  5045 26 Mai 09:54 servermetrics.py`
`-rwxr-xr-x   1 root  wheel  1171 26 Mai 09:54 servermetrics.sh`
`-rwxr-xr-x   1 root  wheel   800 26 Mai 09:54 service_check`
`-rwxr-xr-x   1 root  wheel  2674 26 Mai 09:54 softwareupdate.sh`
`-rwxr-xr-x   1 root  wheel  1919 26 Mai 09:54 submit.preflight`
`-rwxr-xr-x   1 root  wheel  4345 26 Mai 09:54 timemachine`
`-rwxr-xr-x   1 root  wheel  3146 26 Mai 09:54 usb.py`
`-rwxr-xr-x   1 root  wheel  3814 26 Mai 09:54 user_sessions.py`
`-rwxr-xr-x   1 root  wheel   598 26 Mai 09:54 warranty`
`-rwxr-xr-x   1 root  wheel  3323 26 Mai 09:54 wifi`

I also did some additional testing: if I delete a cache file it gets re-created but ONLY if the module was enabled at the time the machine got the first munkireport package installed. If I delete a cache file of a module which was enabled at a later time, re-creation fails. 

As an example: let's assume I had all plugins activated except user_sessions when doing the first installation on a machine. As part of a munkireport-update, I also enabled user_sessions and created a new package which was deployed to the device. Although the respective script and hooks are installed correctly, the muni-run fails repeatedly to create user_sessions.plist.
The only way to fix this issue is to manually run sudo user_sessions.py.

Is there maybe some "execution cache" file somewhere munkireport is using which is not removed correctly by the installation package?

**Comment by bochoven** [comment]
A 'normal' munki run calls `sudo /usr/local/munki/preflight` which will create a couple of files in the cache folder. After munki is finished, it will call `sudo /usr/local/munki/postflight` which checks the files for changes and uploads them to the munkireport server when changed.

It would help if you could post the output of both preflight and postflight.

**Comment by zordanarres** [comment]
I was trying to re-create the issue I've seen after the update, but for whatever reason it now works on all machines (maybe some timing/caching problem?). 

As it runs successfully even when I empty the whole cache folder, I will close this issue and re-open in case I find a way to reliably re-produce the problem
