### ISSUE TITLE
Memory is displayed as GB even if it's actually MB

### ISSUE THREAD

**Issue by davidmnelson** [munkireport/munkireport-php#824]
Anywhere a machine's installed memory is displayed (client detail, hardware report, etc.) the units are falsely assumed to be GB. We have a small number of machines with only 512MB RAM, but MunkiReport shows them having 512GB.
![512gb](https://cloud.githubusercontent.com/assets/4750692/26652367/8d9bb854-4604-11e7-82d2-47cd70b6ba44.png)

**Comment by bochoven** [comment]
Physical memory is stored as an integer, so for 512 MB it would either be 0 or 1.

**Comment by bochoven** [comment]
As silly as it is, I'm closing this. I don't think there are many machines left with < 1GB memory
