### ISSUE TITLE
check_in gets HTTP returncode 500 (internal server error) with deploystudio module enabled

### ISSUE THREAD

**Issue by matt-cahill** [munkireport/munkireport-php#826]
My clients can't check in if I enable the deploystudio module, debug output gives this:
```
<b>Fatal error</b>:  Call to undefined function munkireport\module\deploystudio\curl_init() in <b>/srv/macdeploy/munki/report/app/modules/deploystudio/lib/deploystudio_helper.php</b> on line <b>81</b><br />
```

ubuntu 14.04 PHP version:
```
php5-fpm --version
PHP 5.5.9-1ubuntu4.13 (fpm-fcgi) (built: Sep 29 2015 15:28:48)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

**Comment by bochoven** [comment]
You need the curl library enabled in php: http://php.net/manual/en/book.curl.php

**Comment by matt-cahill** [comment]
Ah ok, thanks @bochoven! That seems to have fixed it up.
As an aside the deploystudio page for a host that isn't in the deploystudio database gives me another 500 for an uncaught exception, should I drop in another issue?
