### ISSUE TITLE
Remote IP Address issue

### ISSUE THREAD

**Issue by 41john** [munkireport/munkireport-php#827]
Since moving a few Macs from being managed by Workgroup Manager to Profile Manager the devices managed by Profile Manager report the Remote IP Address incorrectly.

I have compared the proxy profile formally deployed via WGM against PM and it seems to be the same.

The incorrect Remote IP address listed is now displaying the IP of the proxy server.

Is the Remote IP address necessary since it seems to sometimes be incorrect when behind NAT/Proxy?  Why not just use the data from the Network Tab?

**Comment by bochoven** [comment]
Not sure what your request is. Do you want to show the network IP data on the summary page?

**Comment by 41john** [comment]
Sorry if I wasn't clear. I was questioning the purpose of the remote IP address since in some scenarios it seems to be incorrect.

Is it possible to show the Network IP data instead of Remote IP data both in the summary page and in any other places where Remote IP is used such as Listings>Munki Report, and Reports>Network>Network Location.

Alternatively what options are there to ensure that the Remote IP is always accurate?

Hope that makes more sense?

**Comment by bochoven** [comment]
Remote IP is REMOTE_ADDR which is the address that the Munkireport server 'sees' as the client IP address. If there's a (reverse) proxy header, munkireport will use that value instead. I don't understand why you think that address is not accurate. The network IP data is much harder to use:
- most of my clients are behind some sort of NAT which means they have a private IP address
- clients can have multiple IP adresses (ethernet, WiFi, thunderbolt ethernet, etc.) at the same time which makes it hard to determine which address to use.

Showing multivalued entries in listings would make them much more cumbersome.

**Comment by 41john** [comment]
I appreciate your feedback on this.

I guess I deem it inaccurate because when I look at a client's summary page, Listings>Munki, or Reports>Network>Network Location all devices are reporting the proxy server address instead of their own address. Clearly having a load of devices all listing the proxy server in this environment is not helpful. Bizarrely, it use to report correctly before managing the clients with Profile Manager. Maybe I will need to investigate why this is happening and see if I can stop it happening.

I do understand your comment about a client with multiple IP addresses and the difficulties displaying this. I also understand that in most environments this is likely to be reporting back the client's primary IP address correctly rather than the proxy server address.

I guess if it is possible it would be great to modify the value for Remote IP via the config.php file for environments where all clients are listing the same proxy server address and messing up reports etc. Maybe it could be possible to change it to an active interface, with an option to choose the preferred interface if multiple are available?

**Comment by danlockcuff** [comment]
I am with @41john I would like to have the ip address for the different interfaces displayed in the dashboard. 90% of my fleet is behind a network that I have vpn access too, so it would be nice to see what the IP is on the interface so I know where to ssh into. It would be nice in the ssh dropdown to be able to choose the interface you want to ssh into as well. 
Thanks
