### ISSUE TITLE
Data Tables not displaying in Dashboard or in Reports

### ISSUE THREAD

**Issue by joshua-d-miller** [munkireport/munkireport-php#845]
After some troubleshooting it seems I am unable to display the following Modules:
- Events
- Hardware Model Breakdown
- Local Admins
- Pending Apple Updates
- Pending Munki Updates

I have looked in the actual reports and they do not display there either. I also noticed that there is actually data in the database so the clients are sending this information.

The server setup I'm using is as follows:

OS: CentOS 7
Web Server: Nginx
PHP Version: 7 using php-fpm
Database: MySQL

Below is an except from my server block that also serves munki on 443 and has a redirect for MWA2 product icons at /icons.

    location /report {
      try_files                     $uri $uri/ =404;
    }

    location ~ \.php$ { # PHP Settings for MunkiReport-PHP
        try_files                   $uri =404;
        fastcgi_split_path_info     ^(.+\.php)(/.+)$;
        fastcgi_pass                php-fpm;
        fastcgi_index               index.php;
        include fastcgi_params;
        fastcgi_param   SCRIPT_FILENAME   $document_root$fastcgi_script_name;
        fastcgi_intercept_errors    on;
        access_log /var/log/nginx/munkireport-access.log;
        error_log /var/log/nginx/munkireport-error.log;
    }

**Comment by bochoven** [comment]
Is this still an issue?

**Comment by joshua-d-miller** [comment]
Wow I did not realize this was still open. Please close this
