### ISSUE TITLE
Documentation add on request

### ISSUE THREAD

**Issue by vendettarwb** [munkireport/munkireport-php#846]
Client setup it may be useful for people to al least have a note that set up their url as such: 

http://example.com/report/

bash -c "$(curl http://example.com/report/index.php?/install)" 

At least as a noob this caused me a bit of frustration in the first run test

I would get to this part and started thinking I botched a config file somewhere, or didn't set up the nginx portion properly just trying to save another noob from having this happen :)

Although I am grateful for the experience it gave me setting up the server multiple times.

**Comment by bochoven** [comment]
You can edit the wiki if you have a GitHub account
