### ISSUE TITLE
munki errors not updating

### ISSUE THREAD

**Issue by levmeetup** [munkireport/munkireport-php#86]
hello,
i'm fairly new to munkireport-php, but it's a great tool. i've installed it successfully to report our munki data, but i'm having a small issue. i've been updating clients with new Manifest information and rolling out Munki client updates, but even though munkiwebadmin is showing they've been updated and are running the new version and have all the updates installed, munkireport still shows the old data. is there a way to force the machine to talk back to munkireport to force the data to update?
thanks in advance for the help.

lev

**Comment by TryTryAgain** [comment]
Can you please point me in the direction of: "You need to take extra measures to have a client report to MWA and MR at the same time." ...I thought nothing's changed, but now I'm seeing that content is not updating in MR, but it still is in MWA.

**Comment by clburlison** [comment]
@TryTryAgain  MunkiReport uses Munki's `preflight` and `postflight` scripts located at `/usr/local/munki/`. MunkiWebAdmin also uses those same scripts. If you want both reporting instances to get updated at the same time you'd need to follow something like https://grpugh.wordpress.com/2014/11/07/making-munkireport-php-and-munkiwebadmin-work-nicely-together/
