### ISSUE TITLE
messages widget cannot be loaded if inactive modules are hidden

### ISSUE THREAD

**Issue by diwanicki** [munkireport/munkireport-php#861]
if you set $conf['hide_inactive_modules'] = TRUE; in config.php, the messages widget on the dashboard will error out with "Unknown widget" "messages This widget cannot be found"

It's extremely useful to have the messages widget display Events, but still hide all of the modules we are not using in our environment. I am running this in a docker instance, but do not believe this would have any affect on the issue. Events report and show in the messages widget just fine when "hide" is set to FALSE.

MR v 2.14.0.2785

**Comment by rickheil** [comment]
You can resolve this by adding the "event" module to your list of enabled modules.
