### ISSUE TITLE
CAS Integration

### ISSUE THREAD

**Issue by danner26** [munkireport/munkireport-php#862]
Hello,

I work at a local university in New Jersey, which we have setup Munki. We use Munki extensively on all of our macs, and we are looking to setup MunkiReport-php. Right now, I have setup a PROD and PPRD system for testing, but we need to find a way to integrate CAS so we can use our auth servers for login. Is this something you are planning on integrating or might be able to help me with?

I was looking at different ways that CAS could be integrated, but I hit a few issues when configuring it.

**Comment by danner26** [comment]
I forgot to mention we are using NGINX as the web server proxy, which is standard in our environment.

**Comment by bochoven** [comment]
I rewrote the whole authentication section quite heavily. It should be easier to integrate CAS authentication, but I don't know much about the innards of CAS. I tried spinning up a docker CAS server but got stuck on configuring it. If you could provide a working CAS setup for testing, I could be of more assistance.

**Comment by danner26** [comment]
I'm not sure how you setup the CAS server, but if you could give me access to the server or a VM I can install/configure CAS for you to work with. I dont have any spare instances that aren't already being used for production at the moment.

**Comment by bochoven** [comment]
I set up this server: https://github.com/leo108/php_cas_server
I can get the following response: 

```Successful Authentication!

Current script
index.php
session_name():
session_for:index_php
session_id():
ST-ChL2dxXTcymf4J1pWk2mlldZYMpYE
the user's login is admin.

phpCAS version is 1.3.5.

phpCAS attributes are Array ( [email] => admin@admin.com [real_name] => admin [oauth_profile] => null ) .
```
Not sure how to convert that to groups. Could you share your attributes.

**Comment by danner26** [comment]
What about still having local groups and just match usernames, so for example: 
$conf['roles']['admin'] = array('administrator', );

Where administrator is a CAS user account.

I havent had any spare time to get you responses, but if you still need it I will try to ASAP.

**Comment by bochoven** [comment]
Yes, that would be fine..

**Comment by danner26** [comment]
If you have an idea that you think is better than that, let me know so we can brainstorm. Do you have a branch for the CAS installation by any chance?

**Comment by bochoven** [comment]
No branch yet, I just made some test instances for the CAS server and client. I used this library for the client: https://github.com/apereo/phpCAS

**Comment by danner26** [comment]
Did you ever figure anything out for CAS? If you have any code that integrates the module already I can mess around with it if you dont have time.

**Comment by danner26** [comment]
By the way we use this version: https://apereo.github.io/cas/5.2.x/index.html

**Comment by danner26** [comment]
Have we made any headway on this? We would really love this integration.

Also, we use a custom attribute for our SSO authentication called something like ERP_ID, so as long as there is integration for mapping custom attributes we will be set.

**Comment by danner26** [comment]
Do you have a branch for this somewhere? If so, I can start working on it when I have time since I know you are quite busy.
