### ISSUE TITLE
ADFS Integration

### ISSUE THREAD

**Issue by danner26** [munkireport/munkireport-php#866]
Hello,

This is a spin off of another ticket I created: #862 

I work at a local university in New Jersey, which we have setup Munki. We use Munki extensively on all of our macs, and we are looking to setup MunkiReport-php. Right now, I have setup a PROD and PPRD system for testing, but we need to find a way to use ADFS OR CAS. Either solution would definitely fix our issue, but we would much prefer the CAS solution. As I said in the other ticket, I have CAS kind of working, but not fully.

**Comment by bochoven** [comment]
If you could share what you have, maybe others can assist.

**Comment by bochoven** [comment]
I'm working on SAML support, maybe you could check out https://github.com/munkireport/munkireport-php/tree/saml

**Comment by danner26** [comment]
Sure, when I get some time ill take a look. SAML might work for us until we figure out the CAS integration. In the end that would be our prefered way to authenticate. Thank you!

**Comment by bochoven** [comment]
SAML authentication branch has been merged with the wip branch. https://github.com/munkireport/munkireport-php/tree/wip

**Comment by danner26** [comment]
Any idea when WIP will be released to master?
