### ISSUE TITLE
Blank client detail page after updating munkireport from 2.13.2 to 2.15.0

### ISSUE THREAD

**Issue by bubumannus** [munkireport/munkireport-php#871]
Turned on migration option on
Turned debug on

Turn short tag on in php.ini (php version 5.6.15)
Turned error/debug on in php.ini

no error in httpd log, no error on browser screen, no error in php log

I saw it happened to other users. But none of their solutions work for me.

Any ideas? Thank you.

**Comment by bochoven** [comment]
Things you could try: Force reload the page or open in another browser. Usually it is the caching of some javascript file that is not current anymore.

**Comment by bubumannus** [comment]
Tried in a incognito chrome windows, no luck. 

Updated 2.13.2 to 2.14.3, the client list and detail showed up correctly.

The problem only happens to 2.15.0.

**Comment by bochoven** [comment]
Check the web console for errors.

**Comment by bochoven** [comment]
Could you test if https://github.com/munkireport/munkireport-php/releases/tag/v2.15.1 resolves the issue?

**Comment by bochoven** [comment]
Please reopen if the issue persists.

**Comment by bubumannus** [comment]
Thank you, Bochoven. I will stay with 2.14.3 for the time being, but will keep you updated if I upgrade it to version 3 later. Again, thank you for your timely advice and help.
