### ISSUE TITLE
CrashPlan Errors in the Event Module

### ISSUE THREAD

**Issue by gmarnin** [munkireport/munkireport-php#879]
The Events module is showing `crashplan crashplan.backup_failed` on Macs where CrashPlan hasn't failed. Some Macs show `The backup destination was disconnected` but that message should not show up as a fail in the Events module. Basically seeing a lot of false positives.

**Comment by bochoven** [comment]
Could you share a csv file from a machine that is showing a false positive?

**Comment by gmarnin** [comment]
From `/usr/local/munki/preflight.d/cache/crashplan.txt`:

`destination,start,last_success,duration,last_failure,reason
[12mor101m1 Backup],1508328900,1508273580,27480,1508328900,The backup destination was disconnected`

![screen shot 2017-10-18 at 8 51 14 am](https://user-images.githubusercontent.com/815125/31719542-d163153c-b3e1-11e7-974a-c16867c87ed6.png)
 
![screen shot 2017-10-18 at 8 50 58 am](https://user-images.githubusercontent.com/815125/31719535-cba6db88-b3e1-11e7-9086-ff04f6577f1c.png)

**Comment by bochoven** [comment]
This looks like a true positive? What are you proposing? Only show an event when x hours have passed since the last successful backup?

**Comment by gmarnin** [comment]
The event module should show the actual message. In this case, `The backup destination was disconnected` instead of `crashplan.backup_failed`. The icon should probably also be changed from the red x to the yellow triangle.

**Comment by gmarnin** [comment]
Here's another example from a different Mac. The Events module is showing `crashplan.backup_failed` but the CrashPlan report on the client details page shows `Nothing to do`

`gtv714m1 (ip address)
destination,start,last_success,duration,last_failure,reason
[Default],1508503380,1508446380,0,1508503740,Nothing to do`

![screen shot 2017-10-20 at 8 54 09 am](https://user-images.githubusercontent.com/815125/31821860-84bb1b28-b574-11e7-99ce-d13dd6438a54.png)

![screen shot 2017-10-20 at 8 54 00 am](https://user-images.githubusercontent.com/815125/31821869-8c55da30-b574-11e7-99e7-21b23455ef80.png)

**Comment by gmarnin** [comment]
The new [event filter](https://github.com/munkireport/event/blob/master/README.md#configuration-file) in versions 4.1.3 allows me to filter out all Crashplan events.
