### ISSUE TITLE
Adjust column width computer name tab

### ISSUE THREAD

**Issue by pnerum** [munkireport/munkireport-php#88]
Is it possible to make the column for the computer name resizable?
Our computer names are quite long and also contains the location in the name. As you can see in the screenshot.
![screen shot 2014-03-25 at 11 26 11](https://f.cloud.github.com/assets/2464284/2511563/397b2648-b41b-11e3-986c-307896793a20.png)

regards,

Patrick

**Comment by YehudaBialik** [comment]
Worked like a charm!  Sorry to reopen if I did.
