### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by thorntonbp** [munkireport/munkireport-php#881]
Hi All,

After an upgrade I've got an SQL error. I have see https://github.com/munkireport/munkireport-php/issues/292 which looks similar and have enabled migrations in config.php. I am running v2.15.2. This is the first update in about 3 years so it is possible I have missed some steps in the upgrade path that could have caused this issue. I have updated my local client machine (https://github.com/munkireport/munkireport-php/wiki/Client-setup) and migrated my config.php settings to the new template in v2.15.2. 

Any ideas?

This is from my error log on the the client:

Server info: starting: reportdata
Server An error occurred while processing: \Disk_report_model
Server Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'media_type' in 'field list'
Server info: starting: disk_report
Server danger: Migration error: diskreport: Only migrate in admin session
Server info: starting: munkireport
Server info: starting: profile

**Comment by bochoven** [comment]
You need to log in as admin, enable migrations and visit the diskreport listing

**Comment by thorntonbp** [comment]
Hi bcchoven, 
Many thanks for the reply. I've done that and the page just returns blank. 
I have AD authentication set up and was slightly paranoid this was resulting in not being admin so added in a local user:
$auth_config['admin'] = '$XXXXXXXZXXXXXXXXXXXXXXXXXXX';
With role based authentication:
        $conf['authorization']['global'] = array('admin');
And added the admin user to the role:
        $conf['roles']['admin'] = array('admin');

And then verified it was admin via /index.php?/auth/set_session_props/1:
{"user":"admin","groups":[],"auth":"config","role":"admin","role_why":"admin in \"admin\" role array","machine_groups":["0"],"theme":"Yeti"}

Are there any debug logs on the server I can turn on? I and set debug in config.php but there is a lack of server side logging on my deployment.

I'm probably missing something obvious but any pointers would be much appreciated.

**Comment by thorntonbp** [comment]
I should add that the system is going from version 2.0.11.812 to 2.15.2.2795.

**Comment by thorntonbp** [comment]
Dropping the diskreport table fixed this issue as per the advice on this thread: https://groups.google.com/forum/#!topic/munkireport/9eqcMTBF1CQ
