### ISSUE TITLE
Migration error: network: SQLSTATE[42000]: Syntax error or access violation

### ISSUE THREAD

**Issue by hjuutilainen** [munkireport/munkireport-php#89]
I'm getting the following errors after upgrading from 2.0.5 to the latest version:

    Sending items
    Server info: starting: warranty
    Server info: warranty: current status: Unregistered serialnumber
    Server info: warranty: new status: Unregistered serialnumber
    Server info: starting: installhistory
    Server info: starting: localadmin
    Server info: starting: network
    Server danger: Migration error: network: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
    Server info: starting: disk_report
    Server info: starting: filevault_status
    Server info: starting: munkireport
    Server info: starting: reportdata
    Server info: starting: directory_service
    Server info: starting: inventory
    Server danger: Migration error: inventoryitem: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
    Done.

When viewing clients in browser I get the same error:

    Migration error: inventoryitem: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
    Migration error: network: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

We're using MySQL and we have the '$conf['allow_migrations'] = TRUE;' in config.php. Would this be a bug or a configuration problem in our end? Everything else in MR is working fine.

**Comment by bochoven** [comment]
I'm closing this one as it does not seem to be an issue anymore.
