### ISSUE TITLE
Migration error: reportdata: SQLSTATE[HY000]: General error: 1 duplicate column name: uptime

### ISSUE THREAD

**Issue by andrewvalentine** [munkireport/munkireport-php#899]
Hi,

I've upgraded to MunkiReport 2.15.2, and I'm now seeing this error:

<img width="1270" alt="screen shot 2017-11-24 at 09 10 06" src="https://user-images.githubusercontent.com/5181124/33203276-648a0dde-d0f7-11e7-9e57-04f1409d70ed.png">

I'm using sqlite 3.7.17 and my config.php is set to allow migrations.

Looking at similar closed issues, it seems that ways of resolving this may be:

* Removing sqlite.db and allowing client check ins to rebuild it

* Running a command like:

```
sqlite3 /path/to/db.sqlite

sqlite> UPDATE migration SET version = 3 WHERE table_name = 'uptime';
```

Is my understanding correct? If so, is either resolution preferable? If not, do you know what might be going on here?

**Comment by bochoven** [comment]
Something went wrong with the migration. The reportdata table was migrated to version 3 but that did not get recorded in the migrate table. Running `UPDATE migration SET version = 3 WHERE table_name = 'reportdata';` should fix that.

**Comment by andrewvalentine** [comment]
Yep, that solved it. Thanks for your quick response.
