### ISSUE TITLE
laravel - illuminate/database migration proposal

### ISSUE THREAD

**Issue by mosen** [munkireport/munkireport-php#900]
Hi guys,
As you know i got the idea to rewrite munkireport from scratch. Unfortunately the task was just too gargantuan, with the scope increasing all the time.

So, I decided one possible way of migrating out of kissmvc to laravel would be to adopt one piece at a time. Many of the parts of the laravel framework can be used standalone.

I wanted to make sure that everyone was actually on board for this plan. so I'm making this issue an open discussion.

The plan at this stage is to adopt the Illuminate/Database part of the Laravel framework which would replace migrations, and eventually sql queries. # #

**Comment by bochoven** [comment]
I'm in favour of this change, but I think it is a good idea to keep track of the pros and cons.

PROS

- Structured DB setup
- DB abstraction will open up the possibility to use other backends like PosgreSQL or MSSQL
- Controlled migrations
- Simpler DB syntax for developers

CONS

- DB setup (creating tables) does not happen automatically anymore
- Performance - adding a layer has some negative influence on performance
- Existing documentation needs to be revised

**Comment by bryanzak** [comment]
I would try to make it a goal for zero performance regression.

We have 20,000 computers in MunkiReport, and it would not surprise me if there were even larger implementations out there. I really don’t want to face performance regressions.

Bryan

**Comment by mosen** [comment]
I understand your concern Bryan. I don’t think that performance is so black and white though. Any added feature has the potential to have a performance impact, therefore it’s better to quantify the impact and weigh it against the benefits. If there are no optimisations to be made, the only way to have zero performance impact is to add no features. In which case id just tag the repo and back port hot fixes only.

**Comment by n8felton** [comment]
I personally have never used Laravel, however, I have a number of colleagues that use it and are actively still building apps in it. I'm all about using widely adopted frameworks, or at least ones that are adopted in my circle of peers.

I only ask that we take a look at all of the existing db tables and work on getting them closer to 3NF, if possible. While trying to write some custom reports using SQL, I noticed there are some tables that could use some... TLC.

**Comment by rickheil** [comment]
Agree with you on all counts Nate. This will provide a good opportunity to rework any tables that have grown in strange ways.

**Comment by bochoven** [comment]
Migrations are in place.
