### ISSUE TITLE
SAML auth breaks AutoPkg recipe

### ISSUE THREAD

**Issue by rickheil** [munkireport/munkireport-php#937]
Enabling auth_saml makes AutoPkg redirect to the SSO sign in page instead of downloading the packager script.

**Comment by bochoven** [comment]
I can't replicate the issue. Are you using the correct path for the recipe? (pointing to the `public` directory)

**Comment by DCoobs** [comment]
SAML & AutoPkg recipe seem to be working fine for us

**Comment by rickheil** [comment]
This is working for me now too - this was either some weird config error or a problem that only existed in an untagged version of WIP.
