### ISSUE TITLE
[3.x] Missing semicolon leads to unusable LDAP auth.

### ISSUE THREAD

**Issue by MatthiasKuehneEllerhold** [munkireport/munkireport-php#944]
In https://github.com/munkireport/munkireport-php/blob/wip/app/lib/munkireport/AuthLDAP.php#L34 there is a missing semicolon which leads to 500 server error on index.php?/auth/login

Version used: 3.0.0RC1, still present in branch "wip"

**Comment by poundbangbash** [comment]
@bochoven This can be closed.  It has been addressed in the 3.1 release.
