### ISSUE TITLE
[3.x] Class 'munkireport\models\Machine_group' not found

### ISSUE THREAD

**Issue by MatthiasKuehneEllerhold** [munkireport/munkireport-php#945]
Error: Class 'munkireport\models\Machine_group' not found in /x/munki/app/lib/munkireport/AuthHandler.php:193 
Stack trace: 
#0 /x/munki/app/lib/munkireport/AuthHandler.php(37): munkireport\lib\AuthHandler->setSessionProps() 
#1 /x/munki/app/controllers/auth.php(74): munkireport\lib\AuthHandler->login('', '') 
#2 /x/munki/system/kissmvc_core.php(88): munkireport\controller\Auth->login() 
#3 /x/munki/system/kissmvc.php(17): KISS_Engine->__construct(Array, 'show', 'index', 'AUTO') 
#4 /x/munki/public/index.php(147): Engine->__construct(Array, 'show', 'index', 'AUTO') 
#5 {main}

Version used: 3.0.0RC1

**Comment by bochoven** [comment]
Did you run `composer install --no-dev --no-suggest --optimize-autoloader`

**Comment by MatthiasKuehneEllerhold** [comment]
Yes. The file was also present on the filesystem...

**Comment by bochoven** [comment]
Does `grep -R Machine_group vendor/composer/` give any result?

**Comment by MatthiasKuehneEllerhold** [comment]
Just checked out the newest commit of the branch "wip" and installed it via composer.
This error only happens if auth is disabled (via `conf['auth']['auth_noauth'] = [];` in config.php) and only on the FIRST request to `index.php?/auth/login`. Second request redirects me to the dashboard.

```
$ grep -R Machine_group .
./vendor/composer/autoload_classmap.php:    'munkireport\\models\\Machine_group' => $baseDir . '/app/models/machine_group.php',
./vendor/composer/autoload_static.php:        'munkireport\\models\\Machine_group' => __DIR__ . '/../..' . '/app/models/machine_group.php',
./app/controllers/unit.php:use munkireport\models\Machine_group;
./app/controllers/unit.php:            $mg = new Machine_group;
./app/controllers/unit.php:                } else // Not in Machine_group table
./app/controllers/unit.php:            $mg = new Machine_group;
./app/controllers/admin.php:use munkireport\models\Machine_group;
./app/controllers/admin.php:        $machine_group = new Machine_group;
./app/controllers/admin.php:            $machine_group = new Machine_group;
./app/controllers/admin.php:                $mg = new Machine_group;
./app/controllers/admin.php:            $mg = new Machine_group;
./app/controllers/admin.php:                            $mg = new Machine_group;
./app/controllers/admin.php:        $mg = new Machine_group;
./app/views/admin/business_units.php:					// Reload Machine_groups
./app/helpers/site_helper.php:use munkireport\models\Machine_group, munkireport\lib\Modules;
./app/helpers/site_helper.php:    $machine_group = new Machine_group;
./app/lib/munkireport/AuthHandler.php:use munkireport\models\Machine_group;
./app/lib/munkireport/AuthHandler.php:                $mg = new Machine_group;
./app/models/machine_group.php:class Machine_group extends \Model
```

**Comment by bochoven** [comment]
I cannot replicate the issue, what OS/server are you installing on?

**Comment by MatthiasKuehneEllerhold** [comment]
```
Linux xy 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux

Apache/2.4.25 (Debian)
via PHP7.2-FPM

PHP 7.2.1-1+0~20180105151615.16+stretch~1.gbpd3910a (cli) (built: Jan  5 2018 15:16:17) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.2.1-1+0~20180105151615.16+stretch~1.gbpd3910a, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by MatthiasKuehneEllerhold** [comment]
AH!
```
vendor/composer/autoload_static.php:        'munkireport\\models\\Machine_group' => __DIR__ . '/../..' . '/app/models/machine_group.php',
```
See the lowercase machine_group.php? Linux filesystem is case sensitive... whereas windows is not.

**Comment by bochoven** [comment]
Ubuntu 14.04.5 LTS Apache2 CGI/FastCGI is working, I don't have access to a Debian box atm

**Comment by brushj** [comment]
Ran into the same issue as @MatthiasKuehneEllerhold with the `app/models/machine_group.php` needing to be capitalized and `app/models/hash.php` needing to be renamed to Hash.php as well.

**Comment by aysiu** [comment]
Same here. Ubuntu 16.04 running Nginx. Capitalizing those first letters fixed my HTTP 500 error!
