### ISSUE TITLE
Widget reporting wrong information

### ISSUE THREAD

**Issue by adambarnett52** [munkireport/munkireport-php#95]
Hi Guys

On the munki_widget it is report the wrong information. it  shows there are warnings, but if i click on it i am shown one machine, and on the installed button there are 8 but only 5 are shown. If i connect to the sqlite db and run the qurary 
select sum(installresults > 1) as warnings from munkireport;
it shows that there are 5

Any ideas?

**Comment by mattiasvdm** [comment]
I know this is an old post but I have the same issue. I was using sqlite but recently switched to mysql. I've rebuild the mysql database and the problems seemed to be gone, but now I see the same behavior. I have two MunkiReport environments which show the same incorrect data.
In the below example you can see the number of errors are incorrect. But the warnings, pendings, and installed numbers are also incorrect.

![schermafbeelding 2016-01-21 om 16 01 49](https://cloud.githubusercontent.com/assets/8159258/12484044/94d7b52e-c058-11e5-81b3-bdc2d28893a5.png)
![schermafbeelding 2016-01-21 om 16 02 00](https://cloud.githubusercontent.com/assets/8159258/12484045/94e7ff92-c058-11e5-88ef-f2fd53a0f202.png)
![schermafbeelding 2016-01-21 om 16 03 12](https://cloud.githubusercontent.com/assets/8159258/12484047/94fb37b0-c058-11e5-8e73-b2258e24c720.png)
![schermafbeelding 2016-01-21 om 16 03 22](https://cloud.githubusercontent.com/assets/8159258/12484046/94e9c64c-c058-11e5-8c9f-2bfd37c5c5f6.png)

**Comment by gmarnin** [comment]
Is that because those numbers are statistics only for the past week (as the widget popup saids)?

**Comment by mattiasvdm** [comment]
Yep, you're right. I see it now... Thanks for the heads up!
