### ISSUE TITLE
Cannot declare class Security on Quick Demo v3

### ISSUE THREAD

**Issue by joncrain** [munkireport/munkireport-php#967]
Going through the v3 demo from [the wiki](https://github.com/munkireport/munkireport-php/wiki/Quick-demo-V3).
When running migrations `php database/migrate.php`, I get the error:
```
| => php database/migrate.php

Fatal error: Cannot declare class Security, because the name is already in use in /Users/user/Downloads/munkireport-php-wip/app/modules/security/migrations/2018_01_19_234938_security.php on line 32
```

## Versions
Composer version 1.6.3
MunkiReport Version 3.0.1.3271
macOS 10.13.3

**Comment by bochoven** [comment]
Fixed in latest wip
