### ISSUE TITLE
DB Migration Errors

### ISSUE THREAD

**Issue by danner26** [munkireport/munkireport-php#969]
Hello,

I am receiving multiple errors upton trying to migrate the database.

I am using MYSQL for the database on a CentOS server. The error we keep gettings is:

Migrating: 2017_02_09_231419_bluetooth
ERROR: SQLSTATE[HY000]: General error: 2053  (SQL: INSERT INTO
                bluetooth (serial_number, battery_percent, device_type)
            SELECT
                serial_number,
                battery_percent,
                device_type
            FROM
                bluetooth_orig)

When I run the inset command in the mysql cli as the executing user it executes perfectly fine. Any idea what is going on?

**Comment by bochoven** [comment]
I changed the migrations to use `$capsule::unprepared` instead of `$capsule::select`.
Any way you could check that?

**Comment by danner26** [comment]
Where did you add/make the change? I cant seem to find $capsule::unprepared anywhere.

**Comment by danner26** [comment]
Nevermind, I found where you changed them. I will change it in my env and let you know if it works.

**Comment by danner26** [comment]
Seems to have worked for most, but another issue came up. Please see below:

Migrating: 2017_02_09_231419_bluetooth
Migrated:  2017_02_09_231419_bluetooth
Migrating: 2017_02_09_234100_ard
Migrated:  2017_02_09_234100_ard
Migrating: 2017_02_09_234110_backup2go
Migrated:  2017_02_09_234110_backup2go
Migrating: 2017_02_09_234136_certificate
Migrated:  2017_02_09_234136_certificate
Migrating: 2017_02_09_234207_crashplan
Migrated:  2017_02_09_234207_crashplan
Migrating: 2017_02_09_234219_deploystudio
ERROR: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'username-imac' for column 'dstudio_disabled' at row 1 (SQL: INSERT INTO
                deploystudio (serial_number, architecture, cn, dstudio_auto_disable, dstudio_auto_reset_workflow, dstudio_auto_started_workflow, dstudio_bootcamp_windows_computer_name, dstudio_disabled, dstudio_group, dstudio_host_ard_field_1, dstudio_host_ard_field_2, dstudio_host_ard_field_3, dstudio_host_ard_field_4, dstudio_host_ard_ignore_empty_fields, dstudio_host_delete_other_locations, dstudio_host_model_identifier, dstudio_host_new_network_location, dstudio_host_primary_key, dstudio_host_serial_number, dstudio_host_type, dstudio_hostname, dstudio_last_workflow, dstudio_last_workflow_duration, dstudio_last_workflow_execution_date, dstudio_last_workflow_status, dstudio_mac_addr)
            SELECT
                serial_number,
                architecture,
                cn,
                dstudio_host_new_network_location,
                dstudio_host_primary_key,
                dstudio_host_serial_number,
                dstudio_host_type,
                dstudio_hostname,
                dstudio_last_workflow,
                dstudio_last_workflow_duration,
                dstudio_last_workflow_execution_date,
                dstudio_last_workflow_status,
                dstudio_mac_addr,
                dstudio_auto_disable,
                dstudio_auto_reset_workflow,
                dstudio_auto_started_workflow,
                dstudio_bootcamp_windows_computer_name,
                dstudio_disabled,
                dstudio_group,
                dstudio_host_ard_field_1,
                dstudio_host_ard_field_2,
                dstudio_host_ard_field_3,
                dstudio_host_ard_field_4,
                dstudio_host_ard_ignore_empty_fields,
                dstudio_host_delete_other_locations,
                dstudio_host_model_identifier
            FROM
                deploystudio_orig)

**Comment by danner26** [comment]
Im guessing this is because some of the machines do not have a value for dstudio_disabled
for example: 
*************************** 1. row ***************************
id: 1
serial_number: *REDACTED*
architecture: i386
cn: username-imac
dstudio_auto_disable:
dstudio_auto_reset_workflow:
dstudio_auto_started_workflow:
dstudio_bootcamp_windows_computer_name:
dstudio_disabled:
dstudio_group:
dstudio_host_ard_field_1:
dstudio_host_ard_field_2:
dstudio_host_ard_field_3:
dstudio_host_ard_field_4:
dstudio_host_ard_ignore_empty_fields: NO
dstudio_host_delete_other_locations:
dstudio_host_model_identifier: iMac12,1
dstudio_host_new_network_location:
dstudio_host_primary_key: dstudio-host-serial-number
dstudio_host_serial_number: *REDACTED*
dstudio_host_type: Mac
dstudio_hostname: username-imac
 dstudio_last_workflow: 3. Restore with Updates
dstudio_last_workflow_duration: 0:00:54
dstudio_last_workflow_execution_date: 2017/03/15, 17:56:46
dstudio_last_workflow_status: completed
dstudio_mac_addr: *REDACTED*

**Comment by bochoven** [comment]
Interesting, that migration is not right. The columns don't match.

**Comment by bochoven** [comment]
I pushed a new version that addresses this issue, could you please test?

**Comment by danner26** [comment]
Seems like there might be a few more issues coming popping up in the migration, but almost there!

Migrating: 2017_02_09_234219_deploystudio
Migrated:  2017_02_09_234219_deploystudio
Migrating: 2017_02_09_234232_directoryservice
Migrated:  2017_02_09_234232_directoryservice
Migrating: 2017_02_09_234243_diskreport
Migrated:  2017_02_09_234243_diskreport
Migrating: 2017_02_09_234251_displays
Migrated:  2017_02_09_234251_displays
Migrating: 2017_02_09_234311_filevault_status
Migrated:  2017_02_09_234311_filevault_status
Migrating: 2017_02_09_234321_findmymac
Migrated:  2017_02_09_234321_findmymac
Migrating: 2017_02_09_234329_gsx
Migrated:  2017_02_09_234329_gsx
Migrating: 2017_02_09_234335_inventoryitem
Migrated:  2017_02_09_234335_inventoryitem
Migrating: 2017_02_09_234346_localadmin
Migrated:  2017_02_09_234346_localadmin
Migrating: 2017_02_09_234352_location
Migrated:  2017_02_09_234352_location
Migrating: 2017_02_09_234358_machine
Migrated:  2017_02_09_234358_machine
Migrating: 2017_02_09_234433_managedinstalls
Migrated:  2017_02_09_234433_managedinstalls
Migrating: 2017_02_09_234611_munkiinfo
Migrated:  2017_02_09_234611_munkiinfo
Migrating: 2017_02_09_234619_munkireport
Migrated:  2017_02_09_234619_munkireport
Migrating: 2017_02_09_234656_network
Migrated:  2017_02_09_234656_network
Migrating: 2017_02_09_234916_profile
Migrated:  2017_02_09_234916_profile
Migrating: 2017_02_09_234923_reportdata
Migrated:  2017_02_09_234923_reportdata
Migrating: 2017_02_09_234931_sccm_status
Migrated:  2017_02_09_234931_sccm_status
Migrating: 2017_02_09_234938_security
Migrated:  2017_02_09_234938_security
Migrating: 2017_02_09_234951_timemachine
Migrated:  2017_02_09_234951_timemachine
Migrating: 2017_02_09_234959_warranty
Migrated:  2017_02_09_234959_warranty
Migrating: 2017_02_09_235003_wifi
Migrated:  2017_02_09_235003_wifi
Migrating: 2017_02_11_074454_event
Migrated:  2017_02_11_074454_event
Migrating: 2017_02_12_012330_comment
Migrated:  2017_02_12_012330_comment
Migrating: 2017_02_12_235252_hash
Migrated:  2017_02_12_235252_hash
Migrating: 2017_02_14_091413_installhistory
Migrated:  2017_02_14_091413_installhistory
Migrating: 2017_02_20_085316_machine_group
Migrated:  2017_02_20_085316_machine_group
Migrating: 2017_11_29_000001_extensions
Migrated:  2017_11_29_000001_extensions
Migrating: 2017_12_18_132621_user_sessions
Migrated:  2017_12_18_132621_user_sessions
Migrating: 2017_12_18_173230_business_unit
Migrated:  2017_12_18_173230_business_unit
Migrating: 2017_12_18_211801_appusage
Migrated:  2017_12_18_211801_appusage
Migrating: 2017_12_18_211802_caching
Migrated:  2017_12_18_211802_caching
Migrating: 2017_12_18_211803_fan_temps
Migrated:  2017_12_18_211803_fan_temps
Migrating: 2017_12_18_220830_tag
Migrated:  2017_12_18_220830_tag
Migrating: 2017_12_19_172407_munki_facts
Migrated:  2017_12_19_172407_munki_facts
Migrating: 2017_12_19_193501_usb
Migrated:  2017_12_19_193501_usb
Migrating: 2017_12_19_193803_filevault_escrow
Migrated:  2017_12_19_193803_filevault_escrow
Migrating: 2017_12_19_193901_homebrew_info
Migrated:  2017_12_19_193901_homebrew_info
Migrating: 2017_12_19_194601_firmware_escrow
Migrated:  2017_12_19_194601_firmware_escrow
Migrating: 2017_12_19_195001_fonts
ERROR: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xE3\x83\x92\xE3\x83\xA9...' for column 'name' at row 36 (SQL: INSERT INTO
                fonts
            SELECT
                id,
                serial_number,
                name,
                enabled,
                type_name,
                fullname,
                type_enabled,
                valid,
                duplicate,
                path,
                type,
                family,
                style,
                version,
                embeddable,
                outline,
                unique_id,
                copyright,
                copy_protected,
                description,
                vendor,
                designer,
                trademark
            FROM
                fonts_orig)

Where the select query for row 36 shows
*************************** 36. row ***************************
            id: 309
 serial_number: VMpRkcyxjVmP
          name: ヒラギノ角ゴシック W3.ttc
       enabled: 0
     type_name: HiraKakuInterface-W3
      fullname:
  type_enabled: 1
         valid: 1
     duplicate: 0
          path: /System/Library/Fonts/ヒラギノ角ゴシック W3.ttc
          type: OpenType
        family: Hiragino Kaku Gothic Interface
         style: W3
       version: 11.0d7e4
    embeddable: 1
       outline: 1
     unique_id: Hiragino Kaku Gothic Interface W3; 11.0d7e4; 2015-09-18
     copyright: ver8.21, Copyright (c) 1993-2013 Dainippon Screen Mfg. Co., Ltd. All Rights Reserved.
copy_protected: 0
   description:
        vendor: SCREEN Graphic and Precision Solutions Co., Ltd.
      designer: JIYUKOBO Ltd.
     trademark: HIRAGINO is a trademark of SCREEN Holdings Co., Ltd.

**Comment by bochoven** [comment]
Looks like an UTF8 problem. What are your database connection options? Should be something like:
```
'options'   => [PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci']
```

**Comment by danner26** [comment]
I just had 'options'   => [PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8']
Adding what you suggested caused the Deploy Studio error again.

ERROR: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'dstudio_disabled' at row 1 (SQL: INSERT INTO
                deploystudio (
                  serial_number,
                  architecture,
                  cn,
                  dstudio_host_new_network_location,
                  dstudio_host_primary_key,
                  dstudio_host_serial_number,
                  dstudio_host_type,
                  dstudio_hostname,
                  dstudio_last_workflow,
                  dstudio_last_workflow_duration,
                  dstudio_last_workflow_execution_date,
                  dstudio_last_workflow_status,
                  dstudio_mac_addr,
                  dstudio_auto_disable,
                  dstudio_auto_reset_workflow,
                  dstudio_auto_started_workflow,
                  dstudio_bootcamp_windows_computer_name,
                  dstudio_disabled,
                  dstudio_group,
                  dstudio_host_ard_field_1,
                  dstudio_host_ard_field_2,
                  dstudio_host_ard_field_3,
                  dstudio_host_ard_field_4,
                  dstudio_host_ard_ignore_empty_fields,
                  dstudio_host_delete_other_locations,
                  dstudio_host_model_identifier
            )
            SELECT
                serial_number,
                architecture,
                cn,
                dstudio_host_new_network_location,
                dstudio_host_primary_key,
                dstudio_host_serial_number,
                dstudio_host_type,
                dstudio_hostname,
                dstudio_last_workflow,
                dstudio_last_workflow_duration,
                dstudio_last_workflow_execution_date,
                dstudio_last_workflow_status,
                dstudio_mac_addr,
                dstudio_auto_disable,
                dstudio_auto_reset_workflow,
                dstudio_auto_started_workflow,
                dstudio_bootcamp_windows_computer_name,
                dstudio_disabled,
                dstudio_group,
                dstudio_host_ard_field_1,
                dstudio_host_ard_field_2,
                dstudio_host_ard_field_3,
                dstudio_host_ard_field_4,
                dstudio_host_ard_ignore_empty_fields,
                dstudio_host_delete_other_locations,
                dstudio_host_model_identifier
            FROM
                deploystudio_orig)

**Comment by bochoven** [comment]
I pushed a new commit to fix the issue with dstudio_disabled

**Comment by danner26** [comment]
That fixed the DS issue, still running into the fonts one..
ERROR: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xE3\x83\x92\xE3\x83\xA9...' for column 'name' at row 36 (SQL: INSERT INTO
                fonts
            SELECT
                id,
                serial_number,
                name,
                enabled,
                type_name,
                fullname,
                type_enabled,
                valid,
                duplicate,
                path,
                type,
                family,
                style,
                version,
                embeddable,
                outline,
                unique_id,
                copyright,
                copy_protected,
                description,
                vendor,
                designer,
                trademark
            FROM
                fonts_orig)

Row 36 is the same as before, and the MYSQL connection is setup as follows:
$conf['connection'] = [
    'driver'    => 'mysql',
    'host'      => 'localhost',
    'database'  => 'munkireport_pprd',
    'username'  => '*REDACTED*',
    'password'  => '*REDACTED*',
    'options'   => [PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci'],
  ];

**Comment by bochoven** [comment]
Could you paste the output of
```
SHOW CREATE TABLE `fonts`;
```

**Comment by bochoven** [comment]
This is my output:

```
CREATE TABLE `fonts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `serial_number` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `enabled` tinyint(1) NOT NULL,
  `type_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `fullname` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `type_enabled` tinyint(1) NOT NULL,
  `valid` tinyint(1) NOT NULL,
  `duplicate` tinyint(1) NOT NULL,
  `path` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `family` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `style` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `version` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `embeddable` tinyint(1) NOT NULL,
  `outline` tinyint(1) NOT NULL,
  `unique_id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `copyright` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `copy_protected` tinyint(1) NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `vendor` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `designer` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `trademark` text COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fonts_name_index` (`name`),
  KEY `fonts_type_index` (`type`),
  KEY `fonts_type_name_index` (`type_name`),
  KEY `fonts_family_index` (`family`),
  KEY `fonts_fullname_index` (`fullname`),
  KEY `fonts_style_index` (`style`),
  KEY `fonts_unique_id_index` (`unique_id`),
  KEY `fonts_version_index` (`version`),
  KEY `fonts_enabled_index` (`enabled`),
  KEY `fonts_copy_protected_index` (`copy_protected`),
  KEY `fonts_duplicate_index` (`duplicate`),
  KEY `fonts_embeddable_index` (`embeddable`),
  KEY `fonts_type_enabled_index` (`type_enabled`),
  KEY `fonts_outline_index` (`outline`),
  KEY `fonts_valid_index` (`valid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```

**Comment by bochoven** [comment]
Are you sure you're running the latest version of MunkiReport? That column should be nullable.

**Comment by bochoven** [comment]
As this conversation is getting quite long, I want to suggest to join https://macadmins.herokuapp.com and get into the #munkireport channel.

**Comment by bochoven** [comment]
Yes, please upgrade to 2.15.2 before upgrading to 3.0.1. Please open a new issue if you find any problems. You can search for #munkireport in the search box.
