### ISSUE TITLE
[3.x] Own modules can't create tables

### ISSUE THREAD

**Issue by mikaellofgren** [munkireport/munkireport-php#978]
Hi
Did a new install of version 3 and mysql, my own modules won't create tables anymore.
Is it something thats I'm missing? Getting this error:

 `Uncaught Exception: Create table is not available anymore in /Library/Server/Web/Data/Sites/Default/munkireport3/system/kissmvc.php:401`

And under client detail view the disk space is empty, but data is reported under Storage report.
![skarmavbild 2018-02-19 kl 12 40 01](https://user-images.githubusercontent.com/6194908/36376278-c57ac16e-1572-11e8-9e8a-469294d796df.png)

regards
Mikael

**Comment by tuxudo** [comment]
MunkiReport v3 does not create tables automatically anymore. You must log in as an admin user, click on the Admin tab at the top and go to the Database section. There you can click Update and it will create the tables for you.

**Comment by bochoven** [comment]
Hi Mikael, if you're using custom modules, you need to change them so they work like the built-in modules.

**Comment by mikaellofgren** [comment]
Thanks, how to I change them so they work as the built in. I have looked at the built in ard module. And my module loads successfully. And I run php database/migrate.php and get "nothing to migrate" and nothing on the Admin tab.

**Comment by mikaellofgren** [comment]
For example this modules that reports the size of the .DocumentRevisions-V100 folder
https://github.com/mikaellofgren/documentrevisions_munkireport_module
Anything that Im doing wrong?

**Comment by bochoven** [comment]
Please check this article: https://github.com/munkireport/munkireport-php/wiki/How-to-create-a-migration

**Comment by mikaellofgren** [comment]
Yes Thanks!
This was the fix:
run:
build/addmigration path/to/custom/module
then I added some data in the file created in the migrationsfolder
$table->string('username');
and run
php database/migrate.php

Success!

What about client detail view the disk space is empty, but data is reported under Storage report. Should I open a new Issue for that?
regards
Mikael

**Comment by bochoven** [comment]
That issue is already fixed in wip.
