### ISSUE TITLE
munkiinfo - PHP 7.2.2 Deprecation warning 

### ISSUE THREAD

**Issue by tuxudo** [munkireport/munkireport-php#980]
The munkiinfo module throws a deprecation warning when using PHP 7.2.2. The module appears to still run and process data, but it may stop working in the future. Error message is below

<b>Deprecated</b>:  The each() function is deprecated. This message will be suppressed on further calls in <b>../munkireport-php/app/modules/munkiinfo/munkiinfo_model.php</b> on line <b>47</b>

**Comment by bochoven** [comment]
could you test if the commits fix the issue?

**Comment by tuxudo** [comment]
This issue has been resolved.
