### ISSUE TITLE
[3.0] Fatal error when authenticating with AD/LDAP

### ISSUE THREAD

**Issue by tuxudo** [munkireport/munkireport-php#993]
My MR session expired for the first time since upgrading an instance to MR 3. When trying to log in using Active Directory I get the following error. Ubuntu 10.06, nginx, PHP 7.2.x, php7.2-ldap is installed. 

Fatal error: Uncaught Error: Class 'Adldap\Adldap' not found in munkireport-php-3/app/lib/munkireport/AuthAD.php:22 Stack trace: #0 munkireport-php-3/app/lib/munkireport/AuthHandler.php(54): munkireport\lib\AuthAD->login('userName', 'Pa$$w0rd') #1 munkireport-php-3/app/lib/munkireport/AuthHandler.php(34): munkireport\lib\AuthHandler->validate('userName', 'Pa$$w0rd') #2 munkireport-php-3/app/controllers/auth.php(74): munkireport\lib\AuthHandler->login('userName', 'Pa$$w0rd') #3 munkireport-php-3/system/kissmvc_core.php(88): munkireport\controller\Auth->login() #4 munkireport-php-3/system/kissmvc.php(17): KISS_Engine->__construct(Array, 'show', 'index', 'AUTO') #5 munkireport-php-3/public/index.php(147): Engine->__construct(Array, 'show', 'index', 'AUTO') #6 {main} thrown in munkireport-php-3/app/lib/munkireport/AuthAD.php on line 22

**Comment by bochoven** [comment]
Obvious questions:

- is adldap2 installed
- did you dump the autoload files

**Comment by tuxudo** [comment]
Installing adldap2 with 'composer require adldap2/adldap2; composer install --no-dev --no-suggest --optimize-autoloader' fixed it. Still getting used to this composer thing. Issue is resolved.
